<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
require_login();
$user=current_user();$pdo=db();
if(!$user||!$pdo){flash('error','Account unavailable.');redirect(url('/login.php'));}
if(!ai_usage_accounting_v032_schema_ready($pdo)){
    if(has_permission('users.manage',$user))redirect(url('/upgrade.php'));
    flash('error','AI usage history is unavailable until an administrator completes the database upgrade.');redirect(url('/subscription.php'));
}
$state=ai_usage_accounting_v032_user_state($pdo,(int)$user['id'],200);
$balance=function_exists('subscription_ai_balance')?subscription_ai_balance($user,$pdo):['unlimited'=>false,'remaining'=>0,'package_allowance'=>0,'used'=>0,'credits_remaining'=>0];
$sourceLabels=['homeserver_local'=>'HomeServer Local','user_provider'=>'Connected Provider','vp3_cloud'=>'VP3 Cloud','vp3_retrieval'=>'VP3 Retrieval','vp3_tool'=>'VP3 Tool'];
$month=$state['month'];$today=$state['today'];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI Usage | VP3</title><link rel="stylesheet" href="<?= e(url('/chat.css?v=82')) ?>"><link rel="stylesheet" href="<?= e(url('/account.css?v=account-light-20260904')) ?>"><style>
.usage-wrap{display:grid;gap:16px}.usage-card,.usage-stat{border:1px solid #e4e7ec;border-radius:16px;background:#fff}.usage-card{padding:20px}.usage-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.usage-stat{padding:16px}.usage-stat span,.usage-muted{color:#667085}.usage-stat span{display:block;font-size:12px}.usage-stat strong{display:block;font-size:24px;margin-top:5px}.usage-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap}.usage-actions{display:flex;gap:8px;flex-wrap:wrap}.usage-btn{display:inline-flex;border:1px solid #d0d5dd;border-radius:9px;background:#fff;padding:9px 13px;font-weight:650;color:#101828;text-decoration:none}.usage-table-wrap{overflow:auto}.usage-table{width:100%;min-width:820px;border-collapse:collapse}.usage-table th,.usage-table td{padding:11px 8px;border-bottom:1px solid #eaecf0;text-align:left;vertical-align:top;font-size:13px}.usage-table th{font-size:11px;color:#667085;text-transform:uppercase;letter-spacing:.05em}.usage-pill{display:inline-flex;padding:4px 8px;border-radius:999px;background:#f2f4f7;font-size:11px;font-weight:700}.usage-zero{color:#027a48}.usage-note{font-size:13px;color:#667085;line-height:1.5}@media(max-width:900px){.usage-stats{grid-template-columns:1fr 1fr}}@media(max-width:560px){.usage-stats{grid-template-columns:1fr}}
</style></head><body><div class="chat-app"><?php $workspaceSidebarUser=$user;$workspaceSidebarActive='ai_usage';require __DIR__.'/includes/workspace-sidebar-v82.php';?><div class="chat-sidebar-backdrop" id="chatSidebarBackdrop"></div><main class="chat-main account-chat-main"><header class="chat-topbar"><button class="chat-icon-button mobile-only" id="openChatSidebar" type="button">☰</button><div class="chat-topbar-title"><strong>AI Usage</strong><span>Execution source, model, tokens and estimated cost</span></div></header><section class="account-canvas"><div class="account-canvas-inner usage-wrap">
<section class="account-canvas-hero"><div><span>Usage Ledger</span><h1>Know exactly where your AI ran.</h1><div class="account-canvas-meta"><span><?= !empty($balance['unlimited'])?'Unlimited VP3 plan':number_format((int)($balance['remaining']??0)).' VP3 tokens available' ?></span><span><?= number_format((int)$state['local_requests']) ?> HomeServer-local run<?= (int)$state['local_requests']===1?'':'s' ?></span></div></div><div class="usage-actions"><a class="usage-btn" href="<?= e(url('/ai-usage-export-v032.php')) ?>">Export CSV</a><a class="usage-btn" href="<?= e(url('/subscription.php')) ?>">Plan & Usage</a></div></section>
<div class="usage-stats"><article class="usage-stat"><span>Requests this month</span><strong><?= number_format((int)($month['requests']??0)) ?></strong></article><article class="usage-stat"><span>Model tokens this month</span><strong><?= number_format((int)($month['total_tokens']??0)) ?></strong></article><article class="usage-stat"><span>VP3 tokens charged this month</span><strong><?= number_format((int)($month['cloud_tokens']??0)) ?></strong></article><article class="usage-stat"><span>Estimated provider cost</span><strong><?= e(ai_usage_accounting_v032_format_aggregate_cost((int)($month['estimated_cost_micros']??0),(int)($month['unknown_cost_requests']??0))) ?></strong></article></div>
<section class="usage-card"><div class="usage-head"><div><h2>Today</h2><p class="usage-muted"><?= number_format((int)($today['requests']??0)) ?> requests · <?= number_format((int)($today['total_tokens']??0)) ?> model tokens · <?= number_format((int)($today['cloud_tokens']??0)) ?> VP3 tokens charged</p></div></div><p class="usage-note">HomeServer-local, VP3 retrieval and VP3 tool execution are recorded as <strong>$0 VP3 cloud cost</strong>. Provider cost is estimated only when a matching provider/model rate is configured; otherwise the ledger shows “—” rather than inventing a price.</p></section>
<section class="usage-card"><div class="usage-head"><div><h2>By model and execution source</h2><p class="usage-muted">Input/output model tokens are distinct from VP3 tokens actually charged to your package or top-up balance.</p></div></div><div class="usage-table-wrap"><table class="usage-table"><thead><tr><th>Execution</th><th>Provider / model</th><th>Requests</th><th>Input</th><th>Output</th><th>VP3 charged</th><th>Estimated cost</th></tr></thead><tbody><?php foreach($state['by_model'] as $row):$src=(string)$row['source'];?><tr><td><span class="usage-pill"><?= e($sourceLabels[$src]??$src) ?></span></td><td><?= e(trim((string)$row['provider'].' / '.(string)$row['model'],' /')) ?: '—' ?></td><td><?= number_format((int)$row['requests']) ?></td><td><?= number_format((int)$row['input_tokens']) ?></td><td><?= number_format((int)$row['output_tokens']) ?></td><td><?= number_format((int)$row['cloud_tokens']) ?></td><td class="<?= in_array($src,['homeserver_local','vp3_retrieval','vp3_tool'],true)?'usage-zero':'' ?>"><?= e(ai_usage_accounting_v032_format_aggregate_cost((int)$row['estimated_cost_micros'],(int)($row['unknown_cost_requests']??0))) ?></td></tr><?php endforeach;?><?php if(!$state['by_model']):?><tr><td colspan="7">No AI executions have been recorded yet.</td></tr><?php endif;?></tbody></table></div></section>
<section class="usage-card"><div class="usage-head"><div><h2>Recent execution history</h2><p class="usage-muted">Newest 200 routed Agent executions. Prompts and response bodies are not duplicated into this accounting ledger.</p></div></div><div class="usage-table-wrap"><table class="usage-table"><thead><tr><th>When</th><th>Execution</th><th>Provider / model</th><th>Tokens</th><th>VP3 charged</th><th>Cost</th><th>Route detail</th></tr></thead><tbody><?php foreach($state['recent'] as $row):$src=(string)$row['source'];?><tr><td><?= e((string)$row['created_at']) ?></td><td><span class="usage-pill"><?= e($sourceLabels[$src]??$src) ?></span></td><td><?= e(trim((string)$row['provider'].' / '.(string)$row['model'],' /')) ?: '—' ?></td><td><?= number_format((int)$row['input_tokens']) ?> in / <?= number_format((int)$row['output_tokens']) ?> out</td><td><?= number_format((int)$row['cloud_tokens_charged']) ?></td><td class="<?= in_array($src,['homeserver_local','vp3_retrieval','vp3_tool'],true)?'usage-zero':'' ?>"><?= e(ai_usage_accounting_v032_format_cost($row['estimated_cost_micros']===null?null:(int)$row['estimated_cost_micros'])) ?></td><td><?= !empty($row['fallback_used'])?'Fallback · ':'' ?><?= e((string)$row['failure_class']) ?><?= (int)$row['latency_ms']>0?' · '.number_format((int)$row['latency_ms']).' ms':'' ?></td></tr><?php endforeach;?><?php if(!$state['recent']):?><tr><td colspan="7">No AI executions have been recorded yet.</td></tr><?php endif;?></tbody></table></div></section>
</div></section></main></div><script src="<?= e(url('/chat.js?v=82')) ?>"></script></body></html>