<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
$pdo=db();if(!$pdo||!agent_paid_appointments_schema_ready_v800($pdo)||!agent_commerce_appointment_adapter_ready_v800($pdo)){http_response_code(503);exit('VP3 Commerce is not available. Run the database upgrade.');}
if(!headers_sent()){header('Referrer-Policy: no-referrer');header('X-Robots-Tag: noindex, nofollow, noarchive');header('Cache-Control: no-store, private');}
$manage=strtolower(trim((string)($_GET['manage']??$_POST['manage']??'')));$paid=agent_paid_appointments_public_by_token_v800($pdo,$manage);if(!$paid){http_response_code(404);exit('Appointment payment link not found.');}
agent_commerce_sync_paid_appointment_v800($pdo,$paid);$paid=agent_paid_appointments_public_by_token_v800($pdo,$manage)?:$paid;
$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{if(!verify_csrf())throw new RuntimeException('Payment session expired. Refresh and try again.');agent_scheduling_public_rate_limit_v450('appointment-payment',10,60);if((string)($_POST['action']??'')!=='checkout')throw new RuntimeException('Unknown payment action.');$connectionId=max(0,(int)($_POST['connection_id']??0));$attempt=agent_paid_appointments_create_checkout_v800($pdo,$paid,$connectionId);$paid=agent_paid_appointments_paid_booking_v800($pdo,(int)$paid['id'])?:$paid;agent_commerce_sync_checkout_v800($pdo,$paid,$attempt,'cloud');$checkout=trim((string)($attempt['checkout_url']??''));if($checkout===''||!preg_match('#^https://#i',$checkout))throw new RuntimeException('Payment provider did not return a secure checkout URL.');redirect($checkout);}catch(Throwable $e){$error=$e->getMessage();$paid=agent_paid_appointments_public_by_token_v800($pdo,$manage)?:$paid;}
}
$connections=agent_paid_appointments_available_connections_v800($pdo,$paid);$booking=agent_appointment_lifecycle_booking_v700($pdo,(int)$paid['booking_id']);$when='';if($booking)try{$when=(new DateTimeImmutable((string)$booking['start_at_utc'],new DateTimeZone('UTC')))->setTimezone(new DateTimeZone((string)($booking['organizer_timezone']??'UTC')))->format('D, M j · g:i A T');}catch(Throwable $e){}
$title=trim((string)($booking['event_title']??''))?:'Appointment';$expires=!empty($paid['hold_expires_at'])?strtotime((string)$paid['hold_expires_at']):0;
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Appointment payment — VP3</title><style>body{margin:0;background:#f4f5f7;color:#151515;font:15px/1.5 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.shell{max-width:720px;margin:0 auto;padding:48px 20px}.card{background:#fff;border:1px solid #e1e3e8;border-radius:24px;padding:28px;box-shadow:0 16px 50px rgba(20,25,35,.08)}h1{font-size:30px;margin:0 0 8px}.muted{color:#686d76}.price{font-size:34px;font-weight:750;margin:22px 0}.provider{display:flex;align-items:center;justify-content:space-between;width:100%;padding:16px 18px;margin:10px 0;border:1px solid #d8dbe1;border-radius:14px;background:#fff;font:inherit;font-weight:700;cursor:pointer}.provider:hover{border-color:#111}.alert{padding:12px 14px;border-radius:12px;background:#fff2f1;color:#8b211a;margin:16px 0}.ok{background:#eef9f1;color:#176b35}.terms{border-top:1px solid #eceef1;margin-top:22px;padding-top:18px;font-size:13px;color:#686d76}.secure{font-size:13px;color:#686d76;margin-top:16px}</style></head><body><main class="shell"><section class="card"><div class="muted">VP3 Commerce · Appointment fulfillment</div><h1><?=e($title)?></h1><?php if($when):?><div class="muted"><?=e($when)?></div><?php endif;?><div class="price"><?=e(agent_paid_appointments_money_v800((int)$paid['amount_due_cents'],(string)$paid['currency']))?></div><?php if($error):?><div class="alert" role="alert"><?=e($error)?></div><?php endif;?>
<?php if(in_array((string)$paid['payment_status'],['paid','partially_refunded','refunded'],true)):?><div class="alert ok">Payment received. Your appointment is confirmed.</div>
<?php elseif((string)$paid['payment_status']==='expired'||($expires>0&&$expires<=time())):?><div class="alert">This payment hold has expired. Return to your private booking link to choose another time.</div>
<?php else:?><p>Choose how you want to pay. Your time is held until <?=e($expires?gmdate('g:i A \U\T\C',$expires):'checkout expires')?>.</p><?php foreach($connections as $connection):?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="checkout"><input type="hidden" name="manage" value="<?=e($manage)?>"><input type="hidden" name="connection_id" value="<?=(int)$connection['id']?>"><button class="provider" type="submit"><span><?=e(agent_paid_appointments_provider_label_v800((string)$connection['provider']))?></span><span>Continue →</span></button></form><?php endforeach;?><?php if(!$connections):?><div class="alert">No payment provider is currently available for this offer.</div><?php endif;?><?php endif;?>
<div class="terms"><?php $terms=json_decode((string)($paid['terms_snapshot_json']??''),true);$terms=is_array($terms)?$terms:[];?><?php if(!empty($terms['cancellation_policy'])):?><?=nl2br(e((string)$terms['cancellation_policy']))?><br><?php endif;?>Payment credentials are entered only on the selected provider's secure checkout. VP3 does not store card numbers.</div><div class="secure">The commerce order remains separate from scheduling fulfillment and VP3 subscription billing.</div></section></main></body></html>