<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';require_once __DIR__.'/includes/user-calendar-v1300.php';require_permission('account.access');
$pdo=db();$user=current_user();if(!$pdo||!$user)redirect(url('/login.php'));if(!user_calendar_schema_ready_v1300($pdo))redirect(url('/upgrade.php'));
$userId=(int)$user['id'];$eventId=max(0,(int)($_GET['id']??$_POST['event_id']??0));$event=$eventId>0?user_calendar_event_v1300($pdo,$userId,$eventId):null;if($eventId>0&&!$event)redirect(url('/calendar.php'));
$error='';$defaultTimezone=user_calendar_default_timezone_v1300($pdo,$user);$tz=new DateTimeZone($defaultTimezone);$now=new DateTimeImmutable('now',$tz);$minute=(int)$now->format('i');$rounded=$now->modify('+'.(60-$minute).' minutes')->setTime((int)$now->modify('+'.(60-$minute).' minutes')->format('H'),0);$parts=$event?user_calendar_event_local_parts_v1300($event,$defaultTimezone):['timezone'=>$defaultTimezone,'all_day'=>false,'date'=>$rounded->format('Y-m-d'),'start_time'=>$rounded->format('H:i'),'end_date'=>$rounded->format('Y-m-d'),'end_time'=>$rounded->modify('+1 hour')->format('H:i')];
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verify_csrf())$error='Session expired. Please try again.';else try{
  $action=trim((string)($_POST['action']??'save'));
  if($action==='cancel'){
   if(!$event||!user_calendar_cancel_event_v1300($pdo,$user,$eventId))throw new RuntimeException('Calendar event could not be removed.');
   agent_tool_log($user,'calendar.event.cancel','Calendar event editor','success',['event_id'=>$eventId]);redirect(url('/calendar.php?month='.rawurlencode(substr((string)$parts['date'],0,7)).'&saved='.rawurlencode('Event removed.')));
  }
  $input=['title'=>(string)($_POST['title']??''),'description'=>(string)($_POST['description']??''),'location'=>(string)($_POST['location']??''),'date'=>(string)($_POST['date']??''),'start_time'=>(string)($_POST['start_time']??''),'end_date'=>(string)($_POST['end_date']??''),'end_time'=>(string)($_POST['end_time']??''),'timezone'=>(string)($_POST['timezone']??$defaultTimezone),'all_day'=>!empty($_POST['all_day'])];
  if($event){$saved=user_calendar_update_event_v1300($pdo,$user,$eventId,$input);$message='Event updated.';agent_tool_log($user,'calendar.event.update','Calendar event editor','success',['event_id'=>$eventId]);}
  else{$saved=user_calendar_create_local_event_v1300($pdo,$user,$input,'user');$message='Event added to your calendar.';agent_tool_log($user,'calendar.event.create','Calendar event editor','success',['event_id'=>(int)$saved['id'],'source'=>'user']);}
  $local=user_calendar_event_local_parts_v1300($saved,$defaultTimezone);redirect(url('/calendar.php?month='.rawurlencode(substr((string)$local['date'],0,7)).'&saved='.rawurlencode($message)));
 }catch(Throwable $e){$error=$e->getMessage();$parts=['timezone'=>(string)($_POST['timezone']??$defaultTimezone),'all_day'=>!empty($_POST['all_day']),'date'=>(string)($_POST['date']??''),'start_time'=>(string)($_POST['start_time']??''),'end_date'=>(string)($_POST['end_date']??''),'end_time'=>(string)($_POST['end_time']??'')];}
}
$timezones=DateTimeZone::listIdentifiers();$titleValue=(string)($_POST['title']??($event['title']??''));$locationValue=(string)($_POST['location']??($event['location']??''));$descriptionValue=(string)($_POST['description']??($event['description']??''));
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f7f7f5"><title><?= e(system_agent_name()) ?> | <?= $event?'Edit Event':'New Event' ?></title><link rel="stylesheet" href="<?= e(url('/chat.css?v=82')) ?>"><link rel="stylesheet" href="<?= e(url('/calendar-v1300.css?v=1300')) ?>"></head><body class="calendar-page"><div class="chat-app">
<?php $workspaceSidebarUser=$user;$workspaceSidebarActive='calendar';require __DIR__.'/includes/workspace-sidebar-v82.php'; ?><div class="chat-sidebar-backdrop" id="chatSidebarBackdrop"></div><main class="chat-main calendar-main">
<?php $memberHeaderUser=$user;$memberHeaderTitle=$event?'Edit calendar event':'New calendar event';$memberHeaderSubtitle='Personal time, work blocks, reminders + Agent-managed events';$memberHeaderActions='<a class="calendar-button" href="'.e(url('/calendar.php')).'">← Calendar</a>';require __DIR__.'/includes/member-header.php'; ?>
<section class="calendar-canvas"><div class="calendar-form-shell"><?php if($error!==''): ?><div class="calendar-notice error" role="alert"><?= e($error) ?></div><?php endif; ?><div class="calendar-help"><strong>Calendar event</strong> — this is a dated item on your private VP3 calendar. To create a public appointment people can book, use <a href="<?= e(url('/scheduling-type.php')) ?>">Scheduling → New appointment type</a>.</div>
<div class="calendar-form-card"><h1><?= $event?'Edit event':'Create event' ?></h1><p><?= $event?'Update this event without changing any booking records.':'Add personal time directly, or ask your Agent by text or voice to create events for you.' ?></p>
<form method="post" class="calendar-form"><?= csrf_field() ?><input type="hidden" name="action" value="save"><input type="hidden" name="event_id" value="<?= $eventId ?>">
<label class="span-2"><span>Event title</span><input name="title" maxlength="190" required value="<?= e($titleValue) ?>" placeholder="Dentist appointment"></label>
<label><span>Date</span><input type="date" name="date" required value="<?= e((string)$parts['date']) ?>"></label><label class="checkline"><input type="checkbox" name="all_day" value="1" <?= !empty($parts['all_day'])?'checked':'' ?>><span>All-day event</span></label>
<label><span>Start time</span><input type="time" name="start_time" value="<?= e((string)$parts['start_time']) ?>"></label><label><span>End time</span><input type="time" name="end_time" value="<?= e((string)$parts['end_time']) ?>"></label>
<label><span>End date</span><input type="date" name="end_date" value="<?= e((string)$parts['end_date']) ?>"></label><label><span>Timezone</span><select name="timezone"><?php foreach($timezones as $timezone): ?><option value="<?= e($timezone) ?>" <?= $timezone===(string)$parts['timezone']?'selected':'' ?>><?= e($timezone) ?></option><?php endforeach; ?></select></label>
<label class="span-2"><span>Location</span><input name="location" maxlength="500" value="<?= e($locationValue) ?>" placeholder="Address, room, link or leave blank"></label><label class="span-2"><span>Notes</span><textarea name="description" rows="5" maxlength="10000" placeholder="Optional event notes"><?= e($descriptionValue) ?></textarea></label>
<div class="calendar-form-actions"><a class="calendar-button" href="<?= e(url('/calendar.php')) ?>">Cancel</a><button class="calendar-button primary" type="submit"><?= $event?'Save changes':'Add event' ?></button></div></form>
<?php if($event): ?><form method="post" style="margin-top:18px" onsubmit="return confirm('Remove this event from your calendar?')"><?= csrf_field() ?><input type="hidden" name="action" value="cancel"><input type="hidden" name="event_id" value="<?= $eventId ?>"><button class="calendar-danger" type="submit">Remove event</button></form><?php endif; ?>
</div></div></section></main></div><script src="<?= e(url('/member-shell-v77.js?v=20260911')) ?>"></script></body></html>
