<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';require_once __DIR__.'/includes/user-calendar-v1300.php';require_permission('account.access');
$pdo=db();$user=current_user();if(!$pdo||!$user)redirect(url('/login.php'));if(!user_calendar_schema_ready_v1300($pdo))redirect(url('/upgrade.php'));
$userId=(int)$user['id'];$eventId=max(0,(int)($_GET['id']??$_POST['event_id']??0));$event=$eventId>0?user_calendar_event_v1300($pdo,$userId,$eventId):null;if($eventId>0&&!$event)redirect(url('/calendar.php'));
$manualMeetingReady=function_exists('video_meeting_manual_schema_ready_v1830')&&video_meeting_manual_schema_ready_v1830($pdo);
$linkedMeeting=$event&&video_meeting_schema_ready_v1800($pdo)?video_meeting_for_calendar_event_v1800($pdo,(int)$event['id']):null;
$error='';$notice=trim((string)($_GET['saved']??''));$defaultTimezone=user_calendar_default_timezone_v1300($pdo,$user);$tz=new DateTimeZone($defaultTimezone);$now=new DateTimeImmutable('now',$tz);$minute=(int)$now->format('i');$rounded=$now->modify('+'.(60-$minute).' minutes')->setTime((int)$now->modify('+'.(60-$minute).' minutes')->format('H'),0);$parts=$event?user_calendar_event_local_parts_v1300($event,$defaultTimezone):['timezone'=>$defaultTimezone,'all_day'=>false,'date'=>$rounded->format('Y-m-d'),'start_time'=>$rounded->format('H:i'),'end_date'=>$rounded->format('Y-m-d'),'end_time'=>$rounded->modify('+1 hour')->format('H:i')];
$guestAccessMode=$linkedMeeting&&$manualMeetingReady?video_meeting_guest_access_mode_v1830($pdo,$linkedMeeting):'invite_only';
$attendeeRaw=(string)($_POST['video_attendees']??'');$videoRequested=$linkedMeeting||!empty($_POST['add_video_meeting']);
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verify_csrf())$error='Session expired. Please try again.';else try{
  $action=trim((string)($_POST['action']??'save'));
  if($action==='cancel'){
   if(!$event)throw new RuntimeException('Calendar event could not be removed.');
   $cancelledMeeting=null;$pdo->beginTransaction();
   try{
    if($linkedMeeting&&$manualMeetingReady)$cancelledMeeting=video_meeting_manual_cancel_event_v1830($pdo,$user,$event);
    if(!user_calendar_cancel_event_v1300($pdo,$user,$eventId))throw new RuntimeException('Calendar event could not be removed.');
    $pdo->commit();
   }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
   if($cancelledMeeting)video_meeting_manual_after_cancel_v1830($pdo,$cancelledMeeting);
   agent_tool_log($user,'calendar.event.cancel','Calendar event editor','success',['event_id'=>$eventId,'video_meeting_id'=>(int)($cancelledMeeting['id']??0)]);redirect(url('/calendar.php?month='.rawurlencode(substr((string)$parts['date'],0,7)).'&saved='.rawurlencode('Event removed.')));
  }
  $input=['title'=>(string)($_POST['title']??''),'description'=>(string)($_POST['description']??''),'location'=>(string)($_POST['location']??''),'date'=>(string)($_POST['date']??''),'start_time'=>(string)($_POST['start_time']??''),'end_date'=>(string)($_POST['end_date']??''),'end_time'=>(string)($_POST['end_time']??''),'timezone'=>(string)($_POST['timezone']??$defaultTimezone),'all_day'=>!empty($_POST['all_day'])];
  $videoRequested=$linkedMeeting||!empty($_POST['add_video_meeting']);$manualResult=null;$pdo->beginTransaction();
  try{
   if($event){$saved=user_calendar_update_event_v1300($pdo,$user,$eventId,$input);$message='Event updated.';}
   else{$saved=user_calendar_create_local_event_v1300($pdo,$user,$input,'user');$message='Event added to your calendar.';}
   if($videoRequested){
    if(!$manualMeetingReady)throw new RuntimeException('Manual Video Meetings need the current VP3 database upgrade before this event can be saved as a video meeting.');
    $attendees=video_meeting_manual_parse_attendees_v1830($attendeeRaw);
    $guestAccessMode=(string)($_POST['guest_access_mode']??$guestAccessMode);
    $manualResult=video_meeting_manual_sync_event_v1830($pdo,$user,$saved,$attendees,$guestAccessMode);
   }
   $pdo->commit();
  }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
  $savedId=(int)$saved['id'];$eventId=$savedId;$event=$saved;$delivery=['emails_sent'=>0,'emails_failed'=>0];
  if($manualResult){
   $delivery=video_meeting_manual_after_commit_v1830($pdo,$manualResult,!empty($_POST['send_guest_emails']));
   $linkedMeeting=$manualResult['meeting'];$guestAccessMode=(string)$manualResult['guest_access_mode'];$message.=' VP3 video meeting ready.';
   if((int)$delivery['emails_sent']>0)$message.=' '.(int)$delivery['emails_sent'].' guest invitation'.((int)$delivery['emails_sent']===1?'':'s').' emailed.';
   if((int)$delivery['emails_failed']>0)$message.=' '.(int)$delivery['emails_failed'].' guest email'.((int)$delivery['emails_failed']===1?'':'s').' could not be sent.';
  }
  agent_tool_log($user,$event?'calendar.event.update':'calendar.event.create','Calendar event editor','success',['event_id'=>$savedId,'video_meeting_id'=>(int)($linkedMeeting['id']??0)]);
  $local=user_calendar_event_local_parts_v1300($saved,$defaultTimezone);
  if($manualResult)redirect(url('/calendar-event.php?id='.$savedId.'&saved='.rawurlencode($message)));
  redirect(url('/calendar.php?month='.rawurlencode(substr((string)$local['date'],0,7)).'&saved='.rawurlencode($message)));
 }catch(Throwable $e){$error=$e->getMessage();$parts=['timezone'=>(string)($_POST['timezone']??$defaultTimezone),'all_day'=>!empty($_POST['all_day']),'date'=>(string)($_POST['date']??''),'start_time'=>(string)($_POST['start_time']??''),'end_date'=>(string)($_POST['end_date']??''),'end_time'=>(string)($_POST['end_time']??'')];}
}
$timezones=DateTimeZone::listIdentifiers();$titleValue=(string)($_POST['title']??($event['title']??''));$locationValue=(string)($_POST['location']??($event['location']??''));$descriptionValue=(string)($_POST['description']??($event['description']??''));
$linkedMeeting=$event&&video_meeting_schema_ready_v1800($pdo)?video_meeting_for_calendar_event_v1800($pdo,(int)$event['id']):$linkedMeeting;$videoRequested=$linkedMeeting||!empty($_POST['add_video_meeting']);
if($linkedMeeting&&$manualMeetingReady)$guestAccessMode=video_meeting_guest_access_mode_v1830($pdo,$linkedMeeting);
$meetingParticipants=$linkedMeeting?array_values(array_filter(video_meeting_participants_v1800($pdo,(int)$linkedMeeting['id']),fn($p)=>(string)($p['role']??'')==='attendee')):[];$publicGuestUrl='';$shareError='';
if($linkedMeeting&&$manualMeetingReady&&$guestAccessMode==='email_gate')try{$publicGuestUrl=video_meeting_public_guest_url_v1830($linkedMeeting);}catch(Throwable $e){$shareError=$e->getMessage();}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f7f7f5"><title><?= e(system_agent_name()) ?> | <?= $event?'Edit Event':'New Event' ?></title><link rel="stylesheet" href="<?= e(url('/chat.css?v=82')) ?>"><link rel="stylesheet" href="<?= e(url('/calendar-v1300.css?v=1830')) ?>"></head><body class="calendar-page"><div class="chat-app">
<?php $workspaceSidebarUser=$user;$workspaceSidebarActive='calendar';require __DIR__.'/includes/workspace-sidebar-v82.php'; ?><div class="chat-sidebar-backdrop" id="chatSidebarBackdrop"></div><main class="chat-main calendar-main">
<?php $memberHeaderUser=$user;$memberHeaderTitle=$event?'Edit calendar event':'New calendar event';$memberHeaderSubtitle='Personal events, meetings, reminders + Agent-managed time';$memberHeaderActions='<a class="calendar-button" href="'.e(url('/calendar.php')).'">← Calendar</a>';require __DIR__.'/includes/member-header.php'; ?>
<section class="calendar-canvas"><div class="calendar-form-shell"><?php if($notice!==''): ?><div class="calendar-notice success"><?= e($notice) ?></div><?php endif; ?><?php if($error!==''): ?><div class="calendar-notice error" role="alert"><?= e($error) ?></div><?php endif; ?><div class="calendar-help"><strong>Calendar event</strong> — create private time or turn this event into a VP3 video meeting. For a public appointment people can book themselves, use <a href="<?= e(url('/scheduling-type.php')) ?>">Scheduling → New appointment type</a>.</div>
<div class="calendar-form-card"><h1><?= $event?'Edit event':'Create event' ?></h1><p><?= $event?'Update the event and its linked VP3 meeting in one place.':'Add personal time or create a VP3 video meeting and invite members or guests.' ?></p>
<form method="post" class="calendar-form" id="calendarEventForm"><?= csrf_field() ?><input type="hidden" name="action" value="save"><input type="hidden" name="event_id" value="<?= $eventId ?>">
<label class="span-2"><span>Event title</span><input name="title" maxlength="190" required value="<?= e($titleValue) ?>" placeholder="Project review"></label>
<label><span>Date</span><input type="date" name="date" required value="<?= e((string)$parts['date']) ?>"></label><label class="checkline"><input type="checkbox" name="all_day" value="1" <?= !empty($parts['all_day'])?'checked':'' ?>><span>All-day event</span></label>
<label><span>Start time</span><input type="time" name="start_time" value="<?= e((string)$parts['start_time']) ?>"></label><label><span>End time</span><input type="time" name="end_time" value="<?= e((string)$parts['end_time']) ?>"></label>
<label><span>End date</span><input type="date" name="end_date" value="<?= e((string)$parts['end_date']) ?>"></label><label><span>Timezone</span><select name="timezone"><?php foreach($timezones as $timezone): ?><option value="<?= e($timezone) ?>" <?= $timezone===(string)$parts['timezone']?'selected':'' ?>><?= e($timezone) ?></option><?php endforeach; ?></select></label>
<label class="span-2"><span>Location</span><input name="location" maxlength="500" value="<?= e($locationValue) ?>" placeholder="Address, room, link or leave blank"></label><label class="span-2"><span>Notes</span><textarea name="description" rows="5" maxlength="10000" placeholder="Optional event notes"><?= e($descriptionValue) ?></textarea></label>
<div class="span-2" style="border-top:1px solid rgba(127,127,127,.18);padding-top:18px"><label class="checkline"><input type="checkbox" id="addVideoMeeting" name="add_video_meeting" value="1" <?= $videoRequested?'checked':'' ?> <?= $linkedMeeting?'disabled':'' ?>><span><strong>Add VP3 video meeting</strong></span></label><?php if($linkedMeeting): ?><input type="hidden" name="add_video_meeting" value="1"><div class="calendar-help" style="margin-top:8px">This event already owns a VP3 meeting. Editing the event keeps the same meeting identity and link; removing the event cancels the meeting.</div><?php elseif(!$manualMeetingReady): ?><div class="calendar-help" style="margin-top:8px">Run the current <a href="<?= e(url('/upgrade.php')) ?>">database upgrade</a> before creating manual video meetings.</div><?php endif; ?></div>
<div class="span-2" id="videoMeetingOptions" <?= $videoRequested?'':'hidden' ?>><div class="calendar-help"><strong>Attendees</strong> — VP3 accounts are recognized by email and receive a native VP3 notification and calendar event. Other addresses become guests. On an existing meeting, this field only adds new attendees; existing invitations remain valid.</div><label style="display:block;margin-top:12px"><span>Invite attendees — one per line</span><textarea name="video_attendees" rows="5" maxlength="10000" placeholder="alex@example.com&#10;Jordan Smith &lt;jordan@example.com&gt;"><?= e($attendeeRaw) ?></textarea></label><label style="display:block;margin-top:12px"><span>Guest access</span><select name="guest_access_mode"><option value="invite_only" <?= $guestAccessMode==='invite_only'?'selected':'' ?>>Private invitation link — each guest gets an individual secure link</option><option value="email_gate" <?= $guestAccessMode==='email_gate'?'selected':'' ?>>Public meeting page — invited guest must enter their email</option></select></label><label class="checkline" style="margin-top:12px"><input type="checkbox" name="send_guest_emails" value="1" <?= !empty($_POST['send_guest_emails'])?'checked':'' ?>><span>Email newly added non-VP3 guests after saving</span></label><div class="calendar-help" style="margin-top:8px">Recording stays off by default. Meeting transcription and Phase 18.2 Meeting Intelligence use the organizer's existing VP3/HomeServer processing policy.</div></div>
<div class="calendar-form-actions"><a class="calendar-button" href="<?= e(url('/calendar.php')) ?>">Cancel</a><button class="calendar-button primary" type="submit"><?= $event?'Save changes':'Add event' ?></button></div></form>
<?php if($linkedMeeting): ?><div class="calendar-help" style="margin-top:18px"><strong>Meeting access</strong><br><?= count($meetingParticipants) ?> attendee<?= count($meetingParticipants)===1?'':'s' ?> invited.<?php if($guestAccessMode==='email_gate'): ?><br>Guest mode: public meeting page + invited email verification.<?php else: ?><br>Guest mode: private invitation links. VP3 members can use the meeting from their notification/calendar.<?php endif; ?></div><?php if($guestAccessMode==='email_gate'): ?><?php if($publicGuestUrl!==''): ?><label style="display:block;margin-top:12px"><span>Public guest meeting link</span><div style="display:flex;gap:8px"><input id="publicMeetingLink" readonly value="<?= e($publicGuestUrl) ?>"><button class="calendar-button" type="button" id="copyMeetingLink">Copy</button></div></label><?php elseif($shareError!==''): ?><div class="calendar-notice error" style="margin-top:12px"><?= e($shareError) ?></div><?php endif; ?><?php endif; ?><?php endif; ?>
<?php if($event): ?><form method="post" style="margin-top:18px" onsubmit="return confirm('Remove this event from your calendar<?= $linkedMeeting?' and cancel its VP3 meeting':'' ?>?')"><?= csrf_field() ?><input type="hidden" name="action" value="cancel"><input type="hidden" name="event_id" value="<?= $eventId ?>"><button class="calendar-danger" type="submit">Remove event<?= $linkedMeeting?' + cancel meeting':'' ?></button></form><?php endif; ?>
</div></div></section></main></div><script src="<?= e(url('/member-shell-v77.js?v=20260911')) ?>"></script><script>(function(){const box=document.getElementById('addVideoMeeting'),opts=document.getElementById('videoMeetingOptions');if(box&&opts&&!box.disabled)box.addEventListener('change',()=>{opts.hidden=!box.checked});const copy=document.getElementById('copyMeetingLink'),link=document.getElementById('publicMeetingLink');if(copy&&link)copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(link.value);copy.textContent='Copied';setTimeout(()=>copy.textContent='Copy',1500)}catch(e){link.select()}})})();</script></body></html>