<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
require_login();

$user=current_user();$pdo=db();
if(!$user||!$pdo){http_response_code(503);exit('Campaigns & Rewards is unavailable.');}
if(!function_exists('campaigns_rewards_platform_schema_ready_v100')||!campaigns_rewards_platform_schema_ready_v100($pdo)){http_response_code(503);exit('Campaigns & Rewards needs the latest VP3 database upgrade.');}
if(!campaigns_rewards_user_has_access_v100($pdo,$user)){flash('error','Enable Campaigns & Rewards or ask a Merchant Owner for access.');redirect(url('/plugins.php'));}

$uid=(int)$user['id'];$merchantId=max(0,(int)($_REQUEST['merchant']??$_REQUEST['merchant_id']??0));
$redirectMerchant=static function(int $id,string $suffix=''): never{redirect(url('/campaigns.php'.($id>0?'?merchant='.$id:'').$suffix));};

if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!verify_csrf()){flash('error','Session expired. Try again.');$redirectMerchant($merchantId);}
    $action=(string)($_POST['action']??'');
    try{
        if($action==='merchant_create'){
            $merchant=campaigns_rewards_create_merchant_v100($pdo,$user,$_POST);
            flash('notice','Merchant created.');$redirectMerchant((int)$merchant['id']);
        }
        if($merchantId<1)throw new RuntimeException('Choose a Merchant.');
        if($action==='merchant_update'){
            campaigns_rewards_update_merchant_v100($pdo,$merchantId,$uid,$_POST);flash('notice','Merchant updated.');
        }elseif($action==='merchant_status'){
            campaigns_rewards_set_platform_merchant_status_v100($pdo,$merchantId,$uid,(string)($_POST['status']??'active'),(string)($_POST['reason']??''));flash('notice','Merchant lifecycle updated.');
        }elseif($action==='location_save'){
            campaigns_rewards_save_location_v100($pdo,$merchantId,$uid,$_POST,max(0,(int)($_POST['location_id']??0)));flash('notice','Merchant Location saved.');
        }elseif($action==='campaign_save'){
            $campaign=campaigns_rewards_save_campaign_v100($pdo,$merchantId,$uid,$_POST,max(0,(int)($_POST['campaign_id']??0)));
            flash('notice','Campaign saved.');$redirectMerchant($merchantId,'&edit_campaign='.(int)$campaign['id'].'#campaign-editor');
        }elseif($action==='campaign_status'){
            campaigns_rewards_set_campaign_status_v100($pdo,max(0,(int)($_POST['campaign_id']??0)),$uid,(string)($_POST['status']??'draft'));flash('notice','Campaign lifecycle updated.');
        }elseif($action==='reward_save'){
            campaigns_rewards_save_reward_v100($pdo,max(0,(int)($_POST['campaign_id']??0)),$uid,$_POST,max(0,(int)($_POST['reward_id']??0)));flash('notice','Reward Product saved and attached.');
        }elseif($action==='merchant_member_save'){
            if(!campaigns_rewards_can_own_merchant_v100($pdo,$merchantId,$uid))throw new RuntimeException('Merchant Owner access is required.');
            $email=strtolower(trim((string)($_POST['member_email']??'')));if(!filter_var($email,FILTER_VALIDATE_EMAIL))throw new RuntimeException('Enter an active VP3 user email.');
            $stmt=$pdo->prepare('SELECT id FROM users WHERE email=? AND is_active=1 LIMIT 1');$stmt->execute([$email]);$memberUserId=(int)$stmt->fetchColumn();if($memberUserId<1)throw new RuntimeException('That email does not belong to an active VP3 user.');
            campaigns_rewards_set_member_role_v100($pdo,$merchantId,$uid,$memberUserId,(string)($_POST['member_role']??'customer_service'));flash('notice','Merchant role updated.');
        }elseif($action==='merchant_member_remove'){
            if(!campaigns_rewards_can_own_merchant_v100($pdo,$merchantId,$uid))throw new RuntimeException('Merchant Owner access is required.');
            campaigns_rewards_remove_platform_member_v100($pdo,$merchantId,$uid,max(0,(int)($_POST['member_user_id']??0)),(string)($_POST['reason']??''));flash('notice','Direct Merchant access removed. Any independent Merchant Team grant remains bounded.');
        }elseif($action==='claim_code_create'){
            $code=campaigns_rewards_create_claim_code_v100($pdo,$merchantId,$uid,[
                'display_name'=>$_POST['display_name']??'Claim Code','location_id'=>$_POST['location_id']??0,'device_label'=>$_POST['device_label']??'',
                'daily_claim_limit'=>$_POST['daily_claim_limit']??null,'total_claim_limit'=>$_POST['total_claim_limit']??null,'max_value_minor'=>$_POST['max_value_minor']??null,
                'campaign_ids'=>array_filter(array_map('intval',(array)($_POST['campaign_ids']??[]))),
            ]);
            if(session_status()===PHP_SESSION_ACTIVE)$_SESSION['campaigns_claim_code_once']=['merchant_id'=>$merchantId,'code'=>$code['code'],'display_name'=>$code['display_name'],'public_id'=>$code['public_id']];
            flash('notice','Merchant Claim Code created. Copy it now; VP3 stores only its hash.');
        }elseif($action==='make_good'){
            $email=strtolower(trim((string)($_POST['contact_email']??'')));if(!filter_var($email,FILTER_VALIDATE_EMAIL))throw new RuntimeException('Enter a customer email.');
            $contact=campaigns_rewards_resolve_contact_v100($pdo,$merchantId,['name'=>$_POST['contact_name']??$email,'email'=>$email,'phone'=>$_POST['contact_phone']??'','source'=>'make_good']);
            campaigns_rewards_ensure_merchant_relationship_v100($pdo,$merchantId,(int)$contact['id'],['customer_status'=>'customer','acquisition_source'=>'make_good']);
            $result=campaigns_rewards_make_good_v100($pdo,$merchantId,(int)$contact['id'],$uid,[max(0,(int)($_POST['reward_product_id']??0))],['reason_code'=>$_POST['reason_code']??'service_recovery','summary'=>$_POST['summary']??'Make Good','internal_notes'=>$_POST['internal_notes']??'']);
            $first=$result['issuances'][0]??null;if($first&&session_status()===PHP_SESSION_ACTIVE)$_SESSION['campaigns_reward_secret_once']=['credential'=>$first['credential']??'','public_id'=>$first['public_id']??'','contact_email'=>$email];
            flash('notice','Make Good case opened and Reward issued.');
        }elseif($action==='reconcile'){
            $run=campaigns_rewards_reconcile_v100($pdo,$merchantId,$uid);flash('notice','Reconciliation complete: '.(int)$run['summary']['findings'].' finding(s), no side effects replayed.');
        }else{
            throw new RuntimeException('Unknown Campaigns & Rewards action.');
        }
    }catch(Throwable $e){flash('error',$e->getMessage());}
    $redirectMerchant($merchantId);
}

$merchants=campaigns_rewards_accessible_merchants_v100($pdo,$user);$merchant=null;
if($merchantId>0)foreach($merchants as $candidate)if((int)$candidate['id']===$merchantId){$merchant=$candidate;break;}
if(!$merchant&&$merchants){$merchant=$merchants[0];$merchantId=(int)$merchant['id'];}
$canCreate=campaigns_rewards_enabled_v100($user,$pdo);
$canManage=$merchant?campaigns_rewards_platform_can_v100($pdo,$merchantId,$uid,'merchant.manage'):false;
$canOwn=$merchant?campaigns_rewards_can_own_merchant_v100($pdo,$merchantId,$uid):false;
$canLocations=$merchant?campaigns_rewards_platform_can_v100($pdo,$merchantId,$uid,'locations.manage'):false;
$canCampaignEdit=$merchant?campaigns_rewards_platform_can_v100($pdo,$merchantId,$uid,'campaigns.edit'):false;
$canRewardManage=$merchant?campaigns_rewards_platform_can_v100($pdo,$merchantId,$uid,'rewards.manage'):false;
$canClaimCodes=$merchant?campaigns_rewards_platform_can_v100($pdo,$merchantId,$uid,'claim_codes.manage'):false;
$canClaim=$merchant?campaigns_rewards_platform_can_v100($pdo,$merchantId,$uid,'claims.process'):false;
$canAnalytics=$merchant?campaigns_rewards_platform_can_v100($pdo,$merchantId,$uid,'analytics.view'):false;

$locations=$merchant?campaigns_rewards_locations_v100($pdo,$merchantId):[];
$campaigns=$merchant?campaigns_rewards_campaigns_v100($pdo,$merchantId):[];
$members=$merchant?campaigns_rewards_merchant_members_v100($pdo,$merchantId):[];
$report=$merchant&&$canAnalytics?campaigns_rewards_reporting_v100($pdo,$merchantId,$uid):['active_campaigns'=>0,'landing_views'=>0,'customers'=>0,'claims_issued'=>0,'claims_redeemed'=>0,'redemption_rate'=>0];
$campaignTypes=[];$rewardProducts=[];$claimCodes=[];$recentClaims=[];
if($merchant){
    $s=$pdo->prepare("SELECT type_key,name FROM campaign_types WHERE is_active=1 AND (merchant_id=? OR merchant_id IS NULL) ORDER BY is_system DESC,name");$s->execute([$merchantId]);$campaignTypes=$s->fetchAll()?:[];
    $s=$pdo->prepare("SELECT rp.id,rp.public_id,rp.name,rp.is_active,rt.name reward_type_name FROM reward_products rp INNER JOIN reward_types rt ON rt.id=rp.reward_type_id WHERE rp.merchant_id=? ORDER BY rp.updated_at DESC,rp.id DESC");$s->execute([$merchantId]);$rewardProducts=$s->fetchAll()?:[];
    $s=$pdo->prepare("SELECT * FROM merchant_claim_codes WHERE merchant_id=? ORDER BY updated_at DESC,id DESC LIMIT 30");$s->execute([$merchantId]);$claimCodes=$s->fetchAll()?:[];
    $s=$pdo->prepare("SELECT rc.public_id,rc.status,rc.claimed_at,rc.reversed_at,rp.name reward_title,c.name campaign_title,cc.name customer_name
      FROM reward_claims rc INNER JOIN reward_issuances ri ON ri.id=rc.reward_issuance_id INNER JOIN reward_products rp ON rp.id=ri.reward_product_id
      INNER JOIN campaigns c ON c.id=rc.campaign_id INNER JOIN crm_contacts cc ON cc.id=ri.recipient_contact_id
      WHERE rc.merchant_id=? ORDER BY rc.id DESC LIMIT 30");$s->execute([$merchantId]);$recentClaims=$s->fetchAll()?:[];
}
$editCampaignId=max(0,(int)($_GET['edit_campaign']??0));$editCampaign=null;foreach($campaigns as $row)if((int)$row['id']===$editCampaignId)$editCampaign=$row;
$editLocationId=max(0,(int)($_GET['edit_location']??0));$editLocation=null;foreach($locations as $row)if((int)$row['id']===$editLocationId)$editLocation=$row;
$rewardCampaignId=max(0,(int)($_GET['reward_campaign']??$editCampaignId));$rewardRows=$rewardCampaignId>0?campaigns_rewards_rewards_v100($pdo,$rewardCampaignId):[];
$editRewardId=max(0,(int)($_GET['edit_reward']??0));$editReward=null;foreach($rewardRows as $row)if((int)$row['id']===$editRewardId)$editReward=$row;

$claimCodeOnce=null;$rewardSecretOnce=null;
if(session_status()===PHP_SESSION_ACTIVE){
    $claimCodeOnce=$_SESSION['campaigns_claim_code_once']??null;unset($_SESSION['campaigns_claim_code_once']);
    $rewardSecretOnce=$_SESSION['campaigns_reward_secret_once']??null;unset($_SESSION['campaigns_reward_secret_once']);
}
$notice=flash('notice');$error=flash('error');
$memberHeaderUser=$user;$memberHeaderTitle='Campaigns & Rewards';$memberHeaderSubtitle='Merchant CRM, Campaigns, Reward Wallet, Claiming and reporting';
$actions=[];$actions[]='<a class="cr-btn" href="'.e(url('/rewards-wallet.php')).'">Reward Wallet</a>';if($canClaim)$actions[]='<a class="cr-btn primary" href="'.e(url('/campaign-claim.php?merchant='.$merchantId)).'">Claim Terminal</a>';if($canCreate)$actions[]='<a class="cr-btn" href="'.e(url('/campaigns.php?new_merchant=1#new-merchant')).'">+ Merchant</a>';$memberHeaderActions=implode(' ',$actions);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f7f7f8"><title>VP3 | Campaigns & Rewards</title>
<link rel="stylesheet" href="<?= e(url('/chat.css?v=82')) ?>"><link rel="stylesheet" href="<?= e(url('/campaigns-v100.css?v=101')) ?>"></head>
<body class="cr-page"><div class="chat-app"><?php $workspaceSidebarUser=$user;$workspaceSidebarActive='campaigns';require __DIR__.'/includes/workspace-sidebar-v82.php'; ?><div class="chat-sidebar-backdrop" id="chatSidebarBackdrop"></div>
<main class="chat-main cr-main"><?php require __DIR__.'/includes/member-header.php'; ?><div class="cr-wrap">
<?php if($notice):?><div class="cr-notice success"><?= e($notice) ?></div><?php endif;?><?php if($error):?><div class="cr-notice error"><?= e($error) ?></div><?php endif;?>
<?php if($claimCodeOnce&&((int)($claimCodeOnce['merchant_id']??0)===$merchantId)):?><div class="cr-notice success"><strong><?= e((string)$claimCodeOnce['display_name']) ?>:</strong> <code><?= e((string)$claimCodeOnce['code']) ?></code> — copy this now. Only the hash is stored.</div><?php endif;?>
<?php if($rewardSecretOnce&&!empty($rewardSecretOnce['credential'])):?><div class="cr-notice success"><strong>Make Good Reward Credential:</strong> <code><?= e((string)$rewardSecretOnce['credential']) ?></code> for <?= e((string)$rewardSecretOnce['contact_email']) ?>. Copy it now.</div><?php endif;?>

<section class="cr-toolbar"><div><strong>Merchant workspace</strong><span>Business identity is separate from your VP3 login; Team scope and direct Merchant roles remain independent.</span></div><?php if($merchants):?><form method="get"><select name="merchant" onchange="this.form.submit()"><?php foreach($merchants as $m):?><option value="<?= (int)$m['id'] ?>"<?= (int)$m['id']===$merchantId?' selected':'' ?>><?= e((string)$m['name']) ?> · <?= e(ucwords(str_replace('_',' ',(string)$m['access_role']))) ?></option><?php endforeach;?></select></form><?php endif;?></section>

<?php if(!$merchant):?>
<section class="cr-empty" id="new-merchant"><h2>Create your first Merchant</h2><p>Merchants own business state; your VP3 login remains your personal identity.</p><?php if($canCreate):?><form method="post" class="cr-form"><?= csrf_field() ?><input type="hidden" name="action" value="merchant_create"><label>Name<input name="name" required maxlength="190"></label><label>Public slug<input name="slug" maxlength="100"></label><label>Description<textarea name="description"></textarea></label><div class="cr-form-grid"><label>Website<input name="website_url"></label><label>Timezone<input name="timezone" value="America/Phoenix"></label><label>Currency<input name="currency" value="USD" maxlength="3"></label></div><label class="cr-check"><input type="checkbox" name="sandbox_mode" value="1"> Sandbox Merchant</label><button class="cr-btn primary">Create Merchant</button></form><?php else:?><a class="cr-btn primary" href="<?= e(url('/plugins.php')) ?>">Enable plugin</a><?php endif;?></section>
<?php else:?>

<?php if($canAnalytics):?><section class="cr-metrics"><article><span>Active Campaigns</span><strong><?= number_format((int)$report['active_campaigns']) ?></strong></article><article><span>Landing views</span><strong><?= number_format((int)$report['landing_views']) ?></strong></article><article><span>Merchant relationships</span><strong><?= number_format((int)$report['customers']) ?></strong></article><article><span>Claims</span><strong><?= number_format((int)$report['claims_redeemed']) ?> / <?= number_format((int)$report['claims_issued']) ?></strong><small><?= e(number_format((float)$report['redemption_rate'],1)) ?>% redemption</small></article></section><?php endif;?>

<div class="cr-grid">
<section class="cr-card"><header><div><span>Merchant</span><h2><?= e((string)$merchant['name']) ?></h2></div><strong><?= e(ucfirst((string)$merchant['status'])) ?></strong></header><p><?= e((string)($merchant['description']??'')) ?></p>
<?php if($canManage):?><form method="post" class="cr-form"><?= csrf_field() ?><input type="hidden" name="action" value="merchant_update"><input type="hidden" name="merchant_id" value="<?= $merchantId ?>"><label>Name<input name="name" required value="<?= e((string)$merchant['name']) ?>"></label><label>Slug<input name="slug" required value="<?= e((string)$merchant['slug']) ?>"></label><label>Description<textarea name="description"><?= e((string)($merchant['description']??'')) ?></textarea></label><div class="cr-form-grid"><label>Website<input name="website_url" value="<?= e((string)($merchant['website_url']??'')) ?>"></label><label>Email<input name="contact_email" type="email" value="<?= e((string)($merchant['contact_email']??'')) ?>"></label><label>Phone<input name="contact_phone" value="<?= e((string)($merchant['contact_phone']??'')) ?>"></label><label>Timezone<input name="timezone" value="<?= e((string)$merchant['timezone']) ?>"></label><label>Currency<input name="currency" maxlength="3" value="<?= e((string)$merchant['currency']) ?>"></label></div><label class="cr-check"><input type="checkbox" name="sandbox_mode" value="1"<?= !empty($merchant['sandbox_mode'])?' checked':'' ?>> Sandbox mode</label><button class="cr-btn">Save Merchant</button></form>
<form method="post" class="cr-inline"><?= csrf_field() ?><input type="hidden" name="action" value="merchant_status"><input type="hidden" name="merchant_id" value="<?= $merchantId ?>"><select name="status"><?php foreach(['active','suspended','archived','closed'] as $st):?><option value="<?= e($st) ?>"<?= $merchant['status']===$st?' selected':'' ?>><?= e(ucfirst($st)) ?></option><?php endforeach;?></select><input name="reason" placeholder="Reason"><button>Update lifecycle</button></form><?php endif;?></section>

<section class="cr-card"><header><div><span>Locations</span><h2>Merchant Locations</h2></div></header><div class="cr-list"><?php foreach($locations as $location):?><article><div><strong><?= e((string)$location['name']) ?><?= !empty($location['is_primary'])?' · Primary':'' ?></strong><small><?= e(trim((string)$location['city'].', '.(string)$location['region'],', ')) ?></small></div><?php if($canLocations):?><a href="<?= e(url('/campaigns.php?merchant='.$merchantId.'&edit_location='.(int)$location['id'].'#location-editor')) ?>">Edit</a><?php endif;?></article><?php endforeach;?><?php if(!$locations):?><p>No Locations yet.</p><?php endif;?></div>
<?php if($canLocations):?><form method="post" class="cr-form cr-subform" id="location-editor"><?= csrf_field() ?><input type="hidden" name="action" value="location_save"><input type="hidden" name="merchant_id" value="<?= $merchantId ?>"><input type="hidden" name="location_id" value="<?= (int)($editLocation['id']??0) ?>"><h3><?= $editLocation?'Edit':'Add' ?> Location</h3><label>Name<input name="name" required value="<?= e((string)($editLocation['name']??'')) ?>"></label><div class="cr-form-grid"><label>Address<input name="address_line1" value="<?= e((string)($editLocation['address_line1']??'')) ?>"></label><label>City<input name="city" value="<?= e((string)($editLocation['city']??'')) ?>"></label><label>State / region<input name="region" value="<?= e((string)($editLocation['region']??'')) ?>"></label><label>Postal code<input name="postal_code" value="<?= e((string)($editLocation['postal_code']??'')) ?>"></label><label>Type<input name="location_type" value="<?= e((string)($editLocation['location_type']??'store')) ?>"></label></div><label class="cr-check"><input type="checkbox" name="is_primary" value="1"<?= !empty($editLocation['is_primary'])?' checked':'' ?>> Primary Location</label><button class="cr-btn">Save Location</button></form><?php endif;?></section>
</div>

<section class="cr-card" id="campaign-editor"><header><div><span>Campaigns</span><h2>Campaign lifecycle & landing pages</h2></div><?php if($canCampaignEdit):?><a class="cr-btn primary" href="<?= e(url('/campaigns.php?merchant='.$merchantId.'&edit_campaign=0#campaign-editor')) ?>">+ Campaign</a><?php endif;?></header>
<div class="cr-campaign-grid"><?php foreach($campaigns as $campaign):?><article class="cr-campaign"><div class="cr-status <?= e((string)$campaign['status']) ?>"><?= e(ucfirst((string)$campaign['status'])) ?></div><h3><?= e((string)$campaign['title']) ?></h3><p><?= e((string)$campaign['subtitle']) ?></p><small><?= e(ucwords(str_replace('_',' ',(string)($campaign['campaign_type_key']??'campaign')))) ?> · v<?= (int)$campaign['current_version_no'] ?></small><div class="cr-actions"><a href="<?= e(campaigns_rewards_campaign_url_v100((string)$campaign['slug'])) ?>" target="_blank">Landing page ↗</a><?php if($canCampaignEdit):?><a href="<?= e(url('/campaigns.php?merchant='.$merchantId.'&edit_campaign='.(int)$campaign['id'].'#campaign-editor')) ?>">Edit</a><a href="<?= e(url('/campaigns.php?merchant='.$merchantId.'&reward_campaign='.(int)$campaign['id'].'#rewards')) ?>">Rewards</a><?php endif;?></div><?php if($canCampaignEdit):?><form method="post" class="cr-inline"><?= csrf_field() ?><input type="hidden" name="action" value="campaign_status"><input type="hidden" name="merchant_id" value="<?= $merchantId ?>"><input type="hidden" name="campaign_id" value="<?= (int)$campaign['id'] ?>"><select name="status"><?php foreach(['draft','scheduled','active','paused','completed','archived'] as $st):?><option value="<?= e($st) ?>"<?= $campaign['status']===$st?' selected':'' ?>><?= e(ucfirst($st)) ?></option><?php endforeach;?></select><button>Update</button></form><?php endif;?></article><?php endforeach;?></div>
<?php if($canCampaignEdit):?><form method="post" class="cr-form cr-editor"><?= csrf_field() ?><input type="hidden" name="action" value="campaign_save"><input type="hidden" name="merchant_id" value="<?= $merchantId ?>"><input type="hidden" name="campaign_id" value="<?= (int)($editCampaign['id']??0) ?>"><h3><?= $editCampaign?'Edit Campaign':'Create Campaign' ?></h3><div class="cr-form-grid"><label>Campaign Type<select name="campaign_type"><?php foreach($campaignTypes as $type):?><option value="<?= e((string)$type['type_key']) ?>"<?= ($editCampaign['campaign_type_key']??'signup')===$type['type_key']?' selected':'' ?>><?= e((string)$type['name']) ?></option><?php endforeach;?></select></label><label>Title<input name="title" required value="<?= e((string)($editCampaign['title']??'')) ?>"></label><label>Public slug<input name="slug" value="<?= e((string)($editCampaign['slug']??'')) ?>"></label><label>Subtitle<input name="subtitle" value="<?= e((string)($editCampaign['subtitle']??'')) ?>"></label><label>CTA label<input name="cta_label" value="<?= e((string)($editCampaign['cta_label']??'Claim reward')) ?>"></label><label>Location<select name="location_id"><option value="">All Locations</option><?php foreach($locations as $location):?><option value="<?= (int)$location['id'] ?>"<?= (int)($editCampaign['location_id']??0)===(int)$location['id']?' selected':'' ?>><?= e((string)$location['name']) ?></option><?php endforeach;?></select></label><label>Starts<input name="starts_at" type="datetime-local" value="<?= !empty($editCampaign['starts_at'])?e(date('Y-m-d\TH:i',strtotime((string)$editCampaign['starts_at']))):'' ?>"></label><label>Ends<input name="ends_at" type="datetime-local" value="<?= !empty($editCampaign['ends_at'])?e(date('Y-m-d\TH:i',strtotime((string)$editCampaign['ends_at']))):'' ?>"></label></div><label>Objective<input name="objective" value="<?= e((string)($editCampaign['objective']??'')) ?>"></label><label>Description<textarea name="description"><?= e((string)($editCampaign['description']??'')) ?></textarea></label><label>Terms<textarea name="terms"><?= e((string)($editCampaign['terms']??'')) ?></textarea></label><label class="cr-check"><input type="checkbox" name="profile_visible" value="1"<?= !isset($editCampaign['profile_visible'])||!empty($editCampaign['profile_visible'])?' checked':'' ?>> Publish active Campaign on Owner Profile</label><button class="cr-btn primary">Save Campaign</button></form><?php endif;?></section>

<?php if($rewardCampaignId>0&&$canRewardManage): $rewardCampaign=campaigns_rewards_campaign_v100($pdo,$rewardCampaignId); if($rewardCampaign&&(int)$rewardCampaign['merchant_account_id']===$merchantId):?>
<section class="cr-card" id="rewards"><header><div><span>Reward Products</span><h2><?= e((string)$rewardCampaign['title']) ?></h2></div></header><div class="cr-list"><?php foreach($rewardRows as $reward):?><article><div><strong><?= e((string)$reward['title']) ?></strong><small><?= e((string)$reward['value_label']) ?> · <?= e(ucwords(str_replace('_',' ',(string)$reward['reward_type']))) ?> · <?= e(ucfirst((string)$reward['status'])) ?> · Inventory <?= (int)$reward['inventory_limit']>0?number_format((int)$reward['inventory_limit']):'Untracked' ?></small></div><a href="<?= e(url('/campaigns.php?merchant='.$merchantId.'&reward_campaign='.$rewardCampaignId.'&edit_reward='.(int)$reward['id'].'#rewards')) ?>">Edit</a></article><?php endforeach;?></div><form method="post" class="cr-form cr-subform"><?= csrf_field() ?><input type="hidden" name="action" value="reward_save"><input type="hidden" name="merchant_id" value="<?= $merchantId ?>"><input type="hidden" name="campaign_id" value="<?= $rewardCampaignId ?>"><input type="hidden" name="reward_id" value="<?= (int)($editReward['id']??0) ?>"><h3><?= $editReward?'Edit':'Add' ?> Reward Product</h3><div class="cr-form-grid"><label>Name<input name="title" required value="<?= e((string)($editReward['title']??'')) ?>"></label><label>Value label<input name="value_label" placeholder="25% off, Free pizza, VIP access" value="<?= e((string)($editReward['value_label']??'')) ?>"></label><label>Type<select name="reward_type"><?php foreach(['percentage_discount','fixed_value_discount','free_product','promotional_product','merchandise','account_credit','loyalty_points','free_service','upgrade','membership_access','custom'] as $type):?><option value="<?= e($type) ?>"<?= ($editReward['reward_type']??'free_product')===$type?' selected':'' ?>><?= e(ucwords(str_replace('_',' ',$type))) ?></option><?php endforeach;?></select></label><label>Inventory<input name="inventory_limit" type="number" min="0" value="<?= (int)($editReward['inventory_limit']??0) ?>"></label><label>Per contact<input name="per_customer_limit" type="number" min="1" max="25" value="<?= (int)($editReward['per_customer_limit']??1) ?>"></label><label>Status<select name="status"><option value="active"<?= ($editReward['status']??'active')==='active'?' selected':'' ?>>Active</option><option value="inactive"<?= ($editReward['status']??'')==='inactive'?' selected':'' ?>>Inactive</option></select></label></div><label>Description<textarea name="description"><?= e((string)($editReward['description']??'')) ?></textarea></label><button class="cr-btn">Save Reward Product</button></form></section>
<?php endif; endif; ?>

<div class="cr-grid">
<section class="cr-card"><header><div><span>Merchant access</span><h2>Owners & Team</h2></div></header><div class="cr-list"><?php foreach($members as $member):?><article><div><strong><?= e((string)$member['display_name']) ?></strong><small><?= e((string)$member['email']) ?> · <?= e(ucwords(str_replace('_',' ',(string)($member['effective_role']??$member['member_role'])))) ?><?= !empty($member['team_scope_active'])?' · Merchant Team':'' ?></small></div><?php if($canOwn&&(int)$member['user_id']!==$uid):?><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="merchant_member_remove"><input type="hidden" name="merchant_id" value="<?= $merchantId ?>"><input type="hidden" name="member_user_id" value="<?= (int)$member['user_id'] ?>"><button>Remove direct access</button></form><?php endif;?></article><?php endforeach;?></div><?php if($canOwn):?><form method="post" class="cr-form cr-subform"><?= csrf_field() ?><input type="hidden" name="action" value="merchant_member_save"><input type="hidden" name="merchant_id" value="<?= $merchantId ?>"><h3>Add or update direct Merchant role</h3><label>VP3 email<input name="member_email" type="email" required></label><label>Merchant role<select name="member_role"><?php foreach(campaigns_rewards_merchant_roles_v100() as $role=>$label):?><option value="<?= e($role) ?>"><?= e($label) ?></option><?php endforeach;?></select></label><button class="cr-btn">Save role</button></form><?php endif;?><p class="cr-help">Direct Merchant roles and Merchant Team scope are independent. Removing a direct Administrator never restores admin authority through Team scope.</p></section>

<section class="cr-card"><header><div><span>Claim security</span><h2>Merchant Claim Codes</h2></div><?php if($canClaim):?><a class="cr-btn primary" href="<?= e(url('/campaign-claim.php?merchant='.$merchantId)) ?>">Open Claim Terminal</a><?php endif;?></header><div class="cr-list"><?php foreach($claimCodes as $code):?><article><div><strong><?= e((string)$code['display_name']) ?></strong><small>••••<?= e((string)$code['code_last4']) ?> · <?= e(ucfirst((string)$code['status'])) ?><?= !empty($code['last_used_at'])?' · Last used '.e(date('M j',strtotime((string)$code['last_used_at']))):'' ?></small></div></article><?php endforeach;?><?php if(!$claimCodes):?><p>No Merchant Claim Codes yet.</p><?php endif;?></div><?php if($canClaimCodes):?><form method="post" class="cr-form cr-subform"><?= csrf_field() ?><input type="hidden" name="action" value="claim_code_create"><input type="hidden" name="merchant_id" value="<?= $merchantId ?>"><h3>Create Claim Code</h3><label>Name<input name="display_name" required placeholder="Front register"></label><div class="cr-form-grid"><label>Location<select name="location_id"><option value="">All Locations</option><?php foreach($locations as $location):?><option value="<?= (int)$location['id'] ?>"><?= e((string)$location['name']) ?></option><?php endforeach;?></select></label><label>Device label<input name="device_label" placeholder="POS 1"></label><label>Daily claim limit<input name="daily_claim_limit" type="number" min="1"></label><label>Total claim limit<input name="total_claim_limit" type="number" min="1"></label></div><button class="cr-btn">Generate Claim Code</button></form><?php endif;?></section>
</div>

<div class="cr-grid">
<section class="cr-card"><header><div><span>Customer service</span><h2>Make Good</h2></div></header><?php if($merchant&&campaigns_rewards_platform_can_v100($pdo,$merchantId,$uid,'rewards.issue')):?><form method="post" class="cr-form"><?= csrf_field() ?><input type="hidden" name="action" value="make_good"><input type="hidden" name="merchant_id" value="<?= $merchantId ?>"><label>Customer email<input name="contact_email" type="email" required></label><label>Customer name<input name="contact_name"></label><label>Reward Product<select name="reward_product_id" required><option value="">Choose Reward</option><?php foreach($rewardProducts as $rp):?><option value="<?= (int)$rp['id'] ?>"><?= e((string)$rp['name']) ?> · <?= e((string)$rp['reward_type_name']) ?></option><?php endforeach;?></select></label><label>Reason code<input name="reason_code" value="service_recovery"></label><label>Summary<input name="summary" value="Make Good"></label><label>Internal notes<textarea name="internal_notes"></textarea></label><button class="cr-btn primary">Issue Make Good Reward</button></form><?php else:?><p>You do not have Reward issuance access.</p><?php endif;?></section>

<section class="cr-card"><header><div><span>Audit</span><h2>Recent Claims</h2></div><?php if($canAnalytics):?><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="reconcile"><input type="hidden" name="merchant_id" value="<?= $merchantId ?>"><button>Run reconciliation</button></form><?php endif;?></header><div class="cr-list"><?php foreach($recentClaims as $claim):?><article><div><strong><?= e((string)$claim['reward_title']) ?></strong><small><?= e((string)$claim['campaign_title']) ?> · <?= e((string)$claim['customer_name']) ?> · <?= e(ucfirst((string)$claim['status'])) ?><?php if(!empty($claim['claimed_at'])):?> · <?= e(date('M j, Y g:i A',strtotime((string)$claim['claimed_at']))) ?> UTC<?php endif;?></small></div></article><?php endforeach;?><?php if(!$recentClaims):?><p>No Claims yet.</p><?php endif;?></div></section>
</div>
<?php endif;?>

<?php if(isset($_GET['new_merchant'])&&$canCreate&&$merchant):?><section class="cr-card" id="new-merchant"><header><div><span>New Merchant</span><h2>Create another business entity</h2></div></header><form method="post" class="cr-form"><?= csrf_field() ?><input type="hidden" name="action" value="merchant_create"><label>Name<input name="name" required></label><label>Slug<input name="slug"></label><label>Description<textarea name="description"></textarea></label><div class="cr-form-grid"><label>Website<input name="website_url"></label><label>Timezone<input name="timezone" value="<?= e((string)$merchant['timezone']) ?>"></label><label>Currency<input name="currency" value="<?= e((string)$merchant['currency']) ?>"></label></div><button class="cr-btn primary">Create Merchant</button></form></section><?php endif;?>
</div></main></div><script src="<?= e(url('/workspace-shell-v82.js?v=82')) ?>" defer></script></body></html>
