<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
$pdo=db();if(!$pdo||!video_meeting_schema_ready_v1800($pdo)){http_response_code(503);exit('Video Meetings are not ready.');}
$user=current_user();$publicId=strtolower(trim((string)($_GET['meeting']??'')));$invite=strtolower(trim((string)($_GET['invite']??'')));
$access=video_meeting_secure_access_v1800($pdo,$user,$publicId,$invite);
if(!$access){http_response_code(404);exit('Meeting invitation not found or not available to this account.');}
$meeting=$access['meeting'];$participant=$access['participant'];$isOrganizer=!empty($access['is_organizer']);
$agentName=video_meeting_agent_name_v1800($pdo,$meeting);
$processingPolicy=function_exists('video_meeting_homeserver_public_policy_v1801')?video_meeting_homeserver_public_policy_v1801($pdo,$meeting):['policy_resolved'=>true,'cloud_processing_allowed'=>true,'local_transcription_advertised'=>false];
$processingResolved=!empty($processingPolicy['policy_resolved']);
$privateProcessingRequired=!empty($meeting['transcription_enabled'])&&$processingResolved&&(($processingPolicy['cloud_processing_allowed']??null)===false);
$processingPending=!empty($meeting['transcription_enabled'])&&!$processingResolved;
$participantName=trim((string)($user['display_name']??$participant['display_name']??''))?:'Guest';
try{$localStart=(new DateTimeImmutable((string)$meeting['start_at_utc'],new DateTimeZone('UTC')))->setTimezone(new DateTimeZone((string)$meeting['timezone']));$when=$localStart->format('D, M j · g:i A T');}catch(Throwable $e){$when=(string)$meeting['start_at_utc'].' UTC';}
$closed=in_array((string)$meeting['status'],['cancelled','ended','processed'],true);
$reviewMode=$closed&&$isOrganizer&&$user&&(string)$meeting['status']!=='cancelled';
$intelligenceReady=function_exists('video_meeting_intelligence_schema_ready_v1820')&&video_meeting_intelligence_schema_ready_v1820($pdo);
$csrf=$user?csrf_token():'';
$boot=[
    'meeting'=>(string)$meeting['public_id'],'invite'=>$invite,'csrf'=>$csrf,'participantName'=>$participantName,'isOrganizer'=>$isOrganizer,
    'transcriptionEnabled'=>!empty($meeting['transcription_enabled']),'privateProcessingRequired'=>$privateProcessingRequired,'processingPolicyPending'=>$processingPending,
    'tokenEndpoint'=>url('/api/video-meeting-token.php'),'presenceEndpoint'=>url('/api/video-meeting-presence.php'),'transcriptEndpoint'=>url('/api/video-meeting-transcript.php'),
    'intelligenceEndpoint'=>url('/api/video-meeting-intelligence.php'),'memoryEndpoint'=>url('/api/video-meeting-memory.php'),'transcriptionIntelligenceEndpoint'=>url('/api/artist-listening-intelligence-v300.php'),
    'intelligenceReady'=>$intelligenceReady,'reviewOnly'=>$reviewMode,'meetingsUrl'=>$user?url('/meetings.php'):url('/'),
];
header('Referrer-Policy: no-referrer');
header('X-Robots-Tag: noindex, nofollow, noarchive');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0b0b0c"><title><?= e((string)$meeting['title']) ?> | VP3 Meeting</title><link rel="stylesheet" href="<?= e(url('/video-meetings-v1800.css?v=1801')) ?>"><link rel="stylesheet" href="<?= e(url('/video-meetings-transcript-v1800.css?v=1800')) ?>"><link rel="stylesheet" href="<?= e(url('/video-meetings-intelligence-v1820.css?v=1820')) ?>"></head>
<body class="vp3-meeting-room-page">
<?php if($reviewMode): ?>
<div class="meeting-review-shell"><div class="meeting-review-card"><a class="meeting-review-back" href="<?= e(url('/meetings.php')) ?>">← Back to Meetings</a><div class="meeting-review-head"><div><span class="meeting-lobby-kicker">Meeting Intelligence</span><h1><?= e((string)$meeting['title']) ?></h1><p><?= e($when) ?> · <?= e(ucfirst((string)$meeting['status'])) ?></p></div><a class="video-meeting-brand" href="<?= e(url('/')) ?>"><span class="video-meeting-brand-mark"><i></i><i></i><i></i><i></i></span><span>VP3</span></a></div>
<?php if(!$intelligenceReady): ?><div class="meeting-ended-card"><h2>Meeting Intelligence needs the current database upgrade.</h2><p>Run <code>upgrade.php</code> once, then return to this meeting.</p></div><?php else: ?>
<div class="meeting-review-grid"><section class="meeting-review-panel"><div class="meeting-agent-head"><div class="meeting-agent-id"><strong><?= e($agentName) ?></strong><span class="meeting-agent-mode">Review</span></div><p>Post-meeting intelligence is projected from the canonical VP3 Transcription system. Review findings before promoting them into CRM, Tasks, Knowledge or external follow-up.</p></div>
<div class="meeting-intelligence-toolbar" data-meeting-private><button id="meetingIntelligenceRefresh" type="button">Finalize intelligence</button><button id="meetingIntelligenceHandoff" type="button">Send to Agent Chat</button><a id="meetingFullIntelligenceLink" href="<?= e(url('/artist-listening.php')) ?>">Full intelligence →</a><span id="meetingIntelligenceStatus">Loading intelligence…</span></div><div class="meeting-intelligence-policy" id="meetingIntelligencePolicy" data-meeting-private>Resolving processing route…</div>
<div class="meeting-agent-tabs"><button class="meeting-agent-tab active" data-pane="summary">Summary</button><button class="meeting-agent-tab" data-pane="actions">Actions</button><button class="meeting-agent-tab" data-pane="decisions">Decisions</button><button class="meeting-agent-tab" data-pane="questions">Questions</button><button class="meeting-agent-tab" data-pane="objectives">Objectives</button><button class="meeting-agent-tab" data-pane="notes">Notes</button><button class="meeting-agent-tab" data-pane="crm">CRM</button><button class="meeting-agent-tab" data-pane="activity">Activity</button></div>
<div class="meeting-agent-content"><section class="meeting-agent-pane active" id="meetingPane-summary"><div class="meeting-intelligence-stack" id="meetingIntelligenceSummary"><div class="meeting-agent-empty">Loading the canonical meeting intelligence…</div></div><h3>Risks &amp; blockers</h3><div class="meeting-intelligence-stack" id="meetingIntelligenceRisks"></div></section><section class="meeting-agent-pane" id="meetingPane-actions"><div class="meeting-intelligence-stack" id="meetingIntelligenceActions"></div></section><section class="meeting-agent-pane" id="meetingPane-decisions"><div class="meeting-intelligence-stack" id="meetingIntelligenceDecisions"></div></section><section class="meeting-agent-pane" id="meetingPane-questions"><div class="meeting-intelligence-stack" id="meetingIntelligenceQuestions"></div></section><section class="meeting-agent-pane" id="meetingPane-objectives"><div class="meeting-objective-compose"><input id="meetingObjectiveInput" maxlength="1000" placeholder="Add a meeting objective"><button id="meetingObjectiveAdd" type="button">Add</button></div><div id="meetingObjectiveList"></div></section><section class="meeting-agent-pane" id="meetingPane-notes"><textarea class="meeting-private-note" id="meetingPrivateNotes" placeholder="Private organizer notes…"></textarea></section><section class="meeting-agent-pane" id="meetingPane-crm"><div class="meeting-intelligence-stack" id="meetingIntelligenceCrm"></div><div class="meeting-agent-empty">CRM intelligence remains advisory until you review and promote it from the full Transcription Intelligence workspace.</div></section><section class="meeting-agent-pane" id="meetingPane-activity"><div id="meetingIntelligenceActivity"></div></section></div></section>
<aside class="meeting-review-panel"><div class="meeting-agent-head"><div class="meeting-agent-id"><strong>Meeting record</strong><span class="meeting-agent-mode">Canonical</span></div><p id="meetingTranscriptBridgeState">Loading transcript state…</p></div><div class="meeting-agent-content"><section class="meeting-agent-pane active"><div class="meeting-agent-empty">Transcript, decisions, actions, questions, CRM signals and post-meeting handoff all reference the same VP3 transcription session. No duplicate AI-summary store is created.</div><div style="padding-top:14px"><a class="meeting-summary-open" id="meetingFullIntelligenceLinkSecondary" href="<?= e(url('/artist-listening.php')) ?>">Open full Transcription workspace →</a></div></section></div></aside></div>
<?php endif; ?></div></div>
<script>window.VP3Meeting=<?= json_encode($boot,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) ?>;</script><?php if($intelligenceReady): ?><script src="<?= e(url('/video-meetings-intelligence-v1820.js?v=18120')) ?>"></script><?php endif; ?>
<?php elseif($closed): ?><div class="video-meeting-shell"><div class="meeting-ended-card"><a class="video-meeting-brand" href="<?= e(url('/')) ?>"><span class="video-meeting-brand-mark"><i></i><i></i><i></i><i></i></span><span>VP3</span></a><span class="meeting-lobby-kicker">Video meeting</span><h1><?= e((string)$meeting['status']==='cancelled'?'Meeting cancelled':'Meeting ended') ?></h1><p><?= e((string)$meeting['title']) ?> · <?= e($when) ?></p><?php if($user): ?><a class="meeting-join-button" href="<?= e(url('/meetings.php')) ?>">Back to Meetings</a><?php endif; ?></div></div>
<?php else: ?>
<div class="meeting-lobby" id="meetingLobby"><div class="meeting-lobby-card"><a class="video-meeting-brand" href="<?= e(url('/')) ?>"><span class="video-meeting-brand-mark"><i></i><i></i><i></i><i></i></span><span>VP3</span></a><div class="meeting-lobby-kicker" style="margin-top:24px">Video meeting</div><h1><?= e((string)$meeting['title']) ?></h1><div class="meeting-lobby-meta"><?= e($when) ?><?php if(trim((string)($meeting['description']??''))!==''): ?><br><?= nl2br(e(mb_strimwidth((string)$meeting['description'],0,500,'…'))) ?><?php endif; ?></div>
<div class="meeting-lobby-disclosure"><?php if($privateProcessingRequired): ?><strong><?= e($agentName) ?> · Private processing required</strong><br>The organizer's HomeServer privacy/compute policy prevents VP3 from dispatching the cloud transcription worker. LiveKit still provides the meeting media transport, but VP3 cloud STT will not receive the room audio.<?php elseif($processingPending): ?><strong><?= e($agentName) ?> · Transcription configured</strong><br>The organizer's authenticated processing policy is applied when the organizer joins. This attendee page does not query or probe the organizer's HomeServer.<?php elseif(!empty($meeting['transcription_enabled'])&&(string)$meeting['agent_mode']!=='off'): ?><strong><?= e($agentName) ?> · <?= e(ucfirst((string)$meeting['agent_mode'])) ?> mode</strong><br>This meeting is configured for live speaker-separated transcription and VP3's existing transcription intelligence tools. The meeting Agent uses the organizer's existing VP3 Agent identity and permissions.<?php else: ?><strong>AI meeting assistance is off.</strong><br>No VP3 live transcript is configured for this meeting.<?php endif; ?><br><strong>Recording: <?= !empty($meeting['recording_enabled'])?'On':'Off' ?></strong></div>
<div class="meeting-lobby-form"><label><span>Your display name</span><input id="meetingDisplayName" maxlength="190" value="<?= e($participantName) ?>" <?= $user?'readonly':'' ?>></label><label class="meeting-check"><input type="checkbox" id="joinMic" checked><span>Join with microphone</span></label><label class="meeting-check"><input type="checkbox" id="joinCamera" checked><span>Join with camera</span></label><div class="meeting-room-error" id="meetingRoomError"></div><button class="meeting-join-button" id="meetingJoin" type="button" <?= video_meeting_livekit_ready_v1800()?'':'disabled' ?>><?= video_meeting_livekit_ready_v1800()?'Join meeting':'Meeting service is not configured' ?></button></div></div></div>
<div class="video-meeting-shell"><header class="video-meeting-topbar"><a class="video-meeting-brand" href="<?= e($user?url('/meetings.php'):url('/')) ?>"><span class="video-meeting-brand-mark"><i></i><i></i><i></i><i></i></span><span>VP3</span></a><div class="video-meeting-titlebar"><strong><?= e((string)$meeting['title']) ?></strong><span><?= e($when) ?></span></div><div class="video-meeting-top-actions"><span class="video-meeting-pill" id="meetingParticipantCount">1 participant</span><span class="video-meeting-pill"><?= !empty($meeting['recording_enabled'])?'Recording on':'Not recording' ?></span></div></header>
<div class="video-meeting-body"><main class="video-meeting-stage"><div class="video-participant-grid" id="participantGrid"></div></main><aside class="meeting-agent-panel" id="meetingAgentPanel"><div class="meeting-agent-head"><div class="meeting-agent-id"><strong><?= e($agentName) ?></strong><span class="meeting-agent-mode"><?= e($privateProcessingRequired?'Private':($processingPending?'Policy':ucfirst((string)$meeting['agent_mode']))) ?></span></div><p><?= $privateProcessingRequired?'HomeServer privacy policy is active. Cloud transcription is suppressed for this meeting.':($processingPending?'The organizer\'s processing route is intentionally not resolved from this attendee request.':'Phase 18.2 projects VP3 Transcription Intelligence, meeting objectives and private notes into this Agent workspace without creating a second AI stack.') ?></p></div>
<?php if($intelligenceReady): ?><div class="meeting-intelligence-toolbar" data-meeting-private><button id="meetingIntelligenceRefresh" type="button">Update intelligence</button><button id="meetingIntelligenceHandoff" type="button">Send to Agent Chat</button><a id="meetingFullIntelligenceLink" href="<?= e(url('/artist-listening.php')) ?>">Full intelligence →</a><span id="meetingIntelligenceStatus">Waiting for transcript context.</span></div><div class="meeting-intelligence-policy" id="meetingIntelligencePolicy" data-meeting-private>Resolving processing route…</div><?php endif; ?>
<div class="meeting-agent-tabs"><button class="meeting-agent-tab active" data-pane="transcript">Transcript</button><button class="meeting-agent-tab" data-pane="summary" data-meeting-private>Summary</button><button class="meeting-agent-tab" data-pane="actions" data-meeting-private>Actions</button><button class="meeting-agent-tab" data-pane="decisions" data-meeting-private>Decisions</button><button class="meeting-agent-tab" data-pane="questions" data-meeting-private>Questions</button><button class="meeting-agent-tab" data-pane="objectives" data-meeting-private>Objectives</button><button class="meeting-agent-tab" data-pane="notes" data-meeting-private>Notes</button><button class="meeting-agent-tab" data-pane="crm" data-meeting-private>CRM</button><button class="meeting-agent-tab" data-pane="files">Files</button><button class="meeting-agent-tab" data-pane="activity" data-meeting-private>Activity</button></div>
<div class="meeting-agent-content"><section class="meeting-agent-pane active" id="meetingPane-transcript"><div class="meeting-transcript-list" id="meetingTranscriptList"><div class="meeting-agent-empty"><?= e($privateProcessingRequired?'Cloud transcription is paused by the organizer\'s HomeServer policy. A compatible private transcription path can publish into this same VP3 transcript feed.':($processingPending?'Transcript processing starts according to the organizer\'s authenticated policy.':'Live speaker-separated transcript segments will appear here as the VP3 meeting worker publishes them.')) ?></div></div></section><section class="meeting-agent-pane" id="meetingPane-summary" data-meeting-private><div class="meeting-summary-actions"><span id="meetingTranscriptBridgeState"><?= $privateProcessingRequired?'Private processing policy active':($processingPending?'Organizer policy pending':'Waiting for transcript') ?></span></div><div class="meeting-intelligence-stack" id="meetingIntelligenceSummary"></div><h3>Risks &amp; blockers</h3><div class="meeting-intelligence-stack" id="meetingIntelligenceRisks"></div></section><section class="meeting-agent-pane" id="meetingPane-actions" data-meeting-private><div class="meeting-intelligence-stack" id="meetingIntelligenceActions"></div></section><section class="meeting-agent-pane" id="meetingPane-decisions" data-meeting-private><div class="meeting-intelligence-stack" id="meetingIntelligenceDecisions"></div></section><section class="meeting-agent-pane" id="meetingPane-questions" data-meeting-private><div class="meeting-intelligence-stack" id="meetingIntelligenceQuestions"></div></section><section class="meeting-agent-pane" id="meetingPane-objectives" data-meeting-private><div class="meeting-objective-compose"><input id="meetingObjectiveInput" maxlength="1000" placeholder="Add a meeting objective"><button id="meetingObjectiveAdd" type="button">Add</button></div><div id="meetingObjectiveList"></div></section><section class="meeting-agent-pane" id="meetingPane-notes" data-meeting-private><textarea class="meeting-private-note" id="meetingPrivateNotes" placeholder="Private organizer notes…"></textarea></section><section class="meeting-agent-pane" id="meetingPane-crm" data-meeting-private><div class="meeting-intelligence-stack" id="meetingIntelligenceCrm"></div><div class="meeting-agent-empty">CRM recommendations stay advisory until reviewed in the full intelligence workspace.</div></section><section class="meeting-agent-pane" id="meetingPane-files"><div class="meeting-agent-empty">Shared meeting files use VP3's existing controlled file and Knowledge boundaries rather than a second storage system.</div></section><section class="meeting-agent-pane" id="meetingPane-activity" data-meeting-private><div id="meetingIntelligenceActivity"></div></section></div>
<div class="meeting-device-row" id="meetingDevicePicker" hidden style="padding:10px"><select id="meetingMicDevice" aria-label="Microphone"></select><select id="meetingCameraDevice" aria-label="Camera"></select><select id="meetingSpeakerDevice" aria-label="Speaker"></select></div></aside></div>
<footer class="video-meeting-controls"><button class="meeting-control" id="meetingMic" type="button">Mic on</button><button class="meeting-control" id="meetingCamera" type="button">Camera on</button><button class="meeting-control" id="meetingShare" type="button">Share</button><button class="meeting-control secondary" id="meetingDevices" type="button">Devices</button><button class="meeting-control secondary" id="meetingAgentToggle" type="button">Agent</button><button class="meeting-control end" id="<?= $isOrganizer?'meetingEnd':'meetingLeave' ?>" type="button"><?= $isOrganizer?'End':'Leave' ?></button></footer></div>
<script>window.VP3Meeting=<?= json_encode($boot,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) ?>;</script>
<script src="https://cdn.jsdelivr.net/npm/livekit-client@2.22.3/dist/livekit-client.umd.min.js" crossorigin="anonymous"></script><script src="<?= e(url('/video-meetings-v1800.js?v=1820')) ?>"></script><?php if($intelligenceReady): ?><script src="<?= e(url('/video-meetings-intelligence-v1820.js?v=18120')) ?>"></script><?php endif; ?>
<?php endif; ?></body></html>