<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
require_once __DIR__.'/includes/transcription-app-registry.php';
$pdo=db();if(!$pdo||!video_meeting_schema_ready_v1800($pdo)){http_response_code(503);exit('Video Meetings are not ready.');}
$user=current_user();$publicId=strtolower(trim((string)($_GET['meeting']??'')));$invite=strtolower(trim((string)($_GET['invite']??'')));
$access=video_meeting_access_v1800($pdo,$user,$publicId,$invite);
if(!$access){http_response_code(404);exit('Meeting invitation not found or not available to this account.');}
$meeting=$access['meeting'];$participant=$access['participant'];$isOrganizer=!empty($access['is_organizer']);
$agentName=video_meeting_agent_name_v1800($pdo,$meeting);$apps=transcription_app_registry_public_v300();
$participantName=trim((string)($user['display_name']??$participant['display_name']??''))?:'Guest';
try{$localStart=(new DateTimeImmutable((string)$meeting['start_at_utc'],new DateTimeZone('UTC')))->setTimezone(new DateTimeZone((string)$meeting['timezone']));$when=$localStart->format('D, M j · g:i A T');}catch(Throwable $e){$when=(string)$meeting['start_at_utc'].' UTC';}
$closed=in_array((string)$meeting['status'],['cancelled','ended','processed'],true);
$csrf=$user?csrf_token():'';
header('Referrer-Policy: no-referrer');
header('X-Robots-Tag: noindex, nofollow, noarchive');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0b0b0c"><title><?= e((string)$meeting['title']) ?> | VP3 Meeting</title><link rel="stylesheet" href="<?= e(url('/video-meetings-v1800.css?v=1800')) ?>"></head>
<body class="vp3-meeting-room-page">
<?php if($closed): ?><div class="video-meeting-shell"><div class="meeting-ended-card"><a class="video-meeting-brand" href="<?= e(url('/')) ?>"><span class="video-meeting-brand-mark"><i></i><i></i><i></i><i></i></span><span>VP3</span></a><span class="meeting-lobby-kicker">Video meeting</span><h1><?= e((string)$meeting['status']==='cancelled'?'Meeting cancelled':'Meeting ended') ?></h1><p><?= e((string)$meeting['title']) ?> · <?= e($when) ?></p><?php if($user): ?><a class="meeting-join-button" href="<?= e(url('/meetings.php')) ?>">Back to Meetings</a><?php endif; ?></div></div>
<?php else: ?>
<div class="meeting-lobby" id="meetingLobby"><div class="meeting-lobby-card"><a class="video-meeting-brand" href="<?= e(url('/')) ?>"><span class="video-meeting-brand-mark"><i></i><i></i><i></i><i></i></span><span>VP3</span></a><div class="meeting-lobby-kicker" style="margin-top:24px">Video meeting</div><h1><?= e((string)$meeting['title']) ?></h1><div class="meeting-lobby-meta"><?= e($when) ?><?php if(trim((string)($meeting['description']??''))!==''): ?><br><?= nl2br(e(mb_strimwidth((string)$meeting['description'],0,500,'…'))) ?><?php endif; ?></div>
<div class="meeting-lobby-disclosure"><?php if(!empty($meeting['transcription_enabled'])&&(string)$meeting['agent_mode']!=='off'): ?><strong><?= e($agentName) ?> · <?= e(ucfirst((string)$meeting['agent_mode'])) ?> mode</strong><br>This meeting is configured for live transcription and VP3 AI Summary tools. The meeting Agent uses the organizer's existing VP3 Agent identity and permissions.<?php else: ?><strong>AI meeting assistance is off.</strong><br>No VP3 live transcript is configured for this meeting.<?php endif; ?><br><strong>Recording: <?= !empty($meeting['recording_enabled'])?'On':'Off' ?></strong></div>
<div class="meeting-lobby-form"><label><span>Your display name</span><input id="meetingDisplayName" maxlength="190" value="<?= e($participantName) ?>" <?= $user?'readonly':'' ?>></label><label class="meeting-check"><input type="checkbox" id="joinMic" checked><span>Join with microphone</span></label><label class="meeting-check"><input type="checkbox" id="joinCamera" checked><span>Join with camera</span></label><div class="meeting-room-error" id="meetingRoomError"></div><button class="meeting-join-button" id="meetingJoin" type="button" <?= video_meeting_livekit_ready_v1800()?'':'disabled' ?>><?= video_meeting_livekit_ready_v1800()?'Join meeting':'Meeting service is not configured' ?></button></div></div></div>
<div class="video-meeting-shell"><header class="video-meeting-topbar"><a class="video-meeting-brand" href="<?= e($user?url('/meetings.php'):url('/')) ?>"><span class="video-meeting-brand-mark"><i></i><i></i><i></i><i></i></span><span>VP3</span></a><div class="video-meeting-titlebar"><strong><?= e((string)$meeting['title']) ?></strong><span><?= e($when) ?></span></div><div class="video-meeting-top-actions"><span class="video-meeting-pill" id="meetingParticipantCount">1 participant</span><span class="video-meeting-pill"><?= !empty($meeting['recording_enabled'])?'Recording on':'Not recording' ?></span></div></header>
<div class="video-meeting-body"><main class="video-meeting-stage"><div class="video-participant-grid" id="participantGrid"></div></main><aside class="meeting-agent-panel" id="meetingAgentPanel"><div class="meeting-agent-head"><div class="meeting-agent-id"><strong><?= e($agentName) ?></strong><span class="meeting-agent-mode"><?= e(ucfirst((string)$meeting['agent_mode'])) ?></span></div><p>Meeting intelligence uses the existing VP3 transcription and AI Summary system. Active participation remains policy-controlled.</p></div>
<div class="meeting-agent-tabs"><button class="meeting-agent-tab active" data-pane="transcript">Transcript</button><button class="meeting-agent-tab" data-pane="summary">AI Summary</button><button class="meeting-agent-tab" data-pane="notes">Notes</button><button class="meeting-agent-tab" data-pane="decisions">Decisions</button><button class="meeting-agent-tab" data-pane="questions">Questions</button><button class="meeting-agent-tab" data-pane="files">Files</button><button class="meeting-agent-tab" data-pane="activity">Activity</button></div>
<div class="meeting-agent-content"><section class="meeting-agent-pane active" id="meetingPane-transcript"><div class="meeting-agent-empty">Live speaker-separated transcript segments will appear here when the meeting transcription worker publishes them.</div></section><section class="meeting-agent-pane" id="meetingPane-summary"><div class="meeting-summary-apps"><?php foreach($apps as $app): ?><div class="meeting-summary-app" data-summary-app="<?= e((string)$app['id']) ?>"><strong><?= e((string)$app['title']) ?></strong><span><?= e((string)$app['description']) ?></span></div><?php endforeach; ?></div></section><section class="meeting-agent-pane" id="meetingPane-notes"><div class="meeting-agent-empty">Meeting notes will remain attached to this durable VP3 meeting record.</div></section><section class="meeting-agent-pane" id="meetingPane-decisions"><div class="meeting-agent-empty">The existing Decisions &amp; Commitments transcription app will populate structured outcomes here.</div></section><section class="meeting-agent-pane" id="meetingPane-questions"><div class="meeting-agent-empty">Open questions and follow-up prompts will be derived from transcript intelligence.</div></section><section class="meeting-agent-pane" id="meetingPane-files"><div class="meeting-agent-empty">Shared meeting files will use VP3's existing controlled file/Knowledge boundaries rather than a second storage system.</div></section><section class="meeting-agent-pane" id="meetingPane-activity"><div class="meeting-agent-empty">Agent activity, approvals and follow-up actions will flow through existing VP3 workflow and notification ledgers.</div></section></div>
<div class="meeting-device-row" id="meetingDevicePicker" hidden style="padding:10px"><select id="meetingMicDevice" aria-label="Microphone"></select><select id="meetingCameraDevice" aria-label="Camera"></select><select id="meetingSpeakerDevice" aria-label="Speaker"></select></div></aside></div>
<footer class="video-meeting-controls"><button class="meeting-control" id="meetingMic" type="button">Mic on</button><button class="meeting-control" id="meetingCamera" type="button">Camera on</button><button class="meeting-control" id="meetingShare" type="button">Share</button><button class="meeting-control secondary" id="meetingDevices" type="button">Devices</button><button class="meeting-control secondary" id="meetingAgentToggle" type="button">Agent</button><button class="meeting-control end" id="<?= $isOrganizer?'meetingEnd':'meetingLeave' ?>" type="button"><?= $isOrganizer?'End':'Leave' ?></button></footer></div>
<script>window.VP3Meeting=<?= json_encode(['meeting'=>(string)$meeting['public_id'],'invite'=>$invite,'csrf'=>$csrf,'participantName'=>$participantName,'isOrganizer'=>$isOrganizer,'tokenEndpoint'=>url('/api/video-meeting-token.php'),'presenceEndpoint'=>url('/api/video-meeting-presence.php'),'meetingsUrl'=>$user?url('/meetings.php'):url('/')],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) ?>;</script>
<script src="https://cdn.jsdelivr.net/npm/livekit-client@2.22.3/dist/livekit-client.umd.min.js" crossorigin="anonymous"></script><script src="<?= e(url('/video-meetings-v1800.js?v=1800')) ?>"></script>
<?php endif; ?></body></html>
