<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
require_once __DIR__.'/includes/social-network-v320.php';
require_login();
$user=current_user();$pdo=db();if(!$pdo){http_response_code(503);exit('Messaging is unavailable until the database is configured.');}
try{vp3_social_ensure_schema_v320($pdo);}catch(Throwable $e){http_response_code(503);exit('Messaging storage could not be initialized.');}
$targetId=max(0,(int)($_GET['user_id']??0));$target=null;if($targetId>0&&$targetId!==(int)$user['id']){$stmt=$pdo->prepare('SELECT id,display_name,avatar_path FROM users WHERE id=? AND is_active=1 LIMIT 1');$stmt->execute([$targetId]);$target=$stmt->fetch()?:null;}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f6f7f8"><title>VP3 | Messages</title><link rel="stylesheet" href="<?= e(url('/chat.css?v=82')) ?>"><link rel="stylesheet" href="<?= e(url('/messages-v320.css?v=320')) ?>"></head>
<body class="messages-page"><div class="chat-app"><?php $workspaceSidebarUser=$user;$workspaceSidebarActive='messages';require __DIR__.'/includes/workspace-sidebar-v82.php'; ?><div class="chat-sidebar-backdrop" id="chatSidebarBackdrop"></div><main class="chat-main messages-main"><?php $memberHeaderUser=$user;$memberHeaderTitle='Messages';$memberHeaderSubtitle='Friends, followers and Team conversations';$memberHeaderActions='';require __DIR__.'/includes/member-header.php'; ?>
<div class="messages-shell" data-messages-app data-api="<?= e(url('/api/messages-v320.php')) ?>" data-csrf="<?= e(csrf_token()) ?>" data-user-id="<?= (int)$user['id'] ?>" data-target-id="<?= (int)($target['id']??0) ?>" data-target-name="<?= e((string)($target['display_name']??'')) ?>">
<aside class="messages-inbox"><div class="messages-inbox-head"><div><span>Human messaging</span><h1>Messages</h1></div><button type="button" class="messages-icon-button" data-refresh aria-label="Refresh">↻</button></div><nav class="messages-filter" aria-label="Message sections"><button class="active" data-filter="people">People</button><button data-filter="team">Team</button><button data-filter="requests">Requests <b data-request-count>0</b></button></nav><div class="messages-list" data-list="people"></div><div class="messages-list" data-list="team" hidden></div><div class="messages-list" data-list="requests" hidden></div><button class="messages-settings-link" type="button" data-settings-open>Messaging privacy</button></aside>
<section class="messages-thread"><header class="messages-thread-head"><div><small data-thread-kind>Select a conversation</small><h2 data-thread-title><?= $target?e((string)$target['display_name']):'Your messages' ?></h2></div></header><div class="messages-empty" data-empty><strong><?= $target?'Start a conversation':'Choose a person or Team room.' ?></strong><span><?= $target?'Send a message to '.e((string)$target['display_name']).'. If their privacy settings require it, this will become a Message Request.':'Agent Chat remains separate from these person-to-person conversations.' ?></span></div><div class="messages-stream" data-stream hidden aria-live="polite"></div><div class="messages-request-actions" data-request-actions hidden><span>This person sent you a message request.</span><button type="button" data-request-accept>Accept</button><button type="button" data-request-decline>Decline</button></div><form class="messages-composer" data-composer><textarea name="message" rows="1" maxlength="4000" placeholder="Message" aria-label="Message"></textarea><button type="submit">Send</button></form></section>
</div><dialog class="messages-settings" data-settings><form method="dialog" class="messages-settings-card"><div><small>Privacy</small><h2>Who can message me?</h2><p>Friends and teammates can always reach you. Other permitted messages may arrive as requests.</p></div><label><span>Direct messages</span><select data-message-policy><option value="friends">Friends only</option><option value="following">People I follow</option><option value="followers">Followers</option><option value="anyone">Anyone</option></select></label><label class="messages-check"><input type="checkbox" data-friend-requests><span>Allow friend requests</span></label><div class="messages-settings-actions"><button value="cancel">Cancel</button><button type="button" class="primary" data-settings-save>Save</button></div></form></dialog>
</main></div><script src="<?= e(url('/workspace-shell-v82.js?v=82')) ?>" defer></script><script src="<?= e(url('/messages-v320.js?v=320')) ?>" defer></script></body></html>
