<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
require_permission('users.manage');
$pdo=vp3_browser_trust_require_ready_v2080(db());$user=current_user();$userId=(int)($user['id']??0);$error='';$notice='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verify_csrf())$error='Session expired.';
 else try{vp3_browser_trust_report_action_v2080($pdo,$userId,(string)($_POST['report_id']??''),(string)($_POST['status']??''),(string)($_POST['action_type']??''),(string)($_POST['note']??''));$notice='Moderation report updated.';}catch(Throwable $e){$error=$e->getMessage();}
}
$reports=vp3_browser_trust_reports_v2080($pdo,$userId,200);
$memberHeaderUser=$user;$memberHeaderTitle='Moderation';$memberHeaderSubtitle='Review reported Browser Companion, Live and Claim content';$memberHeaderActions='';
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VP3 | Moderation</title><link rel="stylesheet" href="<?=e(url('/chat.css?v=82'))?>"><style>
.mod-main{background:#f7f8fa}.canvas{height:100%;overflow:auto;padding:24px}.wrap{width:min(1050px,100%);margin:auto;display:grid;gap:12px}.report{padding:16px;border:1px solid #e1e5ea;border-radius:14px;background:#fff}.meta{color:#6b7280;font-size:11px}.pill{display:inline-flex;padding:4px 7px;border-radius:999px;background:#eef1f4;font-size:10px;font-weight:800}.form{display:grid;grid-template-columns:160px 180px 1fr auto;gap:8px;margin-top:12px}.form input,.form select,.form button{padding:8px;border:1px solid #d1d5db;border-radius:8px;background:#fff;font:inherit}.alert{padding:10px;border-radius:9px;background:#f4fbf6}.error{background:#fff4f3;color:#9b1c1c}@media(max-width:760px){.form{grid-template-columns:1fr}.canvas{padding:14px}}</style></head><body><div class="chat-app"><?php $workspaceSidebarUser=$user;$workspaceSidebarActive='moderation';require __DIR__.'/includes/workspace-sidebar-v82.php';?><div class="chat-sidebar-backdrop" id="chatSidebarBackdrop"></div><main class="chat-main mod-main"><?php require __DIR__.'/includes/member-header.php';?><section class="canvas"><div class="wrap"><?php if($notice):?><div class="alert"><?=e($notice)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<?php foreach($reports as $report):?><article class="report"><div><span class="pill"><?=e((string)$report['status'])?></span> <span class="pill"><?=e((string)$report['target_type'])?></span></div><h3><?=e((string)$report['reason'])?></h3><div><?=nl2br(e((string)$report['detail']))?></div><div class="meta">Reported by <?=e((string)$report['reporter'])?> · target <?=e((string)$report['target_id'])?> · <?=e((string)$report['created_at'])?></div>
<form method="post" class="form"><?=csrf_field()?><input type="hidden" name="report_id" value="<?=e((string)$report['id'])?>"><select name="status"><option value="under_review">Under review</option><option value="actioned">Actioned</option><option value="dismissed">Dismissed</option></select><input name="action_type" maxlength="80" placeholder="Action type"><input name="note" maxlength="4000" placeholder="Moderator note"><button type="submit">Save</button></form></article><?php endforeach;?>
<?php if(!$reports):?><article class="report">No moderation reports.</article><?php endif;?></div></section></main></div></body></html>