<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
require_login();
$user=current_user();$pdo=db();if(!$pdo){http_response_code(503);exit('Database unavailable.');}
if(!music_workspace_resources_v330_schema_ready($pdo)){http_response_code(503);exit('Music Workspace database upgrade is required.');}
$requested=max(0,(int)($_GET['workspace']??0));
$workspace=music_workspace_resources_v330_resolve_active($pdo,$user,$requested);
if(!$workspace&&music_workspace_enabled_v320($user)){
    try{music_workspace_ensure_owner_v320($pdo,$user);$workspace=music_workspace_resources_v330_resolve_active($pdo,$user,$requested);}catch(Throwable $e){}
}
if(!$workspace){flash('error','Enable Music Workspace or join a Music Workspace Team to continue.');redirect(url('/plugins.php'));}
$workspaceId=(int)$workspace['id'];$ownerId=(int)$workspace['artist_user_id'];$role=music_workspace_resources_v330_member_role($pdo,$workspaceId,(int)$user['id']);$workspaces=music_workspace_resources_v330_accessible_workspaces($pdo,$user);
$counts=['tracks'=>0,'albums'=>0,'releases'=>0,'shows'=>0,'team'=>0];
foreach(['tracks'=>'artist_catalog_tracks_v181','albums'=>'artist_catalog_albums_v181','shows'=>'artist_catalog_shows_v181'] as $key=>$table){if(table_exists($table)){try{$s=$pdo->prepare("SELECT COUNT(*) FROM {$table} WHERE workspace_id=?");$s->execute([$workspaceId]);$counts[$key]=(int)$s->fetchColumn();}catch(Throwable $e){}}}
if(table_exists('release_plans')&&column_exists('release_plans','workspace_id')){try{$s=$pdo->prepare('SELECT COUNT(*) FROM release_plans WHERE workspace_id=?');$s->execute([$workspaceId]);$counts['releases']=(int)$s->fetchColumn();}catch(Throwable $e){}}
if(table_exists('artist_team_members')){try{$s=$pdo->prepare('SELECT COUNT(*) FROM artist_team_members atm INNER JOIN users u ON u.id=atm.member_user_id AND u.is_active=1 WHERE atm.artist_user_id=?');$s->execute([$ownerId]);$counts['team']=(int)$s->fetchColumn();}catch(Throwable $e){}}
$canListening=has_permission('artist_listening.access',$user);$profileUrl=function_exists('artist_workspace_v181_profile_url')?artist_workspace_v181_profile_url($workspace):'';
$memberHeaderUser=$user;$memberHeaderTitle='Music Workspace';$memberHeaderSubtitle=(string)$workspace['workspace_name'].' · '.ucfirst($role?:'member');$memberHeaderActions='';
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f7f7f8"><title>VP3 | Music Workspace</title><link rel="stylesheet" href="<?= e(url('/chat.css?v=82')) ?>"><style>
.music-main{min-width:0;background:#f7f7f8}.music-wrap{max-width:1160px;margin:0 auto;padding:34px 24px 70px}.music-switch{display:flex;justify-content:flex-end;margin-bottom:12px}.music-switch select{border:1px solid #dfe1e4;background:#fff;border-radius:10px;padding:9px}.music-hero{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(260px,.75fr);gap:24px;align-items:stretch;margin-bottom:22px}.music-card,.music-stat,.music-tool{background:#fff;border:1px solid #e2e4e7;border-radius:18px}.music-card{padding:28px}.music-kicker{font-size:11px;letter-spacing:.1em;text-transform:uppercase;font-weight:800;color:#85888e}.music-card h1{font-size:clamp(30px,5vw,50px);line-height:1;letter-spacing:-.045em;margin:7px 0 12px}.music-card p{color:#6c7077;line-height:1.55;max-width:670px}.music-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:20px}.music-btn{display:inline-flex;align-items:center;text-decoration:none;border:1px solid #dcdfe3;border-radius:11px;background:#fff;color:#202226;padding:10px 14px;font-weight:800}.music-btn.primary{background:#1d1f23;color:#fff;border-color:#1d1f23}.music-btn[aria-disabled="true"]{color:#85888e;background:#f6f6f7;cursor:default}.music-summary{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;padding:16px}.music-stat{padding:17px}.music-stat strong{display:block;font-size:27px}.music-stat span{font-size:12px;color:#787c82}.music-tools{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.music-tool{padding:20px;min-height:150px;display:flex;flex-direction:column}.music-tool h3{margin:8px 0 7px;font-size:18px}.music-tool p{margin:0;color:#74777d;font-size:13px;line-height:1.45}.music-tool .music-btn{margin-top:auto;align-self:flex-start}.music-note{margin-top:20px;padding:16px 18px;border:1px solid #e0e2e5;border-radius:14px;background:#fff;color:#6f7278;font-size:13px;line-height:1.5}.music-note strong{color:#24262b}@media(max-width:850px){.music-hero,.music-tools{grid-template-columns:1fr}.music-summary{grid-template-columns:repeat(4,1fr)}}@media(max-width:560px){.music-summary{grid-template-columns:repeat(2,1fr)}}
</style></head><body><div class="chat-app"><?php $workspaceSidebarUser=$user;$workspaceSidebarActive='music_workspace';require __DIR__.'/includes/workspace-sidebar-v82.php'; ?><div class="chat-sidebar-backdrop" id="chatSidebarBackdrop"></div><main class="chat-main music-main"><?php require __DIR__.'/includes/member-header.php'; ?><div class="music-wrap">
<?php if(count($workspaces)>1): ?><div class="music-switch"><form method="get"><label>Workspace <select name="workspace" onchange="this.form.submit()"><?php foreach($workspaces as $w): ?><option value="<?= (int)$w['id'] ?>" <?= (int)$w['id']===$workspaceId?'selected':'' ?>><?= e((string)$w['workspace_name']) ?><?= !empty($w['access_role'])?' · '.e((string)$w['access_role']):'' ?></option><?php endforeach; ?></select></label></form></div><?php endif; ?>
<section class="music-hero"><div class="music-card"><div class="music-kicker">Professional plugin · <?= e(ucfirst($role?:'member')) ?></div><h1><?= e((string)$workspace['workspace_name']) ?></h1><p>Tracks, albums, releases, production collaboration and music-supervisor workflows live here while your VP3 identity, personal URL, transcription and personal Agent remain the core account.</p><div class="music-actions"><?php if($profileUrl): ?><a class="music-btn primary" href="<?= e($profileUrl) ?>">View music profile</a><?php endif; ?><a class="music-btn" href="<?= e(url('/music-library.php?workspace='.$workspaceId)) ?>">Music Library</a><a class="music-btn" href="<?= e(url('/music-releases.php?workspace='.$workspaceId)) ?>">Releases</a><a class="music-btn" href="<?= e(url('/messages.php')) ?>">Messages</a><?php if($role==='owner'||user_has_role('admin',$user)): ?><a class="music-btn" href="<?= e(url('/team.php')) ?>">Team</a><?php endif; ?></div></div><div class="music-summary"><div class="music-stat"><strong><?= $counts['tracks'] ?></strong><span>Tracks</span></div><div class="music-stat"><strong><?= $counts['albums'] ?></strong><span>Albums</span></div><div class="music-stat"><strong><?= $counts['releases'] ?></strong><span>Releases</span></div><div class="music-stat"><strong><?= $counts['team'] ?></strong><span>Active teammates</span></div></div></section>
<section class="music-tools">
<div class="music-tool"><div class="music-kicker">Catalog</div><h3>Tracks & Albums</h3><p>Workspace-owned catalog records power protected audio, profiles, releases and Studio projects.</p><a class="music-btn" href="<?= e(url('/music-library.php?workspace='.$workspaceId)) ?>">Open library</a></div>
<div class="music-tool"><div class="music-kicker">Production</div><h3>Stems & Versions</h3><p>The mature Stem Studio remains the production engine. Open it from an authorized workspace track so every project and stem inherits workspace ownership.</p><a class="music-btn" href="<?= e(url('/music-library.php?workspace='.$workspaceId)) ?>">Choose a track</a></div>
<div class="music-tool"><div class="music-kicker">Release</div><h3>Release Planning</h3><p>Coordinate release plans, deadlines and tasks inside the active Music Workspace.</p><a class="music-btn" href="<?= e(url('/music-releases.php?workspace='.$workspaceId)) ?>">Open releases</a></div>
<div class="music-tool"><div class="music-kicker">Player</div><h3>Multiuser Player</h3><p>Personal playlists remain VP3 core data while workspace catalog tracks flow into the existing player.</p><a class="music-btn" href="<?= e(url('/player.php')) ?>">Open player</a></div>
<div class="music-tool"><div class="music-kicker">Intelligence</div><h3>Transcription & Notes</h3><p>VP3 transcription remains a personal/core capability and can support work across Music Workspaces.</p><?php if($canListening): ?><a class="music-btn" href="<?= e(url('/artist-listening.php')) ?>">Open transcriptions</a><?php else: ?><span class="music-btn" aria-disabled="true">Use your VP3 transcription plan</span><?php endif; ?></div>
<div class="music-tool"><div class="music-kicker">Collaboration</div><h3>Team General</h3><p>Active workspace members are authorized dynamically for Team General and lose access when membership ends.</p><a class="music-btn" href="<?= e(url('/messages.php')) ?>">Open Team messages</a></div>
</section>
<div class="music-note"><strong>Ownership model:</strong> professional Music resources belong to this workspace. Personal VP3 identity, Agent conversations, transcriptions, favorites and personal playlists remain attached to your individual account.</div>
</div></main></div><script src="<?= e(url('/workspace-shell-v82.js?v=82')) ?>" defer></script></body></html>