<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';require_login();
$pdo=vp3_browser_trust_require_ready_v2080(db());$user=current_user();$userId=(int)($user['id']??0);$error='';$notice='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verify_csrf())$error='Session expired.';
 else try{foreach(['source_changes','replies','follows','live','claims','moderation'] as $type)vp3_browser_trust_set_preference_v2080($pdo,$userId,$type,isset($_POST[$type]));$notice='Notification preferences saved.';}catch(Throwable $e){$error=$e->getMessage();}
}
$prefs=vp3_browser_trust_preferences_v2080($pdo,$userId);
$labels=['source_changes'=>'Source changes','replies'=>'Replies and comments','follows'=>'New followers','live'=>'Live Room activity','claims'=>'Claim updates','moderation'=>'Moderation report updates'];
$memberHeaderUser=$user;$memberHeaderTitle='Notification Settings';$memberHeaderSubtitle='Choose which Browser Companion events should alert you';$memberHeaderActions='<a class="notification-button" href="'.e(url('/notifications.php')).'">Back to notifications</a>';
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VP3 | Notification Settings</title><link rel="stylesheet" href="<?=e(url('/chat.css?v=82'))?>"><style>
.main{background:#f7f8fa}.canvas{height:100%;overflow:auto;padding:26px}.wrap{width:min(760px,100%);margin:auto}.card{padding:20px;background:#fff;border:1px solid #e1e5ea;border-radius:16px}.row{display:flex;justify-content:space-between;gap:18px;padding:14px 0;border-bottom:1px solid #edf0f3}.row:last-child{border-bottom:0}.row input{width:18px;height:18px}.button,.notification-button{display:inline-flex;padding:8px 11px;border:1px solid #d1d5db;border-radius:8px;background:#fff;color:#111827;text-decoration:none;font:inherit;font-size:11px;font-weight:800;cursor:pointer}.alert{margin-bottom:12px;padding:10px;border-radius:9px;background:#f4fbf6}.error{background:#fff4f3;color:#9b1c1c}</style></head><body><div class="chat-app"><?php $workspaceSidebarUser=$user;$workspaceSidebarActive='notifications';require __DIR__.'/includes/workspace-sidebar-v82.php';?><div class="chat-sidebar-backdrop" id="chatSidebarBackdrop"></div><main class="chat-main main"><?php require __DIR__.'/includes/member-header.php';?><section class="canvas"><div class="wrap"><?php if($notice):?><div class="alert"><?=e($notice)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?><form method="post" class="card"><?=csrf_field()?><?php foreach($labels as $type=>$label):?><label class="row"><span><strong><?=e($label)?></strong><br><small>Receive <?=e(strtolower($label))?> notifications on VP3 and in Browser Companion.</small></span><input type="checkbox" name="<?=e($type)?>" <?=!empty($prefs[$type])?'checked':''?>></label><?php endforeach;?><div style="margin-top:16px"><button class="button" type="submit">Save preferences</button></div></form></div></section></main></div></body></html>