<?php
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require_once __DIR__ . '/includes/vp3-public.php';
redirect_logged_in_public_page();
vp3_public_header('Pricing — VP3', 'Simple VP3 plans for personal AI assistance, professionals, teams, and organizations.', ['active'=>'pricing']);
?>
<section class="vp3-public-hero">
  <div class="vp3-kicker">Simple plans. One connected assistant.</div>
  <h1>Choose the VP3 setup that fits how you work.</h1>
  <p>Start personal and add deeper workflow or team capabilities as you need them. Your conversations, transcriptions, knowledge, and assistant context stay connected.</p>
  <div class="vp3-billing"><button class="active" type="button" data-billing="monthly">Monthly</button><button type="button" data-billing="annual">Annual · save 20%</button></div>
</section>
<main>
<section class="vp3-section"><div class="vp3-wrap"><div class="vp3-price-grid">
  <article class="vp3-plan"><h2>Personal</h2><div class="vp3-plan-desc">For an individual building a private AI assistant and second brain.</div><div class="vp3-price"><strong data-monthly="0" data-annual="0">$0</strong><span>/mo</span></div><div class="vp3-price-note">Start with the essentials.</div><a class="vp3-btn" href="<?= e(url('/signup.php')) ?>">Get started</a><ul><li>Personal AI assistant</li><li>Personal URL and profile</li><li>Knowledge workspace</li><li>Basic transcriptions</li><li>Profile Chat Widget</li></ul></article>
  <article class="vp3-plan featured"><span class="vp3-plan-badge">Most popular</span><h2>Professional</h2><div class="vp3-plan-desc">For people using VP3 every day across projects, recordings, knowledge, and proactive work.</div><div class="vp3-price"><strong data-monthly="29" data-annual="23">$29</strong><span>/mo</span></div><div class="vp3-price-note">For a single professional workspace.</div><a class="vp3-btn primary" href="<?= e(url('/signup.php')) ?>">Start with VP3</a><ul><li>Everything in Personal</li><li>Expanded transcription workflows</li><li>AI summaries and action items</li><li>Agent Brain and proactive activity</li><li>Project and contact workflows</li><li>Advanced assistant tools</li></ul></article>
  <article class="vp3-plan"><h2>Team</h2><div class="vp3-plan-desc">For groups that need shared context, controlled access, and coordinated work.</div><div class="vp3-price"><strong data-monthly="59" data-annual="47">$59</strong><span>/mo</span></div><div class="vp3-price-note">Team workspace and management tools.</div><a class="vp3-btn" href="<?= e(url('/book-demo.php')) ?>">Book a demo</a><ul><li>Everything in Professional</li><li>Team and role management</li><li>Shared knowledge controls</li><li>Collaboration workflows</li><li>Activity and approval history</li></ul></article>
  <article class="vp3-plan"><h2>Organization</h2><div class="vp3-plan-desc">For larger operations that need tailored access, workflows, and deployment support.</div><div class="vp3-price"><strong style="font-size:36px">Custom</strong></div><div class="vp3-price-note">Designed around your organization.</div><a class="vp3-btn" href="<?= e(url('/book-demo.php')) ?>">Talk to VP3</a><ul><li>Multiple managed workspaces</li><li>Role-based access</li><li>Centralized administration</li><li>Custom onboarding</li><li>Deployment planning</li></ul></article>
</div></div></section>
<section class="vp3-section soft"><div class="vp3-wrap"><div class="vp3-section-head"><div class="vp3-kicker">Compare plans</div><h2>Start simple. Add what you need.</h2></div><div class="vp3-matrix"><table><thead><tr><th>Capability</th><th>Personal</th><th>Professional</th><th>Team</th><th>Organization</th></tr></thead><tbody><tr><td>Personal assistant</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>Personal URL & Profile Agent</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>Transcriptions</td><td>Basic</td><td>Expanded</td><td>Expanded</td><td>Custom</td></tr><tr><td>AI summaries</td><td>Basic</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>Agent Brain / second brain</td><td>Basic</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>Team management</td><td>—</td><td>—</td><td>✓</td><td>✓</td></tr><tr><td>Organization controls</td><td>—</td><td>—</td><td>—</td><td>✓</td></tr></tbody></table></div></div></section>
<section class="vp3-section"><div class="vp3-wrap"><div class="vp3-section-head"><div class="vp3-kicker">Questions</div><h2>Pricing FAQ</h2></div><div class="vp3-faq-grid"><details open><summary>Can I start without a paid plan?</summary><p>Yes. Personal is designed to let you establish your VP3 account and core assistant workspace first.</p></details><details><summary>Can I change plans later?</summary><p>Yes. Your workspace can move between plan levels as your needs change.</p></details><details><summary>Which plan supports teams?</summary><p>The Team plan adds shared knowledge, role management, collaboration, and team-level operations.</p></details><details><summary>What is the Organization plan?</summary><p>It is a tailored setup for larger groups that need managed deployment, role-based access, and custom workflows.</p></details></div></div></section>
<section class="vp3-section soft"><div class="vp3-wrap"><div class="vp3-cta-box"><div><h2>Not sure which setup fits?</h2><p>Tell us how you work and we’ll map the right VP3 configuration.</p></div><a class="vp3-btn primary" href="<?= e(url('/book-demo.php')) ?>">Find my setup →</a></div></div></section>
</main>
<script>(()=>{const buttons=document.querySelectorAll('[data-billing]'),prices=document.querySelectorAll('[data-monthly][data-annual]');buttons.forEach(btn=>btn.addEventListener('click',()=>{buttons.forEach(b=>b.classList.remove('active'));btn.classList.add('active');const annual=btn.dataset.billing==='annual';prices.forEach(p=>p.textContent='$'+(annual?p.dataset.annual:p.dataset.monthly));}));})();</script>
<?php vp3_public_footer(); ?>
