<?php
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
redirect_logged_in_public_page();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Stonefellow pricing for artists, producers, managers, music supervisors and teams."><title>Pricing — Stonefellow</title><link rel="stylesheet" href="<?= e(url('/marketing.css?v=180')) ?>"></head><body>
<header class="site-header"><div class="wrap nav"><a class="brand" href="<?= e(url('/index.php')) ?>"><span class="brand-mark"><span>S</span></span>Stonefellow</a><nav class="nav-links"><a href="<?= e(url('/index.php#product')) ?>">Product</a><a href="<?= e(url('/index.php#roles')) ?>">Solutions</a><a href="<?= e(url('/index.php#resources')) ?>">Resources</a><a href="<?= e(url('/pricing.php')) ?>">Pricing</a><a href="<?= e(url('/book-demo.php')) ?>">Book a demo</a></nav><div class="nav-actions"><a class="nav-login" href="<?= e(url('/login.php')) ?>">Log in</a><a class="btn btn-primary" href="<?= e(url('/signup.php')) ?>">Start free trial</a><button class="menu-btn" id="menuBtn" aria-label="Open menu" aria-controls="mobileMenu" aria-expanded="false">☰</button></div></div><div class="mobile-menu-overlay" id="mobileMenuOverlay" aria-hidden="true"></div><aside class="mobile-menu" id="mobileMenu" aria-hidden="true"><div class="mobile-menu-head"><a class="brand" href="<?= e(url('/index.php')) ?>"><span class="brand-mark"><span>S</span></span>Stonefellow</a><button class="mobile-menu-close" id="menuClose">×</button></div><nav class="mobile-menu-links"><a href="<?= e(url('/index.php#product')) ?>">Product <span>→</span></a><a href="<?= e(url('/index.php#roles')) ?>">Solutions <span>→</span></a><a href="<?= e(url('/pricing.php')) ?>">Pricing <span>→</span></a><a href="<?= e(url('/book-demo.php')) ?>">Book a demo <span>→</span></a></nav><div class="mobile-menu-actions"><a class="btn btn-light" href="<?= e(url('/signup.php')) ?>">Start free trial</a><a class="btn btn-secondary" href="<?= e(url('/login.php')) ?>">Log in</a></div></aside></header>
<section class="pricing-hero"><div class="wrap"><div class="eyebrow">Simple plans. Real music workflows.</div><h1>Choose the Stonefellow setup that fits how you work.</h1><p>Start with your current workflow and add team access as you grow. AI helps organize, review, track and coordinate the work around your music—never generate the creative output.</p><div class="billing"><button class="active" data-billing="monthly">Monthly</button><button data-billing="annual">Annual · save 20%</button></div></div></section>
<main><section class="pricing-wrap"><div class="wrap"><div class="price-grid">
<article class="plan"><h2>Artist</h2><div class="desc">For independent artists organizing stems, sessions and releases.</div><div class="price"><strong data-monthly="0" data-annual="0">$0</strong><span>/mo</span></div><div class="price-note">Start with the essentials.</div><a class="btn btn-outline" href="<?= e(url('/signup.php')) ?>">Get started</a><ul><li>1 active artist workspace</li><li>Stem and version organization</li><li>Session notes</li><li>Basic release checklist</li><li>Personal activity feed</li></ul></article>
<article class="plan featured"><span class="badge">Most popular</span><h2>Producer</h2><div class="desc">For producers managing multiple projects, versions and collaborators.</div><div class="price"><strong data-monthly="29" data-annual="23">$29</strong><span>/mo</span></div><div class="price-note">Per producer workspace.</div><a class="btn btn-primary" href="<?= e(url('/signup.php')) ?>">Start free trial</a><ul><li>Unlimited active projects</li><li>Stem review and version history</li><li>Recording and session notes</li><li>Project approvals</li><li>AI workflow assistant</li><li>Collaborator access</li></ul></article>
<article class="plan"><h2>Professional</h2><div class="desc">For managers, music supervisors and song or legal operations.</div><div class="price"><strong data-monthly="59" data-annual="47">$59</strong><span>/mo</span></div><div class="price-note">Includes professional workflow tools.</div><a class="btn btn-outline" href="<?= e(url('/book-demo.php')) ?>">Book a demo</a><ul><li>Everything in Producer</li><li>Rights and split management</li><li>Publishing and metadata workflows</li><li>Release planning</li><li>Approvals and audit history</li></ul></article>
<article class="plan"><h2>Organization</h2><div class="desc">For studios, venues and larger teams that need role-based operations.</div><div class="price"><strong style="font-size:36px">Custom</strong></div><div class="price-note">Designed around your team and workflow.</div><a class="btn btn-outline" href="<?= e(url('/book-demo.php')) ?>">Talk to Stonefellow</a><ul><li>Multiple role-based workspaces</li><li>Venue and event operations</li><li>Team permissions</li><li>Centralized activity and approvals</li><li>Custom onboarding</li></ul></article>
</div></div></section>
<section class="matrix-section"><div class="wrap"><div class="center"><div class="eyebrow">Compare plans</div><h2 class="section-title">Start simple. Add the operations you need.</h2></div><div class="matrix"><table><thead><tr><th>Capability</th><th>Artist</th><th>Producer</th><th>Professional</th><th>Organization</th></tr></thead><tbody><tr><td>Stem & project organization</td><td class="yes">✓</td><td class="yes">✓</td><td class="yes">✓</td><td class="yes">✓</td></tr><tr><td>Session notes</td><td class="yes">✓</td><td class="yes">✓</td><td class="yes">✓</td><td class="yes">✓</td></tr><tr><td>Version history</td><td>Limited</td><td class="yes">✓</td><td class="yes">✓</td><td class="yes">✓</td></tr><tr><td>AI workflow assistant</td><td>Basic</td><td class="yes">✓</td><td class="yes">✓</td><td class="yes">✓</td></tr><tr><td>Rights & splits</td><td>—</td><td>—</td><td class="yes">✓</td><td class="yes">✓</td></tr><tr><td>Venue & event operations</td><td>—</td><td>—</td><td>—</td><td class="yes">✓</td></tr></tbody></table></div></div></section>
<section class="faq"><div class="wrap center"><div class="eyebrow">Questions</div><h2 class="section-title">Pricing FAQ</h2><div class="faq-grid" style="text-align:left"><details open><summary>Does Stonefellow create music with AI?</summary><p>No. Stonefellow uses AI to help manage, analyze, organize and coordinate the user's existing stems, sessions, rights, tasks and release workflows.</p></details><details><summary>Can I change plans later?</summary><p>Yes. Workspaces can move between plans as needs change.</p></details><details><summary>Which plan is for supervisors or managers?</summary><p>The Professional plan is designed for management, supervision, rights, publishing and release workflows.</p></details><details><summary>What should a venue choose?</summary><p>Venue and multi-role operations are part of the Organization setup.</p></details></div></div></section>
<section class="cta"><div class="wrap"><div class="cta-box"><div><h2>Not sure which setup fits?</h2><p>Tell us how you work and we will map the right configuration.</p></div><a class="btn btn-primary" href="<?= e(url('/book-demo.php')) ?>">Find my setup</a></div></div></section></main>
<footer class="footer"><div class="wrap"><div class="footer-grid"><div><a class="brand" href="<?= e(url('/index.php')) ?>"><span class="brand-mark"><span>S</span></span>Stonefellow</a><p>AI Studio Assistant for modern music operations.</p></div><div><h4>Product</h4><a href="<?= e(url('/index.php#product')) ?>">Features</a><a href="<?= e(url('/pricing.php')) ?>">Pricing</a></div><div><h4>Solutions</h4><a href="<?= e(url('/index.php#roles')) ?>">Music teams</a><a href="<?= e(url('/book-demo.php')) ?>">Organizations</a></div><div><h4>Resources</h4><a href="<?= e(url('/about.php')) ?>">About</a><a href="<?= e(url('/contact.php')) ?>">Contact</a></div><div><h4>Company</h4><a href="<?= e(url('/privacy.php')) ?>">Privacy</a><a href="<?= e(url('/terms.php')) ?>">Terms</a></div></div><div class="footer-bottom"><span>© 2026 Stonefellow. All rights reserved.</span><span>Built for real music workflows.</span></div></div></footer>
<script src="<?= e(url('/auth.js?v=180')) ?>"></script><script>(()=>{const buttons=document.querySelectorAll('[data-billing]'),prices=document.querySelectorAll('[data-monthly][data-annual]');buttons.forEach(btn=>btn.addEventListener('click',()=>{buttons.forEach(b=>b.classList.remove('active'));btn.classList.add('active');const annual=btn.dataset.billing==='annual';prices.forEach(p=>p.textContent='$'+(annual?p.dataset.annual:p.dataset.monthly));}));})();</script></body></html>
