<?php
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
$contactEmail = (string)setting('contact_email', (string)site_config('email', 'stonefellow74@gmail.com'));
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="How Stonefellow handles account, workflow and service information."><title>Privacy Policy — Stonefellow</title><style>
:root{--ink:#0d1020;--muted:#687083;--line:#e1e4eb;--dark:#0b0c12;--purple:#6f4cff;--max:1040px}*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;color:var(--ink);background:#fff;line-height:1.65}a{color:inherit;text-decoration:none}.wrap{width:min(var(--max),calc(100% - 40px));margin:0 auto}.header{background:#0b0c12;color:#fff;border-bottom:1px solid #242733}.nav{height:74px;display:flex;align-items:center;justify-content:space-between;gap:24px}.brand{display:flex;align-items:center;gap:11px;font-weight:900;font-size:21px}.brand-mark{width:34px;height:34px;border:2px solid currentColor;border-radius:9px;display:grid;place-items:center;transform:rotate(30deg)}.brand-mark span{transform:rotate(-30deg);font-size:16px}.nav-links{display:flex;gap:22px;color:#cfd2db;font-size:13px}.hero{background:linear-gradient(180deg,#0b0c12,#11131b);color:#fff;padding:78px 0 82px}.eyebrow{font-size:12px;font-weight:900;letter-spacing:.13em;text-transform:uppercase;color:#9c8aff}h1{font-size:clamp(48px,7vw,78px);line-height:.98;letter-spacing:-.055em;margin:14px 0 16px}.hero p{color:#b8bdc9;font-size:17px;max-width:700px;margin:0}.legal{padding:72px 0 90px}.legal h2{font-size:25px;letter-spacing:-.02em;margin:38px 0 10px}.legal h2:first-child{margin-top:0}.legal p,.legal li{color:#596071;font-size:15px}.legal ul{padding-left:22px}.updated{display:inline-block;border:1px solid #dedfea;border-radius:999px;padding:7px 11px;font-size:11px;color:#707686;margin-bottom:20px}.footer{border-top:1px solid #e5e7ed;padding:30px 0 45px;color:#7b8190;font-size:12px}.footer-row{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}.footer a{color:#4e46a8;font-weight:700}@media(max-width:760px){.nav-links{display:none}.wrap{width:min(100% - 24px,var(--max))}.hero{padding:58px 0}.legal{padding:52px 0 70px}}
</style></head><body><header class="header"><div class="wrap nav"><a class="brand" href="<?= e(url('/index.php')) ?>"><span class="brand-mark"><span>S</span></span><span>Stonefellow</span></a><nav class="nav-links"><a href="<?= e(url('/index.php#product')) ?>">Product</a><a href="<?= e(url('/pricing.php')) ?>">Pricing</a><a href="<?= e(url('/book-demo.php')) ?>">Book a demo</a><a href="<?= e(url('/login.php')) ?>">Sign in</a></nav></div></header><section class="hero"><div class="wrap"><div class="eyebrow">Stonefellow legal</div><h1>Privacy Policy</h1><p>How Stonefellow handles account, workflow and service information.</p></div></section><main class="legal"><div class="wrap"><span class="updated">Last updated August 31, 2026</span>
<h2>1. Information we collect</h2><p>Stonefellow may collect information you provide directly, including account details, contact and demo-request information, profile details, and music-workflow content you choose to upload or enter. We may also collect technical information needed to operate and secure the service, such as IP address, browser or device information, timestamps, and service activity.</p>
<h2>2. How we use information</h2><p>We use information to provide and secure Stonefellow, authenticate accounts, organize your projects and workflow data, respond to support and demo requests, improve reliability, prevent abuse, and communicate about the service.</p>
<h2>3. Music, files and workspace content</h2><p>You retain ownership of the music, stems, notes, metadata, documents and other content you submit. Stonefellow processes that content only as needed to provide the features you request, subject to these terms and any additional agreement that applies to your account.</p>
<h2>4. AI features</h2><p>Stonefellow may use AI services to analyze, organize, summarize or assist with operational workflows around content you provide. Stonefellow is designed as a studio and business assistant and does not claim ownership of your creative work. Third-party AI providers, when enabled, may process limited data necessary to fulfill the requested feature.</p>
<h2>5. Sharing</h2><p>We do not sell your personal information. We may share information with service providers that help us host, secure, communicate, process requests or operate Stonefellow; when required by law; or as part of a business transaction subject to appropriate safeguards.</p>
<h2>6. Data retention and deletion</h2><p>We retain information for as long as needed to provide the service, meet legal or security obligations, resolve disputes and enforce agreements. Account owners may contact us to request access, correction or deletion where applicable.</p>
<h2>7. Security</h2><p>We use reasonable administrative and technical safeguards intended to protect account and workspace information. No internet service can guarantee absolute security, so users should also protect passwords and account access.</p>
<h2>8. Cookies and local storage</h2><p>Stonefellow may use cookies, sessions and browser storage required for authentication, preferences, security and core product functionality.</p>
<h2>9. Children</h2><p>Stonefellow is not directed to children under 13, and we do not knowingly collect personal information from children under 13.</p>
<h2>10. Changes and contact</h2><p>We may update this Privacy Policy as Stonefellow evolves. Material changes will be reflected by an updated date on this page. Questions or privacy requests can be sent to <a href="mailto:<?= e($contactEmail) ?>"><?= e($contactEmail) ?></a>.</p>
</div></main><footer class="footer"><div class="wrap footer-row"><span>© 2026 Stonefellow. All rights reserved.</span><span><a href="<?= e(url('/privacy.php')) ?>">Privacy</a> · <a href="<?= e(url('/terms.php')) ?>">Terms</a> · <a href="<?= e(url('/contact.php')) ?>">Contact</a></span></div></footer></body></html>
