<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
require_once __DIR__.'/includes/profile-commerce-lifecycle-v1100.php';

header('Cache-Control: no-store, private, max-age=0');
header('Pragma: no-cache');
header('Referrer-Policy: no-referrer');
header('X-Robots-Tag: noindex, nofollow, noarchive');

$pdo=db();if(!$pdo||!profile_agent_schema_ready($pdo)||!agent_commerce_schema_ready_v800($pdo)){http_response_code(503);exit('Profile Commerce is not ready.');}
$username=profile_username_normalize((string)($_GET['username']??''));$orderNumber=trim((string)($_GET['order']??''));$receipt=strtolower(trim((string)($_GET['receipt']??'')));
$profile=profile_by_username($pdo,$username);if(!$profile||empty($profile['is_active'])){http_response_code(404);exit('Order not found.');}
$order=profile_commerce_customer_order_v1100($pdo,(int)$profile['user_id'],$orderNumber,$receipt);if(!$order){http_response_code(404);exit('Order not found.');}
$view=profile_commerce_customer_projection_v1100($order);$seller=trim((string)($profile['display_name']??''));if($seller==='')$seller=(string)$profile['username'];$profileUrl=!empty($profile['is_public'])?profile_public_url($username):'';
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title><?=e($seller)?> · Order <?=e((string)$view['order_number'])?></title><style>
:root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#f4f4f1;color:#171816;font:15px/1.5 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.wrap{max-width:760px;margin:0 auto;padding:42px 20px 64px}.top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:18px}.eyebrow{text-transform:uppercase;letter-spacing:.12em;font-size:12px;color:#74766f}.card{background:#fff;border:1px solid #e0e2dc;border-radius:22px;padding:24px;margin-top:14px}.status{display:inline-flex;align-items:center;border-radius:999px;background:#eff1ec;padding:7px 11px;font-weight:650}.muted{color:#666962}.money{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:16px}.metric{background:#f7f7f4;border-radius:14px;padding:14px}.metric strong{display:block;font-size:18px;margin-top:3px}.item{padding:14px 0;border-top:1px solid #ecece7}.item:first-child{border-top:0}.row{display:flex;justify-content:space-between;gap:16px}.small{font-size:13px}.link{color:#171816;text-decoration:none;border-bottom:1px solid #b8bbb3}@media(max-width:640px){.top,.row{display:block}.money{grid-template-columns:1fr}.wrap{padding-top:24px}}
</style></head><body><main class="wrap"><div class="top"><div><div class="eyebrow">Profile Commerce receipt</div><h1>Order <?=e((string)$view['order_number'])?></h1><p class="muted">Purchased from <?=e($seller)?>.</p></div><?php if($profileUrl!==''):?><a class="link" href="<?=e($profileUrl)?>">Seller profile</a><?php endif;?></div><section class="card"><span class="status"><?=e((string)$view['status']['label'])?></span><h2><?=e((string)$view['status']['message'])?></h2><p class="muted">This page reads the canonical VP3 Commerce order. Payment is shown as paid only after provider verification.</p><div class="money"><div class="metric"><span class="eyebrow">Order total</span><strong><?=e((string)$view['total_label'])?></strong></div><div class="metric"><span class="eyebrow">Paid</span><strong><?=e((string)$view['paid_label'])?></strong></div><div class="metric"><span class="eyebrow">Refunded</span><strong><?=e((string)$view['refunded_label'])?></strong></div></div></section><section class="card"><div class="eyebrow">Items</div><?php foreach((array)$view['items'] as $item):?><div class="item"><div class="row"><div><strong><?=e((string)$item['title'])?></strong><div class="muted small"><?=e((string)$item['fulfillment_type'])?> · Qty <?=(int)$item['quantity']?></div></div><div class="small"><strong><?=e(ucfirst((string)$item['fulfillment_status']))?></strong></div></div></div><?php endforeach;?></section><section class="card"><div class="eyebrow">Order timeline</div><div class="item"><div class="row"><strong>Order created</strong><span class="muted small"><?=e((string)$view['created_at'])?></span></div></div><div class="item"><div class="row"><strong>Latest update</strong><span class="muted small"><?=e((string)$view['updated_at'])?></span></div></div><p class="muted small">Keep this private receipt link. It contains an opaque access token; VP3 stores only the token hash with the canonical order.</p></section></main></body></html>