<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';require_permission('account.access');
$pdo=db();$user=current_user();if(!$pdo||!$user)redirect(url('/login.php'));if(!agent_scheduling_schema_ready_v430($pdo))redirect(url('/upgrade.php'));
$schedule=agent_scheduling_default_schedule_v430($pdo,$user);$scheduleId=max(0,(int)($_GET['schedule']??$_POST['schedule_id']??0));if($scheduleId>0){$candidate=agent_scheduling_schedule_v430($pdo,(int)$user['id'],$scheduleId);if($candidate)$schedule=$candidate;}$scheduleId=(int)$schedule['id'];$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verify_csrf())$error='Session expired. Please try again.';else try{
  $event=agent_scheduling_save_event_type_v430($pdo,$user,['id'=>0,'schedule_id'=>$scheduleId,'title'=>(string)($_POST['title']??''),'slug'=>(string)($_POST['slug']??''),'description'=>(string)($_POST['description']??''),'duration_minutes'=>(int)($_POST['duration_minutes']??30),'slot_interval_minutes'=>(int)($_POST['slot_interval_minutes']??30),'location_type'=>(string)($_POST['location_type']??'virtual'),'location_value'=>(string)($_POST['location_value']??''),'buffer_before_minutes'=>(int)($_POST['buffer_before_minutes']??0),'buffer_after_minutes'=>(int)($_POST['buffer_after_minutes']??0),'minimum_notice_minutes'=>(int)($_POST['minimum_notice_minutes']??60),'booking_window_days'=>(int)($_POST['booking_window_days']??60),'max_bookings_per_day'=>(int)($_POST['max_bookings_per_day']??0),'is_active'=>!empty($_POST['is_active'])]);
  redirect(url('/scheduling.php?schedule='.$scheduleId.'&tab=types&saved='.rawurlencode('Appointment type created.').'&event='.(int)$event['id']));
 }catch(Throwable $e){$error=$e->getMessage();}
}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f7f7f5"><title><?= e(system_agent_name()) ?> | New Appointment Type</title><link rel="stylesheet" href="<?= e(url('/chat.css?v=82')) ?>"><link rel="stylesheet" href="<?= e(url('/scheduling.css?v=agent-calendar-sync-v500-20260911')) ?>"><link rel="stylesheet" href="<?= e(url('/calendar-v1300.css?v=1300')) ?>"></head><body class="scheduling-page"><div class="chat-app">
<?php $workspaceSidebarUser=$user;$workspaceSidebarActive='scheduling';require __DIR__.'/includes/workspace-sidebar-v82.php'; ?><div class="chat-sidebar-backdrop" id="chatSidebarBackdrop"></div><main class="chat-main scheduling-main">
<?php $memberHeaderUser=$user;$memberHeaderTitle='Create appointment type';$memberHeaderSubtitle='A public booking option for '.$schedule['name'];$memberHeaderActions='<a class="calendar-button" href="'.e(url('/scheduling.php?schedule='.$scheduleId.'&tab=types')).'">← Scheduling</a>';require __DIR__.'/includes/member-header.php'; ?>
<section class="scheduling-canvas"><div class="scheduling-inner" style="max-width:980px"><?php if($error!==''): ?><div class="scheduling-notice error" role="alert"><?= e($error) ?></div><?php endif; ?><div class="calendar-help"><strong>Appointment type</strong> — this defines a booking option visitors or your Agent can schedule. For a private dated event, use <a href="<?= e(url('/calendar-event.php')) ?>">Calendar → New event</a>.</div>
<section class="scheduling-section" style="margin-top:0"><div class="scheduling-section-head"><div><span class="scheduling-eyebrow">New booking option</span><h2>Create appointment type</h2><p>Set the duration, cadence, buffers, location and booking rules. Availability is managed separately on the Scheduling page.</p></div></div>
<form method="post" class="scheduling-panel scheduling-form event-form"><?= csrf_field() ?><input type="hidden" name="schedule_id" value="<?= $scheduleId ?>">
<label class="span-2"><span>Title</span><input name="title" maxlength="190" required value="<?= e((string)($_POST['title']??'')) ?>" placeholder="30 Minute Meeting"></label>
<label><span>URL slug</span><input name="slug" maxlength="80" value="<?= e((string)($_POST['slug']??'')) ?>" placeholder="30-minute-meeting"></label>
<label><span>Duration</span><select name="duration_minutes"><?php foreach([15,20,30,45,60,90,120] as $m): ?><option value="<?= $m ?>" <?= (int)($_POST['duration_minutes']??30)===$m?'selected':'' ?>><?= $m ?> minutes</option><?php endforeach; ?></select></label>
<label><span>Start times every</span><select name="slot_interval_minutes"><?php foreach([5,10,15,20,30,45,60] as $m): ?><option value="<?= $m ?>" <?= (int)($_POST['slot_interval_minutes']??30)===$m?'selected':'' ?>><?= $m ?> min</option><?php endforeach; ?></select></label>
<label><span>Location</span><select name="location_type"><?php foreach(['virtual'=>'Virtual','phone'=>'Phone','in_person'=>'In person','custom'=>'Custom'] as $key=>$label): ?><option value="<?= e($key) ?>" <?= (string)($_POST['location_type']??'virtual')===$key?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></label>
<label class="span-2"><span>Location / meeting instructions</span><input name="location_value" maxlength="500" value="<?= e((string)($_POST['location_value']??'')) ?>" placeholder="Video link, phone instructions or address"></label>
<label><span>Buffer before</span><input type="number" min="0" max="1440" name="buffer_before_minutes" value="<?= (int)($_POST['buffer_before_minutes']??0) ?>"></label><label><span>Buffer after</span><input type="number" min="0" max="1440" name="buffer_after_minutes" value="<?= (int)($_POST['buffer_after_minutes']??0) ?>"></label>
<label><span>Minimum notice</span><input type="number" min="0" max="525600" name="minimum_notice_minutes" value="<?= (int)($_POST['minimum_notice_minutes']??60) ?>"><small>Minutes</small></label><label><span>Booking horizon</span><input type="number" min="1" max="730" name="booking_window_days" value="<?= (int)($_POST['booking_window_days']??60) ?>"><small>Days ahead</small></label>
<label><span>Daily limit</span><input type="number" min="0" max="1000" name="max_bookings_per_day" value="<?= (int)($_POST['max_bookings_per_day']??0) ?>"><small>0 = unlimited</small></label><label class="span-2"><span>Description</span><textarea name="description" rows="4" placeholder="What should guests know before booking?"><?= e((string)($_POST['description']??'')) ?></textarea></label>
<label class="toggle-line span-2"><input type="checkbox" name="is_active" value="1" <?= !isset($_POST['is_active'])||!empty($_POST['is_active'])?'checked':'' ?>><span>Accept bookings for this appointment type</span></label><div class="form-actions span-2"><a class="scheduling-button" href="<?= e(url('/scheduling.php?schedule='.$scheduleId.'&tab=types')) ?>">Cancel</a><button type="submit" class="scheduling-button primary">Create appointment type</button></div></form></section>
</div></section></main></div><script src="<?= e(url('/member-shell-v77.js?v=20260911')) ?>"></script></body></html>
