<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
$pdo=vp3_browser_trust_require_ready_v2080(db());$user=current_user();$userId=(int)($user['id']??0);
$changeId=trim((string)($_GET['change']??''));
try{$comparison=vp3_browser_trust_compare_change_v2080($pdo,$userId,$changeId);}catch(Throwable $e){http_response_code(404);$comparison=null;}
function sc_e(string $v): string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Source Change · VP3</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f5f2;color:#171717;font:15px/1.55 Inter,system-ui,sans-serif}.shell{max-width:1000px;margin:auto;padding:28px 18px 70px}.top{display:flex;justify-content:space-between;gap:12px}.brand{font-weight:900;text-decoration:none}.card{margin-top:16px;padding:18px;background:#fff;border:1px solid #e1e1dc;border-radius:16px}.versions{display:grid;grid-template-columns:1fr 1fr;gap:14px}.hash{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;overflow-wrap:anywhere}.annotation{padding:11px;border:1px solid #ecece7;border-radius:10px;margin-top:8px}.quote{padding:9px;border-left:3px solid #d0d0c8;background:#fafaf7;white-space:pre-wrap}.meta{color:#707069;font-size:11px}.empty{padding:36px;text-align:center;color:#777}.button{display:inline-flex;padding:7px 10px;border:1px solid #ccc;border-radius:8px;background:#fff;color:#111;text-decoration:none;font-size:11px;font-weight:800}@media(max-width:700px){.versions{grid-template-columns:1fr}}</style></head><body><main class="shell"><div class="top"><a class="brand" href="<?=sc_e(url('/'))?>">VP3</a><?php if($comparison):?><a class="button" href="<?=sc_e((string)$comparison['source']['page_url'])?>">Back to Source</a><?php endif;?></div>
<?php if(!$comparison):?><div class="empty">This source change is not available.</div><?php else:$change=$comparison['change'];?><section class="card"><small>SOURCE VERSION COMPARISON</small><h1><?=sc_e((string)($comparison['source']['domain']??'Source'))?></h1><p><?=sc_e((string)$change['summary'])?></p><div class="meta">Observed <?=sc_e((string)$change['observed_at'])?>. VP3 compares immutable version fingerprints and the authorized annotations pinned to each version; it does not reconstruct private page text.</div></section>
<div class="versions">
<?php foreach([['Before',$change['from'],$comparison['from_annotations']],['After',$change['to'],$comparison['to_annotations']]] as [$label,$version,$items]):?><section class="card"><small><?=sc_e(strtoupper($label))?></small><h2><?=sc_e((string)($version['title']??'Source version'))?></h2><div class="hash"><?=sc_e((string)($version['hash']??''))?></div><div class="meta"><?=sc_e((string)($version['basis']??''))?> · <?=sc_e((string)($version['captured_at']??''))?></div>
<?php foreach($items as $item):?><article class="annotation"><?php if($item['selection']):?><div class="quote"><?=sc_e((string)$item['selection'])?></div><?php endif;?><?php if($item['note']):?><p><?=sc_e((string)$item['note'])?></p><?php endif;?><div class="meta"><?=sc_e((string)($item['sender']['name']??'VP3 user'))?> · <?=sc_e((string)$item['visibility'])?> · <?=sc_e((string)$item['created_at'])?></div><a class="button" href="<?=sc_e((string)$item['annotation_url'])?>">Open annotation</a></article><?php endforeach;?>
<?php if(!$items):?><div class="empty">No annotations visible to you are pinned to this version.</div><?php endif;?></section><?php endforeach;?></div>
<?php endif;?></main></body></html>