<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
require_login();
$user=current_user();$pdo=db();
if(!$user||!$pdo){flash('error','Account unavailable.');redirect(url('/login.php'));}
if(!subscription_schema_ready($pdo))redirect(url('/upgrade.php'));

$subscription=subscription_current($user);$balance=subscription_ai_balance($user,$pdo);$usage=subscription_usage_by_scope((int)$user['id'],30);$credits=subscription_recent_credits((int)$user['id'],30);$packages=subscription_packages(true);
$allowance=max(0,(int)($balance['package_allowance']??0));$remaining=(int)($balance['remaining']??0);$used=(int)($balance['used']??0);
$percent=$allowance>0?min(100,(int)round(($used/$allowance)*100)):0;
$warning='';
if(empty($balance['unlimited'])){
    if($remaining<=0)$warning='Your AI token balance is exhausted. Non-AI features remain available; an Admin can add tokens or assign another package.';
    elseif($percent>=95)$warning='You have used at least 95% of your package AI allowance.';
    elseif($percent>=80)$warning='You have used at least 80% of your package AI allowance.';
    elseif($percent>=50)$warning='You have used at least 50% of your package AI allowance.';
}
$entitlements=[];
if($subscription){$pkg=subscription_package((int)$subscription['package_id']);foreach(($pkg['entitlements']??[]) as $row)$entitlements[(string)$row['capability_key']]=$row;}
$periodEnd=(string)($subscription['current_period_end']??$subscription['ends_at']??'');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Plan & AI Usage | VP3</title><link rel="stylesheet" href="<?= e(url('/chat.css?v=82')) ?>"><link rel="stylesheet" href="<?= e(url('/account.css?v=account-light-20260904')) ?>"><style>
.plan-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:18px 0}.plan-stat,.plan-card{border:1px solid #dfe3e8;border-radius:14px;background:#fff;padding:18px}.plan-stat span,.plan-card small{display:block;color:#667085;font-size:12px}.plan-stat strong{display:block;font-size:24px;margin-top:5px}.plan-table{width:100%;border-collapse:collapse}.plan-table th,.plan-table td{padding:11px 8px;border-bottom:1px solid #eaecf0;text-align:left}.plan-warning{padding:12px 14px;border:1px solid #d0d5dd;border-radius:10px;margin:14px 0;background:#f9fafb}.plan-feature-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.plan-feature{border:1px solid #eaecf0;border-radius:10px;padding:12px}.plan-feature b{display:block}.plan-options{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.plan-current{outline:2px solid #111827}.plan-progress{height:8px;background:#eaecf0;border-radius:999px;overflow:hidden}.plan-progress i{display:block;height:100%;background:#111827}.plan-muted{color:#667085}.plan-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}@media(max-width:900px){.plan-grid,.plan-feature-grid,.plan-options{grid-template-columns:1fr 1fr}}@media(max-width:620px){.plan-grid,.plan-feature-grid,.plan-options{grid-template-columns:1fr}}
</style></head><body><div class="chat-app"><?php $workspaceSidebarUser=$user;$workspaceSidebarActive='subscription';require __DIR__.'/includes/workspace-sidebar-v82.php';?><div class="chat-sidebar-backdrop" id="chatSidebarBackdrop"></div><main class="chat-main account-chat-main"><header class="chat-topbar"><button class="chat-icon-button mobile-only" id="openChatSidebar" type="button">☰</button><div class="chat-topbar-title"><strong>Plan & AI Usage</strong><span>Package, entitlements and token balance</span></div></header><section class="account-canvas"><div class="account-canvas-inner">
<section class="account-canvas-hero"><div><span>Current Package</span><h1><?= e((string)($subscription['package_name']??'No Package')) ?></h1><div class="account-canvas-meta"><span><?= e(ucfirst((string)($subscription['status']??'unassigned'))) ?></span><?php if($periodEnd):?><span><?= (int)($subscription['is_trial']??0)===1?'Trial ends':'Current period ends' ?> <?= e(date('M j, Y',strtotime($periodEnd))) ?></span><?php endif;?></div></div><div class="account-canvas-actions"><a class="account-shell-button" href="<?= e(url('/account.php')) ?>">My Account</a></div></section>
<?php if($warning):?><div class="plan-warning"><strong>AI usage notice</strong><div><?= e($warning) ?></div></div><?php endif;?>
<div class="plan-grid"><div class="plan-stat"><span>Package allowance</span><strong><?= !empty($balance['unlimited'])?'Unlimited':number_format($allowance) ?></strong></div><div class="plan-stat"><span>Token top-ups</span><strong><?= number_format((int)($balance['credits_remaining']??0)) ?></strong></div><div class="plan-stat"><span>Used this period</span><strong><?= number_format($used) ?></strong></div><div class="plan-stat"><span>Available now</span><strong><?= !empty($balance['unlimited'])?'Unlimited':number_format($remaining) ?></strong></div></div>
<?php if(empty($balance['unlimited'])&&$allowance>0):?><div class="plan-card"><strong><?= $percent ?>% of package AI allowance used</strong><div class="plan-progress" aria-label="AI usage <?= $percent ?> percent"><i style="width:<?= $percent ?>%"></i></div></div><?php endif;?>
<section class="plan-card" style="margin-top:14px"><h2>Included Features</h2><p class="plan-muted">Your package is the commercial account type. Team roles are separate workspace relationships.</p><div class="plan-feature-grid"><?php foreach(subscription_capability_catalog() as $key=>$meta):if(str_starts_with($key,'permission.')||in_array($key,['legacy.permissions','ai.unlimited'],true))continue;$row=$entitlements[$key]??null;$enabled=$row&&(int)$row['is_enabled']===1;?><div class="plan-feature"><small><?= e((string)($meta['category']??'Feature')) ?></small><b><?= e((string)$meta['label']) ?></b><span><?= $enabled?(($meta['type']??'boolean')==='limit'&&$row['limit_value']!==null?number_format((int)$row['limit_value']).' included':'Included'):'Not included' ?></span></div><?php endforeach;?></div></section>
<section class="plan-card" style="margin-top:14px"><h2>AI Usage by Feature</h2><div style="overflow:auto"><table class="plan-table"><thead><tr><th>Feature</th><th>Requests</th><th>Input</th><th>Output</th><th>Total</th></tr></thead><tbody><?php foreach($usage as $row):?><tr><td><?= e((string)$row['scope']) ?></td><td><?= number_format((int)$row['requests']) ?></td><td><?= number_format((int)$row['input_tokens']) ?></td><td><?= number_format((int)$row['output_tokens']) ?></td><td><?= number_format((int)$row['total_tokens']) ?></td></tr><?php endforeach;?><?php if(!$usage):?><tr><td colspan="5">No metered AI usage yet.</td></tr><?php endif;?></tbody></table></div></section>
<section class="plan-card" style="margin-top:14px"><h2>Token Credits</h2><p class="plan-muted">Admin top-ups, promotional credits and future purchased token packs use the same credit ledger.</p><div style="overflow:auto"><table class="plan-table"><thead><tr><th>Amount</th><th>Remaining</th><th>Source</th><th>Expires</th></tr></thead><tbody><?php foreach($credits as $row):?><tr><td><?= number_format((int)$row['amount']) ?></td><td><?= number_format((int)$row['remaining_amount']) ?></td><td><?= e((string)$row['source']) ?></td><td><?= $row['expires_at']?e(date('M j, Y',strtotime((string)$row['expires_at']))):'No expiration' ?></td></tr><?php endforeach;?><?php if(!$credits):?><tr><td colspan="4">No token credits yet.</td></tr><?php endif;?></tbody></table></div></section>
<section class="plan-card" style="margin-top:14px"><h2>Available Packages</h2><p class="plan-muted">Billing is not connected yet. Package changes can currently be assigned by Admin; this catalog is ready for self-service checkout later.</p><div class="plan-options"><?php foreach($packages as $p):?><article class="plan-card <?= (int)($subscription['package_id']??0)===(int)$p['id']?'plan-current':'' ?>"><small><?= (int)$p['is_trial']===1?'Trial':'Package' ?></small><h3><?= e((string)$p['name']) ?></h3><p><?= e((string)$p['description']) ?></p><strong><?= (int)$p['is_trial']===1?number_format((int)$p['trial_tokens']).' trial AI tokens':number_format((int)$p['ai_tokens_monthly']).' AI tokens/month' ?></strong><?php if((int)($subscription['package_id']??0)===(int)$p['id']):?><div class="plan-actions"><span class="status">Current</span></div><?php endif;?></article><?php endforeach;?></div></section>
</div></section></main></div><script src="<?= e(url('/member-shell-v77.js')) ?>"></script></body></html>