<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
$pdo=db();if(!$pdo||!agent_team_scheduling_schema_ready_v600($pdo)){http_response_code(503);exit('Team scheduling is not available.');}
function team_book_display_time(string $utc,string $timezone,string $format='D, M j · g:i A T'): string{try{return(new DateTimeImmutable($utc,new DateTimeZone('UTC')))->setTimezone(new DateTimeZone(agent_scheduling_timezone_v430($timezone)))->format($format);}catch(Throwable $e){return '';}}
$error='';$success='';$manageToken=strtolower(trim((string)($_GET['manage']??$_POST['manage_token']??'')));$managed=null;$pool=null;
if($manageToken!==''){$managed=agent_team_scheduling_booking_by_cancel_token_v600($pdo,$manageToken);if($managed){$pool=agent_team_scheduling_pool_v600($pdo,(int)$managed['workspace_owner_user_id'],(int)$managed['pool_id']);}}
if(!$pool){$publicKey=strtolower(trim((string)($_GET['p']??$_POST['public_key']??'')));$pool=agent_team_scheduling_public_pool_v600($pdo,$publicKey);}
if(!$pool){http_response_code(404);exit('This Team booking page is not available.');}
$timezone=agent_scheduling_timezone_v430((string)$pool['timezone']);$tz=new DateTimeZone($timezone);$today=(new DateTimeImmutable('today',$tz))->format('Y-m-d');$date=trim((string)($_GET['date']??$_POST['date']??$today));$parsed=DateTimeImmutable::createFromFormat('!Y-m-d',$date,$tz);if(!$parsed||$parsed->format('Y-m-d')!==$date||$date<$today)$date=$today;$routingAnswer=mb_strimwidth(trim((string)($_GET['routing_answer']??$_POST['routing_answer']??'')),0,500,'');
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!verify_csrf())$error='Session expired. Please refresh and try again.';
    else try{
        $action=(string)($_POST['action']??'');agent_scheduling_public_rate_limit_v450('team-'.$action,12,60);
        if($action==='book'){
            $publicPool=agent_team_scheduling_public_pool_v600($pdo,(string)($_POST['public_key']??''));if(!$publicPool||(int)$publicPool['id']!==(int)$pool['id'])throw new RuntimeException('This Team booking page is no longer available.');
            if(trim((string)$pool['routing_question'])!==''&&$routingAnswer==='')throw new RuntimeException('Please answer the routing question before choosing a time.');
            $booking=agent_team_scheduling_create_booking_v600($pdo,$publicPool,['start_at_utc'=>(string)($_POST['start_at_utc']??''),'guest_timezone'=>(string)($_POST['guest_timezone']??$timezone),'guest_name'=>(string)($_POST['guest_name']??''),'guest_email'=>(string)($_POST['guest_email']??''),'guest_phone'=>(string)($_POST['guest_phone']??''),'routing_answer'=>$routingAnswer,'source'=>'team_public']);
            redirect(url('/team-book.php?manage='.rawurlencode((string)$booking['cancel_token']).'&booked=1'));
        }
        if($action==='cancel'){
            $booking=agent_team_scheduling_booking_by_cancel_token_v600($pdo,$manageToken);if(!$booking)throw new RuntimeException('This booking-management link is not valid.');if(!agent_team_scheduling_cancel_booking_v600($pdo,$booking))throw new RuntimeException('This Team booking is no longer active.');$managed=agent_team_scheduling_booking_by_cancel_token_v600($pdo,$manageToken);$success='Team booking cancelled across all participant calendars.';
        }
    }catch(Throwable $e){$error=$e->getMessage();}
}
$slots=[];if(!$managed&&empty($error))$slots=agent_team_scheduling_slots_v600($pdo,$pool,$date,$routingAnswer);$booked=!empty($_GET['booked']);
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title><?=e((string)$pool['name'])?> · Team booking</title><link rel="stylesheet" href="<?=e(url('/team-book.css?v=agent-team-scheduling-v600-20260911'))?>"></head><body><main class="team-book-shell">
<header class="team-book-brand"><a href="<?=e(url('/'))?>">VP3</a><span>Team Scheduling</span></header>
<?php if($managed):?>
<section class="team-book-card manage-card"><span class="eyebrow">Booking management</span><h1><?=e((string)$managed['pool_name'])?></h1><?php if($booked):?><div class="notice success">Your Team meeting is confirmed.</div><?php endif;?><?php if($success!==''):?><div class="notice success"><?=e($success)?></div><?php endif;?><?php if($error!==''):?><div class="notice error"><?=e($error)?></div><?php endif;?><div class="booking-summary"><div><span>When</span><strong><?=e(team_book_display_time((string)$managed['start_at_utc'],(string)$managed['pool_timezone']))?></strong></div><div><span>Guest</span><strong><?=e((string)$managed['guest_name'])?></strong></div><div><span>Format</span><strong><?=e((string)$managed['mode']==='round_robin'?'Round-robin host':'Collective Team meeting')?></strong></div><div><span>Status</span><strong><?=e(ucfirst((string)$managed['status']))?></strong></div></div><?php if(in_array((string)$managed['status'],['pending','confirmed'],true)):?><form method="post" onsubmit="return confirm('Cancel this Team meeting for every participant?')"><?=csrf_field()?><input type="hidden" name="action" value="cancel"><input type="hidden" name="manage_token" value="<?=e($manageToken)?>"><button class="danger-button" type="submit">Cancel Team meeting</button></form><?php endif;?><p class="security-note">This private management link controls only this booking. VP3 does not expose participant calendars or other visitors’ appointments.</p></section>
<?php else:?>
<section class="team-book-intro"><span class="eyebrow"><?=e((string)$pool['mode']==='round_robin'?'Round-robin Team':'Collective Team')?></span><h1><?=e((string)$pool['name'])?></h1><?php if(trim((string)$pool['description'])!==''):?><p><?=nl2br(e((string)$pool['description']))?></p><?php else:?><p>Choose a live Team time. VP3 checks the connected availability of the people who can host this meeting.</p><?php endif;?></section>
<?php if($error!==''):?><div class="notice error"><?=e($error)?></div><?php endif;?>
<section class="team-book-card"><form method="get" class="availability-filter"><input type="hidden" name="p" value="<?=e((string)$pool['public_key'])?>"><label><span>Date</span><input type="date" name="date" min="<?=e($today)?>" value="<?=e($date)?>"></label><?php if(trim((string)$pool['routing_question'])!==''):?><label class="wide"><span><?=e((string)$pool['routing_question'])?></span><input name="routing_answer" maxlength="500" required value="<?=e($routingAnswer)?>" placeholder="Tell us what you need"></label><?php endif;?><button type="submit">Check Team availability</button></form></section>
<section class="team-book-card"><div class="section-head"><div><span class="eyebrow">Live availability</span><h2><?=e((new DateTimeImmutable($date,$tz))->format('l, F j'))?></h2></div><span class="timezone-chip"><?=e($timezone)?></span></div><?php if($slots):?><form method="post" class="booking-form"><?=csrf_field()?><input type="hidden" name="action" value="book"><input type="hidden" name="public_key" value="<?=e((string)$pool['public_key'])?>"><input type="hidden" name="date" value="<?=e($date)?>"><input type="hidden" name="routing_answer" value="<?=e($routingAnswer)?>"><input type="hidden" name="guest_timezone" id="guestTimezone" value="<?=e($timezone)?>"><div class="slot-grid"><?php foreach($slots as $i=>$slot):?><label class="slot"><input type="radio" name="start_at_utc" value="<?=e((string)$slot['start_at_utc'])?>" <?=$i===0?'checked':''?>><span><?=e(team_book_display_time((string)$slot['start_at_utc'],$timezone,'g:i A'))?></span></label><?php endforeach;?></div><div class="guest-grid"><label><span>Name</span><input name="guest_name" maxlength="190" autocomplete="name" required></label><label><span>Email</span><input name="guest_email" type="email" maxlength="190" autocomplete="email"></label><label class="wide"><span>Phone <small>optional</small></span><input name="guest_phone" maxlength="80" autocomplete="tel"></label></div><button class="primary-button" type="submit">Confirm Team booking</button><p class="mode-note"><?=(string)$pool['mode']==='round_robin'?'VP3 will assign the fairest available host after checking routing and live calendar conflicts.':'This time is shown only because every required Team participant is currently available.'?></p></form><?php else:?><div class="empty-state"><strong>No Team opening on this date.</strong><p>Try another date<?=trim((string)$pool['routing_question'])!==''?' or adjust your routing answer':''?>.</p></div><?php endif;?></section>
<?php endif;?></main><script>try{document.getElementById('guestTimezone').value=Intl.DateTimeFormat().resolvedOptions().timeZone||'<?=e($timezone)?>';}catch(e){}</script></body></html>