<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
require_permission('account.access');
$pdo=db();$user=current_user();if(!$pdo||!$user)redirect(url('/login.php'));
if(!agent_scheduling_schema_ready_v430($pdo)||!workspace_team_v350_schema_ready()||!agent_team_scheduling_schema_ready_v600($pdo))redirect(url('/upgrade.php'));
$ownerId=(int)$user['id'];
function team_scheduling_ui_redirect(int $poolId,string $saved,string $anchor=''): never{$target=url('/team-scheduling.php'.($poolId>0?'?pool='.$poolId.'&saved='.rawurlencode($saved):'?saved='.rawurlencode($saved)));if($anchor!=='')$target.='#'.rawurlencode($anchor);redirect($target);}
function team_scheduling_ui_time(string $utc,string $timezone): string{try{return(new DateTimeImmutable($utc,new DateTimeZone('UTC')))->setTimezone(new DateTimeZone(agent_scheduling_timezone_v430($timezone)))->format('D, M j · g:i A');}catch(Throwable $e){return '—';}}
$pageError='';
$pools=agent_team_scheduling_pool_list_v600($pdo,$ownerId,false);$requested=max(0,(int)($_GET['pool']??$_POST['pool_id']??0));$pool=null;if($requested>0)$pool=agent_team_scheduling_pool_v600($pdo,$ownerId,$requested);if(!$pool&&$pools)$pool=$pools[0];
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!verify_csrf())$pageError='Session expired. Please try again.';
    else try{
        $action=trim((string)($_POST['action']??''));
        if($action==='save_pool'){$saved=agent_team_scheduling_save_pool_v600($pdo,$user,['id'=>max(0,(int)($_POST['pool_id']??0)),'name'=>(string)($_POST['name']??''),'slug'=>(string)($_POST['slug']??''),'description'=>(string)($_POST['description']??''),'mode'=>(string)($_POST['mode']??'round_robin'),'timezone'=>(string)($_POST['timezone']??'UTC'),'routing_question'=>(string)($_POST['routing_question']??''),'agent_id'=>(int)($_POST['agent_id']??0),'public_enabled'=>!empty($_POST['public_enabled']),'is_active'=>!empty($_POST['is_active'])]);team_scheduling_ui_redirect((int)$saved['id'],'Team schedule saved.','settings');}
        if(!$pool)throw new RuntimeException('Create a Team schedule first.');$poolId=(int)$pool['id'];
        if($action==='save_member'){agent_team_scheduling_save_member_v600($pdo,$user,$poolId,['user_id'=>(int)($_POST['user_id']??0),'event_type_id'=>(int)($_POST['event_type_id']??0),'routing_keywords'=>(string)($_POST['routing_keywords']??''),'priority'=>(int)($_POST['priority']??0),'enabled'=>!empty($_POST['enabled'])]);team_scheduling_ui_redirect($poolId,'Team participant saved.','participants');}
        if($action==='remove_member'){if(!agent_team_scheduling_remove_member_v600($pdo,$user,$poolId,(int)($_POST['member_id']??0)))throw new RuntimeException('That Team participant could not be removed.');team_scheduling_ui_redirect($poolId,'Team participant removed.','participants');}
        if($action==='cancel_team_booking'){$booking=agent_team_scheduling_booking_v600($pdo,$ownerId,(int)($_POST['booking_id']??0));if(!$booking||(int)$booking['pool_id']!==$poolId||!agent_team_scheduling_cancel_booking_v600($pdo,$booking))throw new RuntimeException('That Team booking could not be cancelled.');team_scheduling_ui_redirect($poolId,'Team booking cancelled across participant calendars.','bookings');}
        throw new RuntimeException('Unknown Team scheduling action.');
    }catch(Throwable $e){$pageError=$e->getMessage();}
    $pools=agent_team_scheduling_pool_list_v600($pdo,$ownerId,false);$requested=max(0,(int)($_POST['pool_id']??0));$pool=$requested>0?agent_team_scheduling_pool_v600($pdo,$ownerId,$requested):($pools[0]??null);
}
$poolId=(int)($pool['id']??0);$members=$pool?agent_team_scheduling_members_v600($pdo,$pool,false):[];$memberOptions=agent_team_scheduling_member_event_options_v600($pdo,$ownerId);$upcoming=$pool?agent_team_scheduling_upcoming_v600($pdo,$ownerId,$poolId,50):[];$agents=user_agents_list_v236($pdo,$ownerId,true);$timezoneIds=DateTimeZone::listIdentifiers();$savedMessage=trim((string)($_GET['saved']??''));$publicUrl=$pool?agent_team_scheduling_public_url_v600($pool):'';$activeMembers=count(array_filter($members,static fn(array $m):bool=>!empty($m['enabled'])&&!empty($m['schedule_active'])&&!empty($m['event_active'])));
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f7f7f5"><title><?=e(system_agent_name())?> | Team Scheduling</title><link rel="stylesheet" href="<?=e(url('/chat.css?v=82'))?>"><link rel="stylesheet" href="<?=e(url('/team-scheduling.css?v=agent-team-scheduling-v600-20260911'))?>"></head>
<body class="team-scheduling-page"><div class="chat-app">
<?php $workspaceSidebarUser=$user;$workspaceSidebarActive='team';require __DIR__.'/includes/workspace-sidebar-v82.php';?><div class="chat-sidebar-backdrop" id="chatSidebarBackdrop"></div>
<main class="chat-main team-scheduling-main">
<?php $memberHeaderUser=$user;$memberHeaderTitle='Team Scheduling';$memberHeaderSubtitle='Round-robin, pooled + collective appointment routing';$memberHeaderActions='<a class="team-scheduling-header-button" href="'.e(url('/chat.php')).'">Ask Agent</a>';require __DIR__.'/includes/member-header.php';?>
<section class="team-scheduling-canvas"><div class="team-scheduling-inner">
<?php if($savedMessage!==''):?><div class="team-scheduling-notice success"><?=e($savedMessage)?></div><?php endif;?><?php if($pageError!==''):?><div class="team-scheduling-notice error" role="alert"><?=e($pageError)?></div><?php endif;?>
<section class="team-scheduling-hero"><div><span class="team-scheduling-eyebrow">Phase 6 · Team scheduling</span><h1>One booking surface for the whole Team.</h1><p>Pool each member’s real VP3 availability, route the right guest to the right host, or require everyone to be open at the same time.</p></div><a class="team-scheduling-button primary" href="#new-pool">New Team schedule</a></section>
<?php if($pool):?><section class="team-scheduling-metrics"><article><span>Mode</span><strong><?=e((string)$pool['mode']==='round_robin'?'Round robin':'Collective')?></strong><small>Host assignment</small></article><article><span>Active participants</span><strong><?=$activeMembers?></strong><small><?=count($members)?> configured</small></article><article><span>Upcoming</span><strong><?=count($upcoming)?></strong><small>Team bookings</small></article><article><span>Public booking</span><strong><?=!empty($pool['public_enabled'])?'On':'Off'?></strong><small><?=!empty($pool['is_active'])?'Pool active':'Pool paused'?></small></article></section><?php endif;?>
<section class="team-pool-switcher"><div><strong>Team schedules</strong><span>Workspace owner: <?=e((string)($user['display_name']??$user['email']??'Account'))?></span></div><div class="team-pool-pills"><?php foreach($pools as $item):?><a class="<?=($poolId===(int)$item['id'])?'active':''?>" href="<?=e(url('/team-scheduling.php?pool='.(int)$item['id']))?>"><?=e((string)$item['name'])?></a><?php endforeach;?><a href="#new-pool">+ New</a></div></section>

<?php if($pool):?>
<section class="team-scheduling-section" id="participants"><div class="team-section-head"><div><span class="team-scheduling-eyebrow">Pooled calendars</span><h2>Participants + routing</h2><p>Each participant maps to one of their existing active VP3 appointment types. External Google/Outlook conflicts stay in force automatically.</p></div><span class="team-mode-chip"><?=e(str_replace('_',' ',(string)$pool['mode']))?></span></div>
<div class="team-member-list"><?php foreach($members as $member):?><article><div class="member-avatar"><?=e(mb_strtoupper(mb_substr(trim((string)($member['display_name']??'T')),0,1)))?></div><div class="member-main"><strong><?=e((string)($member['display_name']?:$member['email']))?></strong><small><?=e((string)$member['event_title'])?> · <?=e((string)$member['schedule_name'])?> · <?=(int)$member['duration_minutes']?> min</small><?php if(trim((string)$member['routing_keywords'])!==''):?><span>Routes: <?=e((string)$member['routing_keywords'])?></span><?php endif;?></div><div class="member-stats"><strong><?=(int)$member['assignment_count']?></strong><small>assignments</small></div><span class="member-state <?=!empty($member['enabled'])?'active':''?>"><?=!empty($member['enabled'])?'Active':'Paused'?></span><form method="post" onsubmit="return confirm('Remove this participant from the Team schedule?')"><?=csrf_field()?><input type="hidden" name="action" value="remove_member"><input type="hidden" name="pool_id" value="<?=$poolId?>"><input type="hidden" name="member_id" value="<?=(int)$member['id']?>"><button class="team-text-button danger">Remove</button></form></article><?php endforeach;?><?php if(!$members):?><div class="team-empty">No Team participants yet.</div><?php endif;?></div>
<form method="post" class="team-panel team-member-form"><?=csrf_field()?><input type="hidden" name="action" value="save_member"><input type="hidden" name="pool_id" value="<?=$poolId?>"><h3>Add or update a participant</h3><div class="team-form-grid"><label><span>Team member</span><select name="user_id" id="teamMemberUser" required><option value="">Choose member</option><?php foreach($memberOptions as $uid=>$entry):?><option value="<?=$uid?>"><?=e((string)($entry['user']['display_name']?:$entry['user']['email']))?></option><?php endforeach;?></select></label><label><span>Appointment type</span><select name="event_type_id" id="teamMemberEvent" required><option value="">Choose appointment type</option><?php foreach($memberOptions as $uid=>$entry):foreach($entry['events'] as $event):?><option value="<?=(int)$event['id']?>" data-user="<?=$uid?>"><?=e((string)$event['title'])?> · <?=e((string)$event['schedule_name'])?> · <?=(int)$event['duration_minutes']?> min</option><?php endforeach;endforeach;?></select></label><label class="span-2"><span>Routing keywords</span><input name="routing_keywords" maxlength="4000" placeholder="sales, demo, onboarding, support"><small>Round robin only. Matching answers prefer members with these keywords; blank falls back to the whole pool.</small></label><label><span>Priority</span><input type="number" name="priority" min="-1000" max="1000" value="0"></label><label class="toggle-line"><input type="checkbox" name="enabled" value="1" checked><span>Participant active</span></label></div><button class="team-scheduling-button primary" type="submit">Save participant</button></form>
</section>

<section class="team-scheduling-section" id="bookings"><div class="team-section-head"><div><span class="team-scheduling-eyebrow">Shared calendar</span><h2>Upcoming Team bookings</h2><p>Round-robin bookings identify one host. Collective bookings atomically reserve the same time on every participant’s canonical calendar.</p></div></div><div class="team-booking-list"><?php foreach($upcoming as $booking):?><article><div><strong><?=e(team_scheduling_ui_time((string)$booking['start_at_utc'],(string)$pool['timezone']))?></strong><small><?=e((string)$booking['guest_name'])?><?=trim((string)$booking['guest_email'])!==''?' · '.e((string)$booking['guest_email']):''?></small></div><div><strong><?=e((string)$booking['mode']==='round_robin'?(trim((string)$booking['assigned_name'])?:'Assigned host'):'Whole Team')?></strong><small><?=e(str_replace('_',' ',(string)$booking['source']))?></small></div><span class="booking-mode"><?=e(str_replace('_',' ',(string)$booking['mode']))?></span><form method="post" onsubmit="return confirm('Cancel this Team booking across every participant calendar?')"><?=csrf_field()?><input type="hidden" name="action" value="cancel_team_booking"><input type="hidden" name="pool_id" value="<?=$poolId?>"><input type="hidden" name="booking_id" value="<?=(int)$booking['id']?>"><button class="team-text-button danger">Cancel</button></form></article><?php endforeach;?><?php if(!$upcoming):?><div class="team-empty">No upcoming Team bookings.</div><?php endif;?></div></section>

<section class="team-scheduling-section" id="settings"><div class="team-section-head"><div><span class="team-scheduling-eyebrow">Pool settings</span><h2><?=e((string)$pool['name'])?></h2><p>Round robin unions participant availability and assigns the fairest eligible host. Collective mode only shows times open for every participant.</p></div></div><form method="post" class="team-panel team-form-grid"><?=csrf_field()?><input type="hidden" name="action" value="save_pool"><input type="hidden" name="pool_id" value="<?=$poolId?>"><label><span>Name</span><input name="name" maxlength="190" required value="<?=e((string)$pool['name'])?>"></label><label><span>URL slug</span><input name="slug" maxlength="80" value="<?=e((string)$pool['slug'])?>"></label><label><span>Mode</span><select name="mode"><option value="round_robin" <?=(string)$pool['mode']==='round_robin'?'selected':''?>>Round robin</option><option value="collective" <?=(string)$pool['mode']==='collective'?'selected':''?>>Collective / everyone required</option></select></label><label><span>Timezone</span><select name="timezone"><?php foreach($timezoneIds as $timezone):?><option value="<?=e($timezone)?>" <?=$timezone===(string)$pool['timezone']?'selected':''?>><?=e($timezone)?></option><?php endforeach;?></select></label><label><span>Booking Agent</span><select name="agent_id"><option value="0">No dedicated Agent</option><?php foreach($agents as $agent):?><option value="<?=(int)$agent['id']?>" <?=(int)($pool['agent_id']??0)===(int)$agent['id']?'selected':''?>><?=e((string)$agent['display_name'])?></option><?php endforeach;?></select></label><label class="span-2"><span>Routing question</span><input name="routing_question" maxlength="500" value="<?=e((string)$pool['routing_question'])?>" placeholder="What would you like to meet with us about?"></label><label class="span-2"><span>Description</span><textarea name="description" rows="3"><?=e((string)$pool['description'])?></textarea></label><div class="team-toggle-row span-2"><label class="toggle-line"><input type="checkbox" name="public_enabled" value="1" <?=!empty($pool['public_enabled'])?'checked':''?>><span>Public booking enabled</span></label><label class="toggle-line"><input type="checkbox" name="is_active" value="1" <?=!empty($pool['is_active'])?'checked':''?>><span>Pool active</span></label></div><div class="team-public-link span-2"><span>Public Team booking link</span><?php if($publicUrl!==''):?><input readonly value="<?=e($publicUrl)?>" onclick="this.select()"><a href="<?=e($publicUrl)?>" target="_blank" rel="noopener">Open ↗</a><?php endif;?></div><div class="team-form-actions span-2"><button class="team-scheduling-button primary" type="submit">Save Team schedule</button></div></form></section>
<?php endif;?>

<section class="team-scheduling-section" id="new-pool"><div class="team-section-head"><div><span class="team-scheduling-eyebrow">Create</span><h2>New Team schedule</h2><p>Start with round robin for routed handoffs or collective when every participant must attend.</p></div></div><form method="post" class="team-panel team-form-grid"><?=csrf_field()?><input type="hidden" name="action" value="save_pool"><input type="hidden" name="pool_id" value="0"><label><span>Name</span><input name="name" required maxlength="190" placeholder="Demo Team"></label><label><span>Mode</span><select name="mode"><option value="round_robin">Round robin</option><option value="collective">Collective / everyone required</option></select></label><label><span>Timezone</span><select name="timezone"><?php foreach($timezoneIds as $timezone):?><option value="<?=e($timezone)?>" <?=$timezone===agent_scheduling_timezone_v430((string)($user['timezone']??date_default_timezone_get()),'UTC')?'selected':''?>><?=e($timezone)?></option><?php endforeach;?></select></label><label><span>Booking Agent</span><select name="agent_id"><option value="0">No dedicated Agent</option><?php foreach($agents as $agent):?><option value="<?=(int)$agent['id']?>"><?=e((string)$agent['display_name'])?></option><?php endforeach;?></select></label><label class="span-2"><span>Routing question</span><input name="routing_question" maxlength="500" placeholder="What would you like to meet with us about?"></label><label class="span-2"><span>Description</span><textarea name="description" rows="3" placeholder="How should visitors use this Team booking page?"></textarea></label><label class="toggle-line"><input type="checkbox" name="public_enabled" value="1" checked><span>Public booking enabled</span></label><label class="toggle-line"><input type="checkbox" name="is_active" value="1" checked><span>Pool active</span></label><div class="team-form-actions span-2"><button class="team-scheduling-button primary">Create Team schedule</button></div></form></section>
</div></section></main></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const u=document.getElementById('teamMemberUser'),e=document.getElementById('teamMemberEvent');if(!u||!e)return;const sync=()=>{const id=u.value;for(const o of e.options){if(!o.dataset.user){o.hidden=false;continue;}o.hidden=o.dataset.user!==id;}if(e.selectedOptions[0]?.hidden)e.value='';};u.addEventListener('change',sync);sync();});</script><script src="<?=e(url('/member-shell-v77.js?v=20260911'))?>"></script></body></html>