<?php
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
$contactEmail = (string)setting('contact_email', (string)site_config('email', 'stonefellow74@gmail.com'));
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Terms for using the Stonefellow AI Studio Assistant and related services."><title>Terms of Service — Stonefellow</title><style>
:root{--ink:#0d1020;--muted:#687083;--line:#e1e4eb;--dark:#0b0c12;--purple:#6f4cff;--max:1040px}*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;color:var(--ink);background:#fff;line-height:1.65}a{color:inherit;text-decoration:none}.wrap{width:min(var(--max),calc(100% - 40px));margin:0 auto}.header{background:#0b0c12;color:#fff;border-bottom:1px solid #242733}.nav{height:74px;display:flex;align-items:center;justify-content:space-between;gap:24px}.brand{display:flex;align-items:center;gap:11px;font-weight:900;font-size:21px}.brand-mark{width:34px;height:34px;border:2px solid currentColor;border-radius:9px;display:grid;place-items:center;transform:rotate(30deg)}.brand-mark span{transform:rotate(-30deg);font-size:16px}.nav-links{display:flex;gap:22px;color:#cfd2db;font-size:13px}.hero{background:linear-gradient(180deg,#0b0c12,#11131b);color:#fff;padding:78px 0 82px}.eyebrow{font-size:12px;font-weight:900;letter-spacing:.13em;text-transform:uppercase;color:#9c8aff}h1{font-size:clamp(48px,7vw,78px);line-height:.98;letter-spacing:-.055em;margin:14px 0 16px}.hero p{color:#b8bdc9;font-size:17px;max-width:700px;margin:0}.legal{padding:72px 0 90px}.legal h2{font-size:25px;letter-spacing:-.02em;margin:38px 0 10px}.legal h2:first-child{margin-top:0}.legal p,.legal li{color:#596071;font-size:15px}.legal ul{padding-left:22px}.updated{display:inline-block;border:1px solid #dedfea;border-radius:999px;padding:7px 11px;font-size:11px;color:#707686;margin-bottom:20px}.footer{border-top:1px solid #e5e7ed;padding:30px 0 45px;color:#7b8190;font-size:12px}.footer-row{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}.footer a{color:#4e46a8;font-weight:700}@media(max-width:760px){.nav-links{display:none}.wrap{width:min(100% - 24px,var(--max))}.hero{padding:58px 0}.legal{padding:52px 0 70px}}
</style></head><body><header class="header"><div class="wrap nav"><a class="brand" href="<?= e(url('/index.php')) ?>"><span class="brand-mark"><span>S</span></span><span>Stonefellow</span></a><nav class="nav-links"><a href="<?= e(url('/index.php#product')) ?>">Product</a><a href="<?= e(url('/pricing.php')) ?>">Pricing</a><a href="<?= e(url('/book-demo.php')) ?>">Book a demo</a><a href="<?= e(url('/login.php')) ?>">Sign in</a></nav></div></header><section class="hero"><div class="wrap"><div class="eyebrow">Stonefellow legal</div><h1>Terms of Service</h1><p>Terms for using the Stonefellow AI Studio Assistant and related services.</p></div></section><main class="legal"><div class="wrap"><span class="updated">Last updated August 31, 2026</span>
<h2>1. Acceptance</h2><p>By accessing or using Stonefellow, you agree to these Terms of Service. If you use Stonefellow for an organization, you represent that you have authority to act for that organization. A separate signed agreement may supplement or replace portions of these terms for paid, enterprise or partner accounts.</p>
<h2>2. The service</h2><p>Stonefellow provides tools for music and studio operations, including project organization, stems and sessions, notes, rights and split workflows, release coordination, team activity, and AI-assisted operational features. Features may change as the service develops.</p>
<h2>3. Accounts</h2><p>You are responsible for accurate account information, safeguarding credentials and activity performed through your account. You may not share access in a way that bypasses account permissions or security controls.</p>
<h2>4. Your content</h2><p>You retain ownership of content you submit to Stonefellow. You grant Stonefellow a limited license to host, process, transmit and display that content solely as needed to operate the service and provide features you request. You are responsible for having the rights necessary to upload and use your content.</p>
<h2>5. AI-assisted features</h2><p>AI-assisted output can be incomplete or inaccurate and should be reviewed before relying on it for rights, legal, financial, release or business decisions. Stonefellow is intended to assist operational work around existing creative assets; it does not replace professional legal, accounting or rights-clearance advice.</p>
<h2>6. Acceptable use</h2><p>You may not use Stonefellow to violate law, infringe intellectual-property or privacy rights, distribute malicious software, interfere with the service, bypass security, access another account without authorization, or upload content you do not have the right to use.</p>
<h2>7. Third-party services</h2><p>Stonefellow may integrate with hosting, AI, communications, distribution, payment or other third-party services. Those services may be subject to their own terms and privacy practices, and Stonefellow is not responsible for third-party systems outside our control.</p>
<h2>8. Paid services</h2><p>If you purchase a paid plan, the price, billing period, included usage and any cancellation or refund terms shown at purchase or in a separate agreement apply. Taxes may be added where required.</p>
<h2>9. Suspension and termination</h2><p>We may suspend or terminate access when reasonably necessary to protect users or the service, address security or abuse, comply with law, or respond to a material breach of these terms. You may stop using Stonefellow at any time.</p>
<h2>10. Disclaimers</h2><p>Stonefellow is provided on an “as available” basis to the extent permitted by law. We do not guarantee uninterrupted operation, error-free AI output, or that every feature will meet every professional or regulatory requirement.</p>
<h2>11. Limitation of liability</h2><p>To the fullest extent permitted by applicable law, Stonefellow and its operators will not be liable for indirect, incidental, special, consequential or punitive damages arising from use of the service. Any liability that cannot legally be excluded remains subject to applicable law and any separate written agreement.</p>
<h2>12. Changes and contact</h2><p>We may update these terms as Stonefellow evolves. Continued use after updated terms become effective constitutes acceptance where permitted by law. Questions can be sent to <a href="mailto:<?= e($contactEmail) ?>"><?= e($contactEmail) ?></a>.</p>
</div></main><footer class="footer"><div class="wrap footer-row"><span>© 2026 Stonefellow. All rights reserved.</span><span><a href="<?= e(url('/privacy.php')) ?>">Privacy</a> · <a href="<?= e(url('/terms.php')) ?>">Terms</a> · <a href="<?= e(url('/contact.php')) ?>">Contact</a></span></div></footer></body></html>
