<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
require_login();

$user=current_user();$pdo=db();
if(!$pdo){http_response_code(503);exit('Database unavailable.');}
$trackyStatus=vp3_plugin_effective_state_v360($pdo,$user,'tracky');
if(empty($trackyStatus['enabled'])){flash('error','Enable the Tracky plugin before opening Physical Awareness.');redirect(url('/plugins.php'));}
if(!tracky_cloud_v270_schema_ready($pdo)){
    if(user_has_role('admin',$user))redirect(url('/upgrade.php'));
    http_response_code(503);exit('Tracky Cloud requires a database upgrade.');
}
$userId=(int)$user['id'];
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!verify_csrf()){flash('error','Session expired. Please try again.');redirect(url('/tracky.php'));}
    $action=trim((string)($_POST['action']??''));
    try{
        if($action!=='save_surface_policy')throw new RuntimeException('Unknown Tracky action.');
        $input=[
            'now_enabled'=>isset($_POST['now_enabled']),
            'chat_enabled'=>isset($_POST['chat_enabled']),
            'voice_enabled'=>isset($_POST['voice_enabled']),
            'automation_enabled'=>isset($_POST['automation_enabled']),
            'cross_plugin_access'=>isset($_POST['cross_plugin_access']),
            'cross_plugin_plugins'=>is_array($_POST['cross_plugin_plugins']??null)?$_POST['cross_plugin_plugins']:[],
            'active_perception_enabled'=>isset($_POST['active_perception_enabled']),
            'auto_refresh_stale'=>isset($_POST['auto_refresh_stale']),
            'governed_action_proposals_enabled'=>isset($_POST['governed_action_proposals_enabled']),
            'now_classes'=>is_array($_POST['now_classes']??null)?$_POST['now_classes']:[],
            'chat_classes'=>is_array($_POST['chat_classes']??null)?$_POST['chat_classes']:[],
            'voice_classes'=>is_array($_POST['voice_classes']??null)?$_POST['voice_classes']:[],
            'automation_classes'=>is_array($_POST['automation_classes']??null)?$_POST['automation_classes']:[],
        ];
        tracky_v272_settings_save($pdo,$user,$input);
        flash('notice','Tracky awareness surfaces updated.');
    }catch(Throwable $e){flash('error',$e->getMessage());}
    $site=trim((string)($_POST['site']??''));
    redirect(url('/tracky.php'.($site!==''?'?site='.rawurlencode($site):'')));
}
$surfaceSettings=function_exists('tracky_v272_settings')?tracky_v272_settings($pdo,$userId):[];
$globalVoiceEnabled=function_exists('chat_settings_agent_voice_enabled_v237')?chat_settings_agent_voice_enabled_v237($pdo,$user):false;
$eventClasses=function_exists('tracky_v272_event_classes')?tracky_v272_event_classes():[];
$triggerCatalog=function_exists('tracky_v272_trigger_catalog')?tracky_v272_trigger_catalog():[];
$crossPluginCandidates=[];
if(function_exists('vp3_plugin_catalog_v320')&&function_exists('vp3_plugin_effective_enabled_v360')){
    foreach(vp3_plugin_catalog_v320() as $pluginKey=>$pluginMeta){
        if($pluginKey==='tracky')continue;
        try{$state=vp3_plugin_effective_enabled_v360($pdo,$user,$pluginKey);}catch(Throwable $e){$state=false;}
        if($state)$crossPluginCandidates[$pluginKey]=(string)($pluginMeta['label']??$pluginKey);
    }
}
$sites=tracky_cloud_v270_sites($pdo,$userId);
$selected=trim((string)($_GET['site']??''));
if($selected===''&&!empty($sites))$selected=(string)$sites[0]['site_id'];
$context=$selected!==''?tracky_cloud_v270_current_context($pdo,$userId,$selected):[];
$events=$selected!==''?tracky_cloud_v270_recent_events($pdo,$userId,$selected,25):[];
$world=$selected!==''?tracky_cloud_v270_world_state($pdo,$userId,$selected,100):[];
$selectedEventId=trim((string)($_GET['event']??''));
$selectedEvent=$selected!==''&&$selectedEventId!==''&&function_exists('tracky_v272_event_row')
    ?tracky_v272_event_row($pdo,$userId,$selected,$selectedEventId):null;
$selectedEventCard=$selectedEvent&&function_exists('tracky_v272_card')
    ?tracky_v272_card($pdo,$user,'system',['type'=>'physical_event','id'=>(string)$selectedEvent['id'],'scope'=>'personal'],'expanded')
    :null;
$agentIntegrated=function_exists('tracky_agent_register_cognitive_v271')&&function_exists('tracky_agent_tools_query_v271');
$proactiveIntegrated=function_exists('tracky_v272_observation_now_allowed')&&function_exists('tracky_v272_on_sync');
$joinCapabilities=function_exists('tracky_v273_capabilities')
    ?tracky_v273_capabilities($pdo,$user,false)
    :['available'=>false,'compatible'=>false,'connected'=>false,'reason'=>'v2.73_unavailable','tracky'=>[],'reconciliation'=>[]];
$reliabilityState=function_exists('tracky_v274_reliability_state')
    ?tracky_v274_reliability_state($pdo,$user,$selected)
    :['state'=>'unavailable','reason'=>'v2.74_unavailable','fresh_verification'=>false];
$actionCapability=function_exists('tracky_v275_capability')
    ?tracky_v275_capability($pdo,$user,false)
    :['supported'=>false,'reason'=>'v2.75_unavailable','actions'=>[]];
$modelAccuracy=function_exists('tracky_v276_account_summary')
    ?tracky_v276_account_summary($pdo,$userId,$selected!==''?$selected:null)
    :['available'=>false,'active_profiles'=>0,'active_settlements'=>0,'mean_brier_score'=>null,'mean_expected_calibration_error'=>null];
$modelLifecycle=function_exists('tracky_v277_account_summary')
    ?tracky_v277_account_summary($pdo,$userId,$selected!==''?$selected:null)
    :['available'=>false,'health_state'=>'empty','active_models'=>0,'shadow_models'=>0,'canary_models'=>0,'degraded_models'=>0,'recent_rollbacks'=>0];
$memberHeaderUser=$user;$memberHeaderTitle='Tracky';$memberHeaderSubtitle='Physical Awareness · physical_context.v1';$memberHeaderActions='';
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f7f7f8"><title>VP3 | Tracky</title><link rel="stylesheet" href="<?= e(url('/chat.css?v=82')) ?>"><link rel="stylesheet" href="<?= e(url('/tracky-federation-control-center-v280.css?v=280')) ?>"><link rel="stylesheet" href="<?= e(url('/tracky-physical-world-dashboard-v280.css?v=280')) ?>"><link rel="stylesheet" href="<?= e(url('/tracky-cross-site-presence-v280.css?v=280')) ?>"><link rel="stylesheet" href="<?= e(url('/tracky-federation-sync-visibility-v280.css?v=280')) ?>"><link rel="stylesheet" href="<?= e(url('/tracky-federation-access-operations-v280.css?v=280')) ?>"><link rel="stylesheet" href="<?= e(url('/tracky-federation-agent-health-v280.css?v=280')) ?>"><link rel="stylesheet" href="<?= e(url('/tracky-federation-fleet-health-v280.css?v=280')) ?>"><link rel="stylesheet" href="<?= e(url('/tracky-federation-governed-operations-v280.css?v=280')) ?>"><style>
.tracky-page{background:#f7f7f8;color:#1d1f23}.tracky-main{min-width:0}.tracky-wrap{max-width:1180px;margin:0 auto;padding:28px 24px 70px}.tracky-grid{display:grid;grid-template-columns:repeat(12,1fr);gap:16px}.card{grid-column:span 12;background:#fff;border:1px solid #e3e4e7;border-radius:18px;padding:22px}.card.half{grid-column:span 6}.muted{color:#6e7177}.status{display:inline-flex;padding:6px 10px;border-radius:999px;background:#eef0f2;font-size:12px;font-weight:800}.status.healthy{background:#eaf7ef}.site-tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}.site-tabs a{text-decoration:none;color:#1d1f23;border:1px solid #dfe1e4;background:#fff;border-radius:999px;padding:8px 12px;font-weight:700}.site-tabs a.active{background:#1d1f23;color:#fff}.metric{font-size:28px;font-weight:850}.list{display:grid;gap:10px}.row{border-top:1px solid #ececef;padding-top:10px}.row:first-child{border-top:0;padding-top:0}.pill{display:inline-flex;font-size:11px;font-weight:750;padding:4px 7px;border-radius:999px;background:#f0f1f3;margin-right:6px}.empty{padding:18px;border:1px dashed #d9dbe0;border-radius:12px;color:#6e7177}.privacy{background:#f7faf8}.privacy strong{display:block;margin-bottom:5px}.policy-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.policy-box{border:1px solid #ececef;border-radius:14px;padding:16px}.policy-box h3{margin:0 0 10px}.checks{display:flex;flex-wrap:wrap;gap:8px 12px}.check{display:flex;gap:7px;align-items:center;font-size:13px}.check input{width:16px;height:16px}.policy-actions{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-top:16px}.selected-event{border-color:#b9bdc5;box-shadow:0 10px 30px rgba(0,0,0,.05)}.selected-event h2{margin-top:0}.btn-save{border:0;background:#1d1f23;color:#fff;border-radius:11px;padding:10px 15px;font-weight:800;cursor:pointer}@media(max-width:800px){.card.half{grid-column:span 12}.policy-grid{grid-template-columns:1fr}}
</style></head><body class="tracky-page"><div class="chat-app"><?php $workspaceSidebarUser=$user;$workspaceSidebarActive='plugins';require __DIR__.'/includes/workspace-sidebar-v82.php'; ?><div class="chat-sidebar-backdrop" id="chatSidebarBackdrop"></div><main class="chat-main tracky-main"><?php require __DIR__.'/includes/member-header.php'; ?><div class="tracky-wrap">
<section class="card fed280" id="federationControlCenter" data-endpoint="<?= e(url('/api/tracky-federation-operations-v280.php')) ?>">
<div class="fed280-head"><div><div class="muted">V2.80 · FEDERATION OPERATIONS</div><h2>Physical Network Control Center</h2><p class="muted">Live read-only topology of sites, HomeServers and hardware units. Physical authority remains with each origin site.</p></div><div class="fed280-actions"><span class="muted" data-fed280-status>Loading federation mirror…</span><button class="fed280-refresh" type="button" data-fed280-refresh>Refresh</button></div></div>
<div class="fed280-summary"><div><span>Health</span><strong data-fed280-health><span class="fed280-badge unknown">Unknown</span></strong></div><div><span>Sites</span><strong data-fed280-sites>0</strong></div><div><span>Hardware</span><strong data-fed280-devices>0</strong></div><div><span>Current</span><strong data-fed280-current>0</strong></div><div><span>Issues</span><strong data-fed280-issues>0</strong></div></div>
<div class="fed280-grid"><div><div class="fed280-head"><div><div class="muted">TOPOLOGY REVISION <strong data-fed280-topology>0</strong></div><h3>Sites + authority</h3></div></div><div class="fed280-sites" data-fed280-site-cards><div class="fed280-empty">Loading federated topology…</div></div></div><aside class="fed280-issues"><h3>Federation health</h3><div data-fed280-issue-list><div class="fed280-empty">Loading health…</div></div><div class="fed280-boundary"><strong>Cloud boundary:</strong> VP3 is relay/mirror only. This view cannot assign authority, decide a HomeServer is current, merge physical identities, or execute device actions.</div></aside></div>
</section>
<section class="card csv280" id="federationSyncVisibilityV280" data-endpoint="<?= e(url('/api/tracky-federation-sync-visibility-v280.php')) ?>">
<div class="csv280-headbar"><div><div class="muted">V2.80 · RECONCILIATION & SYNC</div><h3>Federation freshness</h3><p class="muted">Origin-HomeServer reported revision, authority epoch, stale age, retry and reconciliation state.</p></div><div class="csv280-actions"><span class="muted">Reporter <strong data-csv280-reporter>No HomeServer report</strong></span><span class="muted" data-csv280-status>Loading origin-reported mirror…</span><button class="csv280-refresh" type="button" data-csv280-refresh>Refresh</button></div></div>
<div class="csv280-summary"><div><span>State</span><strong data-csv280-state><span class="csv280-state unknown">Unknown</span></strong></div><div><span>Current</span><strong data-csv280-current>0</strong></div><div><span>Reconciling</span><strong data-csv280-reconciling>0</strong></div><div><span>Partitioned</span><strong data-csv280-partitioned>0</strong></div><div><span>Failed</span><strong data-csv280-failed>0</strong></div></div>
<div class="csv280-agent" data-csv280-agent>No origin-reported sync summary.</div>
<div class="csv280-layout"><div><h3>Site freshness</h3><div class="csv280-sites" data-csv280-sites><div class="csv280-empty">Loading federation sync state…</div></div></div><aside><h3>Reconciliation history</h3><div data-csv280-runs><div class="csv280-empty">No reconciliation history reported.</div></div></aside></div>
<div class="csv280-boundary"><strong>Cloud boundary:</strong> VP3 displays the HomeServer report. Cloud does not mark a destination current, transfer authority, or resolve a fingerprint/epoch conflict.</div>
</section>
<section class="card cfa280" id="federationAccessOperationsV280" data-endpoint="<?= e(url('/api/tracky-federation-access-operations-v280.php')) ?>">
<div class="cfa280-headbar"><div><div class="muted">V2.80 · PERMISSIONS & CONSENT</div><h3>Federation access governance</h3><p class="muted">HomeServer-governed policy, consent, revocations and effective peer access. Cloud is explanatory and read-only.</p></div><div class="cfa280-actions"><span class="muted" data-cfa280-status>Loading HomeServer-governed mirror…</span><button class="cfa280-refresh" type="button" data-cfa280-refresh>Refresh</button></div></div>
<div class="cfa280-summary"><div><span>Source sites</span><strong data-cfa280-sources>0</strong></div><div><span>Allowed grants</span><strong data-cfa280-allowed>0</strong></div><div><span>Revoked/denied</span><strong data-cfa280-revoked>0</strong></div><div><span>Stale suppressed</span><strong data-cfa280-suppressed>0</strong></div></div>
<div class="cfa280-sources" data-cfa280-views><div class="cfa280-empty">Loading federation access policy…</div></div>
<div class="cfa280-boundary"><strong>Revocation always wins.</strong> Cloud cannot grant access, change consent, transfer policy authority, or revive a stale grant after the origin HomeServer has revoked it.</div>
</section>
<section class="card cfh280" id="federationAgentHealthV280" data-endpoint="<?= e(url('/api/tracky-federation-agent-health-v280.php')) ?>">
<div class="cfh280-headbar"><div><div class="muted">V2.80 · AGENT BRAIN FEDERATION HEALTH</div><h3>Failures, trust & recovery</h3><p class="muted">Origin-HomeServer reported site, authority-device, relay and reconciliation health. Cloud mirrors the result; it does not decide recovery.</p></div><div class="cfh280-actions"><span class="muted">Reporter <strong data-cfh280-reporter>No HomeServer report</strong></span><span class="muted" data-cfh280-status>Loading origin-reported health…</span><button class="cfh280-refresh" type="button" data-cfh280-refresh>Refresh</button></div></div>
<div class="cfh280-summary"><div><span>Overall</span><strong data-cfh280-overall><span class="cfh280-state unknown">Unknown</span></strong></div><div><span>Current</span><strong data-cfh280-current>0</strong></div><div><span>Degraded</span><strong data-cfh280-degraded>0</strong></div><div><span>Critical</span><strong data-cfh280-critical>0</strong></div><div><span>Recovering</span><strong data-cfh280-recovering>0</strong></div><div><span>Cloud relay</span><strong data-cfh280-relay><span class="cfh280-state unknown">Unknown</span></strong></div></div>
<div class="cfh280-agent" data-cfh280-agent>No origin-reported federation health summary.</div>
<div class="cfh280-layout" style="margin-top:12px"><div><h3>Site trust & recovery</h3><div class="cfh280-sites" data-cfh280-sites><div class="cfh280-empty">Loading federation health…</div></div></div><aside><h3>Operational history</h3><div class="cfh280-history" data-cfh280-history><div class="cfh280-empty">No mirrored federation health events yet.</div></div></aside></div>
<div class="cfh280-boundary"><strong>Recovery rule:</strong> connectivity returning is not recovery. Cloud displays a site as recovered only when the origin HomeServer reports authoritative reconciliation as current.</div>
</section>
<section class="card cffh280" id="federationFleetHealthV280" data-endpoint="<?= e(url('/api/tracky-federation-fleet-health-v280.php')) ?>">
<div class="cffh280-head"><div><div class="muted">V2.80 · FLEET HEALTH & DIAGNOSTICS</div><h3>Hardware runtime health</h3><p class="muted">Origin-reported version, model/calibration, storage, camera/sensor, sync, error and upgrade diagnostics.</p></div><div class="cffh280-actions"><span class="muted" data-cffh280-status>Loading origin-reported diagnostics…</span><button class="cffh280-refresh" type="button" data-cffh280-refresh>Refresh</button></div></div>
<div class="cffh280-summary"><div><span>Overall</span><strong data-cffh280-overall><span class="cffh280-state unknown">Unknown</span></strong></div><div><span>Sites</span><strong data-cffh280-sites>0</strong></div><div><span>Devices</span><strong data-cffh280-devices>0</strong></div><div><span>Degraded</span><strong data-cffh280-degraded>0</strong></div><div><span>Critical</span><strong data-cffh280-critical>0</strong></div></div>
<div data-cffh280-list><div class="cffh280-empty">Loading fleet diagnostics…</div></div>
<div class="cffh280-empty"><strong>Cloud boundary:</strong> read-only mirror. Section 7 federation freshness remains authoritative; diagnostics cannot mark a site current, recovered, or execute a remote fleet action.</div>
</section>
<section class="card cfgo280" id="federationGovernedOperationsV280" data-endpoint="<?= e(url('/api/tracky-federation-governed-operations-v280.php')) ?>">
<div class="cfgo280-head"><div><div class="muted">V2.80 · GOVERNED FEDERATION OPERATIONS</div><h3>Request, approve locally, reconcile</h3><p class="muted">Cloud can create a request and mirror progress. HomeServer remains the executor and authority.</p></div><div class="cfgo280-actions"><span class="muted" data-cfgo-status>Loading operations…</span><button type="button" data-cfgo-refresh>Refresh</button></div></div>
<div class="cfgo280-summary"><div><span>Active</span><strong data-cfgo-active>0</strong></div><div><span>Awaiting approval</span><strong data-cfgo-approval>0</strong></div><div><span>Reconciling</span><strong data-cfgo-reconciling>0</strong></div></div>
<form class="cfgo280-form" data-cfgo-form><label>Operation<select name="operation_type" required><option value="reconnect">Reconnect</option><option value="reconcile">Reconcile</option><option value="restart_runtime">Restart runtime</option><option value="request_update">Request update</option><option value="revoke_device">Revoke device</option><option value="transfer_authority">Transfer authority</option></select></label><label>Target site UUID<input name="target_site_id" required maxlength="64"></label><label>Device ID<input name="device_id" maxlength="80"></label><label>New authority device<input name="new_authority_device_id" maxlength="80"></label><label>Reason<input name="reason" maxlength="240"></label><label><input type="checkbox" name="explicit_confirmation" value="1"> Explicitly confirm authority transfer</label><button type="submit">Create governed request</button></form>
<div class="cfgo280-head"><h3>Origin HomeServer ledger</h3><span class="muted">Execution stays local</span></div><div data-cfgo-list><div class="cfgo-empty">Loading operations…</div></div>
<div class="cfgo280-head"><h3>Cloud requests</h3><span class="muted">Proposal relay only</span></div><div data-cfgo-requests><div class="cfgo-empty">No Cloud requests yet.</div></div>
<div class="cfgo-empty"><strong>Recovery boundary:</strong> Cloud cannot execute a command, transfer authority, or mark a site recovered. Reconnect/update/restart/transfer complete only after authoritative HomeServer reconciliation is current; transfer also requires an advanced authority epoch.</div>
</section>
<section class="card pw280" id="physicalWorldDashboardV280" data-endpoint="<?= e(url('/api/tracky-physical-world-dashboard-v280.php')) ?>" data-selected-site="<?= e($selected) ?>">
<div class="pw280-head"><div><div class="muted">V2.80 · PHYSICAL WORLD</div><h2>Physical World Dashboard</h2><p class="muted">Rooms, people, objects and hardware across authorized sites. Site switching changes the Agent's dashboard view only.</p></div><div class="pw280-controls"><label>Site<select data-pw280-site-select disabled><option>Loading sites…</option></select></label><button class="pw280-refresh" type="button" data-pw280-refresh>Refresh</button></div></div>
<div class="muted" data-pw280-status>Loading governed Cloud mirror…</div><div class="pw280-warning" data-pw280-warning hidden></div><div class="pw280-sync-warning unknown" data-pw280-sync-warning hidden></div>
<div class="pw280-site-line"><span>Selected <strong data-pw280-site-name>No site</strong></span><span>Health <strong data-pw280-health>unknown</strong></span><span>Federation <strong data-pw280-federation>unknown</strong></span><span>World revision <strong data-pw280-revision>0</strong></span></div>
<div class="pw280-summary"><div><span>Rooms</span><strong data-pw280-rooms>0</strong></div><div><span>People</span><strong data-pw280-people>0</strong></div><div><span>Objects</span><strong data-pw280-objects>0</strong></div><div><span>Hardware</span><strong data-pw280-hardware-count>0</strong></div></div>
<div class="pw280-panel"><h3>Agent selected-site context</h3><div class="pw280-agent"><div><span>Agent view site</span><strong data-pw280-agent-view>None</strong></div><div><span>Physical current site</span><strong data-pw280-agent-physical>Unknown</strong></div><div><span>View basis</span><strong data-pw280-agent-basis>none</strong></div></div><p class="pw280-agent-note" data-pw280-agent-note>Site selection never changes physical authority or invents a current location.</p></div><section class="csp280" id="crossSitePresenceV280" data-endpoint="<?= e(url('/api/tracky-cross-site-presence-v280.php')) ?>">
<div class="csp280-headbar"><div><div class="muted">V2.80 · CROSS-SITE PRESENCE</div><h3>Mobile transitions</h3><p class="muted">People continuity subjects and mobile hardware moving between authorized sites.</p></div><div class="csp280-actions"><span class="muted" data-csp280-status>Loading governed Cloud mirror…</span><button class="csp280-refresh" type="button" data-csp280-refresh>Refresh</button></div></div>
<div class="csp280-summary"><div><span>Active</span><strong data-csp280-active-count>0</strong></div><div><span>In transit</span><strong data-csp280-transit-count>0</strong></div><div><span>Arriving</span><strong data-csp280-arriving-count>0</strong></div><div><span>Offline</span><strong data-csp280-offline-count>0</strong></div></div>
<div class="csp280-boundary" data-csp280-agent-rule>Agent confirms destination presence only after ARRIVED.</div>
<div class="csp280-layout"><div><h3>Active movement</h3><div class="csp280-list" data-csp280-active><div class="csp280-empty">Loading transitions…</div></div></div><aside><h3>Presence by site</h3><div data-csp280-sites><div class="csp280-empty">Loading site presence…</div></div></aside></div>
<div class="csp280-headbar" style="margin-top:12px"><div><h3>Transition timeline</h3></div><span class="muted" data-csp280-history>Current snapshots only</span></div><div class="csp280-timeline" data-csp280-timeline><div class="csp280-empty">Loading transition history…</div></div>
<div class="csp280-boundary"><strong>Boundary:</strong> departure never proves arrival. Offline and temporary contexts do not become durable sites; moving an authority device never transfers authority; Cloud remains mirror-only.</div>
</section>
<div class="pw280-grid"><section class="pw280-panel"><h3>Rooms + areas</h3><div class="pw280-list" data-pw280-room-list><div class="pw280-empty">Loading rooms…</div></div></section><section class="pw280-panel"><h3>People</h3><div class="pw280-list" data-pw280-people-list><div class="pw280-empty">Loading people…</div></div></section><section class="pw280-panel"><h3>Objects + locations</h3><div class="pw280-list" data-pw280-object-list><div class="pw280-empty">Loading objects…</div></div></section><section class="pw280-panel"><h3>Registered hardware</h3><div data-pw280-hardware-list><div class="pw280-empty">Loading hardware…</div></div></section></div>
<div class="pw280-boundary"><strong>Cloud boundary:</strong> governed semantic summaries only. Selecting a site does not grant permission, merge site-local identities, assign authority, or execute a physical action.</div>
</section>
<section class="card" style="margin-bottom:16px"><h2>Awareness surfaces</h2><p class="muted">Choose where governed Tracky events may appear. VP3's existing attention budget, quiet/focus rules, permissions and global voice setting still apply.</p>
<form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save_surface_policy"><input type="hidden" name="site" value="<?= e($selected) ?>">
<div class="policy-grid">
<div class="policy-box"><h3>Agent Now</h3><label class="check"><input type="checkbox" name="now_enabled" value="1" <?= !empty($surfaceSettings['now_enabled'])?'checked':'' ?>> Enabled</label><div class="checks" style="margin-top:10px"><?php foreach($eventClasses as $class): ?><label class="check"><input type="checkbox" name="now_classes[]" value="<?= e($class) ?>" <?= in_array($class,(array)($surfaceSettings['now_classes']??[]),true)?'checked':'' ?>><?= e(ucfirst($class)) ?></label><?php endforeach; ?></div></div>
<div class="policy-box"><h3>Proactive Agent Chat</h3><label class="check"><input type="checkbox" name="chat_enabled" value="1" <?= !empty($surfaceSettings['chat_enabled'])?'checked':'' ?>> Enabled</label><div class="checks" style="margin-top:10px"><?php foreach($eventClasses as $class): ?><label class="check"><input type="checkbox" name="chat_classes[]" value="<?= e($class) ?>" <?= in_array($class,(array)($surfaceSettings['chat_classes']??[]),true)?'checked':'' ?>><?= e(ucfirst($class)) ?></label><?php endforeach; ?></div></div>
<div class="policy-box"><h3>Agent voice</h3><label class="check"><input type="checkbox" name="voice_enabled" value="1" <?= !empty($surfaceSettings['voice_enabled'])?'checked':'' ?>> Allow Tracky voice alerts</label><div class="checks" style="margin-top:10px"><?php foreach($eventClasses as $class): ?><label class="check"><input type="checkbox" name="voice_classes[]" value="<?= e($class) ?>" <?= in_array($class,(array)($surfaceSettings['voice_classes']??[]),true)?'checked':'' ?>><?= e(ucfirst($class)) ?></label><?php endforeach; ?></div><p class="muted" style="margin-bottom:0">Global Agent voice: <strong><?= $globalVoiceEnabled?'On':'Off' ?></strong>. Tracky voice is off by default and never bypasses global voice, focus/quiet or interruption rules.</p></div>
<div class="policy-box"><h3>Automation triggers</h3><label class="check"><input type="checkbox" name="automation_enabled" value="1" <?= !empty($surfaceSettings['automation_enabled'])?'checked':'' ?>> Publish governed triggers</label><div class="checks" style="margin-top:10px"><?php foreach($eventClasses as $class): ?><label class="check"><input type="checkbox" name="automation_classes[]" value="<?= e($class) ?>" <?= in_array($class,(array)($surfaceSettings['automation_classes']??[]),true)?'checked':'' ?>><?= e(ucfirst($class)) ?></label><?php endforeach; ?></div><p class="muted" style="margin-bottom:0"><?= count($triggerCatalog) ?> trigger families are available. V2.72 publishes trigger metadata only; it does not execute physical actions.</p></div>
</div>
<div class="policy-actions"><label class="check"><input type="checkbox" name="cross_plugin_access" value="1" <?= !empty($surfaceSettings['cross_plugin_access'])?'checked':'' ?>> Allow selected VP3 plugins to read the governed current physical-context summary</label></div>
<div class="policy-box" style="margin-top:16px"><h3>Active perception</h3>
<label class="check"><input type="checkbox" name="active_perception_enabled" value="1" <?= !empty($surfaceSettings['active_perception_enabled'])?'checked':'' ?>> Allow Agent to request a fresh HomeServer perception check</label>
<label class="check" style="margin-top:8px"><input type="checkbox" name="auto_refresh_stale" value="1" <?= !empty($surfaceSettings['auto_refresh_stale'])?'checked':'' ?>> Automatically refresh stale physical answers when possible</label>
<p class="muted" style="margin-bottom:0">Off by default. Requests are sensor reads only, use the existing v2.4 HomeServer relay, respect local privacy, and never authorize physical device actions.</p>
<label class="check" style="margin-top:12px"><input type="checkbox" name="governed_action_proposals_enabled" value="1" <?= !empty($surfaceSettings['governed_action_proposals_enabled'])?'checked':'' ?>> Allow Tracky/Agent to create governed physical-action proposals</label>
<p class="muted" style="margin-bottom:0">Off by default. A proposal can create a local suggestion or approval request only. VP3 Cloud cannot approve a physical action, and OTRO never grants device-control permission automatically.</p>
</div>
<?php if($crossPluginCandidates): ?><div class="checks" style="margin-top:10px"><?php foreach($crossPluginCandidates as $pluginKey=>$pluginLabel): ?><label class="check"><input type="checkbox" name="cross_plugin_plugins[]" value="<?= e($pluginKey) ?>" <?= in_array($pluginKey,(array)($surfaceSettings['cross_plugin_plugins']??[]),true)?'checked':'' ?>><?= e($pluginLabel) ?></label><?php endforeach; ?></div><?php else: ?><p class="muted">No other enabled plugins are currently eligible for physical-context access.</p><?php endif; ?>
<div class="policy-actions"><button class="btn-save" type="submit">Save awareness settings</button></div>
</form></section>
<?php if(empty($sites)): ?><section class="card"><h2>No Tracky site has synchronized yet.</h2><p class="muted">Tracky is enabled in VP3 Cloud. When your paired OTRO HomeServer advertises <code>physical_context.v1</code> and begins governed synchronization, its site will appear here.</p></section><?php else: ?>
<nav class="site-tabs"><?php foreach($sites as $site): ?><a class="<?= $selected===(string)$site['site_id']?'active':'' ?>" href="<?= e(url('/tracky.php?site='.rawurlencode((string)$site['site_id']))) ?>"><?= e((string)($site['label']?:$site['site_id'])) ?></a><?php endforeach; ?></nav>
<?php $site=null;foreach($sites as $candidate)if((string)$candidate['site_id']===$selected){$site=$candidate;break;} ?>
<div class="tracky-grid">
<?php if(is_array($selectedEventCard)): ?><section class="card selected-event"><h2><?= e((string)$selectedEventCard['title']) ?></h2><div class="muted"><?= e((string)$selectedEventCard['subtitle']) ?> · <?= e((string)$selectedEventCard['timestamp']) ?></div><p><?= e((string)$selectedEventCard['summary']) ?></p><div class="checks"><?php foreach((array)($selectedEventCard['badges']??[]) as $badge): ?><span class="pill"><?= e((string)$badge) ?></span><?php endforeach; ?><span class="pill"><?= e((string)$selectedEventCard['status']) ?></span></div></section><?php endif; ?>
<section class="card"><div style="display:flex;justify-content:space-between;gap:20px;align-items:flex-start;flex-wrap:wrap"><div><div class="muted">Site</div><h1 style="margin:4px 0 6px"><?= e((string)($site['label']??$selected)) ?></h1><div class="muted"><?= e($selected) ?> · <?= e((string)($site['device_id']??'')) ?></div></div><div><span class="status <?= e((string)($site['status']??'')) ?>"><?= e(ucfirst((string)($site['status']??'unknown'))) ?></span><div class="muted" style="margin-top:8px">Protocol <?= e((string)($site['protocol_version']??'')) ?></div></div></div></section>
<section class="card half"><div class="muted">Current room</div><div class="metric"><?= e((string)($context['context']['current_room']??'Unknown')) ?></div><p class="muted">Confidence <?= e(number_format((float)($context['context']['confidence']??0)*100,1)) ?>%</p></section>
<section class="card half"><div class="muted">Cloud projection</div><div class="metric"><?= count($world) ?> facts</div><p class="muted"><?= count($events) ?> recent events loaded · sequence <?= e((string)($site['last_sequence']??0)) ?></p></section>
<section class="card half"><h2>Physical context</h2><?php if(empty($context)): ?><div class="empty">No context snapshot yet.</div><?php else: ?><div class="list"><div class="row"><strong>Present</strong><div class="muted"><?= e(implode(', ',(array)($context['context']['people_present']??[]))?:'No one reported') ?></div></div><div class="row"><strong>Environment</strong><div class="muted"><?= e((string)($context['context']['environment_status']??'unknown')) ?></div></div><div class="row"><strong>Recent changes</strong><div class="muted"><?= e(implode(' · ',(array)($context['context']['recent_changes']??[]))?:'None') ?></div></div><div class="row"><strong>Exceptions</strong><div class="muted"><?= e(implode(' · ',(array)($context['context']['exceptions']??[]))?:'None') ?></div></div></div><?php endif; ?></section>
<section class="card half"><h2>Health & capabilities</h2><div class="list"><div class="row"><strong>Health</strong><pre style="white-space:pre-wrap;margin:6px 0 0"><?= e(json_encode($site['health']??[],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)) ?></pre></div><div class="row"><strong>Capabilities</strong><pre style="white-space:pre-wrap;margin:6px 0 0"><?= e(json_encode($site['capabilities']??[],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)) ?></pre></div></div></section>
<section class="card"><h2>Recent governed events</h2><?php if(empty($events)): ?><div class="empty">No governed events yet.</div><?php else: ?><div class="list"><?php foreach($events as $event): ?><div class="row"><span class="pill"><?= e((string)$event['event_type']) ?></span><span class="pill"><?= e((string)$event['severity']) ?></span><strong><?= e((string)$event['occurred_at']) ?></strong><div class="muted">Confidence <?= e(number_format((float)$event['confidence']*100,1)) ?>% · <?= !empty($event['is_fresh'])?'fresh':'historical' ?> · <?= e((string)$event['privacy_class']) ?></div></div><?php endforeach; ?></div><?php endif; ?></section>
<section class="card half"><div class="muted">Agent Brain integration</div><div class="metric"><?= $agentIntegrated?'Ready':'Unavailable' ?></div><p class="muted">Ask Agent Chat where something is, who is present, what changed, when an entity was last seen, how confident Tracky is, why it believes a physical fact, or whether Tracky is healthy.</p></section>
<section class="card half"><div class="muted">Cross-surface integration</div><div class="metric"><?= $proactiveIntegrated?'Ready':'Unavailable' ?></div><p class="muted">Meaningful physical events can flow through Agent Now, existing attention-budgeted notifications, proactive Chat and opt-in voice according to the policy above.</p></section>
<section class="card half"><div class="muted">OTRO contract join</div><div class="metric"><?= !empty($joinCapabilities['compatible'])?'Compatible':'Not ready' ?></div><p class="muted">HomeServer: <?= !empty($joinCapabilities['connected'])?'connected':'offline' ?> · V2.4 reconciliation: <?= !empty($joinCapabilities['reconciliation']['needs_reconciliation'])?'required':'current' ?> · local perception provider: <?= !empty($joinCapabilities['tracky']['provider']['available'])?'available':'unavailable' ?>.</p></section>
<section class="card half"><div class="muted">End-to-end reliability · V2.74</div><div class="metric"><?= e(ucfirst((string)($reliabilityState['state']??'unknown'))) ?></div><p class="muted"><?= e(str_replace('_',' ',(string)($reliabilityState['reason']??'unknown'))) ?> · fresh verification <?= !empty($reliabilityState['fresh_verification'])?'available':'blocked' ?>.</p></section>
<section class="card half"><div class="muted">Governed physical actions · V2.75</div><div class="metric"><?= !empty($actionCapability['supported'])?'Ready':'Unavailable' ?></div><p class="muted">Proposal mode only · remote approval never allowed · default Cloud device-control permission remains off. Controllable categories remain limited by OTRO's existing room/device policy.</p></section>
<section class="card half"><div class="muted">Model accuracy · V2.76</div><div class="metric"><?= !empty($modelAccuracy['available'])?e((string)(int)($modelAccuracy['active_settlements']??0)).' verified':'Awaiting evidence' ?></div><p class="muted"><?php if(!empty($modelAccuracy['available'])): ?><?= e((string)(int)($modelAccuracy['active_profiles']??0)) ?> active model profile(s) · Brier <?= $modelAccuracy['mean_brier_score']===null?'n/a':e(number_format((float)$modelAccuracy['mean_brier_score'],3)) ?> · calibration error <?= $modelAccuracy['mean_expected_calibration_error']===null?'n/a':e(number_format((float)$modelAccuracy['mean_expected_calibration_error'],3)) ?>.<?php else: ?>No governed calibration summary has synchronized yet. Tracky waits for verified outcomes before calibrating future confidence.<?php endif; ?></p><p class="muted">Cloud is read-only: predictions, settlements and confidence buckets remain on the HomeServer/Tracky authority.</p></section>
<section class="card half"><div class="muted">Model lifecycle · V2.77</div><div class="metric"><?= !empty($modelLifecycle['available'])?e(ucfirst((string)($modelLifecycle['health_state']??'unknown'))):'Awaiting lifecycle' ?></div><p class="muted"><?php if(!empty($modelLifecycle['available'])): ?><?= e((string)(int)($modelLifecycle['active_models']??0)) ?> active · <?= e((string)(int)($modelLifecycle['shadow_models']??0)) ?> shadow · <?= e((string)(int)($modelLifecycle['canary_models']??0)) ?> canary · <?= e((string)(int)($modelLifecycle['degraded_models']??0)) ?> degraded · <?= e((string)(int)($modelLifecycle['recent_rollbacks']??0)) ?> recent rollback(s).<?php else: ?>No governed model lifecycle summary has synchronized yet.<?php endif; ?></p><p class="muted">Cloud is read-only. Candidate registration, promotion, activation, canary assignment and rollback remain local to Tracky/HomeServer.</p></section>
<section class="card half"><div class="muted">Agent authority</div><div class="metric">Read + verify + propose</div><p class="muted">Tracky may read context, request fresh perception, and—only when enabled—create a governed physical-action proposal. OTRO's existing local-owner approval and device execution authority remain unchanged.</p></section>
<section class="card privacy"><strong>Privacy boundary</strong><div class="muted">This Cloud view contains governed physical meaning only. Tracky rejects raw frames, video, audio, face embeddings, local filesystem paths and camera source URIs from the Cloud synchronization contract. Agent Brain receives the same governed projection, never the raw perception stream.</div></section>
</div><?php endif; ?>
</div></main></div><script src="<?= e(url('/workspace-shell-v82.js?v=82')) ?>" defer></script><script src="<?= e(url('/tracky-federation-control-center-v280.js?v=280')) ?>" defer></script><script src="<?= e(url('/tracky-physical-world-dashboard-v280.js?v=280')) ?>" defer></script><script src="<?= e(url('/tracky-cross-site-presence-v280.js?v=280')) ?>" defer></script><script src="<?= e(url('/tracky-federation-sync-visibility-v280.js?v=280')) ?>" defer></script><script src="<?= e(url('/tracky-federation-access-operations-v280.js?v=280')) ?>" defer></script><script src="<?= e(url('/tracky-federation-agent-health-v280.js?v=280')) ?>" defer></script><script src="<?= e(url('/tracky-federation-fleet-health-v280.js?v=280')) ?>" defer></script><script src="<?= e(url('/tracky-federation-governed-operations-v280.js?v=280')) ?>" defer></script></body></html>
