CREATE TABLE IF NOT EXISTS campaign_journey_instances (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  public_id CHAR(36) NOT NULL,
  campaign_id BIGINT UNSIGNED NOT NULL,
  journey_id BIGINT UNSIGNED NOT NULL,
  journey_version_id BIGINT UNSIGNED NOT NULL,
  contact_id BIGINT UNSIGNED NOT NULL,
  instance_key VARCHAR(96) NOT NULL,
  trigger_event VARCHAR(80) NOT NULL,
  trigger_event_id VARCHAR(190) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  current_step_key VARCHAR(80) NULL,
  metadata_json LONGTEXT NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_activity_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  paused_at DATETIME NULL,
  completed_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_campaign_journey_instance_public (public_id),
  UNIQUE KEY uq_campaign_journey_instance_key (instance_key),
  INDEX idx_campaign_journey_instance_journey (journey_id,status,last_activity_at,id),
  INDEX idx_campaign_journey_instance_contact (contact_id,status,id),
  INDEX idx_campaign_journey_instance_version (journey_version_id,status,id),
  INDEX idx_campaign_journey_instance_campaign (campaign_id,status,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
