CREATE TABLE IF NOT EXISTS campaign_decisions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  public_id CHAR(36) NOT NULL,
  merchant_id BIGINT UNSIGNED NOT NULL,
  campaign_id BIGINT UNSIGNED NOT NULL,
  journey_id BIGINT UNSIGNED NULL,
  journey_version_id BIGINT UNSIGNED NULL,
  journey_instance_id BIGINT UNSIGNED NULL,
  delivery_id BIGINT UNSIGNED NULL,
  contact_id BIGINT UNSIGNED NOT NULL,
  step_key VARCHAR(80) NOT NULL DEFAULT '',
  decision_type VARCHAR(50) NOT NULL,
  decision_key VARCHAR(190) NOT NULL,
  context_hash CHAR(64) NOT NULL,
  context_json LONGTEXT NOT NULL,
  rules_json LONGTEXT NOT NULL,
  outcome_json LONGTEXT NOT NULL,
  is_holdout TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'decided',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_campaign_decision_public (public_id),
  UNIQUE KEY uq_campaign_decision_key (merchant_id,decision_key),
  INDEX idx_campaign_decision_contact (merchant_id,contact_id,created_at,id),
  INDEX idx_campaign_decision_campaign (campaign_id,decision_type,created_at,id),
  INDEX idx_campaign_decision_journey (journey_id,journey_version_id,created_at,id),
  INDEX idx_campaign_decision_instance (journey_instance_id,created_at,id),
  INDEX idx_campaign_decision_holdout (campaign_id,is_holdout,decision_type,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
