-- VP3 Phase 14 — Agent Workflow Runs + Execution History
-- Canonical orchestration ledger. Domain systems retain mutation authority.

CREATE TABLE IF NOT EXISTS agent_workflow_runs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  owner_user_id INT UNSIGNED NOT NULL,
  agent_id BIGINT UNSIGNED NULL,
  workflow_type VARCHAR(80) NOT NULL DEFAULT 'agent_next_action',
  origin VARCHAR(40) NOT NULL DEFAULT 'brain',
  source_kind VARCHAR(100) NOT NULL DEFAULT '',
  source_key VARCHAR(190) NOT NULL DEFAULT '',
  source_hash CHAR(40) NOT NULL DEFAULT '',
  dedupe_key CHAR(64) NOT NULL,
  title VARCHAR(190) NOT NULL,
  goal TEXT NULL,
  decision_summary TEXT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'queued',
  risk_level VARCHAR(16) NOT NULL DEFAULT 'low',
  requires_approval TINYINT(1) NOT NULL DEFAULT 0,
  approval_status VARCHAR(24) NOT NULL DEFAULT 'not_required',
  execution_target VARCHAR(24) NOT NULL DEFAULT 'cloud',
  capability_key VARCHAR(160) NOT NULL DEFAULT '',
  current_action_id BIGINT UNSIGNED NULL,
  attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
  last_error_class VARCHAR(80) NOT NULL DEFAULT '',
  started_at DATETIME NULL,
  approved_at DATETIME NULL,
  completed_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_agent_workflow_owner_dedupe (owner_user_id,dedupe_key),
  INDEX idx_agent_workflow_owner_status (owner_user_id,status,updated_at,id),
  INDEX idx_agent_workflow_source (owner_user_id,source_kind,source_key),
  INDEX idx_agent_workflow_agent (agent_id,status,updated_at,id),
  CONSTRAINT fk_agent_workflow_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_workflow_actions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  run_id BIGINT UNSIGNED NOT NULL,
  owner_user_id INT UNSIGNED NOT NULL,
  sequence_no INT UNSIGNED NOT NULL,
  action_key VARCHAR(120) NOT NULL DEFAULT '',
  action_type VARCHAR(40) NOT NULL DEFAULT 'execute',
  label VARCHAR(190) NOT NULL,
  summary TEXT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'queued',
  requires_approval TINYINT(1) NOT NULL DEFAULT 0,
  execution_target VARCHAR(24) NOT NULL DEFAULT 'cloud',
  capability_key VARCHAR(160) NOT NULL DEFAULT '',
  attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
  result_summary TEXT NULL,
  result_json MEDIUMTEXT NULL,
  error_class VARCHAR(80) NOT NULL DEFAULT '',
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_agent_workflow_action_sequence (run_id,sequence_no),
  INDEX idx_agent_workflow_action_owner (owner_user_id,status,run_id,sequence_no),
  CONSTRAINT fk_agent_workflow_action_run FOREIGN KEY (run_id) REFERENCES agent_workflow_runs(id) ON DELETE CASCADE,
  CONSTRAINT fk_agent_workflow_action_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_workflow_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  run_id BIGINT UNSIGNED NOT NULL,
  owner_user_id INT UNSIGNED NOT NULL,
  event_type VARCHAR(60) NOT NULL,
  from_status VARCHAR(32) NOT NULL DEFAULT '',
  to_status VARCHAR(32) NOT NULL DEFAULT '',
  actor_kind VARCHAR(32) NOT NULL DEFAULT 'system',
  summary VARCHAR(500) NOT NULL DEFAULT '',
  metadata_json TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_agent_workflow_event_run (run_id,id),
  INDEX idx_agent_workflow_event_owner (owner_user_id,created_at,id),
  CONSTRAINT fk_agent_workflow_event_run FOREIGN KEY (run_id) REFERENCES agent_workflow_runs(id) ON DELETE CASCADE,
  CONSTRAINT fk_agent_workflow_event_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
