-- VP3 Phase 19.2 — Webhook + Event Infrastructure
-- Durable sanitized ingress. Phase 19.0 remains the execution queue.

CREATE TABLE IF NOT EXISTS agent_event_inbox (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  event_uuid CHAR(36) NOT NULL,
  owner_user_id INT UNSIGNED NOT NULL,
  source VARCHAR(80) NOT NULL,
  event_type VARCHAR(120) NOT NULL,
  schema_version SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  external_event_id VARCHAR(190) NOT NULL DEFAULT '',
  dedupe_hash CHAR(64) NOT NULL,
  verification_status VARCHAR(24) NOT NULL DEFAULT 'trusted',
  verification_key_id VARCHAR(120) NOT NULL DEFAULT '',
  processing_status VARCHAR(24) NOT NULL DEFAULT 'accepted',
  occurred_at DATETIME NULL,
  received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processing_started_at DATETIME NULL,
  processed_at DATETIME NULL,
  replay_count INT UNSIGNED NOT NULL DEFAULT 0,
  correlation_id VARCHAR(120) NOT NULL DEFAULT '',
  causation_id VARCHAR(120) NOT NULL DEFAULT '',
  payload_json MEDIUMTEXT NULL,
  linked_run_id BIGINT UNSIGNED NULL,
  last_error_code VARCHAR(80) NOT NULL DEFAULT '',
  last_error_message VARCHAR(300) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_agent_event_uuid (event_uuid),
  UNIQUE KEY uq_agent_event_owner_dedupe (owner_user_id,dedupe_hash),
  INDEX idx_agent_event_owner_recent (owner_user_id,received_at,id),
  INDEX idx_agent_event_processing (processing_status,received_at,id),
  INDEX idx_agent_event_source (owner_user_id,source,event_type,received_at,id),
  INDEX idx_agent_event_run (linked_run_id),
  CONSTRAINT fk_agent_event_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_agent_event_run FOREIGN KEY (linked_run_id) REFERENCES agent_workflow_runs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
