-- Stonefellow v181 Artist Workspace. /upgrade.php installs this schema idempotently.
CREATE TABLE IF NOT EXISTS artist_workspaces_v181 (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  artist_user_id INT UNSIGNED NOT NULL,
  workspace_name VARCHAR(190) NOT NULL,
  profile_slug VARCHAR(190) NULL,
  bio TEXT NULL,
  profile_image_path VARCHAR(500) NOT NULL DEFAULT '',
  cover_image_path VARCHAR(500) NOT NULL DEFAULT '',
  website_url VARCHAR(500) NOT NULL DEFAULT '',
  instagram_url VARCHAR(500) NOT NULL DEFAULT '',
  tiktok_url VARCHAR(500) NOT NULL DEFAULT '',
  youtube_url VARCHAR(500) NOT NULL DEFAULT '',
  spotify_url VARCHAR(500) NOT NULL DEFAULT '',
  apple_music_url VARCHAR(500) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_artist_workspace_user (artist_user_id),
  UNIQUE KEY uq_artist_workspace_profile_slug (profile_slug),
  CONSTRAINT fk_artist_workspace_user_v181 FOREIGN KEY (artist_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE artist_workspaces_v181
  ADD COLUMN IF NOT EXISTS profile_slug VARCHAR(190) NULL AFTER workspace_name,
  ADD COLUMN IF NOT EXISTS bio TEXT NULL AFTER profile_slug,
  ADD COLUMN IF NOT EXISTS profile_image_path VARCHAR(500) NOT NULL DEFAULT '' AFTER bio,
  ADD COLUMN IF NOT EXISTS cover_image_path VARCHAR(500) NOT NULL DEFAULT '' AFTER profile_image_path,
  ADD COLUMN IF NOT EXISTS website_url VARCHAR(500) NOT NULL DEFAULT '' AFTER cover_image_path,
  ADD COLUMN IF NOT EXISTS instagram_url VARCHAR(500) NOT NULL DEFAULT '' AFTER website_url,
  ADD COLUMN IF NOT EXISTS tiktok_url VARCHAR(500) NOT NULL DEFAULT '' AFTER instagram_url,
  ADD COLUMN IF NOT EXISTS youtube_url VARCHAR(500) NOT NULL DEFAULT '' AFTER tiktok_url,
  ADD COLUMN IF NOT EXISTS spotify_url VARCHAR(500) NOT NULL DEFAULT '' AFTER youtube_url,
  ADD COLUMN IF NOT EXISTS apple_music_url VARCHAR(500) NOT NULL DEFAULT '' AFTER spotify_url,
  ADD UNIQUE INDEX IF NOT EXISTS uq_artist_workspace_profile_slug (profile_slug);

CREATE TABLE IF NOT EXISTS artist_catalog_tracks_v181 (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,workspace_id BIGINT UNSIGNED NOT NULL,source_track_id INT UNSIGNED NULL,title VARCHAR(190) NOT NULL,album VARCHAR(190) NOT NULL DEFAULT '',audio_path VARCHAR(500) NOT NULL DEFAULT '',cover_path VARCHAR(500) NOT NULL DEFAULT '',visibility VARCHAR(30) NOT NULL DEFAULT 'members',is_published TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_artist_track_source (workspace_id,source_track_id),INDEX idx_artist_track_workspace (workspace_id,updated_at),CONSTRAINT fk_artist_track_workspace_v181 FOREIGN KEY (workspace_id) REFERENCES artist_workspaces_v181(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS artist_catalog_photos_v181 (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,workspace_id BIGINT UNSIGNED NOT NULL,source_photo_id INT UNSIGNED NULL,title VARCHAR(190) NOT NULL,image_path VARCHAR(500) NOT NULL,visibility VARCHAR(30) NOT NULL DEFAULT 'members',is_published TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_artist_photo_source (workspace_id,source_photo_id),INDEX idx_artist_photo_workspace (workspace_id,updated_at),CONSTRAINT fk_artist_photo_workspace_v181 FOREIGN KEY (workspace_id) REFERENCES artist_workspaces_v181(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS artist_catalog_merch_v181 (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,workspace_id BIGINT UNSIGNED NOT NULL,source_merch_id INT UNSIGNED NULL,title VARCHAR(190) NOT NULL,description TEXT NOT NULL,price_cents INT UNSIGNED NOT NULL DEFAULT 0,image_path VARCHAR(500) NOT NULL DEFAULT '',product_url VARCHAR(500) NOT NULL DEFAULT '',visibility VARCHAR(30) NOT NULL DEFAULT 'members',is_published TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_artist_merch_source (workspace_id,source_merch_id),INDEX idx_artist_merch_workspace (workspace_id,updated_at),CONSTRAINT fk_artist_merch_workspace_v181 FOREIGN KEY (workspace_id) REFERENCES artist_workspaces_v181(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS artist_catalog_shows_v181 (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,workspace_id BIGINT UNSIGNED NOT NULL,source_show_id INT UNSIGNED NULL,show_date DATETIME NOT NULL,venue VARCHAR(190) NOT NULL,city VARCHAR(190) NOT NULL DEFAULT '',region VARCHAR(190) NOT NULL DEFAULT '',notes TEXT NOT NULL,ticket_url VARCHAR(500) NOT NULL DEFAULT '',is_published TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_artist_show_source (workspace_id,source_show_id),INDEX idx_artist_show_workspace (workspace_id,show_date),CONSTRAINT fk_artist_show_workspace_v181 FOREIGN KEY (workspace_id) REFERENCES artist_workspaces_v181(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS artist_catalog_albums_v181 (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,workspace_id BIGINT UNSIGNED NOT NULL,source_album_id INT UNSIGNED NULL,title VARCHAR(190) NOT NULL,release_date DATE NULL,description TEXT NOT NULL,cover_path VARCHAR(500) NOT NULL DEFAULT '',visibility VARCHAR(30) NOT NULL DEFAULT 'members',is_published TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_artist_album_source (workspace_id,source_album_id),INDEX idx_artist_album_workspace (workspace_id,updated_at),CONSTRAINT fk_artist_album_workspace_v181 FOREIGN KEY (workspace_id) REFERENCES artist_workspaces_v181(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS artist_posts_v181 (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,workspace_id BIGINT UNSIGNED NOT NULL,source_post_id INT UNSIGNED NULL,title VARCHAR(190) NOT NULL,body TEXT NOT NULL,post_type VARCHAR(30) NOT NULL DEFAULT 'update',image_path VARCHAR(500) NOT NULL DEFAULT '',media_url VARCHAR(500) NOT NULL DEFAULT '',visibility VARCHAR(30) NOT NULL DEFAULT 'members',is_published TINYINT(1) NOT NULL DEFAULT 0,published_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_artist_post_source (workspace_id,source_post_id),INDEX idx_artist_post_workspace (workspace_id,updated_at),CONSTRAINT fk_artist_post_workspace_v181 FOREIGN KEY (workspace_id) REFERENCES artist_workspaces_v181(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS artist_release_plans_v181 (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,workspace_id BIGINT UNSIGNED NOT NULL,source_release_id BIGINT UNSIGNED NULL,title VARCHAR(190) NOT NULL,release_type VARCHAR(40) NOT NULL DEFAULT 'single',status VARCHAR(30) NOT NULL DEFAULT 'planning',priority VARCHAR(20) NOT NULL DEFAULT 'normal',target_date DATETIME NULL,agent_goal TEXT NULL,notes TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_artist_release_source (workspace_id,source_release_id),INDEX idx_artist_release_workspace (workspace_id,target_date,status),CONSTRAINT fk_artist_release_workspace_v181 FOREIGN KEY (workspace_id) REFERENCES artist_workspaces_v181(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS artist_workspace_track_favorites_v181 (user_id INT UNSIGNED NOT NULL,artist_track_id BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_id,artist_track_id),CONSTRAINT fk_artist_favorite_user_v181 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_artist_favorite_track_v181 FOREIGN KEY (artist_track_id) REFERENCES artist_catalog_tracks_v181(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS artist_workspace_playlist_tracks_v181 (playlist_id INT UNSIGNED NOT NULL,artist_track_id BIGINT UNSIGNED NOT NULL,sort_order INT UNSIGNED NOT NULL DEFAULT 0,added_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(playlist_id,artist_track_id),CONSTRAINT fk_artist_playlist_track_playlist_v181 FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE,CONSTRAINT fk_artist_playlist_track_track_v181 FOREIGN KEY (artist_track_id) REFERENCES artist_catalog_tracks_v181(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS artist_workspace_saved_shows_v181 (user_id INT UNSIGNED NOT NULL,artist_show_id BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_id,artist_show_id),INDEX idx_artist_saved_show_user (user_id,created_at),CONSTRAINT fk_artist_saved_show_user_v181 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_artist_saved_show_v181 FOREIGN KEY (artist_show_id) REFERENCES artist_catalog_shows_v181(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS artist_workspace_saved_photos_v181 (user_id INT UNSIGNED NOT NULL,artist_photo_id BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_id,artist_photo_id),INDEX idx_artist_saved_photo_user (user_id,created_at),CONSTRAINT fk_artist_saved_photo_user_v181 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_artist_saved_photo_v181 FOREIGN KEY (artist_photo_id) REFERENCES artist_catalog_photos_v181(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE chat_conversations ADD COLUMN IF NOT EXISTS artist_workspace_id BIGINT UNSIGNED NULL AFTER user_id, ADD INDEX IF NOT EXISTS idx_chat_conversations_artist_workspace (artist_workspace_id,updated_at);
ALTER TABLE playlists ADD COLUMN IF NOT EXISTS artist_workspace_id BIGINT UNSIGNED NULL AFTER owner_user_id, ADD INDEX IF NOT EXISTS idx_playlists_artist_workspace (artist_workspace_id,updated_at);
