(() => {
  'use strict';
  const cfg=window.STONEFELLOW_VIDEO_EDITOR||{};
  const $=id=>document.getElementById(id);
  const mediaList=$('videoMediaLibrary'),musicList=$('videoMusicLibrary'),visualLane=$('videoVisualTimeline'),audioLane=$('videoAudioTimeline');
  const previewVideo=$('videoPreviewVideo'),previewImage=$('videoPreviewImage'),previewEmpty=$('videoPreviewEmpty');
  const inspectorForm=$('videoInspectorForm'),inspectorEmpty=$('videoInspectorEmpty'),inspectorTitle=$('videoInspectorTitle'),status=$('videoEditorStatus'),playhead=$('videoTimelinePlayhead'),clock=$('videoTimelineClock'),projectTitle=$('videoProjectTitle');
  const timelinePanel=document.querySelector('.video-timeline-panel');
  let projectId=Number(cfg.projectId||0),assets=Array.isArray(cfg.assets)?cfg.assets:[],tracks=Array.isArray(cfg.tracks)?cfg.tracks:[];
  let timeline=Array.isArray(cfg.timeline)?cfg.timeline.map((item,i)=>normalizeItem(item,i)):[],selectedId='',playing=false,playStart=0,playOffset=0,raf=0,activeVisualId='';
  let pixelsPerSecond=Math.max(8,Math.min(180,Number(localStorage.getItem('stonefellow:video:zoom')||32))),snapEnabled=localStorage.getItem('stonefellow:video:snap')!=='0';
  const liveAudio=new Map();
  const sessionKey=sessionStorage.getItem('stonefellow:video:edit-session')||((crypto.randomUUID?.()||('video-'+Date.now()+'-'+Math.random().toString(36).slice(2))));
  sessionStorage.setItem('stonefellow:video:edit-session',sessionKey);
  let suppressLedger=false,gestureBefore=null,gestureAction='edit';

  function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
  function uid(){return 'clip-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);}
  function clamp(v,min,max){v=Number(v);return Number.isFinite(v)?Math.max(min,Math.min(max,v)):min;}
  function fmt(seconds){seconds=Math.max(0,Number(seconds)||0);const m=Math.floor(seconds/60),s=Math.floor(seconds%60);return `${m}:${String(s).padStart(2,'0')}`;}
  function snapTime(v){if(!snapEnabled)return Math.max(0,v);const step=pixelsPerSecond>=80?.05:pixelsPerSecond>=40?.1:.25;return Math.max(0,Math.round(v/step)*step);}
  function normalizeItem(item,i=0){
    const trimStart=clamp(item.trim_start,0,86400),trimEnd=clamp(item.trim_end,0,86400);
    return {
      id:String(item.id||`clip-${i}-${Date.now()}`),source_kind:item.source_kind==='track'?'track':'asset',source_id:Number(item.source_id||0),media_type:['photo','video','audio'].includes(item.media_type)?item.media_type:'audio',title:String(item.title||'Clip'),start:clamp(item.start,0,86400),duration:trimEnd>trimStart?clamp(trimEnd-trimStart,.1,86400):clamp(item.duration||5,.1,86400),trim_start:trimStart,trim_end:trimEnd,volume:clamp(item.volume??1,0,1.5),muted:Boolean(item.muted),opacity:clamp(item.opacity??1,0,1),fade_in:clamp(item.fade_in??0,0,60),fade_out:clamp(item.fade_out??0,0,60),lane:Math.max(0,Math.min(7,Number(item.lane||0))),locked:Boolean(item.locked),lane_volume:clamp(item.lane_volume??1,0,1.5),lane_muted:Boolean(item.lane_muted),lane_solo:Boolean(item.lane_solo),order:Number(item.order||i)
    };
  }
  function setStatus(message='',state=''){if(!status)return;status.hidden=!message;status.textContent=message;status.dataset.state=state;}
  function assetById(id){return assets.find(a=>Number(a.id)===Number(id))||null;}
  function trackById(id){return tracks.find(t=>Number(t.id)===Number(id))||null;}
  function sourceFor(item){if(item.source_kind==='track'){const track=trackById(item.source_id);return track?{url:track.audio,cover:track.cover,title:track.title,available:true}:null;}const asset=assetById(item.source_id);return asset?{url:asset.url,title:asset.title,available:asset.available!==false,mime_type:asset.mime_type||'',media_type:asset.media_type||item.media_type}:null;}
  function sourceError(message){previewVideo.pause();previewVideo.removeAttribute('src');previewVideo.load();previewVideo.hidden=true;previewImage.hidden=true;previewEmpty.hidden=false;previewEmpty.innerHTML=`<strong>Media unavailable</strong><span>${esc(message)}</span>`;previewEmpty.closest('.video-preview-stage')?.setAttribute('data-source-error','1');setStatus(message,'error');}
  function clearSourceError(){previewEmpty.closest('.video-preview-stage')?.removeAttribute('data-source-error');}
  function canPlayVideoMime(mime){if(!mime)return true;return (previewVideo?.canPlayType?.(mime)||'')!=='';}
  async function previewLibraryAsset(assetId){const asset=assetById(assetId);if(!asset)return;if(asset.available===false)return sourceError(`“${asset.title||'This media item'}” is saved but its file is unavailable.`);clearSourceError();if(asset.media_type==='photo'){previewVideo.pause();previewVideo.hidden=true;previewImage.src=asset.url;previewImage.hidden=false;previewEmpty.hidden=true;setStatus(`Previewing ${asset.title}. Add it to the timeline to edit.`,'success');return;}if(asset.media_type==='video'){if(!canPlayVideoMime(asset.mime_type))return sourceError(`This browser cannot decode ${asset.mime_type||'this video format'}.`);previewImage.hidden=true;previewVideo.hidden=false;previewEmpty.hidden=true;previewVideo.src=asset.url;previewVideo.currentTime=0;previewVideo.load();try{await previewVideo.play();previewVideo.pause();setStatus(`Loaded ${asset.title}. Add it to the timeline to edit.`,'success');}catch(error){sourceError(`Could not load “${asset.title}”. ${error?.message||''}`.trim());}}}
  function playableDuration(item){const duration=clamp(item?.duration,.1,86400),trimStart=clamp(item?.trim_start,0,86400),trimEnd=clamp(item?.trim_end,0,86400);return trimEnd>trimStart?Math.min(duration,Math.max(.1,trimEnd-trimStart)):duration;}
  function timelineEnd(){return timeline.reduce((max,item)=>Math.max(max,item.start+playableDuration(item)),0);}
  function nextStart(type,lane=0){return timeline.filter(i=>(type==='audio'?i.media_type==='audio':i.media_type!=='audio')&&i.lane===lane).reduce((m,i)=>Math.max(m,i.start+playableDuration(i)),0);}
  function defaultDuration(asset){if(asset.media_type==='photo')return 5;return Number(asset.duration_seconds)>0?Number(asset.duration_seconds):10;}
  function clipById(id){return timeline.find(i=>i.id===id)||null;}
  function laneClips(type,lane){return timeline.filter(i=>(type==='audio'?i.media_type==='audio':i.media_type!=='audio')&&i.lane===lane);}
  function laneState(type,lane){const clips=laneClips(type,lane),first=clips[0];return {volume:first?.lane_volume??1,muted:Boolean(first?.lane_muted),solo:Boolean(first?.lane_solo)};}
  function setLaneState(type,lane,patch){timeline.forEach(i=>{if((type==='audio'?i.media_type==='audio':i.media_type!=='audio')&&i.lane===lane)Object.assign(i,patch);});}

  function projectSettings(){return {width:clamp($('videoProjectWidth')?.value,320,3840),height:clamp($('videoProjectHeight')?.value,240,2160),fps:clamp($('videoProjectFps')?.value,12,60)};}
  function editorState(){return {project_id:projectId,title:projectTitle?.value||'Untitled Video',settings:projectSettings(),selected_id:selectedId,playhead:Number((playing?currentPlayTime():playOffset).toFixed(4)),snap:snapEnabled,zoom:pixelsPerSecond,clips:timeline.map(i=>({...i}))};}
  function diffStates(before,after){const changes=[];const walk=(a,b,path)=>{if(JSON.stringify(a)===JSON.stringify(b))return;if(Array.isArray(a)&&Array.isArray(b)&&a.every(x=>x&&typeof x==='object'&&'id'in x)&&b.every(x=>x&&typeof x==='object'&&'id'in x)){const am=new Map(a.map(x=>[String(x.id),x])),bm=new Map(b.map(x=>[String(x.id),x]));new Set([...am.keys(),...bm.keys()]).forEach(id=>{if(!am.has(id))changes.push({path:`${path}[${id}]`,before:null,after:bm.get(id)});else if(!bm.has(id))changes.push({path:`${path}[${id}]`,before:am.get(id),after:null});else walk(am.get(id),bm.get(id),`${path}[${id}]`);});return;}if(a&&b&&typeof a==='object'&&typeof b==='object'&&!Array.isArray(a)&&!Array.isArray(b)){new Set([...Object.keys(a),...Object.keys(b)]).forEach(k=>walk(a[k],b[k],path?`${path}.${k}`:k));return;}changes.push({path,before:a??null,after:b??null});};walk(before,after,'');return changes.slice(0,500);}
  async function recordLedger(before,after,meta={}){if(suppressLedger||!cfg.ledgerEndpoint)return;const changes=diffStates(before,after);if(!changes.length)return;document.dispatchEvent(new CustomEvent('stonefellow:video-change',{detail:{action:meta.action||'edit',changes:changes.length}}));try{await fetch(cfg.ledgerEndpoint,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'record',csrf_token:cfg.csrfToken,editor_kind:'video',project_id:projectId,session_key:sessionKey,source_kind:meta.source||'manual',action_key:meta.action||'edit',request_text:meta.request||'',model_provider:meta.provider||'',model_name:meta.model||'',conversation_id:Number(meta.conversationId||cfg.conversationId||0),playhead_seconds:after.playhead,before,after,changes})});}catch(e){console.warn('Video edit ledger:',e);}}
  function beginGesture(action='edit'){if(!gestureBefore){gestureBefore=editorState();gestureAction=action;}}
  function endGesture(action=gestureAction){if(!gestureBefore)return;const before=gestureBefore;gestureBefore=null;recordLedger(before,editorState(),{source:'manual',action});}
  async function mutate(action,fn,meta={}){const before=editorState();await fn();const after=editorState();recordLedger(before,after,{source:meta.source||'manual',action,request:meta.request||'',provider:meta.provider||'',model:meta.model||'',conversationId:meta.conversationId||0});}

  function injectV90Controls(){
    const timelineHead=timelinePanel?.querySelector('header');
    if(timelineHead&&!$('videoV90Tools')){const tools=document.createElement('div');tools.id='videoV90Tools';tools.className='video-v90-tools';tools.innerHTML=`<button type="button" id="videoSplitClip" title="Split selected clip at playhead">Split</button><button type="button" id="videoDuplicateClip">Duplicate</button><button type="button" id="videoDeleteClip">Delete</button><button type="button" id="videoSnapToggle" class="${snapEnabled?'active':''}">Snap</button><button type="button" id="videoZoomOut">−</button><span id="videoZoomValue">${Math.round(pixelsPerSecond)} px/s</span><button type="button" id="videoZoomIn">+</button>`;timelineHead.appendChild(tools);}
    if(inspectorForm&&!$('videoItemLane')){const remove=$('videoRemoveItem');const box=document.createElement('div');box.className='video-v90-inspector';box.innerHTML=`<label><span>Timeline Lane</span><input id="videoItemLane" type="number" min="0" max="7" step="1"></label><label id="videoOpacityLabel"><span>Opacity</span><input id="videoItemOpacity" type="range" min="0" max="1" step="0.01"></label><label><span>Fade In (seconds)</span><input id="videoItemFadeIn" type="number" min="0" max="60" step="0.05"></label><label><span>Fade Out (seconds)</span><input id="videoItemFadeOut" type="number" min="0" max="60" step="0.05"></label><label class="video-inspector-check"><input id="videoItemLocked" type="checkbox"><span>Lock Clip</span></label>`;inspectorForm.insertBefore(box,remove);}
  }

  function renderLibraries(){
    mediaList.innerHTML=assets.map(asset=>{const unavailable=asset.available===false,visual=asset.media_type==='photo'?`<img src="${esc(asset.url)}" alt="">`:asset.media_type==='video'?`<video class="video-preview-v100" src="${esc(asset.url)}" muted playsinline preload="metadata"></video>`:`<span class="video-library-thumb">AUD</span>`,meta=unavailable?'File unavailable':`${esc(asset.media_type)}${asset.duration_seconds?' · '+fmt(asset.duration_seconds):' · Ready'}`;return `<article class="video-library-card ${unavailable?'media-unavailable-v100':''}" data-preview-asset="${Number(asset.id)}">${visual}<div><strong>${esc(asset.title)}</strong><small>${meta}</small><button type="button" data-add-asset="${Number(asset.id)}" ${unavailable?'disabled':''}>Add to Timeline</button></div></article>`;}).join('')||'<p>No media saved yet. Capture something in Agent Chat or upload a file.</p>';
    musicList.innerHTML=tracks.map(track=>`<article class="video-library-card"><img src="${esc(track.cover)}" alt=""><div><strong>${esc(track.title)}</strong><small>${esc(track.saved?'Saved Song · ':'')}${esc(track.album||'Stonefellow')}</small><button type="button" data-add-track="${Number(track.id)}">Add Audio</button></div></article>`).join('')||'<p>No playable songs are available to this account.</p>';
  }

  function laneCount(type){const relevant=timeline.filter(i=>type==='audio'?i.media_type==='audio':i.media_type!=='audio');return Math.max(1,...relevant.map(i=>i.lane+1));}
  function renderLane(container,type,lane){const state=laneState(type,lane),width=Math.max(900,(timelineEnd()+10)*pixelsPerSecond);const row=document.createElement('div');row.className='video-v90-lane';row.dataset.mediaLane=type;row.dataset.lane=String(lane);row.innerHTML=`<div class="video-v90-lane-controls"><strong>${type==='audio'?'A':'V'}${lane+1}</strong><button type="button" data-lane-mute aria-pressed="${state.muted?'true':'false'}">M</button><button type="button" data-lane-solo aria-pressed="${state.solo?'true':'false'}">S</button><input data-lane-volume type="range" min="0" max="1.5" step="0.01" value="${state.volume}" title="Lane volume"></div><div class="video-v90-lane-surface" style="width:${Math.ceil(width)}px"></div>`;
    const surface=row.querySelector('.video-v90-lane-surface');
    laneClips(type,lane).sort((a,b)=>a.start-b.start||a.order-b.order).forEach(item=>{const el=document.createElement('article');el.className=`video-timeline-item video-v90-clip ${item.id===selectedId?'selected':''} ${item.locked?'locked':''}`;el.dataset.itemId=item.id;el.dataset.type=item.media_type;el.style.left=`${item.start*pixelsPerSecond}px`;el.style.width=`${Math.max(28,item.duration*pixelsPerSecond)}px`;el.innerHTML=`<span class="video-v90-trim left" data-trim="left"></span><div class="video-v90-clip-body"><strong>${esc(item.title)}</strong><small>${fmt(item.start)} · ${fmt(item.duration)}${item.fade_in||item.fade_out?` · fade ${item.fade_in.toFixed(2)}/${item.fade_out.toFixed(2)}`:''}</small></div><span class="video-v90-trim right" data-trim="right"></span>`;surface.appendChild(el);});
    container.appendChild(row);return row;
  }
  function renderTimeline(){visualLane.innerHTML='';audioLane.innerHTML='';for(let i=0;i<laneCount('visual');i++)renderLane(visualLane,'visual',i);for(let i=0;i<laneCount('audio');i++)renderLane(audioLane,'audio',i);clock.textContent=`${fmt(playing?currentPlayTime():playOffset)} / ${fmt(timelineEnd())}`;$('videoZoomValue')&&($('videoZoomValue').textContent=`${Math.round(pixelsPerSecond)} px/s`);$('videoSnapToggle')?.classList.toggle('active',snapEnabled);renderInspector();updatePlayhead(playing?currentPlayTime():playOffset);}
  function renderInspector(){const item=clipById(selectedId);inspectorForm.hidden=!item;inspectorEmpty.hidden=Boolean(item);if(!item){inspectorTitle.textContent='No clip selected';return;}inspectorTitle.textContent=item.title;$('videoItemStart').value=String(item.start);$('videoItemDuration').value=String(item.duration);$('videoItemTrimStart').value=String(item.trim_start);$('videoItemTrimEnd').value=String(item.trim_end);$('videoItemVolume').value=String(item.volume);$('videoItemMuted').checked=item.muted;$('videoItemLane').value=String(item.lane);$('videoItemOpacity').value=String(item.opacity);$('videoItemFadeIn').value=String(item.fade_in);$('videoItemFadeOut').value=String(item.fade_out);$('videoItemLocked').checked=item.locked;$('videoVolumeLabel').hidden=item.media_type==='photo';$('videoMuteLabel').hidden=item.media_type==='photo';$('videoOpacityLabel').hidden=item.media_type==='audio';}
  function selectItem(id){selectedId=id;renderTimeline();showSelected();}

  function addAsset(assetId,start=null,lane=0){const asset=assetById(assetId);if(!asset){sourceError(`Media #${assetId} is not available to this project.`);return null;}if(asset.available===false){sourceError(`“${asset.title||'This media item'}” cannot be added because its file is unavailable.`);return null;}const type=asset.media_type==='audio'?'audio':'visual',state=laneState(type,lane);const item=normalizeItem({id:uid(),source_kind:'asset',source_id:asset.id,media_type:asset.media_type,title:asset.title,start:start===null?nextStart(type,lane):snapTime(start),lane,duration:defaultDuration(asset),volume:1,lane_volume:state.volume,lane_muted:state.muted,lane_solo:state.solo},timeline.length);timeline.push(item);selectedId=item.id;renderTimeline();showSelected();return item;}
  function addTrack(trackId,start=null,lane=0){const track=trackById(trackId);if(!track)return null;const state=laneState('audio',lane),item=normalizeItem({id:uid(),source_kind:'track',source_id:track.id,media_type:'audio',title:track.title,start:start===null?nextStart('audio',lane):snapTime(start),lane,duration:180,volume:1,lane_volume:state.volume,lane_muted:state.muted,lane_solo:state.solo},timeline.length);timeline.push(item);selectedId=item.id;renderTimeline();const probe=new Audio(track.audio);probe.preload='metadata';probe.addEventListener('loadedmetadata',()=>{if(Number.isFinite(probe.duration)&&probe.duration>0){const before=editorState();item.duration=probe.duration;renderTimeline();recordLedger(before,editorState(),{source:'import',action:'probe_duration'});}},{once:true});return item;}
  function splitClip(id=selectedId,time=playing?currentPlayTime():playOffset){const item=clipById(id);if(!item||item.locked)return false;if(time<=item.start+.05||time>=item.start+item.duration-.05)return false;const cut=time;const originalEnd=item.start+item.duration,firstDuration=cut-item.start,secondDuration=originalEnd-cut;const second=normalizeItem({...item,id:uid(),start:cut,duration:secondDuration,trim_start:item.trim_start+firstDuration,order:timeline.length},timeline.length);item.duration=firstDuration;item.fade_out=0;second.fade_in=0;timeline.push(second);selectedId=second.id;renderTimeline();return true;}
  function duplicateClip(id=selectedId){const item=clipById(id);if(!item)return false;const copy=normalizeItem({...item,id:uid(),start:snapTime(item.start+item.duration+.1),order:timeline.length},timeline.length);timeline.push(copy);selectedId=copy.id;renderTimeline();return true;}
  function deleteClip(id=selectedId){const item=clipById(id);if(!item||item.locked)return false;timeline=timeline.filter(i=>i.id!==id);if(selectedId===id)selectedId='';renderTimeline();showSelected();return true;}

  function showSelected(){const item=clipById(selectedId);if(!item||item.media_type==='audio')return;const source=sourceFor(item);if(!source||source.available===false){sourceError(`The source for “${item.title}” is unavailable. The timeline clip has been preserved.`);return;}clearSourceError();if(item.media_type==='video'&&!canPlayVideoMime(source.mime_type)){sourceError(`This browser cannot decode ${source.mime_type||'the selected video format'}.`);return;}if(item.media_type==='photo'){previewVideo.pause();previewVideo.hidden=true;previewImage.src=source.url;previewImage.style.opacity=String(item.opacity);previewImage.hidden=false;previewEmpty.hidden=true;}else{previewImage.hidden=true;previewVideo.hidden=false;previewEmpty.hidden=true;if(previewVideo.src!==new URL(source.url,location.href).href)previewVideo.src=source.url;previewVideo.currentTime=Math.max(0,item.trim_start);previewVideo.style.opacity=String(item.opacity);}}
  function currentPlayTime(){return playOffset+(performance.now()-playStart)/1000;}
  function stopAudio(){liveAudio.forEach(audio=>audio.pause());liveAudio.clear();}
  function updatePlayhead(time){const max=Math.max(.1,timelineEnd()),scroll=Number(visualLane?.scrollLeft||0),x=Math.max(0,time*pixelsPerSecond-scroll);if(playhead){playhead.style.left=`${x}px`;playhead.style.width='2px';playhead.style.transform='none';}clock.textContent=`${fmt(time)} / ${fmt(max)}`;}
  function seek(time){playOffset=clamp(time,0,Math.max(0,timelineEnd()));if(playing)playStart=performance.now();stopAudio();activeVisualId='';syncVisual(playOffset);updatePlayhead(playOffset);}
  function stopTimeline(reset=false){playing=false;cancelAnimationFrame(raf);previewVideo.pause();stopAudio();activeVisualId='';if(reset)playOffset=0;updatePlayhead(playOffset);}
  function visualLaneAudible(item){const candidates=timeline.filter(i=>i.media_type!=='audio'),solo=candidates.some(i=>i.lane_solo);return !item.muted&&!item.lane_muted&&(!solo||item.lane_solo);}
  function audioLaneAudible(item){const candidates=timeline.filter(i=>i.media_type==='audio'),solo=candidates.some(i=>i.lane_solo);return !item.muted&&!item.lane_muted&&(!solo||item.lane_solo);}
  function fadeGain(item,local){let gain=1;if(item.fade_in>0)gain=Math.min(gain,clamp(local/item.fade_in,0,1));const remain=item.duration-local;if(item.fade_out>0)gain=Math.min(gain,clamp(remain/item.fade_out,0,1));return gain;}
  function syncVisual(time){const active=timeline.filter(i=>i.media_type!=='audio'&&time>=i.start&&time<i.start+i.duration&&visualLaneAudible(i)).sort((a,b)=>b.lane-a.lane||b.order-a.order)[0];if(!active){previewVideo.pause();previewVideo.hidden=true;previewImage.hidden=true;previewEmpty.hidden=false;activeVisualId='';return;}const source=sourceFor(active);if(!source||source.available===false){sourceError(`The source for “${active.title}” is unavailable.`);return;}const offset=time-active.start+active.trim_start,opacity=active.opacity*fadeGain(active,time-active.start);if(active.media_type==='photo'){if(activeVisualId!==active.id){previewVideo.pause();previewVideo.hidden=true;previewImage.src=source.url;previewImage.hidden=false;previewEmpty.hidden=true;activeVisualId=active.id;}previewImage.style.opacity=String(opacity);return;}previewImage.hidden=true;previewVideo.hidden=false;previewEmpty.hidden=true;if(activeVisualId!==active.id||previewVideo.src!==new URL(source.url,location.href).href){previewVideo.src=source.url;previewVideo.currentTime=Math.max(0,offset);previewVideo.play().catch(error=>sourceError(`Video playback failed. ${error?.message||''}`.trim()));activeVisualId=active.id;}else{if(Math.abs(previewVideo.currentTime-offset)>.6)previewVideo.currentTime=Math.max(0,offset);if(previewVideo.paused)previewVideo.play().catch(error=>sourceError(`Video playback failed. ${error?.message||''}`.trim()));}previewVideo.style.opacity=String(opacity);previewVideo.volume=clamp(active.volume*active.lane_volume*fadeGain(active,time-active.start),0,1);}
  function syncAudio(time){const activeIds=new Set();timeline.filter(i=>i.media_type==='audio').forEach(item=>{if(time<item.start||time>=item.start+item.duration||!audioLaneAudible(item))return;activeIds.add(item.id);const source=sourceFor(item);if(!source)return;const offset=time-item.start+item.trim_start;let audio=liveAudio.get(item.id);if(!audio){audio=new Audio(source.url);audio.preload='auto';liveAudio.set(item.id,audio);audio.currentTime=Math.max(0,offset);audio.play().catch(()=>{});}audio.volume=clamp(item.volume*item.lane_volume*fadeGain(item,time-item.start),0,1);if(Math.abs(audio.currentTime-offset)>.7)audio.currentTime=Math.max(0,offset);if(audio.paused)audio.play().catch(()=>{});});liveAudio.forEach((audio,id)=>{if(!activeIds.has(id)){audio.pause();liveAudio.delete(id);}});}
  function tick(){if(!playing)return;const time=currentPlayTime(),end=timelineEnd();if(time>=end){stopTimeline(true);return;}updatePlayhead(time);syncVisual(time);syncAudio(time);raf=requestAnimationFrame(tick);}
  function playTimeline(){if(!timeline.length)return;if(playOffset>=timelineEnd())playOffset=0;playing=true;playStart=performance.now();tick();}

  async function saveProject(saveAs=false){setStatus('Saving…','working');try{const response=await fetch(cfg.saveEndpoint,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save',csrf_token:cfg.csrfToken,project_id:saveAs?0:projectId,title:projectTitle.value,timeline,width:Number($('videoProjectWidth').value),height:Number($('videoProjectHeight').value),fps:Number($('videoProjectFps').value)})});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'Could not save project.');projectId=Number(data.project_id||projectId);const u=new URL(location.href);u.searchParams.set('project',String(projectId));history.replaceState(null,'',u.pathname+u.search+u.hash);setStatus(data.message||'Saved.','success');return true;}catch(error){setStatus(error.message||'Could not save project.','error');return false;}}
  async function uploadBlob(blob,title,source='video_editor'){const mime=String(blob.type||'').split(';')[0].toLowerCase(),type=mime.startsWith('image/')?'photo':mime.startsWith('video/')?'video':mime.startsWith('audio/')?'audio':'';if(!type)throw new Error('Unsupported media format.');let mediaDuration=0;if(type==='audio'||type==='video'){mediaDuration=await new Promise(resolve=>{const objectUrl=URL.createObjectURL(blob),probe=document.createElement(type==='video'?'video':'audio');const done=value=>{URL.revokeObjectURL(objectUrl);resolve(Number.isFinite(value)&&value>0?value:0);};probe.preload='metadata';probe.onloadedmetadata=()=>done(probe.duration);probe.onerror=()=>done(0);probe.src=objectUrl;});}const begin=new FormData();begin.append('action','begin');begin.append('csrf_token',cfg.csrfToken);begin.append('media_type',type);begin.append('mime_type',mime);begin.append('title',title);begin.append('source',source);begin.append('original_name',blob.name||title);const beginRes=await fetch(cfg.mediaEndpoint,{method:'POST',credentials:'same-origin',body:begin});const beginData=await beginRes.json();if(!beginRes.ok||!beginData.ok)throw new Error(beginData.error||'Could not start upload.');const chunkSize=Number(beginData.chunk_size||8388608),total=Math.ceil(blob.size/chunkSize);for(let i=0;i<total;i++){const form=new FormData();form.append('action','chunk');form.append('csrf_token',cfg.csrfToken);form.append('token',beginData.token);form.append('index',String(i));form.append('total_chunks',String(total));form.append('chunk',blob.slice(i*chunkSize,Math.min(blob.size,(i+1)*chunkSize),mime),'chunk.bin');const res=await fetch(cfg.mediaEndpoint,{method:'POST',credentials:'same-origin',body:form});const data=await res.json();if(!res.ok||!data.ok)throw new Error(data.error||'Upload failed.');}const finish=new FormData();finish.append('action','finish');finish.append('csrf_token',cfg.csrfToken);finish.append('token',beginData.token);finish.append('duration_seconds',String(mediaDuration));const finishRes=await fetch(cfg.mediaEndpoint,{method:'POST',credentials:'same-origin',body:finish});const finishData=await finishRes.json();if(!finishRes.ok||!finishData.ok)throw new Error(finishData.error||'Could not save media.');return finishData.asset;}

  function updateSelectedFromInspector(){const item=clipById(selectedId);if(!item||item.locked)return;item.start=snapTime(clamp($('videoItemStart').value,0,86400));item.duration=clamp($('videoItemDuration').value,.1,86400);item.trim_start=clamp($('videoItemTrimStart').value,0,86400);item.trim_end=clamp($('videoItemTrimEnd').value,0,86400);if(item.trim_end>item.trim_start)item.duration=clamp(item.trim_end-item.trim_start,.1,86400);item.volume=clamp($('videoItemVolume').value,0,1.5);item.muted=$('videoItemMuted').checked;item.lane=Math.max(0,Math.min(7,Number($('videoItemLane').value||0)));item.opacity=clamp($('videoItemOpacity').value,0,1);item.fade_in=clamp($('videoItemFadeIn').value,0,Math.min(60,item.duration));item.fade_out=clamp($('videoItemFadeOut').value,0,Math.min(60,item.duration));item.locked=$('videoItemLocked').checked;renderTimeline();showSelected();}

  function bindTimelinePointer(){
    let drag=null;
    const onMove=e=>{if(!drag||e.pointerId!==drag.pointerId)return;const item=clipById(drag.id);if(!item)return;const dx=e.clientX-drag.x;if(drag.mode==='move'){item.start=snapTime(Math.max(0,drag.start+dx/pixelsPerSecond));}else if(drag.mode==='right'){const newDuration=clamp(snapTime(drag.duration+dx/pixelsPerSecond),.1,86400);item.duration=newDuration;}else if(drag.mode==='left'){const delta=clamp(snapTime(dx/pixelsPerSecond),-drag.start,drag.duration-.1);item.start=snapTime(drag.start+delta);item.duration=clamp(drag.duration-delta,.1,86400);item.trim_start=Math.max(0,drag.trimStart+delta);}renderTimeline();e.preventDefault();};
    const finish=e=>{if(!drag||e.pointerId!==drag.pointerId)return;drag=null;endGesture('timeline_drag_trim');document.removeEventListener('pointermove',onMove,true);document.removeEventListener('pointerup',finish,true);};
    document.addEventListener('pointerdown',e=>{const clip=e.target.closest('.video-v90-clip');if(!clip)return;const item=clipById(clip.dataset.itemId);if(!item){return;}selectItem(item.id);if(item.locked)return;beginGesture('timeline_drag_trim');const handle=e.target.closest('[data-trim]');drag={pointerId:e.pointerId,id:item.id,x:e.clientX,start:item.start,duration:item.duration,trimStart:item.trim_start,mode:handle?handle.dataset.trim:'move'};document.addEventListener('pointermove',onMove,true);document.addEventListener('pointerup',finish,true);e.preventDefault();},true);
    document.addEventListener('click',e=>{const surface=e.target.closest('.video-v90-lane-surface');if(!surface||e.target.closest('.video-v90-clip'))return;const rect=surface.getBoundingClientRect();seek(snapTime((e.clientX-rect.left)/pixelsPerSecond));},true);
  }

  async function executeCommands(commands,meta={}){const before=editorState();suppressLedger=true;try{for(const c of commands||[]){const type=String(c.type||'');const item=c.clip_id?clipById(c.clip_id):null;switch(type){case'play':playTimeline();break;case'pause':stopTimeline(false);break;case'seek':seek(Number(c.time||0));break;case'split':splitClip(c.clip_id,playOffset);break;case'duplicate':duplicateClip(c.clip_id);break;case'delete':deleteClip(c.clip_id);break;case'move':if(item&&!item.locked){item.start=snapTime(Number(c.start||0));renderTimeline();}break;case'trim':if(item&&!item.locked){item.duration=clamp(c.duration,.1,86400);renderTimeline();}break;case'set_volume':if(item&&!item.locked){item.volume=clamp(c.value,0,1.5);renderTimeline();}break;case'set_mute':if(item&&!item.locked){item.muted=!!c.value;renderTimeline();}break;case'set_opacity':if(item&&!item.locked){item.opacity=clamp(c.value,0,1);renderTimeline();showSelected();}break;case'set_fade':if(item&&!item.locked){if(c.edge==='out')item.fade_out=clamp(c.value,0,60);else item.fade_in=clamp(c.value,0,60);renderTimeline();}break;case'set_lane':if(item&&!item.locked){item.lane=Math.max(0,Math.min(7,Number(c.lane||0)));renderTimeline();}break;case'add_asset':addAsset(Number(c.source_id),Number(c.start||0),Number(c.lane||0));break;case'add_track':addTrack(Number(c.source_id),Number(c.start||0),Number(c.lane||0));break;case'save':await saveProject(false);break;case'zoom':pixelsPerSecond=clamp(pixelsPerSecond*(c.direction==='out'?.8:1.25),8,180);localStorage.setItem('stonefellow:video:zoom',String(pixelsPerSecond));renderTimeline();break;case'snap':snapEnabled=!!c.value;localStorage.setItem('stonefellow:video:snap',snapEnabled?'1':'0');renderTimeline();break;}}}finally{suppressLedger=false;}const after=editorState();await recordLedger(before,after,{source:'agent',action:'agent_plan',request:meta.request||'',provider:meta.provider||'',model:meta.model||'',conversationId:meta.conversationId||0});return {before,after,changes:diffStates(before,after)};}

  injectV90Controls();

  document.querySelectorAll('[data-library-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-library-tab]').forEach(b=>b.classList.toggle('active',b===button));document.querySelectorAll('[data-library-panel]').forEach(panel=>panel.hidden=panel.dataset.libraryPanel!==button.dataset.libraryTab);}));
  document.addEventListener('click',e=>{const assetButton=e.target.closest('[data-add-asset]');if(assetButton){mutate('add_asset',()=>addAsset(Number(assetButton.dataset.addAsset)));return;}const previewCard=e.target.closest('[data-preview-asset]');if(previewCard&&!e.target.closest('button,a,input')){void previewLibraryAsset(Number(previewCard.dataset.previewAsset));return;}const trackButton=e.target.closest('[data-add-track]');if(trackButton){mutate('add_track',()=>addTrack(Number(trackButton.dataset.addTrack)));return;}const item=e.target.closest('[data-item-id]');if(item){selectItem(item.dataset.itemId);return;}const laneRow=e.target.closest('.video-v90-lane');if(laneRow){const type=laneRow.dataset.mediaLane,lane=Number(laneRow.dataset.lane);if(e.target.closest('[data-lane-mute]')){mutate('lane_mute',()=>{const s=laneState(type,lane);setLaneState(type,lane,{lane_muted:!s.muted});renderTimeline();});}else if(e.target.closest('[data-lane-solo]')){mutate('lane_solo',()=>{const s=laneState(type,lane);setLaneState(type,lane,{lane_solo:!s.solo});renderTimeline();});}}});
  document.addEventListener('input',e=>{const vol=e.target.closest('[data-lane-volume]');if(vol){const row=vol.closest('.video-v90-lane');if(!gestureBefore)beginGesture('lane_volume');setLaneState(row.dataset.mediaLane,Number(row.dataset.lane),{lane_volume:clamp(vol.value,0,1.5)});}});
  document.addEventListener('change',e=>{if(e.target.closest('[data-lane-volume]'))endGesture('lane_volume');});
  ['videoItemStart','videoItemDuration','videoItemTrimStart','videoItemTrimEnd','videoItemVolume','videoItemMuted','videoItemLane','videoItemOpacity','videoItemFadeIn','videoItemFadeOut','videoItemLocked'].forEach(id=>{const el=$(id);el?.addEventListener('focus',()=>beginGesture(`inspector_${id}`));el?.addEventListener('pointerdown',()=>beginGesture(`inspector_${id}`));el?.addEventListener('input',updateSelectedFromInspector);el?.addEventListener('change',()=>endGesture(`inspector_${id}`));el?.addEventListener('pointerup',()=>endGesture(`inspector_${id}`));});
  ['videoProjectTitle','videoProjectWidth','videoProjectHeight','videoProjectFps'].forEach(id=>{const el=$(id);el?.addEventListener('focus',()=>beginGesture(`project_${id}`));el?.addEventListener('change',()=>endGesture(`project_${id}`));});
  $('videoRemoveItem')?.addEventListener('click',()=>mutate('delete_clip',()=>deleteClip(selectedId)));
  $('videoTimelinePlay')?.addEventListener('click',playTimeline);$('videoTimelineStop')?.addEventListener('click',()=>stopTimeline(true));$('videoClearTimeline')?.addEventListener('click',()=>{if(confirm('Clear this timeline?'))mutate('clear_timeline',()=>{stopTimeline(true);timeline=[];selectedId='';renderTimeline();});});$('videoSaveProject')?.addEventListener('click',()=>saveProject(false));$('videoSaveAsProject')?.addEventListener('click',()=>saveProject(true));$('videoOpenCamera')?.addEventListener('click',()=>{location.href=cfg.agentChatUrl;});$('videoOpenCameraMenu')?.addEventListener('click',()=>{location.href=cfg.agentChatUrl;});$('videoProjectPicker')?.addEventListener('change',e=>{if(e.target.value){const u=new URL(location.href);u.searchParams.set('project',e.target.value);location.href=u.pathname+u.search;}});
  $('videoSplitClip')?.addEventListener('click',()=>mutate('split_clip',()=>splitClip()));$('videoDuplicateClip')?.addEventListener('click',()=>mutate('duplicate_clip',()=>duplicateClip()));$('videoDeleteClip')?.addEventListener('click',()=>mutate('delete_clip',()=>deleteClip()));$('videoSnapToggle')?.addEventListener('click',()=>mutate('snap',()=>{snapEnabled=!snapEnabled;localStorage.setItem('stonefellow:video:snap',snapEnabled?'1':'0');renderTimeline();}));$('videoZoomIn')?.addEventListener('click',()=>mutate('zoom',()=>{pixelsPerSecond=clamp(pixelsPerSecond*1.25,8,180);localStorage.setItem('stonefellow:video:zoom',String(pixelsPerSecond));renderTimeline();}));$('videoZoomOut')?.addEventListener('click',()=>mutate('zoom',()=>{pixelsPerSecond=clamp(pixelsPerSecond*.8,8,180);localStorage.setItem('stonefellow:video:zoom',String(pixelsPerSecond));renderTimeline();}));
  const handleMediaUpload=async e=>{const selected=[...(e.target.files||[])];if(!selected.length)return;setStatus(`Uploading ${selected.length} file${selected.length===1?'':'s'}…`,'working');try{for(const file of selected){const asset=await uploadBlob(file,file.name,'video_editor_upload');assets.unshift(asset);}renderLibraries();setStatus('Media added to your library.','success');}catch(error){setStatus(error.message||'Upload failed.','error');}e.target.value='';};$('videoMediaUpload')?.addEventListener('change',handleMediaUpload);$('videoMenuMediaUpload')?.addEventListener('change',handleMediaUpload);
  const workspace=document.querySelector('.video-editor-workspace'),menu=$('videoMainMenu'),menuToggle=$('videoMainMenuToggle'),libraryToggle=$('videoLibraryToggle'),inspectorToggle=$('videoInspectorToggle');const setPanel=(kind,visible)=>{if(!workspace)return;workspace.classList.toggle(`${kind}-hidden`,!visible);const b=kind==='library'?libraryToggle:inspectorToggle;b?.setAttribute('aria-expanded',visible?'true':'false');};menuToggle?.addEventListener('click',()=>{const open=menu?.hidden!==false;if(menu)menu.hidden=!open;menuToggle.setAttribute('aria-expanded',open?'true':'false');});libraryToggle?.addEventListener('click',()=>setPanel('library',workspace?.classList.contains('library-hidden')));inspectorToggle?.addEventListener('click',()=>setPanel('inspector',workspace?.classList.contains('inspector-hidden')));$('videoMenuLibraryToggle')?.addEventListener('click',()=>{setPanel('library',true);if(menu)menu.hidden=true;});$('videoMenuInspectorToggle')?.addEventListener('click',()=>{setPanel('inspector',true);if(menu)menu.hidden=true;});document.addEventListener('click',e=>{if(menu&&!menu.hidden&&!menu.contains(e.target)&&e.target!==menuToggle){menu.hidden=true;menuToggle?.setAttribute('aria-expanded','false');}});if(matchMedia('(max-width:1100px)').matches){setPanel('library',false);setPanel('inspector',false);}
  document.addEventListener('keydown',e=>{if((e.target.matches?.('input,textarea,select')||e.target.isContentEditable))return;if(e.code==='Space'){e.preventDefault();playing?stopTimeline(false):playTimeline();}if(e.key.toLowerCase()==='s'&&!e.ctrlKey&&!e.metaKey){if(selectedId)mutate('split_clip',()=>splitClip());}});

  let v90ScrollSync=false;
  const syncTimelineScroll=source=>{if(v90ScrollSync)return;v90ScrollSync=true;const value=source.scrollLeft;if(source!==visualLane)visualLane.scrollLeft=value;if(source!==audioLane)audioLane.scrollLeft=value;updatePlayhead(playing?currentPlayTime():playOffset);v90ScrollSync=false;};
  visualLane?.addEventListener('scroll',()=>syncTimelineScroll(visualLane));audioLane?.addEventListener('scroll',()=>syncTimelineScroll(audioLane));

  bindTimelinePointer();renderLibraries();if(Number(cfg.autoAssetId)>0&&!timeline.some(i=>i.source_kind==='asset'&&Number(i.source_id)===Number(cfg.autoAssetId))){mutate('auto_add_asset',()=>addAsset(Number(cfg.autoAssetId)));}else{const firstVisual=timeline.filter(i=>i.media_type!=='audio').sort((a,b)=>a.start-b.start||a.order-b.order)[0];selectedId=firstVisual?.id||timeline[0]?.id||'';renderTimeline();if(firstVisual)showSelected();else{const firstLibraryVisual=assets.find(a=>a.available!==false&&(a.media_type==='video'||a.media_type==='photo'));if(firstLibraryVisual)void previewLibraryAsset(Number(firstLibraryVisual.id));}if(Array.isArray(cfg.missingAssetIds)&&cfg.missingAssetIds.length)setStatus(`${cfg.missingAssetIds.length} saved project media source${cfg.missingAssetIds.length===1?' is':'s are'} missing. Timeline references were preserved.`,'error');}
  window.StonefellowVideoEditor={getState:()=>({...editorState(),assets:assets.filter(a=>a.available!==false).map(a=>({id:Number(a.id),title:String(a.title||''),media_type:String(a.media_type||'')})),tracks:tracks.map(t=>({id:Number(t.id),title:String(t.title||''),media_type:'audio'}))}),executeCommands,saveProject,previewLibraryAsset,sessionKey,getProjectId:()=>projectId,getPlayhead:()=>playing?currentPlayTime():playOffset,recordLedger,diffStates};
})();
