<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/bootstrap.php';

$user=current_user();
if(!$user || !user_has_role('artist',$user)){http_response_code(403);exit('Artist music access is required.');}
$canManageTracks=has_permission('tracks.manage',$user);
$canManageAlbums=has_permission('albums.manage',$user);
$pdo=db();if(!$pdo){http_response_code(503);exit('Database unavailable.');}
artist_music_v185_ensure_schema($pdo);artist_media_v182_ensure_schema($pdo);
$workspace=artist_workspace_v181_for_user($pdo,$user);$workspaceId=(int)$workspace['id'];
$tab=(string)($_GET['tab']??'tracks');if(!in_array($tab,['tracks','albums'],true))$tab='tracks';
if(($tab==='albums'&&!$canManageAlbums)||($tab==='tracks'&&!$canManageTracks)){http_response_code(403);exit('Artist music access is required.');}

if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!verify_csrf()){flash('error','Session expired. Try again.');redirect(url('/admin/artist-music.php'));}
    $kind=(string)($_POST['kind']??'track');$action=(string)($_POST['action']??'save');$id=(int)($_POST['id']??0);
    $writePermission=$kind==='album'?'albums.manage':'tracks.manage';
    if(!has_permission($writePermission,$user)){http_response_code(403);exit('Artist music access is required.');}
    try{
        music_catalog_write($pdo,$workspaceId,$user,$kind,$action,$_POST,$_FILES);
        flash('notice',$action==='delete'?'Music item removed; Studio history preserved.':'Music item saved.');
    }catch(Throwable $e){flash('error',$e->getMessage());}
    redirect(url('/admin/artist-music.php?tab='.($kind==='album'?'albums':'tracks')));
}

$albums=artist_music_v185_albums($pdo,$workspaceId,true);$tracks=artist_music_v185_tracks($pdo,$workspaceId,true);$photos=artist_media_v182_picker($pdo,$workspaceId,120);
$editId=(int)($_GET['edit']??0);$editing=$editId>0?($tab==='albums'?artist_music_v185_album($pdo,$workspaceId,$editId):artist_music_v185_track($pdo,$workspaceId,$editId)):null;$showForm=isset($_GET['new'])||$editing!==null;
$adminTitle='Music';$adminActive='music';require __DIR__.'/_header.php';
?>
<style>
.music-tabs,.music-actions{display:flex;gap:8px;flex-wrap:wrap}.music-tabs{margin:18px 0}.music-tabs .active{box-shadow:inset 0 0 0 1px rgba(255,255,255,.55)}.music-list{display:grid;gap:12px}.music-row{display:grid;grid-template-columns:72px minmax(0,1fr) auto;gap:14px;align-items:center;padding:12px;border:1px solid rgba(255,255,255,.1);border-radius:12px}.music-cover{width:72px;height:72px;border-radius:8px;object-fit:cover;background:#171717}.music-copy strong{display:block}.music-copy small{color:#999}.music-row-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.music-row-actions form{margin:0}.music-row-actions audio{max-width:290px}.music-picker{display:grid;grid-template-columns:repeat(auto-fill,minmax(110px,1fr));gap:9px;max-height:360px;overflow:auto}.music-photo{display:block;border:1px solid rgba(255,255,255,.12);border-radius:9px;padding:7px;cursor:pointer}.music-photo:has(input:checked){border-color:#fff}.music-photo img{width:100%;aspect-ratio:1/1;object-fit:cover;border-radius:6px;margin:5px 0}@media(max-width:700px){.music-row{grid-template-columns:58px minmax(0,1fr)}.music-cover{width:58px;height:58px}.music-row-actions{grid-column:1/-1}.music-row-actions audio{width:100%;max-width:none}}
</style>
<div class="panel"><div class="content-library-heading"><div><p class="muted">Artist catalog</p><h2>Music Library</h2><p class="muted">Upload songs, organize albums, choose cover art from Media Library and control what appears on your Artist Profile.</p></div><a class="btn" href="<?= e(artist_workspace_v181_profile_url($workspace)) ?>" target="_blank" rel="noopener">View Artist Profile ↗</a></div>
<div class="music-tabs"><?php if($canManageTracks): ?><a class="btn <?= $tab==='tracks'?'active':'' ?>" href="<?= e(url('/admin/artist-music.php?tab=tracks')) ?>">Tracks <?= count($tracks) ?></a><?php endif; ?><?php if($canManageAlbums): ?><a class="btn <?= $tab==='albums'?'active':'' ?>" href="<?= e(url('/admin/artist-music.php?tab=albums')) ?>">Albums <?= count($albums) ?></a><?php endif; ?><?php if(has_permission('photos.manage',$user)): ?><a class="btn" href="<?= e(url('/admin/artist-media.php')) ?>">Media Library</a><?php endif; ?></div>
<div class="content-library-heading"><div><h3><?= $tab==='tracks'?'Tracks':'Albums' ?></h3></div><a class="btn primary" href="<?= e(url('/admin/artist-music.php?tab='.$tab.'&new=1#music-form')) ?>">+ Add <?= $tab==='tracks'?'Track':'Album' ?></a></div><div class="music-list">
<?php if($tab==='tracks'): foreach($tracks as $track): ?><article class="music-row"><img class="music-cover" src="<?= e(url('/artist-music-image.php?type=track&id='.(int)$track['id'])) ?>" alt="" onerror="this.style.visibility='hidden'"><div class="music-copy"><strong><?= e((string)$track['title']) ?></strong><small><?= !empty($track['is_published'])?'Published':'Draft' ?> · <?= e((string)($track['album_title']?:'Single / Unassigned')) ?><?php if((string)$track['genre']!==''): ?> · <?= e((string)$track['genre']) ?><?php endif; ?></small></div><div class="music-row-actions"><audio controls preload="none" src="<?= e(url('/artist-track-audio.php?track='.(int)$track['id'])) ?>"></audio><a class="btn" href="<?= e(url('/admin/artist-music.php?tab=tracks&edit='.(int)$track['id'].'#music-form')) ?>">Edit</a><form method="post" onsubmit="return confirm('Delete this track and its uploaded audio?')"><?= csrf_field() ?><input type="hidden" name="kind" value="track"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int)$track['id'] ?>"><button class="btn danger">Delete</button></form></div></article><?php endforeach; if(!$tracks): ?><p class="muted">No artist tracks yet.</p><?php endif; ?>
<?php else: foreach($albums as $album): ?><article class="music-row"><img class="music-cover" src="<?= e(url('/artist-music-image.php?type=album&id='.(int)$album['id'])) ?>" alt="" onerror="this.style.visibility='hidden'"><div class="music-copy"><strong><?= e((string)$album['title']) ?></strong><small><?= !empty($album['is_published'])?'Published':'Draft' ?> · <?= (int)$album['track_count'] ?> track<?= (int)$album['track_count']===1?'':'s' ?><?php if(!empty($album['release_date'])): ?> · <?= e(date('M j, Y',strtotime((string)$album['release_date']))) ?><?php endif; ?></small></div><div class="music-row-actions"><a class="btn" href="<?= e(url('/admin/artist-music.php?tab=albums&edit='.(int)$album['id'].'#music-form')) ?>">Edit</a><form method="post" onsubmit="return confirm('Delete this album? Its tracks will remain available.')"><?= csrf_field() ?><input type="hidden" name="kind" value="album"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int)$album['id'] ?>"><button class="btn danger">Delete</button></form></div></article><?php endforeach; if(!$albums): ?><p class="muted">No artist albums yet.</p><?php endif; endif; ?></div></div>

<?php if($showForm): $selectedCover=(int)($editing['cover_photo_id']??0); ?>
<div class="panel" id="music-form"><div class="content-form-heading"><div><p class="muted"><?= $editing?'Edit':'New' ?></p><h2><?= $tab==='tracks'?'Track Editor':'Album Editor' ?></h2></div><a class="btn" href="<?= e(url('/admin/artist-music.php?tab='.$tab)) ?>">Close</a></div><form method="post" enctype="multipart/form-data" class="form-grid"><?= csrf_field() ?><input type="hidden" name="kind" value="<?= $tab==='tracks'?'track':'album' ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int)($editing['id']??0) ?>"><?php if($editing): ?><input type="hidden" name="revision" value="<?= e(music_catalog_revision($editing)) ?>"><?php endif; ?><label><span>Title</span><input name="title" required maxlength="190" value="<?= e((string)($editing['title']??'')) ?>"></label>
<?php if($tab==='tracks'): ?><label><span>Album</span><select name="album_id"><option value="0">Single / Unassigned</option><?php foreach($albums as $album): ?><option value="<?= (int)$album['id'] ?>" <?= (int)($editing['album_id']??0)===(int)$album['id']?'selected':'' ?>><?= e((string)$album['title']) ?></option><?php endforeach; ?></select></label><label><span>Track #</span><input type="number" min="0" name="track_number" value="<?= (int)($editing['track_number']??0) ?>"></label><label><span>Duration (seconds)</span><input type="number" min="0" name="duration_seconds" value="<?= (int)($editing['duration_seconds']??0) ?>"></label><label><span>Genre</span><input name="genre" maxlength="120" value="<?= e((string)($editing['genre']??'')) ?>"></label><label class="wide"><span>Description</span><textarea name="description" rows="4"><?= e((string)($editing['description']??'')) ?></textarea></label><label class="wide"><span><?= $editing?'Replace audio':'Audio file' ?></span><input name="audio_file" type="file" accept="audio/mpeg,audio/mp4,audio/wav,audio/ogg,.mp3,.m4a,.wav,.ogg" <?= $editing?'':'required' ?>><small class="muted">MP3, M4A, WAV or OGG. Stored privately and streamed through the Artist Profile.</small></label>
<?php else: ?><label><span>Release date</span><input type="date" name="release_date" value="<?= e((string)($editing['release_date']??'')) ?>"></label><label><span>Sort order</span><input type="number" name="sort_order" value="<?= (int)($editing['sort_order']??0) ?>"></label><label class="wide"><span>Description</span><textarea name="description" rows="4"><?= e((string)($editing['description']??'')) ?></textarea></label><?php endif; ?>
<div class="wide"><strong>Cover image</strong><p class="muted">Choose from your artist Media Library. Leave “No cover” selected for no artwork.</p><div class="music-picker"><label class="music-photo"><input type="radio" name="cover_photo_id" value="0" <?= $selectedCover===0?'checked':'' ?>><span>No cover</span></label><?php foreach($photos as $photo): ?><label class="music-photo"><input type="radio" name="cover_photo_id" value="<?= (int)$photo['id'] ?>" <?= $selectedCover===(int)$photo['id']?'checked':'' ?>><img src="<?= e(url('/content-image.php?type=artist_photo&id='.(int)$photo['id'])) ?>" alt="<?= e((string)($photo['alt_text']??'')) ?>" loading="lazy"><small><?= e((string)$photo['title']) ?></small></label><?php endforeach; ?></div><?php if(!$photos): ?><p class="muted"><a href="<?= e(url('/admin/artist-media.php?new=1')) ?>">Upload cover art to Media Library</a>.</p><?php endif; ?></div><label><span>Visibility</span><select name="visibility"><?php foreach(visibility_options() as $value=>$label): ?><option value="<?= e($value) ?>" <?= (string)($editing['visibility']??'public')===$value?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></label><label><span><input type="checkbox" name="is_published" value="1" <?= !empty($editing['is_published'])?'checked':'' ?>> Publish on Artist Profile</span></label><div class="wide music-actions"><button class="btn primary" type="submit">Save <?= $tab==='tracks'?'Track':'Album' ?></button><a class="btn" href="<?= e(url('/admin/artist-music.php?tab='.$tab)) ?>">Cancel</a></div></form></div>
<?php endif; ?>
<?php require __DIR__.'/_footer.php'; ?>
