<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/bootstrap.php';
$user=current_user();
if(!$user || !user_has_role('artist',$user) || !has_permission('shows.manage',$user)){http_response_code(403);exit('Artist show access is required.');}
$pdo=db();if(!$pdo){http_response_code(503);exit('Database unavailable.');}
artist_shows_v184_ensure_schema($pdo);
$workspace=artist_workspace_v181_for_user($pdo,$user);$workspaceId=(int)$workspace['id'];

if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!verify_csrf()){flash('error','Session expired. Try again.');redirect(url('/admin/artist-shows.php'));}
    $action=(string)($_POST['action']??'save');$id=(int)($_POST['id']??0);$existing=$id>0?artist_shows_v184_show($pdo,$workspaceId,$id):null;
    if($id>0 && !$existing){flash('error','Show not found in your artist workspace.');redirect(url('/admin/artist-shows.php'));}
    try{
        if($action==='delete'){$pdo->prepare('DELETE FROM artist_catalog_shows_v181 WHERE id=? AND workspace_id=?')->execute([$id,$workspaceId]);flash('notice','Show deleted.');redirect(url('/admin/artist-shows.php'));}
        if($action!=='save')throw new RuntimeException('Unknown show action.');
        $eventName=trim((string)($_POST['event_name']??''));$venue=trim((string)($_POST['venue']??''));$city=trim((string)($_POST['city']??''));$region=trim((string)($_POST['region']??''));$notes=trim((string)($_POST['notes']??''));
        $rawDate=trim((string)($_POST['show_date']??''));$timestamp=$rawDate!==''?strtotime($rawDate):false;$showDate=$timestamp===false?'':date('Y-m-d H:i:s',$timestamp);
        $ticket=artist_workspace_v181_validate_external_url((string)($_POST['ticket_url']??''));$status=(string)($_POST['show_status']??'scheduled');$published=isset($_POST['is_published'])?1:0;
        if($showDate==='' || $venue==='')throw new RuntimeException('Date/time and venue are required.');
        if(mb_strlen($eventName)>190 || mb_strlen($venue)>190 || mb_strlen($city)>190 || mb_strlen($region)>190)throw new RuntimeException('One of the show fields is too long.');
        if(!array_key_exists($status,artist_shows_v184_statuses()))throw new RuntimeException('Choose a valid show status.');
        if($id>0){$stmt=$pdo->prepare('UPDATE artist_catalog_shows_v181 SET event_name=?,show_date=?,venue=?,city=?,region=?,notes=?,ticket_url=?,show_status=?,is_published=? WHERE id=? AND workspace_id=?');$stmt->execute([$eventName,$showDate,$venue,$city,$region,$notes,$ticket,$status,$published,$id,$workspaceId]);}
        else{$stmt=$pdo->prepare('INSERT INTO artist_catalog_shows_v181 (workspace_id,event_name,show_date,venue,city,region,notes,ticket_url,show_status,is_published) VALUES (?,?,?,?,?,?,?,?,?,?)');$stmt->execute([$workspaceId,$eventName,$showDate,$venue,$city,$region,$notes,$ticket,$status,$published]);}
        flash('notice',$published?'Show published.':'Show draft saved.');
    }catch(Throwable $e){flash('error',$e->getMessage());}
    redirect(url('/admin/artist-shows.php'));
}

$filter=(string)($_GET['filter']??'upcoming');if(!in_array($filter,['upcoming','past','draft','all'],true))$filter='upcoming';
$editId=(int)($_GET['edit']??0);$editing=$editId>0?artist_shows_v184_show($pdo,$workspaceId,$editId):null;$showForm=isset($_GET['new'])||$editing!==null;
$shows=artist_shows_v184_list($pdo,$workspaceId,$filter,250);$counts=artist_shows_v184_counts($pdo,$workspaceId);
$adminTitle='Shows';$adminActive='shows';require __DIR__.'/_header.php';
?>
<style>
.artist-show-toolbar{display:flex;justify-content:space-between;gap:16px;align-items:center;flex-wrap:wrap}.artist-show-filters{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.artist-show-filters .active{box-shadow:inset 0 0 0 1px rgba(255,255,255,.55)}.artist-show-list{display:grid;gap:12px}.artist-show-row{border:1px solid rgba(255,255,255,.1);border-radius:14px;padding:16px;display:grid;grid-template-columns:150px minmax(0,1fr) auto;gap:18px;align-items:center}.artist-show-date strong,.artist-show-copy strong{display:block}.artist-show-date span,.artist-show-copy p{color:#999;font-size:13px}.artist-show-copy p{margin:6px 0 0}.artist-show-actions{display:flex;gap:8px;flex-wrap:wrap}.artist-show-actions form{margin:0}.artist-show-status{font-size:11px;text-transform:uppercase;letter-spacing:.08em}.artist-show-status.cancelled{color:#e78a7d}.artist-show-status.postponed{color:#d7b56d}@media(max-width:720px){.artist-show-row{grid-template-columns:1fr;gap:10px}.artist-show-actions{justify-content:flex-start}}
</style>
<div class="panel"><div class="artist-show-toolbar"><div><p class="muted">Artist schedule</p><h2>Shows</h2><p class="muted">Manage upcoming dates, past performances, ticket links and public status.</p></div><div class="actions"><a class="btn" href="<?= e(url('/admin/artist.php')) ?>">Artist Workspace</a><a class="btn primary" href="<?= e(url('/admin/artist-shows.php?new=1#show-form')) ?>">+ Add Show</a></div></div>
<div class="artist-show-filters"><a class="btn <?= $filter==='upcoming'?'active':'' ?>" href="<?= e(url('/admin/artist-shows.php?filter=upcoming')) ?>">Upcoming <?= $counts['upcoming'] ?></a><a class="btn <?= $filter==='past'?'active':'' ?>" href="<?= e(url('/admin/artist-shows.php?filter=past')) ?>">Past <?= $counts['past'] ?></a><a class="btn <?= $filter==='draft'?'active':'' ?>" href="<?= e(url('/admin/artist-shows.php?filter=draft')) ?>">Drafts <?= $counts['draft'] ?></a><a class="btn <?= $filter==='all'?'active':'' ?>" href="<?= e(url('/admin/artist-shows.php?filter=all')) ?>">All</a></div>
<div class="artist-show-list"><?php foreach($shows as $show): $when=strtotime((string)$show['show_date']); ?><article class="artist-show-row"><div class="artist-show-date"><strong><?= e(date('M j, Y',$when)) ?></strong><span><?= e(date('g:i A',$when)) ?></span></div><div class="artist-show-copy"><span class="artist-show-status <?= e((string)$show['show_status']) ?>"><?= e(artist_shows_v184_statuses()[$show['show_status']]??(string)$show['show_status']) ?> · <?= !empty($show['is_published'])?'Published':'Draft' ?></span><strong><?= e(trim((string)$show['event_name'])!==''?(string)$show['event_name']:(string)$show['venue']) ?></strong><?php if(trim((string)$show['event_name'])!==''): ?><p><?= e((string)$show['venue']) ?></p><?php endif; ?><p><?= e(trim((string)$show['city'].((string)$show['region']!==''?', '.(string)$show['region']:''))) ?></p></div><div class="artist-show-actions"><?php if(!empty($show['ticket_url'])): ?><a class="btn" href="<?= e((string)$show['ticket_url']) ?>" target="_blank" rel="noopener noreferrer">Tickets ↗</a><?php endif; ?><a class="btn" href="<?= e(url('/admin/artist-shows.php?edit='.(int)$show['id'].'#show-form')) ?>">Edit</a><form method="post" onsubmit="return confirm('Delete this show?')"><?= csrf_field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int)$show['id'] ?>"><button class="btn danger" type="submit">Delete</button></form></div></article><?php endforeach; ?><?php if(!$shows): ?><p class="muted">No <?= e($filter) ?> shows.</p><?php endif; ?></div></div>
<?php if($showForm): ?>
<div class="panel" id="show-form"><div class="content-library-heading"><div><p class="muted"><?= $editing?'Edit show':'New show' ?></p><h2><?= $editing?'Show Details':'Add Show' ?></h2></div><a class="btn" href="<?= e(url('/admin/artist-shows.php')) ?>">Close</a></div><form method="post" class="form-grid"><?= csrf_field() ?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int)($editing['id']??0) ?>">
<label><span>Event name <small class="muted">optional</small></span><input name="event_name" maxlength="190" value="<?= e((string)($editing['event_name']??'')) ?>" placeholder="Tour or event name"></label><label><span>Date & time</span><input name="show_date" type="datetime-local" required value="<?= !empty($editing['show_date'])?e(date('Y-m-d\TH:i',strtotime((string)$editing['show_date']))):'' ?>"></label><label><span>Venue</span><input name="venue" maxlength="190" required value="<?= e((string)($editing['venue']??'')) ?>"></label><label><span>City</span><input name="city" maxlength="190" value="<?= e((string)($editing['city']??'')) ?>"></label><label><span>State / region</span><input name="region" maxlength="190" value="<?= e((string)($editing['region']??'')) ?>"></label><label><span>Status</span><select name="show_status"><?php foreach(artist_shows_v184_statuses() as $value=>$label): ?><option value="<?= e($value) ?>" <?= (string)($editing['show_status']??'scheduled')===$value?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></label><label class="wide"><span>Ticket URL</span><input name="ticket_url" type="url" inputmode="url" value="<?= e((string)($editing['ticket_url']??'')) ?>" placeholder="https://"></label><label class="wide"><span>Notes</span><textarea name="notes" rows="5"><?= e((string)($editing['notes']??'')) ?></textarea></label><label class="wide"><span><input type="checkbox" name="is_published" value="1" <?= !empty($editing['is_published'])?'checked':'' ?>> Publish on Artist Profile</span></label><div class="wide actions"><button class="btn primary" type="submit"><?= $editing?'Save Show':'Add Show' ?></button><a class="btn" href="<?= e(url('/admin/artist-shows.php')) ?>">Cancel</a></div></form></div>
<?php endif; ?>
<?php require __DIR__.'/_footer.php'; ?>
