<?php
declare(strict_types=1);
/** VP3 Phase 17.11 — Goal Planning & Adaptive Strategy.
 * Advisory milestones sit above Phase 17.10. They never execute, approve,
 * schedule, lease, retry, receipt, or complete work. Execution remains fresh
 * Phase 17.5 objectives; achievement is derived from Phase 17.6 verification.
 */
const VP3_AGENT_GOAL_PLANNING_V1711='agent-goal-planning-v1711-20260915';
const VP3_AGENT_GOAL_MILESTONE_LIMIT_V1711=16;
require_once __DIR__.'/agent-goal-strategy-v1710.php';

function agent_goal_planning_schema_ready_v1711(?PDO $pdo=null): bool{
    $pdo??=db();return (bool)($pdo&&agent_goal_strategy_schema_ready_v1710($pdo)&&table_exists('agent_goal_milestones')&&column_exists('agent_goal_milestones','owner_user_id')&&column_exists('agent_goal_milestones','goal_id')&&column_exists('agent_goal_milestones','objective_run_id')&&column_exists('agent_goal_milestones','sequence_no'));
}
function agent_goal_planning_ensure_schema_v1711(?PDO $pdo=null): void{
    $pdo??=db();if(!$pdo)throw new RuntimeException('Database connection is unavailable.');agent_goal_strategy_ensure_schema_v1710($pdo);
    $pdo->exec("CREATE TABLE IF NOT EXISTS agent_goal_milestones (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, owner_user_id BIGINT UNSIGNED NOT NULL, goal_id BIGINT UNSIGNED NOT NULL,
      sequence_no INT UNSIGNED NOT NULL DEFAULT 1, title VARCHAR(240) NOT NULL DEFAULT '', success_signal VARCHAR(900) NOT NULL DEFAULT '',
      target_date DATE NULL, objective_run_id BIGINT UNSIGNED NULL, status VARCHAR(24) NOT NULL DEFAULT 'planned',
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, retired_at DATETIME NULL,
      PRIMARY KEY (id), KEY idx_agent_goal_milestones_goal (owner_user_id,goal_id,status,sequence_no,id), KEY idx_agent_goal_milestones_objective (owner_user_id,objective_run_id,id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
}
function agent_goal_planning_require_v1711(PDO $pdo,array $user): int{
    $uid=agent_goal_strategy_require_v1710($pdo,$user);if(!agent_goal_planning_schema_ready_v1711($pdo))throw new RuntimeException('Goal planning is not ready yet. Run the normal VP3 database upgrade first.');return $uid;
}
function agent_goal_milestone_row_v1711(PDO $pdo,int $uid,int $goalId,int $id): array{
    $s=$pdo->prepare('SELECT * FROM agent_goal_milestones WHERE id=? AND owner_user_id=? AND goal_id=? LIMIT 1');$s->execute([$id,$uid,$goalId]);$r=$s->fetch();if(!is_array($r))throw new RuntimeException('Goal milestone not found.');return $r;
}
function agent_goal_milestones_v1711(PDO $pdo,int $uid,int $goalId,bool $retired=false): array{
    $sql="SELECT m.*,r.title objective_title,r.goal objective_goal,r.status objective_status,r.objective_verification_status FROM agent_goal_milestones m LEFT JOIN agent_workflow_runs r ON r.id=m.objective_run_id AND r.owner_user_id=m.owner_user_id AND r.source_kind='objective_plan' WHERE m.owner_user_id=? AND m.goal_id=?".($retired?'':" AND m.status<>'retired'")." ORDER BY m.sequence_no,m.id LIMIT ".VP3_AGENT_GOAL_MILESTONE_LIMIT_V1711;$s=$pdo->prepare($sql);$s->execute([$uid,$goalId]);return $s->fetchAll()?:[];
}
function agent_goal_milestone_state_v1711(array $r): string{
    if((string)($r['status']??'')==='retired')return 'retired';if((int)($r['objective_run_id']??0)<1)return 'advisory';$v=(string)($r['objective_verification_status']??'');$s=(string)($r['objective_status']??'');
    if($v==='achieved')return 'achieved';if($v==='needs_remediation'||in_array($s,['failed','cancelled'],true))return 'blocked';if($s==='approval_pending')return 'waiting_approval';if($s==='paused')return 'paused';return 'active';
}
function agent_goal_plan_state_v1711(PDO $pdo,array $user,int $goalId): array{
    $uid=agent_goal_planning_require_v1711($pdo,$user);$base=agent_goal_state_v1710($pdo,$user,$goalId);$g=(array)$base['goal'];$rows=agent_goal_milestones_v1711($pdo,$uid,$goalId);$today=strtotime(gmdate('Y-m-d').' 00:00:00 UTC')?:time();$target=trim((string)($g['target_date']??''));$targetTs=$target!==''?(strtotime($target.' 00:00:00 UTC')?:0):0;$remaining=0;$milestones=[];$mapped=[];
    foreach($rows as $r){$state=agent_goal_milestone_state_v1711($r);if(!in_array($state,['achieved','retired'],true))$remaining++;if((int)($r['objective_run_id']??0)>0)$mapped[(int)$r['objective_run_id']]=true;$milestones[]=['id'=>(int)$r['id'],'sequence_no'=>(int)$r['sequence_no'],'title'=>(string)$r['title'],'success_signal'=>(string)$r['success_signal'],'target_date'=>(string)($r['target_date']??''),'objective_run_id'=>(int)($r['objective_run_id']??0),'state'=>$state,'projected_date'=>''];}
    if($targetTs>$today&&$remaining){$span=max(86400,$targetTs-$today);$n=0;foreach($milestones as &$m){if(in_array($m['state'],['achieved','retired'],true))continue;$n++;$m['projected_date']=$m['target_date']!==''?$m['target_date']:gmdate('Y-m-d',(int)round($today+$span*($n/$remaining)));}unset($m);}
    $next=null;foreach($milestones as $m)if(!in_array($m['state'],['achieved','retired'],true)){$next=$m;break;}$health='moving';$reason='The plan has an actionable next milestone.';$stalled=false;
    if((string)($g['status']??'')==='paused'){$health='paused';$reason='The goal is paused, so planning changes are intentionally on hold.';}elseif((string)($g['derived_status']??'')==='achieved'){$health='achieved';$reason='Every linked objective has a verified achieved outcome.';}elseif(!$milestones){$health='plan_missing';$reason='No roadmap milestones exist yet.';$stalled=true;}elseif(!$next){$health='review_needed';$reason='All roadmap milestones are resolved, but the goal itself is not verified achieved.';$stalled=true;}elseif($next['state']==='advisory'){$health='awaiting_objective';$reason='The next roadmap milestone is advisory and has not been converted into an executable objective.';$stalled=true;}elseif(in_array($next['state'],['blocked','paused'],true)){$health='blocked';$reason='The next roadmap milestone is blocked by its linked objective state.';$stalled=true;}elseif($next['state']==='waiting_approval'){$health='waiting_approval';$reason='The next roadmap milestone is waiting on the canonical objective approval path.';}
    $deadline=(array)($base['strategy']['deadline']??[]);if(!empty($deadline['at_risk'])&&$health!=='achieved')$reason.=' Deadline risk: '.(string)($deadline['reason']??'');$unmapped=[];foreach((array)$base['objectives'] as $o)if(!isset($mapped[(int)$o['id']]))$unmapped[]=$o;
    return ['build'=>VP3_AGENT_GOAL_PLANNING_V1711,'goal'=>$g,'base'=>$base,'plan'=>['milestones'=>$milestones,'next_milestone'=>$next,'remaining_count'=>$remaining,'health'=>['status'=>$health,'stalled'=>$stalled,'reason'=>$reason],'unmapped_objectives'=>array_slice($unmapped,0,8)]];
}
function agent_goal_plan_next_sequence_v1711(PDO $pdo,int $uid,int $goalId): int{$s=$pdo->prepare("SELECT COALESCE(MAX(sequence_no),0) FROM agent_goal_milestones WHERE owner_user_id=? AND goal_id=? AND status<>'retired'");$s->execute([$uid,$goalId]);return max(1,(int)$s->fetchColumn()+1);}
function agent_goal_plan_add_milestone_v1711(PDO $pdo,array $user,int $goalId,string $title): array{
    $uid=agent_goal_planning_require_v1711($pdo,$user);$g=agent_goal_row_v1710($pdo,$uid,$goalId);agent_goal_require_active_v1710($g);$title=agent_goal_text_v1710($title,240);if($title==='')throw new RuntimeException('A milestone title is required.');$seq=agent_goal_plan_next_sequence_v1711($pdo,$uid,$goalId);$s=$pdo->prepare('INSERT INTO agent_goal_milestones (owner_user_id,goal_id,sequence_no,title,success_signal,status) VALUES (?,?,?,?,?,?)');$s->execute([$uid,$goalId,$seq,$title,'Convert this advisory milestone into a fresh objective and verify its outcome before considering the milestone achieved.','planned']);agent_goal_event_v1710($pdo,$uid,$goalId,'milestone_created','Goal roadmap milestone created.',['milestone_id'=>(int)$pdo->lastInsertId(),'sequence_no'=>$seq]);return agent_goal_plan_state_v1711($pdo,$user,$goalId);
}
function agent_goal_plan_seed_v1711(PDO $pdo,array $user,int $goalId): array{
    $uid=agent_goal_planning_require_v1711($pdo,$user);$g=agent_goal_row_v1710($pdo,$uid,$goalId);agent_goal_require_active_v1710($g);if(agent_goal_milestones_v1711($pdo,$uid,$goalId))return agent_goal_plan_state_v1711($pdo,$user,$goalId);$base=agent_goal_state_v1710($pdo,$user,$goalId);$items=[];
    foreach((array)$base['objectives'] as $o)$items[]=['title'=>agent_goal_text_v1710($o['goal']??$o['title']??'',240),'objective'=>(int)$o['id']];if(!$items)foreach(agent_objective_heuristic_stages_v175((string)$g['goal']) as $stage){$step=is_array($stage[0]??null)?$stage[0]:[];$t=agent_goal_text_v1710($step['title']??'',240);if($t!=='')$items[]=['title'=>$t,'objective'=>0];}
    $pdo->beginTransaction();try{$s=$pdo->prepare('INSERT INTO agent_goal_milestones (owner_user_id,goal_id,sequence_no,title,success_signal,objective_run_id,status) VALUES (?,?,?,?,?,?,?)');$i=0;foreach(array_slice($items,0,VP3_AGENT_GOAL_MILESTONE_LIMIT_V1711) as $item){$i++;$oid=(int)$item['objective'];$signal=$oid>0?'Phase 17.6 verifies objective #'.$oid.' as achieved.':'Convert this advisory milestone into a fresh objective and verify its outcome before considering the milestone achieved.';$s->execute([$uid,$goalId,$i,(string)$item['title'],$signal,$oid?:null,'planned']);}agent_goal_event_v1710($pdo,$uid,$goalId,'plan_generated','Goal roadmap generated as advisory planning metadata.',['milestone_count'=>$i,'source'=>$base['objectives']?'linked_objectives':'heuristic_advisory']);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}return agent_goal_plan_state_v1711($pdo,$user,$goalId);
}
function agent_goal_plan_link_objective_v1711(PDO $pdo,array $user,int $goalId,int $milestoneId,int $objectiveId): array{
    $uid=agent_goal_planning_require_v1711($pdo,$user);$g=agent_goal_row_v1710($pdo,$uid,$goalId);agent_goal_require_active_v1710($g);$m=agent_goal_milestone_row_v1711($pdo,$uid,$goalId,$milestoneId);if((string)$m['status']==='retired')throw new RuntimeException('Retired milestones are immutable history.');agent_goal_objective_row_v1710($pdo,$uid,$objectiveId);$s=$pdo->prepare('SELECT 1 FROM agent_goal_objectives WHERE owner_user_id=? AND goal_id=? AND objective_run_id=? LIMIT 1');$s->execute([$uid,$goalId,$objectiveId]);if(!$s->fetchColumn())throw new RuntimeException('Attach that objective to the goal before linking it to a milestone.');$pdo->prepare('UPDATE agent_goal_milestones SET objective_run_id=? WHERE id=? AND owner_user_id=? AND goal_id=?')->execute([$objectiveId,$milestoneId,$uid,$goalId]);agent_goal_event_v1710($pdo,$uid,$goalId,'milestone_objective_linked','Milestone linked to an existing goal objective.',['milestone_id'=>$milestoneId,'objective_run_id'=>$objectiveId]);return agent_goal_plan_state_v1711($pdo,$user,$goalId);
}
function agent_goal_plan_create_objective_v1711(PDO $pdo,array $user,int $goalId,int $milestoneId,int $conversationId=0): array{
    $uid=agent_goal_planning_require_v1711($pdo,$user);$g=agent_goal_row_v1710($pdo,$uid,$goalId);agent_goal_require_active_v1710($g);$m=agent_goal_milestone_row_v1711($pdo,$uid,$goalId,$milestoneId);if((string)($m['status']??'')==='retired')throw new RuntimeException('Retired milestones are immutable history.');if((int)($m['objective_run_id']??0)>0)throw new RuntimeException('This milestone already has a linked objective.');$text=agent_goal_text_v1710($m['title']??'',900);$created=agent_objective_create_v175($pdo,$user,$text,agent_objective_heuristic_stages_v175($text),$conversationId,null);$oid=(int)($created['objective']['id']??0);if($oid<1)throw new RuntimeException('The objective could not be created.');agent_goal_link_objective_v1710($pdo,$user,$goalId,$oid,100);$pdo->prepare('UPDATE agent_goal_milestones SET objective_run_id=? WHERE id=? AND owner_user_id=? AND goal_id=?')->execute([$oid,$milestoneId,$uid,$goalId]);agent_goal_event_v1710($pdo,$uid,$goalId,'milestone_objective_created','A fresh canonical objective was explicitly created for a roadmap milestone.',['milestone_id'=>$milestoneId,'objective_run_id'=>$oid]);return agent_goal_plan_state_v1711($pdo,$user,$goalId);
}
function agent_goal_plan_resequence_v1711(PDO $pdo,array $user,int $goalId,int $milestoneId,int $position): array{
    $uid=agent_goal_planning_require_v1711($pdo,$user);$g=agent_goal_row_v1710($pdo,$uid,$goalId);agent_goal_require_active_v1710($g);agent_goal_milestone_row_v1711($pdo,$uid,$goalId,$milestoneId);$ids=[];foreach(agent_goal_milestones_v1711($pdo,$uid,$goalId) as $r)if((int)$r['id']!==$milestoneId)$ids[]=(int)$r['id'];$position=max(1,min(count($ids)+1,$position));array_splice($ids,$position-1,0,[$milestoneId]);$pdo->beginTransaction();try{$s=$pdo->prepare('UPDATE agent_goal_milestones SET sequence_no=? WHERE id=? AND owner_user_id=? AND goal_id=?');foreach($ids as $i=>$id)$s->execute([$i+1,$id,$uid,$goalId]);agent_goal_event_v1710($pdo,$uid,$goalId,'plan_resequenced','Goal roadmap order changed without changing objective execution.',['milestone_id'=>$milestoneId,'position'=>$position]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}return agent_goal_plan_state_v1711($pdo,$user,$goalId);
}
function agent_goal_plan_retire_milestone_v1711(PDO $pdo,array $user,int $goalId,int $milestoneId): array{
    $uid=agent_goal_planning_require_v1711($pdo,$user);$g=agent_goal_row_v1710($pdo,$uid,$goalId);agent_goal_require_active_v1710($g);$m=agent_goal_milestone_row_v1711($pdo,$uid,$goalId,$milestoneId);$pdo->prepare("UPDATE agent_goal_milestones SET status='retired',retired_at=? WHERE id=? AND owner_user_id=? AND goal_id=?")->execute([gmdate('Y-m-d H:i:s'),$milestoneId,$uid,$goalId]);agent_goal_event_v1710($pdo,$uid,$goalId,'milestone_retired','Goal roadmap milestone retired. Linked objective execution, approvals, and receipts were not changed.',['milestone_id'=>$milestoneId,'objective_run_id'=>(int)($m['objective_run_id']??0)]);return agent_goal_plan_state_v1711($pdo,$user,$goalId);
}
function agent_goal_plan_suggested_strategy_v1711(array $state): string{
    $g=(array)($state['goal']??[]);$p=(array)($state['plan']??[]);$h=(array)($p['health']??[]);$n=is_array($p['next_milestone']??null)?$p['next_milestone']:null;$s=(array)($state['base']['strategy']??[]);$parts=['Advance goal #'.(int)($g['id']??0).' through the roadmap in sequence while preserving verified completed work.'];if($n)$parts[]='Focus next on milestone #'.(int)$n['id'].' “'.agent_goal_text_v1710($n['title']??'',180).'”.';if(($h['status']??'')==='awaiting_objective')$parts[]='Convert the next advisory milestone into a fresh Phase 17.5 objective before execution.';elseif(($h['status']??'')==='blocked')$parts[]='Repair or explicitly replace the blocked linked objective before advancing dependent work.';elseif(($h['status']??'')==='waiting_approval')$parts[]='Resolve the existing objective approval through the canonical approval path; do not bypass it.';if((array)($s['blockers']??[]))$parts[]='Treat current objective blockers as strategy evidence and re-rank after they change.';if((array)($s['learned_outcomes']??[]))$parts[]='Use similar verified outcome history as evidence when choosing between remaining objectives.';if(!empty($s['deadline']['at_risk']))$parts[]='Deadline risk is active; prefer highest-contribution unblocked work and reduce nonessential scope rather than weakening verification.';return agent_goal_text_v1710(implode(' ',$parts),1500);
}
function agent_goal_plan_revise_strategy_v1711(PDO $pdo,array $user,int $goalId): array{
    $uid=agent_goal_planning_require_v1711($pdo,$user);$g=agent_goal_row_v1710($pdo,$uid,$goalId);agent_goal_require_active_v1710($g);$state=agent_goal_plan_state_v1711($pdo,$user,$goalId);$new=agent_goal_plan_suggested_strategy_v1711($state);$old=(string)$g['strategy_summary'];if($new!==$old){agent_goal_update_v1710($pdo,$user,$goalId,['strategy_summary'=>$new]);agent_goal_event_v1710($pdo,$uid,$goalId,'adaptive_strategy_revised','Goal strategy explicitly revised from current roadmap evidence.',['previous_strategy'=>$old,'new_strategy'=>$new,'plan_health'=>(string)($state['plan']['health']['status']??'')]);}return agent_goal_plan_state_v1711($pdo,$user,$goalId);
}
function agent_goal_plan_answer_v1711(array $state): string{
    $g=(array)$state['goal'];$p=(array)$state['plan'];$h=(array)$p['health'];$ms=(array)$p['milestones'];$a='Goal #'.(int)$g['id'].' roadmap · '.count($ms).' milestone'.(count($ms)===1?'':'s').' · plan health '.str_replace('_',' ',(string)$h['status']).'. '.(string)$h['reason'];if(!$ms)return $a.' Say “build plan for goal #'.(int)$g['id'].'” to create an advisory roadmap.';$lines=[];foreach(array_slice($ms,0,8) as $m){$x=(int)$m['sequence_no'].'. Milestone #'.(int)$m['id'].' · '.str_replace('_',' ',(string)$m['state']).' · '.agent_goal_text_v1710($m['title']??'',180);if((int)$m['objective_run_id']>0)$x.=' · objective #'.(int)$m['objective_run_id'];if((string)$m['projected_date']!=='')$x.=' · projected '.(string)$m['projected_date'];$lines[]=$x;}$a.="\n".implode("\n",$lines);if((array)$p['unmapped_objectives'])$a.="\n".count($p['unmapped_objectives']).' linked objective'.(count($p['unmapped_objectives'])===1?' is':'s are').' not yet represented by a roadmap milestone.';if(!empty($h['stalled']))$a.="\nSuggested strategy: ".agent_goal_plan_suggested_strategy_v1711($state);return $a;
}
function agent_goal_plan_chat_v1711(string $query,array $user,int $conversationId=0): array{
    $empty=agent_objective_empty_tool_v175();$q=trim($query);if($q===''||!preg_match('/\b(?:goal\s+(?:plan|roadmap)|goal\s*#?\s*\d+\s+(?:plan|roadmap)|plan\s+(?:for\s+)?goal|roadmap\s+(?:for\s+)?goal|milestone|stalled|adaptive\s+strategy|revise\s+strategy)\b/i',$q))return $empty;if(!preg_match('/\bgoal\s*#?\s*(\d+)\b/i',$q,$gm))return $empty;$goalId=(int)$gm[1];$pdo=db();if(!$pdo)return $empty;
    try{$tool='goal.plan.inspect';if(preg_match('/\b(?:build|create|generate|make)\s+(?:a\s+)?(?:plan|roadmap)\s+(?:for\s+)?goal\s*#?\s*\d+/i',$q)||preg_match('/^\s*plan\s+goal\s*#?\s*\d+\s*$/i',$q)){$state=agent_goal_plan_seed_v1711($pdo,$user,$goalId);$tool='goal.plan.build';}
      elseif(preg_match('/\badd\s+milestone\s+(.+?)\s+(?:to|for)\s+goal\s*#?\s*\d+\s*$/i',$q,$m)){$state=agent_goal_plan_add_milestone_v1711($pdo,$user,$goalId,(string)$m[1]);$tool='goal.plan.milestone.add';}
      elseif(preg_match('/\blink\s+objective\s*#?\s*(\d+)\s+(?:to\s+)?milestone\s*#?\s*(\d+)/i',$q,$m)){$state=agent_goal_plan_link_objective_v1711($pdo,$user,$goalId,(int)$m[2],(int)$m[1]);$tool='goal.plan.milestone.link';}
      elseif(preg_match('/\bcreate\s+(?:a\s+)?(?:new\s+)?objective\s+(?:for\s+)?milestone\s*#?\s*(\d+)/i',$q,$m)){$state=agent_goal_plan_create_objective_v1711($pdo,$user,$goalId,(int)$m[1],$conversationId);$tool='goal.plan.milestone.objective.create';}
      elseif(preg_match('/\b(?:move|reorder)\s+milestone\s*#?\s*(\d+)\s+(?:to\s+)?(?:position\s+)?(\d+)/i',$q,$m)){$state=agent_goal_plan_resequence_v1711($pdo,$user,$goalId,(int)$m[1],(int)$m[2]);$tool='goal.plan.resequence';}
      elseif(preg_match('/\b(?:retire|remove)\s+milestone\s*#?\s*(\d+)/i',$q,$m)){$state=agent_goal_plan_retire_milestone_v1711($pdo,$user,$goalId,(int)$m[1]);$tool='goal.plan.milestone.retire';}
      elseif(preg_match('/\b(?:revise|update|adapt)\s+(?:the\s+)?strategy\b/i',$q)){$state=agent_goal_plan_revise_strategy_v1711($pdo,$user,$goalId);$tool='goal.plan.strategy.revise';}
      else{$state=agent_goal_plan_state_v1711($pdo,$user,$goalId);if(preg_match('/\bstalled\b/i',$q))$tool='goal.plan.health';}
      $out=$empty;$out['handled']=true;$out['answer']=agent_goal_plan_answer_v1711($state);if(function_exists('agent_tool_log'))agent_tool_log($user,$tool,$query,'success',['goal_id'=>$goalId,'build'=>VP3_AGENT_GOAL_PLANNING_V1711],$conversationId);return $out;
    }catch(Throwable $e){$out=$empty;$out['handled']=true;$out['answer']='I could not use the goal planning layer: '.$e->getMessage();if(function_exists('agent_tool_log'))agent_tool_log($user,'goal.plan',$query,'error',['error'=>get_class($e)],$conversationId);return $out;}
}
