<?php
declare(strict_types=1);

function agent_commerce_oauth_state_v800(array $user,string $provider): string
{
    $provider=strtolower(trim($provider));if(!in_array($provider,['stripe','square'],true))throw new RuntimeException('That provider does not use this connection flow.');$token=bin2hex(random_bytes(24));$_SESSION['vp3_commerce_oauth'][$token]=['user_id'=>(int)$user['id'],'provider'=>$provider,'expires_at'=>time()+900];return $token;
}
function agent_commerce_oauth_state_take_v800(array $user,string $state): array
{
    $row=$_SESSION['vp3_commerce_oauth'][$state]??null;unset($_SESSION['vp3_commerce_oauth'][$state]);if(!is_array($row)||(int)($row['user_id']??0)!==(int)$user['id']||(int)($row['expires_at']??0)<time())throw new RuntimeException('Payment provider connection session expired. Please try again.');return $row;
}
function agent_commerce_oauth_callback_v800(): string
{
    return agent_commerce_absolute_url_v800('/commerce-provider-oauth.php');
}
function agent_commerce_oauth_url_v800(array $user,string $provider): string
{
    $provider=strtolower(trim($provider));if(!agent_commerce_provider_ready_v800($provider))throw new RuntimeException(agent_commerce_provider_label_v800($provider).' is not configured for VP3 Commerce.');$cfg=agent_commerce_config_v800();$state=agent_commerce_oauth_state_v800($user,$provider);$redirect=agent_commerce_oauth_callback_v800();if($provider==='stripe')return 'https://connect.stripe.com/oauth/authorize?'.http_build_query(['response_type'=>'code','client_id'=>$cfg['stripe']['connect_client_id'],'scope'=>'read_write','redirect_uri'=>$redirect,'state'=>$state],'','&',PHP_QUERY_RFC3986);$base=$cfg['square']['environment']==='production'?'https://connect.squareup.com':'https://connect.squareupsandbox.com';return $base.'/oauth2/authorize?'.http_build_query(['client_id'=>$cfg['square']['application_id'],'scope'=>'MERCHANT_PROFILE_READ PAYMENTS_READ PAYMENTS_WRITE ORDERS_READ ORDERS_WRITE PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS','session'=>'false','redirect_uri'=>$redirect,'state'=>$state],'','&',PHP_QUERY_RFC3986);
}
function agent_commerce_square_base_v800(): string
{
    return agent_commerce_config_v800()['square']['environment']==='production'?'https://connect.squareup.com':'https://connect.squareupsandbox.com';
}
function agent_commerce_capabilities_v800(array $connection): array
{
    $decoded=json_decode((string)($connection['capabilities_json']??''),true);return is_array($decoded)?$decoded:[];
}
function agent_commerce_square_profile_v800(string $accessToken): array
{
    $resp=agent_commerce_http_v800('GET',agent_commerce_square_base_v800().'/v2/merchants',['Authorization: Bearer '.$accessToken,'Square-Version: 2026-08-19'])['json'];$merchants=$resp['merchant']??$resp['merchants']??[];$merchant=is_array($merchants)&&isset($merchants[0])&&is_array($merchants[0])?$merchants[0]:[];$merchantId=trim((string)($merchant['id']??''));$locationId=trim((string)($merchant['main_location_id']??''));if($merchantId===''||$locationId==='')throw new RuntimeException('Square merchant or main location could not be verified.');return ['merchant_id'=>$merchantId,'location_id'=>$locationId,'business_name'=>trim((string)($merchant['business_name']??'')),'currency'=>strtolower(trim((string)($merchant['currency']??'')))];
}
function agent_commerce_oauth_exchange_v800(PDO $pdo,array $user,string $provider,string $code): array
{
    $cfg=agent_commerce_config_v800();$redirect=agent_commerce_oauth_callback_v800();$provider=strtolower(trim($provider));$code=trim($code);if($code==='')throw new RuntimeException('Payment provider authorization code is missing.');if($provider==='stripe'){$resp=agent_commerce_http_v800('POST','https://connect.stripe.com/oauth/token',[],['client_secret'=>$cfg['stripe']['secret_key'],'code'=>$code,'grant_type'=>'authorization_code'],true)['json'];$external=trim((string)($resp['stripe_user_id']??''));if($external==='')throw new RuntimeException('Stripe did not return a connected account ID.');return agent_commerce_store_connection_v800($pdo,(int)$user['id'],'stripe',$external,['access_token'=>(string)($resp['access_token']??''),'refresh_token'=>(string)($resp['refresh_token']??''),'account_label'=>'Stripe '.$external,'capabilities'=>['checkout'=>true,'refunds'=>true]]);}if($provider==='square'){$resp=agent_commerce_http_v800('POST',agent_commerce_square_base_v800().'/oauth2/token',['Square-Version: 2026-08-19'],['client_id'=>$cfg['square']['application_id'],'client_secret'=>$cfg['square']['client_secret'],'code'=>$code,'grant_type'=>'authorization_code','redirect_uri'=>$redirect])['json'];$access=trim((string)($resp['access_token']??''));if($access==='')throw new RuntimeException('Square did not return an access token.');$profile=agent_commerce_square_profile_v800($access);$external=trim((string)($resp['merchant_id']??$profile['merchant_id']));if($external===''||!hash_equals((string)$profile['merchant_id'],$external))throw new RuntimeException('Square merchant identity could not be verified.');$expires=null;if(!empty($resp['expires_at'])){try{$expires=(new DateTimeImmutable((string)$resp['expires_at']))->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');}catch(Throwable $e){}}return agent_commerce_store_connection_v800($pdo,(int)$user['id'],'square',$external,['access_token'=>$access,'refresh_token'=>(string)($resp['refresh_token']??''),'token_expires_at'=>$expires,'account_label'=>(string)($profile['business_name']?:'Square '.$external),'capabilities'=>['checkout'=>true,'refunds'=>true,'location_id'=>$profile['location_id'],'currency'=>$profile['currency']]]);}throw new RuntimeException('Unsupported payment provider connection flow.');
}
function agent_commerce_square_access_token_v800(PDO $pdo,array $connection): string
{
    $token=agent_commerce_decrypt_v800((string)($connection['access_token_ciphertext']??''));if($token==='')throw new RuntimeException('Square connection token is unavailable.');$expires=(string)($connection['token_expires_at']??'');if($expires===''||strtotime($expires)>time()+300)return $token;$refresh=agent_commerce_decrypt_v800((string)($connection['refresh_token_ciphertext']??''));if($refresh==='')throw new RuntimeException('Square connection needs to be reconnected.');$cfg=agent_commerce_config_v800();$resp=agent_commerce_http_v800('POST',agent_commerce_square_base_v800().'/oauth2/token',['Square-Version: 2026-08-19'],['client_id'=>$cfg['square']['application_id'],'client_secret'=>$cfg['square']['client_secret'],'refresh_token'=>$refresh,'grant_type'=>'refresh_token'])['json'];$new=trim((string)($resp['access_token']??''));if($new==='')throw new RuntimeException('Square token refresh failed.');$newRefresh=trim((string)($resp['refresh_token']??$refresh));$newExpires=null;if(!empty($resp['expires_at'])){try{$newExpires=(new DateTimeImmutable((string)$resp['expires_at']))->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');}catch(Throwable $e){}}$pdo->prepare("UPDATE agent_commerce_provider_connections_v800 SET access_token_ciphertext=?,refresh_token_ciphertext=?,token_expires_at=?,last_verified_at=NOW(),last_error='' WHERE id=?")->execute([agent_commerce_encrypt_v800($new),agent_commerce_encrypt_v800($newRefresh),$newExpires,(int)$connection['id']]);return $new;
}
function agent_commerce_paypal_base_v800(): string
{
    return agent_commerce_config_v800()['paypal']['environment']==='production'?'https://api-m.paypal.com':'https://api-m.sandbox.paypal.com';
}
function agent_commerce_paypal_platform_token_v800(): string
{
    $cfg=agent_commerce_config_v800()['paypal'];$basic=base64_encode($cfg['client_id'].':'.$cfg['client_secret']);$resp=agent_commerce_http_v800('POST',agent_commerce_paypal_base_v800().'/v1/oauth2/token',['Authorization: Basic '.$basic],['grant_type'=>'client_credentials'],true)['json'];$token=trim((string)($resp['access_token']??''));if($token==='')throw new RuntimeException('PayPal platform access token could not be created.');return $token;
}
function agent_commerce_paypal_assertion_v800(string $merchantId): string
{
    $client=agent_commerce_config_v800()['paypal']['client_id'];$enc=static fn(array $v):string=>rtrim(strtr(base64_encode((string)json_encode($v,JSON_UNESCAPED_SLASHES)),'+/','-_'),'=');return $enc(['alg'=>'none']).'.'.$enc(['iss'=>$client,'payer_id'=>$merchantId]).'.';
}
function agent_commerce_attach_paypal_v800(PDO $pdo,int $ownerUserId,string $merchantId): array
{
    if(!agent_commerce_provider_ready_v800('paypal'))throw new RuntimeException('PayPal is not configured for VP3 Commerce.');$merchantId=strtoupper(trim($merchantId));if(!preg_match('/^[2-9A-HJ-NP-Z]{13}$/',$merchantId))throw new RuntimeException('Enter a valid PayPal Merchant ID.');$cfg=agent_commerce_config_v800()['paypal'];$token=agent_commerce_paypal_platform_token_v800();$url=agent_commerce_paypal_base_v800().'/v1/customer/partners/'.rawurlencode($cfg['partner_id']).'/merchant-integrations/'.rawurlencode($merchantId);$headers=['Authorization: Bearer '.$token];if($cfg['bn_code']!=='')$headers[]='PayPal-Partner-Attribution-Id: '.$cfg['bn_code'];$resp=agent_commerce_http_v800('GET',$url,$headers)['json'];if(empty($resp['payments_receivable'])||empty($resp['primary_email_confirmed']))throw new RuntimeException('This PayPal merchant is not currently eligible to receive customer payments.');return agent_commerce_store_connection_v800($pdo,$ownerUserId,'paypal',$merchantId,['account_label'=>(string)($resp['legal_name']??'PayPal '.$merchantId),'account_email'=>(string)($resp['primary_email']??''),'capabilities'=>['checkout'=>true,'refunds'=>true,'payments_receivable'=>true]]);
}
function agent_commerce_create_checkout_v800(PDO $pdo,array $order,int $connectionId,string $returnUrl,string $cancelUrl): array
{
    if(!in_array((string)$order['payment_status'],['awaiting_payment','partially_paid'],true)|| (int)$order['amount_due_cents']<1)throw new RuntimeException('This order is not awaiting payment.');if(!empty($order['hold_expires_at'])&&strtotime((string)$order['hold_expires_at'])<=time())throw new RuntimeException('This payment hold has expired.');if(!preg_match('#^https?://#',$returnUrl)||!preg_match('#^https?://#',$cancelUrl))throw new RuntimeException('Commerce return and cancel URLs must be absolute.');$allowed=agent_commerce_available_connections_v800($pdo,$order);$connection=null;foreach($allowed as $candidate)if((int)$candidate['id']===$connectionId){$connection=$candidate;break;}if(!$connection)throw new RuntimeException('Choose an available payment provider.');$provider=(string)$connection['provider'];if(!agent_commerce_provider_ready_v800($provider))throw new RuntimeException(agent_commerce_provider_label_v800($provider).' is not configured on this VP3 deployment.');$existingStmt=$pdo->prepare("SELECT * FROM agent_commerce_checkout_attempts_v800 WHERE order_id=? AND connection_id=? ORDER BY id DESC LIMIT 1");$existingStmt->execute([(int)$order['id'],$connectionId]);$existing=$existingStmt->fetch();if($existing&&$existing['status']==='open')return $existing;$countStmt=$pdo->prepare('SELECT COUNT(*) FROM agent_commerce_checkout_attempts_v800 WHERE order_id=? AND connection_id=?');$countStmt->execute([(int)$order['id'],$connectionId]);$attemptNumber=(int)$countStmt->fetchColumn()+1;$due=max(1,(int)$order['amount_due_cents']);$currency=strtolower((string)$order['currency']);$idempotency=hash('sha256','vp3-commerce-checkout|'.(int)$order['id'].'|'.$connectionId.'|'.$due.'|'.$currency.'|'.$attemptNumber);$name=agent_commerce_order_title_v800($pdo,$order);$fee=max(0,min($due-1,(int)floor($due*(int)agent_commerce_config_v800()['platform_fee_bps']/10000)));$externalId='';$externalPayment='';$checkoutUrl='';
    if($provider==='stripe'){$cfg=agent_commerce_config_v800()['stripe'];$params=['mode'=>'payment','success_url'=>$returnUrl.'&session_id={CHECKOUT_SESSION_ID}','cancel_url'=>$cancelUrl,'line_items'=>[['quantity'=>1,'price_data'=>['currency'=>$currency,'unit_amount'=>$due,'product_data'=>['name'=>$name]]]],'metadata'=>['vp3_commerce_order_id'=>(string)$order['id']],'payment_intent_data'=>['metadata'=>['vp3_commerce_order_id'=>(string)$order['id']]]];$payerEmail=trim((string)$order['payer_email']);if($payerEmail!==''&&filter_var($payerEmail,FILTER_VALIDATE_EMAIL))$params['customer_email']=$payerEmail;if($fee>0)$params['payment_intent_data']['application_fee_amount']=$fee;$resp=agent_commerce_http_v800('POST','https://api.stripe.com/v1/checkout/sessions',['Authorization: Bearer '.$cfg['secret_key'],'Stripe-Account: '.(string)$connection['external_account_id'],'Idempotency-Key: '.$idempotency],$params,true)['json'];$externalId=trim((string)($resp['id']??''));$checkoutUrl=trim((string)($resp['url']??''));}
    elseif($provider==='square'){$token=agent_commerce_square_access_token_v800($pdo,$connection);$caps=agent_commerce_capabilities_v800($connection);$locationId=trim((string)($caps['location_id']??''));if($locationId===''){$profile=agent_commerce_square_profile_v800($token);$locationId=(string)$profile['location_id'];$caps['location_id']=$locationId;$caps['currency']=$profile['currency'];$pdo->prepare('UPDATE agent_commerce_provider_connections_v800 SET capabilities_json=?,last_verified_at=NOW(),updated_at=NOW() WHERE id=?')->execute([json_encode($caps,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),(int)$connection['id']]);}$squareCurrency=strtoupper(trim((string)($caps['currency']??'')));if($squareCurrency!==''&&$squareCurrency!==strtoupper($currency))throw new RuntimeException('This Square location does not support the order currency.');$body=['idempotency_key'=>$idempotency,'quick_pay'=>['name'=>$name,'price_money'=>['amount'=>$due,'currency'=>strtoupper($currency)],'location_id'=>$locationId],'checkout_options'=>['redirect_url'=>$returnUrl]];if($fee>0){$squareCfg=agent_commerce_config_v800()['square'];if((string)$squareCfg['environment']!=='production')throw new RuntimeException('Square sandbox does not support application fees for hosted commerce checkout. Set the commerce platform fee to 0 while testing Square sandbox.');$body['checkout_options']['app_fee_money']=['amount'=>$fee,'currency'=>strtoupper($currency)];}$resp=agent_commerce_http_v800('POST',agent_commerce_square_base_v800().'/v2/online-checkout/payment-links',['Authorization: Bearer '.$token,'Square-Version: 2026-08-19'],$body)['json'];$link=$resp['payment_link']??[];$externalId=trim((string)($link['id']??''));$externalPayment=trim((string)($link['order_id']??''));$checkoutUrl=trim((string)($link['url']??''));}
    elseif($provider==='paypal'){$cfg=agent_commerce_config_v800()['paypal'];$token=agent_commerce_paypal_platform_token_v800();$merchant=(string)$connection['external_account_id'];$headers=['Authorization: Bearer '.$token,'PayPal-Request-Id: '.$idempotency,'PayPal-Auth-Assertion: '.agent_commerce_paypal_assertion_v800($merchant)];if($cfg['bn_code']!=='')$headers[]='PayPal-Partner-Attribution-Id: '.$cfg['bn_code'];$unit=['reference_id'=>'vp3-commerce-'.$order['id'],'payee'=>['merchant_id'=>$merchant],'amount'=>['currency_code'=>strtoupper($currency),'value'=>agent_commerce_minor_to_decimal_v800($due)]];if($fee>0)$unit['payment_instruction']=['disbursement_mode'=>'INSTANT','platform_fees'=>[['amount'=>['currency_code'=>strtoupper($currency),'value'=>agent_commerce_minor_to_decimal_v800($fee)]]]];$resp=agent_commerce_http_v800('POST',agent_commerce_paypal_base_v800().'/v2/checkout/orders',$headers,['intent'=>'CAPTURE','purchase_units'=>[$unit],'application_context'=>['return_url'=>$returnUrl,'cancel_url'=>$cancelUrl,'shipping_preference'=>'NO_SHIPPING']])['json'];$externalId=trim((string)($resp['id']??''));foreach((array)($resp['links']??[]) as $link)if(($link['rel']??'')==='approve'){$checkoutUrl=(string)($link['href']??'');break;}}
    if($externalId===''||$checkoutUrl==='')throw new RuntimeException(agent_commerce_provider_label_v800($provider).' did not return a usable checkout.');$stmt=$pdo->prepare("INSERT INTO agent_commerce_checkout_attempts_v800 (order_id,connection_id,provider,external_session_id,external_payment_id,checkout_url,status,amount_cents,currency,idempotency_key,expires_at) VALUES (?,?,?,?,?,?,'open',?,?,?,?)");$stmt->execute([(int)$order['id'],$connectionId,$provider,$externalId,$externalPayment,$checkoutUrl,$due,$currency,$idempotency,$order['hold_expires_at']]);$attemptId=(int)$pdo->lastInsertId();$route=$pdo->prepare("UPDATE agent_commerce_orders_v800 SET connection_id=?,provider_snapshot=?,external_account_snapshot=?,updated_at=NOW() WHERE id=? AND payment_status IN ('awaiting_payment','partially_paid') AND (connection_id IS NULL OR connection_id=?)");$route->execute([$connectionId,$provider,(string)$connection['external_account_id'],(int)$order['id'],$connectionId]);if($route->rowCount()!==1)throw new RuntimeException('Order payment provider selection changed. Reload the private payment link.');agent_commerce_audit_v800($pdo,(int)$order['id'],(int)$order['owner_user_id'],(int)($order['workspace_owner_user_id']??0)?:null,'guest',null,null,'checkout_created','awaiting_payment','awaiting_payment',$due,['provider'=>$provider,'attempt_id'=>$attemptId,'attempt_number'=>$attemptNumber]);return agent_commerce_checkout_attempt_v800($pdo,$attemptId)?:throw new RuntimeException('Checkout attempt could not be saved.');
}
