<?php
declare(strict_types=1);

/**
 * VP3 Phase 19.2 — Webhook + Event Infrastructure.
 * Durable ingress only. Agent Brain remains the decision layer and Phase 19.0
 * remains the sole durable execution queue.
 */
const VP3_AGENT_EVENT_INFRA_V1920='agent-event-infrastructure-v1920-20260914';
const VP3_AGENT_EVENT_MAX_PAYLOAD_BYTES_V1920=65536;
const VP3_AGENT_EVENT_MAX_DEPTH_V1920=8;
const VP3_AGENT_EVENT_SIGNATURE_TOLERANCE_V1920=300;
const VP3_AGENT_EVENT_DISPATCH_STALE_SECONDS_V1920=300;
require_once __DIR__.'/agent-job-engine-v1900.php';

function agent_event_schema_ready_v1920(?PDO $pdo=null): bool{
    $pdo??=db();if(!$pdo||!table_exists('agent_event_inbox'))return false;
    foreach(['event_uuid','owner_user_id','source','event_type','dedupe_hash','verification_status','processing_status','payload_json','linked_run_id','replay_count','processing_started_at'] as $c)if(!column_exists('agent_event_inbox',$c))return false;
    return true;
}
function agent_event_ensure_schema_v1920(?PDO $pdo=null): void{
    $pdo??=db();if(!$pdo)throw new RuntimeException('Database connection is unavailable.');
    if(!agent_job_engine_schema_ready_v1900($pdo))throw new RuntimeException('Phase 19.0 Durable Agent Jobs must be installed before Phase 19.2.');
    $pdo->exec("CREATE TABLE IF NOT EXISTS agent_event_inbox (
      id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,event_uuid CHAR(36) NOT NULL,owner_user_id INT UNSIGNED NOT NULL,source VARCHAR(80) NOT NULL,event_type VARCHAR(120) NOT NULL,schema_version SMALLINT UNSIGNED NOT NULL DEFAULT 1,external_event_id VARCHAR(190) NOT NULL DEFAULT '',dedupe_hash CHAR(64) NOT NULL,verification_status VARCHAR(24) NOT NULL DEFAULT 'trusted',verification_key_id VARCHAR(120) NOT NULL DEFAULT '',processing_status VARCHAR(24) NOT NULL DEFAULT 'accepted',occurred_at DATETIME NULL,received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,processing_started_at DATETIME NULL,processed_at DATETIME NULL,replay_count INT UNSIGNED NOT NULL DEFAULT 0,correlation_id VARCHAR(120) NOT NULL DEFAULT '',causation_id VARCHAR(120) NOT NULL DEFAULT '',payload_json MEDIUMTEXT NULL,linked_run_id BIGINT UNSIGNED NULL,last_error_code VARCHAR(80) NOT NULL DEFAULT '',last_error_message VARCHAR(300) NOT NULL DEFAULT '',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      UNIQUE KEY uq_agent_event_uuid (event_uuid),UNIQUE KEY uq_agent_event_owner_dedupe (owner_user_id,dedupe_hash),INDEX idx_agent_event_owner_recent (owner_user_id,received_at,id),INDEX idx_agent_event_processing (processing_status,received_at,id),INDEX idx_agent_event_source (owner_user_id,source,event_type,received_at,id),INDEX idx_agent_event_run (linked_run_id),CONSTRAINT fk_agent_event_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
}
function agent_event_text_v1920(mixed $v,int $limit=500): string{$t=preg_replace('/\s+/u',' ',trim((string)$v))??'';return mb_strimwidth($t,0,max(1,$limit),'…');}
function agent_event_name_v1920(mixed $v,int $limit): string{$t=strtolower(agent_event_text_v1920($v,$limit));return preg_match('/^[a-z0-9][a-z0-9._:-]*$/',$t)?$t:'';}
function agent_event_uuid_v1920(): string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);$h=bin2hex($b);return substr($h,0,8).'-'.substr($h,8,4).'-'.substr($h,12,4).'-'.substr($h,16,4).'-'.substr($h,20);}
function agent_event_forbidden_key_v1920(string $k): bool{return (bool)preg_match('/(?:authorization|cookie|password|secret|token|credential|private[_-]?key|signature|api[_-]?key|access[_-]?key|refresh[_-]?key|native[_-]?path|filesystem[_-]?path|absolute[_-]?path|local[_-]?path)/i',$k);}
function agent_event_sanitize_value_v1920(mixed $v,int $depth=0): mixed{
    if($depth>=VP3_AGENT_EVENT_MAX_DEPTH_V1920)return '[depth-limited]';if($v===null||is_bool($v)||is_int($v)||is_float($v))return $v;if(is_string($v))return agent_event_text_v1920($v,2000);if(!is_array($v))return agent_event_text_v1920((string)$v,500);
    $out=[];$count=0;foreach($v as $k=>$item){if(++$count>100)break;$k=agent_event_text_v1920((string)$k,80);if($k===''||agent_event_forbidden_key_v1920($k))continue;$out[$k]=agent_event_sanitize_value_v1920($item,$depth+1);}return $out;
}
function agent_event_json_v1920(mixed $v): string{$j=json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_INVALID_UTF8_SUBSTITUTE);return is_string($j)?$j:'{}';}
function agent_event_sanitize_payload_v1920(array $p): array{$safe=agent_event_sanitize_value_v1920($p);if(!is_array($safe))return [];$j=agent_event_json_v1920($safe);return strlen($j)>VP3_AGENT_EVENT_MAX_PAYLOAD_BYTES_V1920?['payload_truncated'=>true,'payload_sha256'=>hash('sha256',$j)]:$safe;}
function agent_event_canonicalize_v1920(mixed $v): mixed{if(!is_array($v))return $v;if(array_is_list($v))return array_map('agent_event_canonicalize_v1920',$v);ksort($v,SORT_STRING);foreach($v as $k=>$x)$v[$k]=agent_event_canonicalize_v1920($x);return $v;}
function agent_event_dedupe_hash_v1920(int $uid,string $source,string $type,string $externalId,array $payload,string $rawHash=''): string{$identity=$externalId!==''?'external:'.$externalId:'payload:'.($rawHash!==''?$rawHash:hash('sha256',agent_event_json_v1920(agent_event_canonicalize_v1920($payload))));return hash('sha256',$uid.'|'.$source.'|'.$type.'|'.$identity);}
function agent_event_parse_time_v1920(mixed $v): ?string{if($v===null||$v==='')return null;$ts=is_numeric($v)?(int)$v:(strtotime((string)$v)?:0);return $ts>0?gmdate('Y-m-d H:i:s',$ts):null;}
function agent_event_row_v1920(PDO $pdo,int $uid,int $id,bool $lock=false): ?array{if($uid<1||$id<1||!agent_event_schema_ready_v1920($pdo))return null;$s=$pdo->prepare('SELECT * FROM agent_event_inbox WHERE id=? AND owner_user_id=? LIMIT 1'.($lock?' FOR UPDATE':''));$s->execute([$id,$uid]);$r=$s->fetch();return is_array($r)?$r:null;}
function agent_event_public_v1920(array $r): array{$p=json_decode((string)($r['payload_json']??''),true);if(!is_array($p))$p=[];return ['id'=>(int)($r['id']??0),'event_uuid'=>(string)($r['event_uuid']??''),'source'=>(string)($r['source']??''),'event_type'=>(string)($r['event_type']??''),'schema_version'=>(int)($r['schema_version']??1),'external_event_id'=>(string)($r['external_event_id']??''),'verification_status'=>(string)($r['verification_status']??''),'processing_status'=>(string)($r['processing_status']??''),'occurred_at'=>(string)($r['occurred_at']??''),'received_at'=>(string)($r['received_at']??''),'processed_at'=>(string)($r['processed_at']??''),'replay_count'=>(int)($r['replay_count']??0),'correlation_id'=>(string)($r['correlation_id']??''),'causation_id'=>(string)($r['causation_id']??''),'payload'=>$p,'linked_run_id'=>(int)($r['linked_run_id']??0),'last_error_code'=>(string)($r['last_error_code']??''),'last_error_message'=>(string)($r['last_error_message']??''),'build'=>VP3_AGENT_EVENT_INFRA_V1920];}
function agent_event_recent_v1920(PDO $pdo,array $user,int $limit=30): array{$uid=(int)($user['id']??0);$limit=max(1,min(100,$limit));if($uid<1||!agent_event_schema_ready_v1920($pdo))return [];$s=$pdo->prepare('SELECT * FROM agent_event_inbox WHERE owner_user_id=? ORDER BY received_at DESC,id DESC LIMIT '.$limit);$s->execute([$uid]);return array_map('agent_event_public_v1920',$s->fetchAll()?:[]);}

function agent_event_ingest_v1920(PDO $pdo,int $uid,string $source,string $type,array $payload,array $options=[]): array{
    if(!agent_event_schema_ready_v1920($pdo))throw new RuntimeException('Agent Event Infrastructure is not installed.');$source=agent_event_name_v1920($source,80);$type=agent_event_name_v1920($type,120);if($uid<1||$source===''||$type==='')throw new RuntimeException('Event identity is incomplete.');
    $verify=(string)($options['verification_status']??'trusted');if(!in_array($verify,['trusted','verified'],true))throw new RuntimeException('Only trusted or verified events may enter the inbox.');$safe=agent_event_sanitize_payload_v1920($payload);$external=agent_event_text_v1920($options['external_event_id']??'',190);$rawHash=agent_event_text_v1920($options['raw_hash']??'',64);if($rawHash!==''&&!preg_match('/^[a-f0-9]{64}$/',$rawHash))$rawHash='';$dedupe=agent_event_dedupe_hash_v1920($uid,$source,$type,$external,$safe,$rawHash);$uuid=agent_event_uuid_v1920();
    $v=[$uuid,$uid,$source,$type,max(1,min(65535,(int)($options['schema_version']??1))),$external,$dedupe,$verify,agent_event_text_v1920($options['verification_key_id']??'',120),agent_event_parse_time_v1920($options['occurred_at']??null),agent_event_text_v1920($options['correlation_id']??'',120),agent_event_text_v1920($options['causation_id']??'',120),agent_event_json_v1920($safe)];
    try{$s=$pdo->prepare('INSERT INTO agent_event_inbox (event_uuid,owner_user_id,source,event_type,schema_version,external_event_id,dedupe_hash,verification_status,verification_key_id,occurred_at,correlation_id,causation_id,payload_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)');$s->execute($v);$r=agent_event_row_v1920($pdo,$uid,(int)$pdo->lastInsertId());return ['duplicate'=>false,'event'=>$r?agent_event_public_v1920($r):null];}
    catch(PDOException $e){if((string)$e->getCode()!=='23000')throw $e;$s=$pdo->prepare('SELECT * FROM agent_event_inbox WHERE owner_user_id=? AND dedupe_hash=? LIMIT 1');$s->execute([$uid,$dedupe]);$r=$s->fetch();if(!is_array($r))throw $e;return ['duplicate'=>true,'event'=>agent_event_public_v1920($r)];}
}

function &agent_event_handlers_v1920(): array{if(!isset($GLOBALS['vp3_agent_event_handlers_v1920'])||!is_array($GLOBALS['vp3_agent_event_handlers_v1920']))$GLOBALS['vp3_agent_event_handlers_v1920']=[];return $GLOBALS['vp3_agent_event_handlers_v1920'];}
function agent_event_register_handler_v1920(string $source,string $type,callable $handler): void{$source=agent_event_name_v1920($source,80);$type=agent_event_name_v1920($type,120);if($source===''||$type==='')throw new InvalidArgumentException('Event route is incomplete.');$h=&agent_event_handlers_v1920();$h[$source.'|'.$type]=$handler;}
function agent_event_brain_observe_v1920(array $user,array $row,string $summary=''): void{if(!function_exists('agent_brain_v122_upsert_system_memory'))return;$id=(int)($row['id']??0);if($id<1)return;$source=agent_event_text_v1920($row['source']??'',80);$type=agent_event_text_v1920($row['event_type']??'',120);$summary=agent_event_text_v1920($summary,300);$text='Verified Agent event “'.$type.'” arrived from '.$source.'.'.($summary!==''?' '.$summary:'');$meta=['event_id'=>$id,'event_uuid'=>(string)($row['event_uuid']??''),'source'=>$source,'event_type'=>$type,'occurred_at'=>(string)($row['occurred_at']??''),'received_at'=>(string)($row['received_at']??''),'build'=>VP3_AGENT_EVENT_INFRA_V1920];try{agent_brain_v122_upsert_system_memory($user,'external_event','event-'.(string)$row['event_uuid'],$text,$meta,0.97);}catch(Throwable $e){}}
function agent_event_priority_v1920(array $row,array $requested): array{$uuid=(string)($row['event_uuid']??'');$source=agent_event_name_v1920($requested['source']??('event_'.(string)($row['source']??'external')),100);if($source==='')$source='event_external';$title=agent_event_text_v1920($requested['title']??('Review '.(string)($row['event_type']??'event')),190);$prompt=agent_event_text_v1920($requested['prompt']??$requested['goal']??$title,2000);return ['key'=>'event-'.$uuid,'suggestion_hash'=>sha1('event|'.$uuid),'source'=>$source,'title'=>$title,'prompt'=>$prompt,'reason'=>agent_event_text_v1920($requested['reason']??'Triggered by a verified durable event.',1500),'score'=>max(0.0,min(1.0,(float)($requested['score']??0.75))),'risk_level'=>(string)($requested['risk_level']??'low'),'requires_approval'=>!empty($requested['requires_approval']),'event_id'=>'event-'.$uuid,'action_id'=>'event-action-'.sha1($uuid)];}

function agent_event_dispatch_v1920(PDO $pdo,array $user,int $id,bool $replay=false): array{
    $uid=(int)($user['id']??0);if($uid<1)throw new RuntimeException('A signed-in account is required.');if(!agent_event_schema_ready_v1920($pdo))throw new RuntimeException('Agent Event Infrastructure is not installed.');
    try{$pdo->beginTransaction();$row=agent_event_row_v1920($pdo,$uid,$id,true);if(!$row)throw new RuntimeException('Event not found.');if(!in_array((string)$row['verification_status'],['trusted','verified'],true))throw new RuntimeException('Event verification state does not permit dispatch.');$status=(string)$row['processing_status'];
        if($status==='processing'){$started=strtotime((string)($row['processing_started_at']??''))?:0;if($started>0&&$started>time()-VP3_AGENT_EVENT_DISPATCH_STALE_SECONDS_V1920)throw new RuntimeException('This event is already being dispatched.');$pdo->prepare("UPDATE agent_event_inbox SET processing_status='failed',last_error_code='stale_dispatch_recovered',last_error_message='Recovered an abandoned dispatch claim.' WHERE id=? AND owner_user_id=?")->execute([$id,$uid]);$status='failed';$replay=true;}
        if($status==='processed'&&!$replay){$pdo->commit();return ['duplicate_dispatch'=>true,'event'=>agent_event_public_v1920($row)];}
        $pdo->prepare("UPDATE agent_event_inbox SET processing_status='processing',processing_started_at=UTC_TIMESTAMP(),processed_at=NULL,last_error_code='',last_error_message='',replay_count=replay_count+? WHERE id=? AND owner_user_id=?")->execute([$replay?1:0,$id,$uid]);$pdo->commit();
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    $row=agent_event_row_v1920($pdo,$uid,$id);if(!$row)throw new RuntimeException('Event not found.');$handlers=&agent_event_handlers_v1920();$handler=$handlers[(string)$row['source'].'|'.(string)$row['event_type']]??null;$linked=0;$summary='Observed by Agent Brain; no workflow route registered.';
    try{$result=[];if(is_callable($handler)){$result=$handler(agent_event_public_v1920($row),$user);if(!is_array($result))throw new RuntimeException('Registered event handler returned an invalid result.');$summary=agent_event_text_v1920($result['summary']??'Event route processed.',300);}agent_event_brain_observe_v1920($user,$row,$summary);
        if(is_array($result['priority']??null)){if(!agent_job_engine_schema_ready_v1900($pdo))throw new RuntimeException('Durable Agent Jobs are not ready for event dispatch.');$run=agent_job_enqueue_from_brain_v1900($pdo,$user,agent_event_priority_v1920($row,$result['priority']),isset($result['agent_id'])?(int)$result['agent_id']:null);$linked=(int)($run['id']??0);}
        $pdo->prepare("UPDATE agent_event_inbox SET processing_status='processed',processed_at=UTC_TIMESTAMP(),linked_run_id=?,last_error_code='',last_error_message='' WHERE id=? AND owner_user_id=? AND processing_status='processing'")->execute([$linked>0?$linked:null,$id,$uid]);$final=agent_event_row_v1920($pdo,$uid,$id);return ['duplicate_dispatch'=>false,'event'=>$final?agent_event_public_v1920($final):null,'linked_run_id'=>$linked,'summary'=>$summary];
    }catch(Throwable $e){$code=$e instanceof RuntimeException?'dispatch_rejected':'dispatch_failed';$msg=$e instanceof RuntimeException?agent_event_text_v1920($e->getMessage(),300):'Event dispatch failed.';$pdo->prepare("UPDATE agent_event_inbox SET processing_status='failed',last_error_code=?,last_error_message=? WHERE id=? AND owner_user_id=? AND processing_status='processing'")->execute([$code,$msg,$id,$uid]);throw $e;}
}
function agent_event_dispatch_ingest_v1920(PDO $pdo,array $user,array $ingest): array{$event=(array)($ingest['event']??[]);$id=(int)($event['id']??0);if($id<1)return $ingest;$status=(string)($event['processing_status']??'accepted');if(empty($ingest['duplicate']))$ingest['dispatch']=agent_event_dispatch_v1920($pdo,$user,$id,false);elseif(in_array($status,['accepted','failed'],true))$ingest['dispatch']=agent_event_dispatch_v1920($pdo,$user,$id,true);return $ingest;}
function agent_event_emit_internal_v1920(PDO $pdo,array $user,string $source,string $type,array $payload=[],array $options=[]): array{$uid=(int)($user['id']??0);if($uid<1)throw new RuntimeException('A signed-in account is required.');$options['verification_status']='trusted';return agent_event_dispatch_ingest_v1920($pdo,$user,agent_event_ingest_v1920($pdo,$uid,$source,$type,$payload,$options));}

function agent_event_verify_hmac_v1920(string $raw,string $sig,string $key,string $timestamp='',int $tolerance=VP3_AGENT_EVENT_SIGNATURE_TOLERANCE_V1920): bool{if($key===''||$sig==='')return false;$timestamp=trim($timestamp);if($timestamp!==''){$ts=(int)$timestamp;if($ts<1||abs(time()-$ts)>max(30,min(1800,$tolerance)))return false;}$signed=$timestamp!==''?$timestamp.'.'.$raw:$raw;$expected=hash_hmac('sha256',$signed,$key);$provided=strtolower(trim(preg_replace('/^sha256=/i','',$sig)??''));return preg_match('/^[a-f0-9]{64}$/',$provided)===1&&hash_equals($expected,$provided);}
function &agent_event_webhook_sources_v1920(): array{if(!isset($GLOBALS['vp3_agent_event_webhook_sources_v1920'])||!is_array($GLOBALS['vp3_agent_event_webhook_sources_v1920']))$GLOBALS['vp3_agent_event_webhook_sources_v1920']=[];return $GLOBALS['vp3_agent_event_webhook_sources_v1920'];}
function agent_event_register_webhook_source_v1920(string $source,callable $verifier,array $types): void{$source=agent_event_name_v1920($source,80);$allowed=[];foreach($types as $type){$type=agent_event_name_v1920($type,120);if($type!=='')$allowed[$type]=true;}if($source===''||!$allowed)throw new InvalidArgumentException('Webhook source requires an allowlisted event type.');$s=&agent_event_webhook_sources_v1920();$s[$source]=['verifier'=>$verifier,'types'=>$allowed];}
function agent_event_accept_webhook_v1920(PDO $pdo,string $source,string $raw,array $headers=[]): array{$source=agent_event_name_v1920($source,80);if($source===''||strlen($raw)>VP3_AGENT_EVENT_MAX_PAYLOAD_BYTES_V1920)throw new RuntimeException('Webhook request was rejected.');$sources=&agent_event_webhook_sources_v1920();$config=$sources[$source]??null;if(!is_array($config)||!is_callable($config['verifier']??null))throw new RuntimeException('Webhook source is not registered.');$verified=($config['verifier'])($raw,$headers);if(!is_array($verified)||empty($verified['verified'])||!is_array($verified['user']??null))throw new RuntimeException('Webhook verification failed.');$user=$verified['user'];$uid=(int)($user['id']??0);$type=agent_event_name_v1920($verified['event_type']??'',120);if($uid<1||$type===''||empty($config['types'][$type]))throw new RuntimeException('Webhook event type is not allowed.');$payload=is_array($verified['payload']??null)?$verified['payload']:[];$opts=['verification_status'=>'verified','verification_key_id'=>agent_event_text_v1920($verified['key_id']??'',120),'external_event_id'=>agent_event_text_v1920($verified['external_event_id']??'',190),'occurred_at'=>$verified['occurred_at']??null,'correlation_id'=>agent_event_text_v1920($verified['correlation_id']??'',120),'causation_id'=>agent_event_text_v1920($verified['causation_id']??'',120),'schema_version'=>(int)($verified['schema_version']??1),'raw_hash'=>hash('sha256',$raw)];return agent_event_dispatch_ingest_v1920($pdo,$user,agent_event_ingest_v1920($pdo,$uid,$source,$type,$payload,$opts));}
