<?php
declare(strict_types=1);

function agent_paid_appointments_public_by_token_v800(PDO $pdo,string $token): ?array
{
    $token=strtolower(trim($token));if(!preg_match('/^[a-f0-9]{64}$/',$token))return null;
    $stmt=$pdo->prepare("SELECT pb.* FROM agent_paid_bookings_v800 pb LEFT JOIN agent_team_scheduling_bookings tb ON tb.id=pb.team_booking_id JOIN agent_scheduling_bookings b ON b.id=pb.booking_id WHERE (pb.team_booking_id IS NULL AND b.cancel_token=?) OR (pb.team_booking_id IS NOT NULL AND tb.cancel_token=?) LIMIT 1");$stmt->execute([$token,$token]);return $stmt->fetch()?:null;
}
function agent_paid_appointments_manage_token_v800(PDO $pdo,array $paid): string
{
    if((int)($paid['team_booking_id']??0)>0){$stmt=$pdo->prepare('SELECT cancel_token FROM agent_team_scheduling_bookings WHERE id=? LIMIT 1');$stmt->execute([(int)$paid['team_booking_id']]);return (string)$stmt->fetchColumn();}
    $stmt=$pdo->prepare('SELECT cancel_token FROM agent_scheduling_bookings WHERE id=? LIMIT 1');$stmt->execute([(int)$paid['booking_id']]);return (string)$stmt->fetchColumn();
}

function agent_paid_appointments_confirmation_after_payment_v800(PDO $pdo,array $paid): void
{
    if((int)($paid['team_booking_id']??0)>0){$stmt=$pdo->prepare('SELECT canonical_booking_id FROM agent_team_scheduling_booking_members WHERE team_booking_id=? ORDER BY id');$stmt->execute([(int)$paid['team_booking_id']]);foreach($stmt->fetchAll()?:[] as $row){$b=agent_appointment_lifecycle_booking_v700($pdo,(int)$row['canonical_booking_id']);if(!$b)continue;if(agent_appointment_lifecycle_status_v700($b)==='pending')$b=agent_appointment_lifecycle_transition_v700($pdo,$b,'confirmed','system',null,null,['source'=>'paid_appointments_v800','paid_booking_id'=>(int)$paid['id']]);agent_appointment_lifecycle_queue_booking_v700($pdo,$b,true);}return;}
    $b=agent_appointment_lifecycle_booking_v700($pdo,(int)$paid['booking_id']);if(!$b)return;if(agent_appointment_lifecycle_status_v700($b)==='pending')$b=agent_appointment_lifecycle_transition_v700($pdo,$b,'confirmed','system',null,null,['source'=>'paid_appointments_v800','paid_booking_id'=>(int)$paid['id']]);agent_appointment_lifecycle_queue_booking_v700($pdo,$b,true);
}

function agent_paid_appointments_mark_paid_v800(PDO $pdo,int $paidBookingId,string $provider,string $externalSessionId,string $externalPaymentId,int $amountCents,string $currency): array
{
    $provider=strtolower(trim($provider));$currency=strtolower(trim($currency));$owns=!$pdo->inTransaction();if($owns)$pdo->beginTransaction();
    try{$stmt=$pdo->prepare('SELECT * FROM agent_paid_bookings_v800 WHERE id=? LIMIT 1 FOR UPDATE');$stmt->execute([$paidBookingId]);$paid=$stmt->fetch();if(!$paid)throw new RuntimeException('Paid appointment record not found.');if($paid['payment_status']==='paid'||$paid['payment_status']==='partially_refunded'||$paid['payment_status']==='refunded'){if($owns)$pdo->commit();return $paid;}if($paid['payment_status']!=='awaiting_payment')throw new RuntimeException('Appointment is no longer awaiting payment.');if((string)$paid['provider_snapshot']!==$provider)throw new RuntimeException('Payment provider does not match this appointment.');if($amountCents<(int)$paid['amount_due_cents'])throw new RuntimeException('Payment amount is less than the required amount.');if($currency!==strtolower((string)$paid['currency']))throw new RuntimeException('Payment currency does not match this appointment.');
      $attempt=$pdo->prepare('SELECT * FROM agent_paid_checkout_attempts_v800 WHERE paid_booking_id=? AND provider=? AND external_session_id=? LIMIT 1 FOR UPDATE');$attempt->execute([$paidBookingId,$provider,$externalSessionId]);$a=$attempt->fetch();if(!$a)throw new RuntimeException('Payment checkout lineage could not be verified.');if((int)$a['amount_cents']!==(int)$paid['amount_due_cents']||strtolower((string)$a['currency'])!==$currency)throw new RuntimeException('Payment checkout terms do not match the canonical booking.');
      $pdo->prepare("UPDATE agent_paid_checkout_attempts_v800 SET external_payment_id=?,status='completed',completed_at=NOW(),updated_at=NOW() WHERE id=?")->execute([mb_strimwidth($externalPaymentId,0,190,''),(int)$a['id']]);$pdo->prepare("UPDATE agent_paid_bookings_v800 SET amount_paid_cents=?,payment_status='paid',paid_at=NOW(),hold_expires_at=NULL,updated_at=NOW() WHERE id=? AND payment_status='awaiting_payment'")->execute([(int)$paid['amount_due_cents'],$paidBookingId]);if((int)($paid['team_booking_id']??0)>0)$pdo->prepare("UPDATE agent_team_scheduling_bookings SET status='confirmed',updated_at=NOW() WHERE id=? AND status='pending'")->execute([(int)$paid['team_booking_id']]);agent_paid_appointments_audit_v800($pdo,$paidBookingId,(int)$paid['owner_user_id'],(int)($paid['workspace_owner_user_id']??0)?:null,'provider',null,null,'payment_completed','awaiting_payment','paid',(int)$paid['amount_due_cents'],['provider'=>$provider,'external_session_id'=>$externalSessionId]);if($owns)$pdo->commit();
    }catch(Throwable $e){if($owns&&$pdo->inTransaction())$pdo->rollBack();throw $e;}
    $fresh=agent_paid_appointments_paid_booking_v800($pdo,$paidBookingId)?:throw new RuntimeException('Paid appointment could not be reloaded.');agent_paid_appointments_confirmation_after_payment_v800($pdo,$fresh);if(function_exists('agent_appointment_lifecycle_housekeeping_v700'))agent_appointment_lifecycle_housekeeping_v700($pdo,120);return $fresh;
}

function agent_paid_appointments_expire_one_v800(PDO $pdo,array $paid): void
{
    if((string)$paid['payment_status']!=='awaiting_payment')return;
    if((int)($paid['team_booking_id']??0)>0){$stmt=$pdo->prepare('SELECT * FROM agent_team_scheduling_bookings WHERE id=? LIMIT 1');$stmt->execute([(int)$paid['team_booking_id']]);$team=$stmt->fetch();if($team&&in_array((string)$team['status'],['pending','confirmed'],true))agent_team_scheduling_cancel_booking_v600($pdo,$team);$m=$pdo->prepare('SELECT canonical_booking_id FROM agent_team_scheduling_booking_members WHERE team_booking_id=?');$m->execute([(int)$paid['team_booking_id']]);foreach($m->fetchAll()?:[] as $row){$b=agent_appointment_lifecycle_booking_v700($pdo,(int)$row['canonical_booking_id']);if($b&&agent_appointment_lifecycle_status_v700($b)==='pending'){try{agent_appointment_lifecycle_transition_v700($pdo,$b,'cancelled','system',null,null,['source'=>'payment_hold_expired']);}catch(Throwable $e){}}}}
    else{$b=agent_appointment_lifecycle_booking_v700($pdo,(int)$paid['booking_id']);if($b&&agent_appointment_lifecycle_status_v700($b)==='pending')agent_appointment_lifecycle_transition_v700($pdo,$b,'cancelled','system',null,null,['source'=>'payment_hold_expired']);}
    $stmt=$pdo->prepare("UPDATE agent_paid_bookings_v800 SET payment_status='expired',cancelled_at=NOW(),updated_at=NOW() WHERE id=? AND payment_status='awaiting_payment'");$stmt->execute([(int)$paid['id']]);$pdo->prepare("UPDATE agent_paid_checkout_attempts_v800 SET status='expired',updated_at=NOW() WHERE paid_booking_id=? AND status='open'")->execute([(int)$paid['id']]);agent_paid_appointments_audit_v800($pdo,(int)$paid['id'],(int)$paid['owner_user_id'],(int)($paid['workspace_owner_user_id']??0)?:null,'system',null,null,'payment_hold_expired','awaiting_payment','expired',(int)$paid['amount_due_cents']);
}
function agent_paid_appointments_expire_holds_v800(PDO $pdo,int $limit=100): int
{
    $stmt=$pdo->query("SELECT * FROM agent_paid_bookings_v800 WHERE payment_status='awaiting_payment' AND hold_expires_at IS NOT NULL AND hold_expires_at<=UTC_TIMESTAMP() ORDER BY hold_expires_at,id LIMIT ".max(1,min(500,$limit)));$rows=$stmt->fetchAll()?:[];foreach($rows as $row)try{agent_paid_appointments_expire_one_v800($pdo,$row);}catch(Throwable $e){error_log('VP3 paid appointment hold expiry failed: '.$e->getMessage());}return count($rows);
}
function agent_paid_appointments_housekeeping_maybe_v800(): void
{
    if(PHP_SAPI==='cli'||mt_rand(1,20)!==1)return;$pdo=db();if(!$pdo||!agent_paid_appointments_schema_ready_v800($pdo))return;try{agent_paid_appointments_expire_holds_v800($pdo,50);}catch(Throwable $e){error_log('VP3 paid appointment housekeeping failed: '.$e->getMessage());}
}

function agent_paid_appointments_stripe_verify_v800(string $payload,string $signature): bool
{
    $secret=(string)agent_paid_appointments_config_v800()['stripe']['webhook_secret'];if($secret===''||$payload===''||$signature==='')return false;$timestamp=0;$sigs=[];foreach(explode(',',$signature) as $part){[$k,$v]=array_pad(explode('=',trim($part),2),2,'');if($k==='t'&&ctype_digit($v))$timestamp=(int)$v;elseif($k==='v1'&&preg_match('/^[a-f0-9]{64}$/i',$v))$sigs[]=strtolower($v);}if($timestamp<1||abs(time()-$timestamp)>300||!$sigs)return false;$expected=hash_hmac('sha256',$timestamp.'.'.$payload,$secret);foreach($sigs as $sig)if(hash_equals($expected,$sig))return true;return false;
}
function agent_paid_appointments_square_verify_v800(string $payload,string $signature): bool
{
    $key=(string)agent_paid_appointments_config_v800()['square']['webhook_signature_key'];if($key===''||$signature==='')return false;$url=agent_paid_appointments_absolute_url_v800('/appointment-payment-webhook.php?provider=square');$expected=base64_encode(hash_hmac('sha256',$url.$payload,$key,true));return hash_equals($expected,$signature);
}
function agent_paid_appointments_paypal_verify_v800(array $headers,array $event): bool
{
    $cfg=agent_paid_appointments_config_v800()['paypal'];if($cfg['webhook_id']==='')return false;$required=['paypal-transmission-id','paypal-transmission-time','paypal-transmission-sig','paypal-cert-url','paypal-auth-algo'];foreach($required as $key)if(trim((string)($headers[$key]??''))==='')return false;$token=agent_paid_appointments_paypal_platform_token_v800();$body=['auth_algo'=>$headers['paypal-auth-algo'],'cert_url'=>$headers['paypal-cert-url'],'transmission_id'=>$headers['paypal-transmission-id'],'transmission_sig'=>$headers['paypal-transmission-sig'],'transmission_time'=>$headers['paypal-transmission-time'],'webhook_id'=>$cfg['webhook_id'],'webhook_event'=>$event];$resp=agent_paid_appointments_http_v800('POST',agent_paid_appointments_paypal_base_v800().'/v1/notifications/verify-webhook-signature',['Authorization: Bearer '.$token],$body)['json'];return strtoupper((string)($resp['verification_status']??''))==='SUCCESS';
}

function agent_paid_appointments_webhook_claim_v800(PDO $pdo,string $provider,string $eventId,string $eventType,string $payload): bool
{
    try{$pdo->prepare("INSERT INTO agent_paid_webhook_events_v800 (provider,external_event_id,event_type,payload_sha256,status) VALUES (?,?,?,?, 'processing')")->execute([$provider,mb_strimwidth($eventId,0,190,''),mb_strimwidth($eventType,0,120,''),hash('sha256',$payload)]);return true;}catch(PDOException $e){if((string)$e->getCode()==='23000')return false;throw $e;}
}
function agent_paid_appointments_webhook_finish_v800(PDO $pdo,string $provider,string $eventId,string $status,string $error=''): void
{
    $pdo->prepare('UPDATE agent_paid_webhook_events_v800 SET status=?,error_message=?,processed_at=NOW(),updated_at=NOW() WHERE provider=? AND external_event_id=?')->execute([$status,mb_strimwidth($error,0,1000,''),$provider,$eventId]);
}

function agent_paid_appointments_process_webhook_v800(PDO $pdo,string $provider,string $payload,array $headers=[]): void
{
    $event=json_decode($payload,true);if(!is_array($event))throw new RuntimeException('Webhook payload is not valid JSON.');$provider=strtolower(trim($provider));$eventId=trim((string)($event['id']??$event['event_id']??''));$eventType=trim((string)($event['type']??$event['event_type']??''));if($eventId===''||$eventType==='')throw new RuntimeException('Webhook event identity is missing.');
    $valid=match($provider){'stripe'=>agent_paid_appointments_stripe_verify_v800($payload,(string)($headers['stripe-signature']??'')),'square'=>agent_paid_appointments_square_verify_v800($payload,(string)($headers['x-square-hmacsha256-signature']??'')),'paypal'=>agent_paid_appointments_paypal_verify_v800($headers,$event),default=>false};if(!$valid)throw new RuntimeException('Webhook signature verification failed.');if(!agent_paid_appointments_webhook_claim_v800($pdo,$provider,$eventId,$eventType,$payload))return;
    try{
      if($provider==='stripe'&&$eventType==='checkout.session.completed'){$obj=$event['data']['object']??[];$paidId=(int)($obj['metadata']['vp3_paid_booking_id']??0);$session=(string)($obj['id']??'');$payment=(string)($obj['payment_intent']??'');$amount=(int)($obj['amount_total']??0);$currency=(string)($obj['currency']??'');if($paidId>0&&(string)($obj['payment_status']??'')==='paid')agent_paid_appointments_mark_paid_v800($pdo,$paidId,'stripe',$session,$payment,$amount,$currency);}
      elseif($provider==='square'&&in_array($eventType,['payment.created','payment.updated'],true)){$payment=$event['data']['object']['payment']??[];if(strtoupper((string)($payment['status']??''))==='COMPLETED'){$order=(string)($payment['order_id']??'');$attempt=agent_paid_appointments_attempt_by_external_v800($pdo,'square',$order);if($attempt){$amount=(int)($payment['amount_money']['amount']??0);$currency=(string)($payment['amount_money']['currency']??'');agent_paid_appointments_mark_paid_v800($pdo,(int)$attempt['paid_booking_id'],'square',(string)$attempt['external_session_id'],(string)($payment['id']??$order),$amount,$currency);}}}
      elseif($provider==='paypal'&&$eventType==='PAYMENT.CAPTURE.COMPLETED'){$capture=$event['resource']??[];$order=(string)($capture['supplementary_data']['related_ids']['order_id']??'');$attempt=agent_paid_appointments_attempt_by_external_v800($pdo,'paypal',$order);if($attempt){$amount=(int)round(((float)($capture['amount']['value']??0))*100);$currency=(string)($capture['amount']['currency_code']??'');agent_paid_appointments_mark_paid_v800($pdo,(int)$attempt['paid_booking_id'],'paypal',(string)$attempt['external_session_id'],(string)($capture['id']??''),$amount,$currency);}}
      agent_paid_appointments_webhook_finish_v800($pdo,$provider,$eventId,'processed');
    }catch(Throwable $e){agent_paid_appointments_webhook_finish_v800($pdo,$provider,$eventId,'failed',$e->getMessage());throw $e;}
}

function agent_paid_appointments_return_verify_v800(PDO $pdo,array $paid,string $provider,array $query): array
{
    $provider=strtolower(trim($provider));$attemptStmt=$pdo->prepare("SELECT * FROM agent_paid_checkout_attempts_v800 WHERE paid_booking_id=? AND provider=? AND status='open' ORDER BY id DESC LIMIT 1");$attemptStmt->execute([(int)$paid['id'],$provider]);$attempt=$attemptStmt->fetch();if(!$attempt)return $paid;$connection=agent_paid_appointments_connection_v800($pdo,(int)$attempt['connection_id']);if(!$connection)return $paid;
    if($provider==='stripe'){$session=trim((string)($query['session_id']??''));if($session===''||!hash_equals((string)$attempt['external_session_id'],$session))return $paid;$cfg=agent_paid_appointments_config_v800()['stripe'];$resp=agent_paid_appointments_http_v800('GET','https://api.stripe.com/v1/checkout/sessions/'.rawurlencode($session),['Authorization: Bearer '.$cfg['secret_key'],'Stripe-Account: '.(string)$connection['external_account_id']])['json'];if((string)($resp['payment_status']??'')==='paid')return agent_paid_appointments_mark_paid_v800($pdo,(int)$paid['id'],'stripe',$session,(string)($resp['payment_intent']??''),(int)($resp['amount_total']??0),(string)($resp['currency']??''));}
    elseif($provider==='paypal'){$order=trim((string)($query['token']??$attempt['external_session_id']));if(!hash_equals((string)$attempt['external_session_id'],$order))return $paid;$cfg=agent_paid_appointments_config_v800()['paypal'];$token=agent_paid_appointments_paypal_platform_token_v800();$headers=['Authorization: Bearer '.$token,'PayPal-Request-Id: '.hash('sha256','vp3-capture|'.$attempt['id']),'PayPal-Auth-Assertion: '.agent_paid_appointments_paypal_assertion_v800((string)$connection['external_account_id'])];if($cfg['bn_code']!=='')$headers[]='PayPal-Partner-Attribution-Id: '.$cfg['bn_code'];$resp=agent_paid_appointments_http_v800('POST',agent_paid_appointments_paypal_base_v800().'/v2/checkout/orders/'.rawurlencode($order).'/capture',$headers,new stdClass())['json'];$capture=$resp['purchase_units'][0]['payments']['captures'][0]??[];if(strtoupper((string)($capture['status']??''))==='COMPLETED')return agent_paid_appointments_mark_paid_v800($pdo,(int)$paid['id'],'paypal',$order,(string)($capture['id']??''),(int)round(((float)($capture['amount']['value']??0))*100),(string)($capture['amount']['currency_code']??''));}
    elseif($provider==='square'){$cfg=agent_paid_appointments_config_v800()['square'];$base=$cfg['environment']==='production'?'https://connect.squareup.com':'https://connect.squareupsandbox.com';$token=agent_paid_appointments_square_access_token_v800($pdo,$connection);$order=(string)$attempt['external_payment_id'];if($order!==''){$resp=agent_paid_appointments_http_v800('GET',$base.'/v2/payments?'.http_build_query(['order_id'=>$order]),['Authorization: Bearer '.$token,'Square-Version: 2026-08-19'])['json'];foreach((array)($resp['payments']??[]) as $payment)if(strtoupper((string)($payment['status']??''))==='COMPLETED')return agent_paid_appointments_mark_paid_v800($pdo,(int)$paid['id'],'square',(string)$attempt['external_session_id'],(string)($payment['id']??''),(int)($payment['amount_money']['amount']??0),(string)($payment['amount_money']['currency']??''));}}
    return agent_paid_appointments_paid_booking_v800($pdo,(int)$paid['id'])?:$paid;
}

function agent_paid_appointments_refundable_cents_v800(PDO $pdo,array $paid): int
{
    if(!in_array((string)$paid['payment_status'],['paid','partially_refunded'],true))return 0;$remaining=max(0,(int)$paid['amount_paid_cents']-(int)$paid['amount_refunded_cents']);if($remaining<1)return 0;$snapshot=json_decode((string)($paid['terms_snapshot_json']??''),true);if(!is_array($snapshot))$snapshot=[];$hours=max(0,(int)($snapshot['refund_before_hours']??24));$fee=max(0,(int)($snapshot['cancellation_fee_cents']??0));$stmt=$pdo->prepare('SELECT start_at_utc FROM agent_scheduling_bookings WHERE id=? LIMIT 1');$stmt->execute([(int)$paid['booking_id']]);$start=(string)$stmt->fetchColumn();if($start===''||strtotime($start)<time()+($hours*3600))return 0;return max(0,$remaining-min($fee,$remaining));
}

function agent_paid_appointments_refund_v800(PDO $pdo,array $paid,int $amountCents,string $reason,?array $actor=null,bool $approved=false,?int $agentId=null): array
{
    $actor??=current_user();$actorId=(int)($actor['id']??0);$authority=(int)($paid['workspace_owner_user_id']??0)>0?(int)$paid['workspace_owner_user_id']:(int)$paid['owner_user_id'];if($actorId<1||$actorId!==$authority)throw new RuntimeException('Only the appointment account owner can approve a refund.');if(!$approved)throw new RuntimeException('Explicit refund approval is required before money is sent back to the customer.');$max=agent_paid_appointments_refundable_cents_v800($pdo,$paid);$amountCents=max(0,$amountCents);if($amountCents<1||$amountCents>$max)throw new RuntimeException('Refund amount exceeds the amount allowed by this appointment cancellation policy.');
    $stmt=$pdo->prepare("SELECT * FROM agent_paid_checkout_attempts_v800 WHERE paid_booking_id=? AND status='completed' ORDER BY id DESC LIMIT 1");$stmt->execute([(int)$paid['id']]);$attempt=$stmt->fetch();if(!$attempt)throw new RuntimeException('Completed payment lineage was not found.');$connection=agent_paid_appointments_connection_v800($pdo,(int)$attempt['connection_id']);if(!$connection)throw new RuntimeException('Payment provider connection is unavailable.');$provider=(string)$attempt['provider'];$externalRefund='';$status='completed';$idempotency=hash('sha256','vp3-refund|'.(int)$paid['id'].'|'.$amountCents.'|'.(int)$paid['amount_refunded_cents']);$reason=mb_strimwidth(trim($reason),0,500,'');
    if($provider==='stripe'){$cfg=agent_paid_appointments_config_v800()['stripe'];$payment=(string)$attempt['external_payment_id'];if($payment==='')throw new RuntimeException('Stripe PaymentIntent is unavailable.');$params=['payment_intent'=>$payment,'amount'=>$amountCents,'metadata'=>['vp3_paid_booking_id'=>(string)$paid['id']]];if((int)$paid['platform_fee_cents']>0)$params['refund_application_fee']='true';$resp=agent_paid_appointments_http_v800('POST','https://api.stripe.com/v1/refunds',['Authorization: Bearer '.$cfg['secret_key'],'Stripe-Account: '.(string)$connection['external_account_id'],'Idempotency-Key: '.$idempotency],$params,true)['json'];$externalRefund=(string)($resp['id']??'');$status=(string)($resp['status']??'succeeded')==='succeeded'?'completed':'pending';}
    elseif($provider==='square'){$cfg=agent_paid_appointments_config_v800()['square'];$base=$cfg['environment']==='production'?'https://connect.squareup.com':'https://connect.squareupsandbox.com';$token=agent_paid_appointments_square_access_token_v800($pdo,$connection);$payment=(string)$attempt['external_payment_id'];if($payment===''||str_starts_with($payment,'order'))throw new RuntimeException('Square payment ID is unavailable.');$body=['idempotency_key'=>$idempotency,'amount_money'=>['amount'=>$amountCents,'currency'=>strtoupper((string)$paid['currency'])],'payment_id'=>$payment,'reason'=>$reason?:'Appointment refund'];$resp=agent_paid_appointments_http_v800('POST',$base.'/v2/refunds',['Authorization: Bearer '.$token,'Square-Version: 2026-08-19'],$body)['json'];$refund=$resp['refund']??[];$externalRefund=(string)($refund['id']??'');$status=in_array(strtoupper((string)($refund['status']??'')),['COMPLETED','APPROVED'],true)?'completed':'pending';}
    elseif($provider==='paypal'){$cfg=agent_paid_appointments_config_v800()['paypal'];$capture=(string)$attempt['external_payment_id'];if($capture==='')throw new RuntimeException('PayPal capture ID is unavailable.');$token=agent_paid_appointments_paypal_platform_token_v800();$headers=['Authorization: Bearer '.$token,'PayPal-Request-Id: '.$idempotency,'PayPal-Auth-Assertion: '.agent_paid_appointments_paypal_assertion_v800((string)$connection['external_account_id'])];if($cfg['bn_code']!=='')$headers[]='PayPal-Partner-Attribution-Id: '.$cfg['bn_code'];$resp=agent_paid_appointments_http_v800('POST',agent_paid_appointments_paypal_base_v800().'/v2/payments/captures/'.rawurlencode($capture).'/refund',$headers,['amount'=>['currency_code'=>strtoupper((string)$paid['currency']),'value'=>number_format($amountCents/100,2,'.','')],'note_to_payer'=>$reason?:'Appointment refund'])['json'];$externalRefund=(string)($resp['id']??'');$status=strtoupper((string)($resp['status']??''))==='COMPLETED'?'completed':'pending';}
    else throw new RuntimeException('Unsupported refund provider.');if($externalRefund==='')throw new RuntimeException('Payment provider did not return a refund ID.');
    $pdo->prepare('INSERT INTO agent_paid_refunds_v800 (paid_booking_id,checkout_attempt_id,provider,external_refund_id,amount_cents,status,reason,requested_by_user_id,requested_by_agent_id,approved_by_user_id,completed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)')->execute([(int)$paid['id'],(int)$attempt['id'],$provider,$externalRefund,$amountCents,$status,$reason,$actorId,$agentId,$actorId,$status==='completed'?gmdate('Y-m-d H:i:s'):null]);if($status==='completed'){$newRefunded=(int)$paid['amount_refunded_cents']+$amountCents;$newStatus=$newRefunded>=(int)$paid['amount_paid_cents']?'refunded':'partially_refunded';$pdo->prepare('UPDATE agent_paid_bookings_v800 SET amount_refunded_cents=?,payment_status=?,refunded_at=IF(?=\'refunded\',NOW(),refunded_at),updated_at=NOW() WHERE id=?')->execute([$newRefunded,$newStatus,$newStatus,(int)$paid['id']]);agent_paid_appointments_audit_v800($pdo,(int)$paid['id'],(int)$paid['owner_user_id'],(int)($paid['workspace_owner_user_id']??0)?:null,'user',$actorId,$agentId,'refund_completed',(string)$paid['payment_status'],$newStatus,$amountCents,['provider'=>$provider,'external_refund_id'=>$externalRefund,'reason'=>$reason]);}else agent_paid_appointments_audit_v800($pdo,(int)$paid['id'],(int)$paid['owner_user_id'],(int)($paid['workspace_owner_user_id']??0)?:null,'user',$actorId,$agentId,'refund_requested',(string)$paid['payment_status'],'refund_pending',$amountCents,['provider'=>$provider,'external_refund_id'=>$externalRefund,'reason'=>$reason]);return agent_paid_appointments_paid_booking_v800($pdo,(int)$paid['id'])?:$paid;
}
