<?php
declare(strict_types=1);

/**
 * VP3 Cognitive Runtime v23.70 — canonical domain integration inventory.
 *
 * This is a read-only architecture manifest. Domain subsystems remain the
 * authority for their own records; the cognitive runtime references them.
 */
const VP3_COGNITIVE_DOMAIN_MANIFEST_V2370='vp3-cognitive-domain-manifest-v2370-20260922';

function vp3_cognitive_domain_manifest_v2370(): array
{
    return [
        'build'=>VP3_COGNITIVE_DOMAIN_MANIFEST_V2370,
        'contract'=>'vp3-unified-cognitive-domains-v1',
        'principles'=>[
            'one_event_ingress'=>true,
            'one_live_session_state'=>true,
            'one_attention_pipeline'=>true,
            'domain_records_remain_authoritative'=>true,
            'raw_evidence_never_user_facing'=>true,
            'low_level_events_do_not_auto_promote_to_brain'=>true,
        ],
        'domains'=>[
            'session'=>[
                'authority'=>['agent_activity_state','agent_activity_events','agent_live_sessions_v2370','agent_live_session_segments_v2370'],
                'objects'=>['live_session','session_segment'],
                'events'=>['session.started','session.resumed','session.idle_started','session.idle_ended','session.surface_changed','session.focus_changed','session.ended'],
                'phase'=>'v23.70',
            ],
            'agent_chat'=>[
                'authority'=>['chat_conversations','chat_messages','agent_chat_archive'],
                'objects'=>['conversation','chat_message'],
                'events'=>['chat.conversation_opened','chat.message_sent','chat.response_completed','chat.response_interrupted','chat.stop_requested','chat.knowledge_scope_changed'],
                'phase'=>'v23.70',
            ],
            'agent_brain_history'=>[
                'authority'=>['agent_memory_items','agent_learning_history','agent_edit_events','agent_tool_history'],
                'objects'=>['brain_memory','brain_task','history_episode'],
                'events'=>['brain.memory_promoted','brain.memory_superseded','brain.task_changed','history.episode_closed'],
                'phase'=>'v24.00',
            ],
            'profile_agent'=>[
                'authority'=>['profile_visit_sessions','profile_events','profile_agent_conversations','vp3_agent_contacts'],
                'objects'=>['profile','profile_visit','profile_conversation','contact'],
                'events'=>['profile.visited','profile.return_visitor','profile.conversation_started','profile.message_received','profile.message_sent','profile.booking_intent','profile.product_intent','profile.booking_converted','profile.product_converted','relationship.opportunity_changed'],
                'phase'=>'v23.80',
            ],
            'scheduling'=>[
                'authority'=>['agent_scheduling_schedules','agent_scheduling_event_types'],
                'objects'=>['schedule','scheduling_type'],
                'events'=>['schedule.created','schedule.updated','availability.changed'],
                'phase'=>'v23.80',
            ],
            'booking_appointments'=>[
                'authority'=>['agent_scheduling_bookings','agent_scheduling_lifecycle_events','agent_scheduling_followups','agent_commerce_payments_v800'],
                'objects'=>['booking','appointment'],
                'events'=>['booking.created','booking.confirmed','booking.rescheduled','booking.cancelled','booking.completed','booking.no_show','appointment.payment_changed','appointment.followup_due'],
                'phase'=>'v23.80',
            ],
            'calendar'=>[
                'authority'=>['user_calendar_events'],
                'objects'=>['calendar_event'],
                'events'=>['calendar.event_created','calendar.event_updated','calendar.event_cancelled','calendar.event_starting','calendar.conflict_detected','calendar.commitment_overdue'],
                'phase'=>'v23.80',
            ],
            'commerce'=>[
                'authority'=>['agent_commerce_products_v800','agent_commerce_orders_v800','agent_commerce_order_items_v800','agent_commerce_payments_v800','agent_commerce_refunds_v800'],
                'objects'=>['product','commerce_order','commerce_customer','sale','refund'],
                'events'=>['product.created','product.updated','product.published','product.unpublished','order.created','order.payment_received','order.paid','order.fulfillment_started','order.fulfilled','order.cancelled','order.expired','refund.requested','refund.completed','refund.failed','customer.returned','sale.converted'],
                'phase'=>'v23.80',
            ],
            'crm_relationships'=>[
                'authority'=>['crm_contacts','crm_leads','vp3_agent_contacts','vp3_agent_referral_events'],
                'objects'=>['contact','lead','relationship'],
                'events'=>['contact.created','contact.updated','lead.created','lead.stage_changed','followup.due','message.awaiting_reply','relationship.opportunity_changed','relationship.risk_changed'],
                'phase'=>'v23.80',
            ],
            'meetings'=>[
                'authority'=>['video_meetings','video_meeting_participants','video_meeting_transcript_segments','video_meeting_artifacts'],
                'objects'=>['meeting','meeting_brief'],
                'events'=>['meeting.created','meeting.updated','meeting.reminder_due','meeting.started','meeting.ended','meeting.transcription_ready','meeting.summary_ready','meeting.followup_due'],
                'phase'=>'integrated',
            ],
            'browser'=>[
                'authority'=>['extension_devices_v2000','browser_shares_v2010','browser_submission_intents_v2240','browser_web_interactions_v2210','browser_agent_runtime_sessions_v2200'],
                'objects'=>['browser_companion','browser_page_context','browser_transaction','annotation'],
                'events'=>['browser.session_connected','browser.page_context_changed','browser.research_saved','browser.annotation_created','browser.transaction_started','browser.transaction_completed','browser.transaction_changed','browser.transaction_followup_due'],
                'phase'=>'v23.90',
            ],
            'knowledge_research'=>[
                'authority'=>['knowledge_items','knowledge_chunks','research_projects_v2060','research_project_items_v2060','research_project_events_v2060','research_findings_v2060'],
                'objects'=>['knowledge','research','source','annotation','claim'],
                'events'=>['knowledge.created','knowledge.updated','knowledge.deleted','research.created','research.updated','research.source_added','annotation.created','source.changed','claim.updated'],
                'phase'=>'v23.90',
            ],
            'workflows_tools_approvals'=>[
                'authority'=>['agent_workflow_runs','agent_workflow_actions','agent_workflow_events','agent_tool_history'],
                'objects'=>['workflow','task','tool_action','approval'],
                'events'=>['workflow.started','workflow.progressed','workflow.blocked','workflow.completed','workflow.failed','tool.started','tool.completed','tool.failed','tool.cancelled','approval.requested','approval.granted','approval.denied'],
                'phase'=>'v23.90',
            ],
            'messaging_team'=>[
                'authority'=>['human_conversations','human_conversation_members','human_messages','workspace_memberships_v350','workspace_team_invitations_v350'],
                'objects'=>['human_message','team_activity','team_assignment'],
                'events'=>['team.message_received','team.message_sent','team.assignment_created','team.assignment_completed','team.member_joined','team.member_left'],
                'phase'=>'v23.90',
            ],
            'media_studio'=>[
                'authority'=>['tracks','agent_edit_events','artist_transcript_sessions_v172','recordings'],
                'objects'=>['track','recording','transcription','studio_project'],
                'events'=>['project.opened','project.updated','track.played','track.updated','recording.started','recording.completed','transcription.completed','edit.completed','export.completed'],
                'phase'=>'v23.90',
            ],
            'homeserver'=>[
                'authority'=>['homeserver_connections','remote HomeServer action.list/action.approve/action.deny authority'],
                'objects'=>['homeserver','device','action_request'],
                'events'=>['homeserver.connected','homeserver.disconnected','device.state_changed','action_request.created','action_request.approved','action_request.completed'],
                'phase'=>'v23.90',
            ],
            'analytics_attribution'=>[
                'authority'=>['vp3_radar_sessions','vp3_radar_events','vp3_radar_properties','vp3_agent_referrals','vp3_agent_referral_events'],
                'objects'=>['analytics_signal','attribution'],
                'events'=>['analytics.signal_detected','referral.attributed','conversion.attributed'],
                'phase'=>'v23.90',
            ],
            'notifications'=>[
                'authority'=>['notifications'],
                'objects'=>['notification'],
                'events'=>['notification.created','notification.read','notification.dismissed'],
                'phase'=>'v23.80',
            ],
            'subscription_billing'=>[
                'authority'=>['user_subscriptions','subscription_packages','package_entitlements','subscription_audit_log'],
                'objects'=>['subscription','billing_event'],
                'events'=>['subscription.changed','subscription.renewal_due','billing.payment_failed','billing.payment_recovered'],
                'phase'=>'v23.90',
            ],
            'client_release'=>[
                'authority'=>['client_release_rollouts_v110','client_release_update_state_v110','client_release_health_snapshots_v120','client_release_incidents_v130'],
                'objects'=>['client_release','release_incident'],
                'events'=>['release.started','release.health_changed','release.failed','release.completed','release.followup_due'],
                'phase'=>'v23.90',
            ],
        ],
    ];
}
