<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title><?=e((string)$pool['name'])?> · Team booking</title><link rel="stylesheet" href="<?=e(url('/team-book.css?v=agent-paid-appointments-v800-20260911'))?>"></head>
<body><main class="team-book-shell">
<header class="team-book-brand"><a href="<?=e(url('/'))?>">VP3</a><span>Team Scheduling</span></header>
<?php if($managed):?>
<?php $paymentAwaiting=$managedPaid&&(string)$managedPaid['payment_status']==='awaiting_payment';$paymentUrl=$managedPaid?agent_paid_appointments_payment_url_v800($pdo,$managedPaid):'';?>
<section class="team-book-card manage-card"><span class="eyebrow">Booking management</span><h1><?=e((string)$managed['pool_name'])?></h1>
<?php if($booked):?><div class="notice success">Your Team meeting is confirmed. Participant reminders and preparation are now scheduled.</div><?php endif;?>
<?php if($paymentAwaiting):?><div class="notice">Payment is required before this Team meeting is confirmed.<?php if($paymentUrl!==''):?> <a href="<?=e($paymentUrl)?>">Continue payment →</a><?php endif;?></div><?php endif;?>
<?php if($success!==''):?><div class="notice success"><?=e($success)?></div><?php endif;?>
<?php if($error!==''):?><div class="notice error"><?=e($error)?></div><?php endif;?>
<div class="booking-summary"><div><span>When</span><strong><?=e(team_book_display_time((string)$managed['start_at_utc'],(string)$managed['pool_timezone']))?></strong></div><div><span>Guest</span><strong><?=e((string)$managed['guest_name'])?></strong></div><div><span>Format</span><strong><?=e((string)$managed['mode']==='round_robin'?'Round-robin host':'Collective Team meeting')?></strong></div><div><span>Status</span><strong><?=e(ucfirst((string)$managed['status']))?></strong></div><?php if($managedPaid):?><div><span>Payment</span><strong><?=e(ucwords(str_replace('_',' ',(string)$managedPaid['payment_status'])))?></strong></div><div><span>Paid</span><strong><?=e(agent_paid_appointments_money_v800((int)$managedPaid['amount_paid_cents'],(string)$managedPaid['currency']))?></strong></div><?php endif;?></div>
<?php if($paymentAwaiting&&$paymentUrl!==''):?><p><a class="primary-button" href="<?=e($paymentUrl)?>">Complete payment</a></p><?php endif;?>
<?php if(in_array((string)$managed['status'],['pending','confirmed'],true)):?><form method="post" onsubmit="return confirm('Cancel this Team meeting for every participant?')"><?=csrf_field()?><input type="hidden" name="action" value="cancel"><input type="hidden" name="manage_token" value="<?=e($manageToken)?>"><button class="danger-button" type="submit">Cancel Team meeting</button></form><?php endif;?>
<p class="security-note">This private management link controls only this booking. VP3 does not expose participant calendars or other visitors’ appointments. Paid cancellations follow the displayed policy; refunds require Team Super Admin approval.</p></section>
<?php else:?>
<section class="team-book-intro"><span class="eyebrow"><?=e((string)$pool['mode']==='round_robin'?'Round-robin Team':'Collective Team')?></span><h1><?=e((string)$pool['name'])?></h1><?php if(trim((string)$pool['description'])!==''):?><p><?=nl2br(e((string)$pool['description']))?></p><?php else:?><p>Choose a live Team time. VP3 checks the connected availability of the people who can host this meeting.</p><?php endif;?><?php if($teamPaymentTerms):?><p><strong><?=e(agent_paid_appointments_display_terms_v800($teamPaymentTerms))?></strong><?php if((string)$teamPaymentTerms['payment_mode']!=='free'):?> · Team checkout uses the Team Super Admin’s primary payment provider.<?php endif;?></p><?php endif;?></section>
<?php if($error!==''):?><div class="notice error"><?=e($error)?></div><?php endif;?>
<?php if($teamPaymentTerms&&(string)$teamPaymentTerms['payment_mode']!=='free'):?><section class="team-book-card"><div class="section-head"><div><span class="eyebrow">Payment terms</span><h2><?=e(agent_paid_appointments_display_terms_v800($teamPaymentTerms))?></h2></div></div><p>Your selected Team time is held while payment is completed. The meeting is confirmed only after the payment provider verifies the charge.</p><?php if(trim((string)$teamPaymentTerms['cancellation_policy'])!==''):?><p><?=nl2br(e((string)$teamPaymentTerms['cancellation_policy']))?></p><?php endif;?></section><?php endif;?>
<section class="team-book-card"><form method="get" class="availability-filter"><input type="hidden" name="p" value="<?=e((string)$pool['public_key'])?>"><label><span>Date</span><input type="date" name="date" min="<?=e($today)?>" value="<?=e($date)?>"></label><?php if(trim((string)$pool['routing_question'])!==''):?><label class="wide"><span><?=e((string)$pool['routing_question'])?></span><input name="routing_answer" maxlength="500" required value="<?=e($routingAnswer)?>" placeholder="Tell us what you need"></label><?php endif;?><button type="submit">Check Team availability</button></form></section>
<section class="team-book-card"><div class="section-head"><div><span class="eyebrow">Live availability</span><h2><?=e((new DateTimeImmutable($date,$tz))->format('l, F j'))?></h2></div><span class="timezone-chip"><?=e($timezone)?></span></div>
<?php if($slots):?><form method="post" class="booking-form"><?=csrf_field()?><input type="hidden" name="action" value="book"><input type="hidden" name="public_key" value="<?=e((string)$pool['public_key'])?>"><input type="hidden" name="date" value="<?=e($date)?>"><input type="hidden" name="routing_answer" value="<?=e($routingAnswer)?>"><input type="hidden" name="guest_timezone" id="guestTimezone" value="<?=e($timezone)?>">
<div class="slot-grid"><?php foreach($slots as $i=>$slot):?><label class="slot"><input type="radio" name="start_at_utc" value="<?=e((string)$slot['start_at_utc'])?>" <?=$i===0?'checked':''?>><span><?=e(team_book_display_time((string)$slot['start_at_utc'],$timezone,'g:i A'))?></span></label><?php endforeach;?></div>
<div class="guest-grid"><label><span>Name</span><input name="guest_name" maxlength="190" autocomplete="name" required></label><label><span>Email</span><input name="guest_email" type="email" maxlength="190" autocomplete="email" <?=($teamPaymentTerms&&agent_paid_appointments_amount_due_v800($teamPaymentTerms)>0)?'required':''?>></label><label class="wide"><span>Phone <small>optional</small></span><input name="guest_phone" maxlength="80" autocomplete="tel"></label></div>
<button class="primary-button" type="submit"><?=($teamPaymentTerms&&(string)$teamPaymentTerms['payment_mode']!=='free')?'Continue to payment':'Confirm Team booking'?></button><p class="mode-note"><?=(string)$pool['mode']==='round_robin'?'VP3 will assign the fairest available host after checking routing and live calendar conflicts.':'This time is shown only because every required Team participant is currently available.'?></p></form>
<?php else:?><div class="empty-state"><strong>No Team opening on this date.</strong><p>Try another date<?=trim((string)$pool['routing_question'])!==''?' or adjust your routing answer':''?>.</p></div><?php endif;?></section>
<?php endif;?>
</main><script>try{document.getElementById('guestTimezone').value=Intl.DateTimeFormat().resolvedOptions().timeZone||'<?=e($timezone)?>';}catch(e){}</script></body></html>
