<?php
declare(strict_types=1);
require dirname(__DIR__) . '/includes/bootstrap.php';
require_once dirname(__DIR__) . '/includes/chat-execution-v019.php';
require_once dirname(__DIR__) . '/includes/homeserver-agent-v025.php';
require_once dirname(__DIR__) . '/includes/agent-chat-boundary-v380.php';
require_once dirname(__DIR__) . '/includes/agent-tool-authorization-v400.php';
require_once dirname(__DIR__) . '/includes/agent-work-control-v173.php';
require_once dirname(__DIR__) . '/includes/user-calendar-v1300.php';
require_once dirname(__DIR__) . '/includes/user-calendar-agent-v1300.php';
require_once dirname(__DIR__) . '/includes/knowledge-retrieval-v162.php';
require_once dirname(__DIR__) . '/includes/browser-context-v2130.php';
require_once dirname(__DIR__) . '/includes/video-meetings-memory-v18120.php';
require_once dirname(__DIR__) . '/includes/video-meetings-commitment-command-v18230-chat.php';
require_once dirname(__DIR__) . '/includes/agent-chat-runtime-v2160.php';
header('Content-Type: application/json; charset=UTF-8');header('Cache-Control: no-store');
$user=current_user();if(!$user||!has_permission('chat.access',$user)){http_response_code(403);echo json_encode(['ok'=>false,'error'=>'Chat access is not available for this account.']);exit;}
$pdo=db();if(!$pdo||!table_exists('chat_conversations')||!user_agent_system_schema_ready_v236($pdo)){http_response_code(503);echo json_encode(['ok'=>false,'error'=>'Agent Chat storage is not ready. An administrator needs to run the database upgrade.']);exit;}
$userId=(int)$user['id'];$brainAllowed=personal_capability_has_v242('agent_brain.access',$user);
$requestedAgentId=max(0,(int)($_GET['agent']??0));
try{$activeAgent=vp3_agent_chat_resolve_agent_v380($pdo,$user,$requestedAgentId);}catch(RuntimeException $e){http_response_code(404);echo json_encode(['ok'=>false,'error'=>$e->getMessage()]);exit;}
$principal=vp3_agent_chat_principal_v380($user,$activeAgent);
$input=json_decode((string)file_get_contents('php://input'),true);if(!is_array($input))$input=$_POST;$csrf=(string)($input['csrf_token']??'');if($csrf===''||!hash_equals(csrf_token(),$csrf)){http_response_code(419);echo json_encode(['ok'=>false,'error'=>'Session expired. Refresh the page and try again.']);exit;}$action=(string)($input['action']??'send');

function chat_v236_scope_sql(?array $agent,string $alias='c'): array{return vp3_agent_chat_scope_sql_v380($agent,$alias);}
function chat_v236_conversation(PDO $pdo,int $conversationId,int $userId,?array $agent): ?array{return vp3_agent_chat_conversation_v380($pdo,$conversationId,$userId,$agent);}
function chat_v236_authorized_media(array $media,array $context): array{$titles=[];foreach($context as $item){$source=(string)($item['source']??'');if(str_starts_with($source,'database:track:')||str_starts_with($source,'artist:track:'))$titles[mb_strtolower(trim((string)($item['title']??'')))]=true;}if(!$titles)return [];return array_values(array_filter($media,static function(array $item)use($titles):bool{$title=mb_strtolower(trim((string)($item['title']??'')));return $title!==''&&isset($titles[$title]);}));}
function chat_v236_calendar_context_events(array $awareness): array{$events=[];if(empty($awareness['available']))return $events;$current=is_array($awareness['current']??null)?$awareness['current']:null;if($current){$events[]=['id'=>'calendar-current-'.(string)($current['ref']??''),'type'=>'event','event_kind'=>'calendar_current','title'=>(string)($current['title']??'Current commitment'),'summary'=>'In progress until '.(string)($current['end_local']??'').'.','source'=>'calendar_awareness'];}$next=is_array($awareness['next']??null)?$awareness['next']:null;if($next){$events[]=['id'=>'calendar-next-'.(string)($next['ref']??''),'type'=>'event','event_kind'=>'calendar_next','title'=>(string)($next['title']??'Next commitment'),'summary'=>'Starts '.(string)($next['start_local']??'').' · '.max(0,(int)($next['starts_in_minutes']??0)).' minutes from now.','source'=>'calendar_awareness'];}foreach(array_slice((array)($awareness['conflicts']??[]),0,2) as $index=>$conflict){if(!is_array($conflict))continue;$events[]=['id'=>'calendar-conflict-'.$index.'-'.sha1((string)($conflict['left_ref']??'').'|'.(string)($conflict['right_ref']??'')),'type'=>'event','event_kind'=>'calendar_conflict','title'=>'Calendar overlap','summary'=>(string)($conflict['left_title']??'Scheduled item').' overlaps '.(string)($conflict['right_title']??'Scheduled item').' by about '.max(1,(int)($conflict['overlap_minutes']??0)).' minutes.','source'=>'calendar_awareness'];}return array_slice($events,0,4);}

try{
if($action==='list'){[$scope,$params]=chat_v236_scope_sql($activeAgent,'c');$stmt=$pdo->prepare("SELECT c.id,c.title,c.created_at,c.updated_at,COALESCE(MAX(m.id),0) latest_message_id FROM chat_conversations c LEFT JOIN chat_messages m ON m.conversation_id=c.id WHERE c.user_id=? AND {$scope} GROUP BY c.id ORDER BY latest_message_id DESC,c.updated_at DESC,c.id DESC LIMIT 50");$stmt->execute(array_merge([$userId],$params));echo json_encode(['ok'=>true,'conversations'=>$stmt->fetchAll(),'agent_name'=>(string)$principal['display_name'],'agent_id'=>(int)$principal['agent_id']]);exit;}
if($action==='activity'){player_process_show_reminders($user);[$scope,$params]=chat_v236_scope_sql($activeAgent,'c');$stmt=$pdo->prepare("SELECT c.id FROM chat_conversations c WHERE c.user_id=? AND {$scope} ORDER BY c.updated_at DESC,c.id DESC LIMIT 1");$stmt->execute(array_merge([$userId],$params));$activeConversationId=(int)$stmt->fetchColumn();$activeMessageId=0;if($activeConversationId>0){$m=$pdo->prepare('SELECT COALESCE(MAX(id),0) FROM chat_messages WHERE conversation_id=?');$m->execute([$activeConversationId]);$activeMessageId=(int)$m->fetchColumn();}if(!table_exists('notifications')){echo json_encode(['ok'=>true,'updates'=>[],'latest_id'=>0,'unread_count'=>0,'conversation_id'=>$activeConversationId,'latest_message_id'=>$activeMessageId]);exit;}$afterId=max(0,(int)($input['after_id']??0));if($afterId>0){$n=$pdo->prepare("SELECT id,type,title,body,target_url,created_at FROM notifications WHERE user_id=? AND id>? AND type IN ('agent_track_share','producer_track_share','agent_supervisor_listen','stem_region_note','production_note','new_track_release','new_album_release','show_reminder','artist_post','release_deadline','release_action') ORDER BY id ASC LIMIT 30");$n->execute([$userId,$afterId]);$updates=$n->fetchAll();}else{$n=$pdo->prepare("SELECT id,type,title,body,target_url,created_at FROM notifications WHERE user_id=? AND type IN ('agent_track_share','producer_track_share','agent_supervisor_listen','stem_region_note','production_note','new_track_release','new_album_release','show_reminder','artist_post','release_deadline','release_action') AND created_at>=DATE_SUB(NOW(),INTERVAL 7 DAY) ORDER BY id DESC LIMIT 10");$n->execute([$userId]);$updates=array_reverse($n->fetchAll());}$latest=$pdo->prepare("SELECT COALESCE(MAX(id),0) FROM notifications WHERE user_id=? AND type IN ('agent_track_share','producer_track_share','agent_supervisor_listen','stem_region_note','production_note','new_track_release','new_album_release','show_reminder','artist_post','release_deadline','release_action')");$latest->execute([$userId]);echo json_encode(['ok'=>true,'updates'=>$updates,'latest_id'=>(int)$latest->fetchColumn(),'unread_count'=>notification_unread_count($user),'conversation_id'=>$activeConversationId,'latest_message_id'=>$activeMessageId],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
if($action==='new'){$workspaceId=artist_workspace_v181_scope_id($user);$conversation=vp3_agent_chat_create_conversation_v380($pdo,$user,$activeAgent,'New chat',$workspaceId);echo json_encode(['ok'=>true,'conversation_id'=>(int)$conversation['id']]);exit;}
if($action==='load'){$conversationId=(int)($input['conversation_id']??0);$conversation=chat_v236_conversation($pdo,$conversationId,$userId,$activeAgent);if(!$conversation)throw new RuntimeException('Conversation not found for this agent.');$stmt=$pdo->prepare('SELECT id,role,message,context_json,created_at FROM chat_messages WHERE conversation_id=? ORDER BY created_at DESC,id DESC LIMIT 300');$stmt->execute([$conversationId]);echo json_encode(['ok'=>true,'conversation'=>$conversation,'messages'=>array_reverse($stmt->fetchAll()),'agent_name'=>(string)$principal['display_name']]);exit;}
if($action==='messages_after'){$conversationId=(int)($input['conversation_id']??0);if(!chat_v236_conversation($pdo,$conversationId,$userId,$activeAgent))throw new RuntimeException('Conversation not found for this agent.');$afterId=max(0,(int)($input['after_id']??0));$stmt=$pdo->prepare('SELECT id,role,message,context_json,created_at FROM chat_messages WHERE conversation_id=? AND id>? ORDER BY id ASC LIMIT 80');$stmt->execute([$conversationId,$afterId]);echo json_encode(['ok'=>true,'conversation_id'=>$conversationId,'messages'=>$stmt->fetchAll()],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
if($action==='delete'){$conversationId=(int)($input['conversation_id']??0);if(!chat_v236_conversation($pdo,$conversationId,$userId,$activeAgent))throw new RuntimeException('Conversation not found for this agent.');homeserver_agent_v018_forget($userId,$conversationId);$pdo->prepare('DELETE FROM chat_conversations WHERE id=? AND user_id=?')->execute([$conversationId,$userId]);echo json_encode(['ok'=>true]);exit;}
if($action==='send'){
    $payload=vp3_agent_chat_send_v2160($pdo,$user,$activeAgent,$principal,$input,$brainAllowed);
    echo json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
    exit;
}
throw new RuntimeException('Unknown chat action.');
}catch(Throwable $e){http_response_code(400);echo json_encode(['ok'=>false,'error'=>$e->getMessage()]);}