<?php
declare(strict_types=1);
require dirname(__DIR__).'/includes/bootstrap.php';
require_once dirname(__DIR__).'/includes/social-network-v320.php';
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
function team_chat_v320_json(array $p,int $s=200): never{http_response_code($s);echo json_encode($p,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function team_chat_v320_avatar(string $p): string{$p=trim($p);return $p===''?'':(preg_match('#^https?://#i',$p)?$p:url($p));}
function team_chat_v320_user(array $r): array{return ['id'=>(int)$r['id'],'name'=>(string)$r['display_name'],'role'=>(string)$r['role'],'role_label'=>role_label((string)$r['role']),'avatar'=>team_chat_v320_avatar((string)($r['avatar_path']??'')),'page'=>(string)($r['page_key']??''),'context'=>(string)($r['context_label']??''),'unread'=>(int)($r['unread_count']??0),'online'=>(bool)($r['online']??false)];}
function team_chat_v320_message(array $r): array{return ['id'=>(int)$r['id'],'sender_id'=>(int)$r['sender_user_id'],'recipient_id'=>(int)$r['recipient_user_id'],'text'=>(string)$r['message_text'],'created_at'=>(string)$r['created_at'],'read_at'=>$r['read_at']!==null?(string)$r['read_at']:null,'sender'=>['id'=>(int)$r['sender_user_id'],'name'=>(string)($r['sender_name']??''),'role'=>(string)($r['sender_role']??''),'role_label'=>role_label((string)($r['sender_role']??'')),'avatar'=>team_chat_v320_avatar((string)($r['sender_avatar']??''))],'recipient'=>['id'=>(int)$r['recipient_user_id'],'name'=>(string)($r['recipient_name']??''),'role'=>(string)($r['recipient_role']??''),'role_label'=>role_label((string)($r['recipient_role']??'')),'avatar'=>team_chat_v320_avatar((string)($r['recipient_avatar']??''))]];}
function team_chat_v320_touch(PDO $pdo,int $uid,string $page,string $context): void{$page=substr(preg_replace('/[^a-z0-9_-]/i','',$page)?:'workspace',0,60);$context=mb_strimwidth(trim($context),0,190,'');$pdo->prepare('INSERT INTO team_user_presence (user_id,page_key,context_label,last_seen_at) VALUES (?,?,?,NOW()) ON DUPLICATE KEY UPDATE page_key=VALUES(page_key),context_label=VALUES(context_label),last_seen_at=NOW()')->execute([$uid,$page,$context]);}
function team_chat_v320_peers(PDO $pdo,int $uid): array{if(!table_exists('artist_team_members'))return [];$stmt=$pdo->prepare('SELECT member_user_id id FROM artist_team_members WHERE artist_user_id=? UNION SELECT artist_user_id id FROM artist_team_members WHERE member_user_id=? UNION SELECT a2.member_user_id id FROM artist_team_members a1 INNER JOIN artist_team_members a2 ON a2.artist_user_id=a1.artist_user_id WHERE a1.member_user_id=? AND a2.member_user_id<>?');$stmt->execute([$uid,$uid,$uid,$uid]);$out=[];foreach($stmt->fetchAll(PDO::FETCH_COLUMN)?:[] as $id){$id=(int)$id;if($id>0&&$id!==$uid)$out[$id]=true;}return array_keys($out);}
function team_chat_v320_peer(PDO $pdo,int $uid,int $peer): ?array{if($peer<1||$peer===$uid||!vp3_social_shared_workspace_v320($pdo,$uid,$peer)||empty(chat_settings_get_v237($pdo,$peer)['social_chat_enabled']))return null;$stmt=$pdo->prepare('SELECT id,display_name,role,avatar_path,is_active FROM users WHERE id=? AND is_active=1 LIMIT 1');$stmt->execute([$peer]);$row=$stmt->fetch();return $row?:null;}
$user=current_user();if(!$user)team_chat_v320_json(['ok'=>false,'error'=>'login_required'],401);$pdo=db();if(!$pdo)team_chat_v320_json(['ok'=>false,'error'=>'database_unavailable'],503);$uid=(int)$user['id'];if(!table_exists('artist_team_members')||!table_exists('team_user_presence')||!table_exists('team_direct_messages'))team_chat_v320_json(['ok'=>false,'error'=>'upgrade_required'],503);
$action=(string)($_POST['action']??$_GET['action']??'poll');$page=(string)($_POST['page']??$_GET['page']??'workspace');$context=(string)($_POST['context']??$_GET['context']??'');
try{team_chat_v320_touch($pdo,$uid,$page,$context);$settings=chat_settings_get_v237($pdo,$uid);$peers=team_chat_v320_peers($pdo,$uid);
 if($action==='poll'){$since=max(0,(int)($_GET['since']??0));$users=[];if(!empty($settings['social_chat_enabled'])&&$peers){$marks=implode(',',array_fill(0,count($peers),'?'));$stmt=$pdo->prepare("SELECT u.id,u.display_name,u.role,u.avatar_path,COALESCE(p.page_key,'') page_key,COALESCE(p.context_label,'') context_label,CASE WHEN p.last_seen_at IS NOT NULL AND p.last_seen_at>=DATE_SUB(NOW(),INTERVAL 15 SECOND) AND COALESCE(p.presence_mode,'online')='online' THEN 1 ELSE 0 END online,(SELECT COUNT(*) FROM team_direct_messages dm WHERE dm.sender_user_id=u.id AND dm.recipient_user_id=? AND dm.read_at IS NULL) unread_count FROM users u LEFT JOIN team_user_presence p ON p.user_id=u.id WHERE u.id IN ($marks) AND u.is_active=1 AND COALESCE(p.social_chat_enabled,1)=1 ORDER BY online DESC,unread_count DESC,u.display_name,u.id");$stmt->execute([$uid,...$peers]);$users=array_map('team_chat_v320_user',$stmt->fetchAll()?:[]);}$cur=$pdo->prepare('SELECT COALESCE(MAX(id),0) FROM team_direct_messages WHERE sender_user_id=? OR recipient_user_id=?');$cur->execute([$uid,$uid]);$cursor=(int)$cur->fetchColumn();$messages=[];if($since>0){$stmt=$pdo->prepare("SELECT dm.*,su.display_name sender_name,su.role sender_role,su.avatar_path sender_avatar,ru.display_name recipient_name,ru.role recipient_role,ru.avatar_path recipient_avatar FROM team_direct_messages dm INNER JOIN users su ON su.id=dm.sender_user_id INNER JOIN users ru ON ru.id=dm.recipient_user_id WHERE dm.id>? AND (dm.sender_user_id=? OR dm.recipient_user_id=?) ORDER BY dm.id ASC LIMIT 200");$stmt->execute([$since,$uid,$uid]);foreach($stmt->fetchAll()?:[] as $r){$peer=(int)$r['sender_user_id']===$uid?(int)$r['recipient_user_id']:(int)$r['sender_user_id'];if(vp3_social_shared_workspace_v320($pdo,$uid,$peer))$messages[]=team_chat_v320_message($r);}}team_chat_v320_json(['ok'=>true,'cursor'=>$cursor,'users'=>$users,'messages'=>$messages,'settings'=>$settings,'poll_ms'=>3000]);}
 if($action==='history'){$peer=max(0,(int)($_GET['user_id']??0));$target=team_chat_v320_peer($pdo,$uid,$peer);if(!$target)team_chat_v320_json(['ok'=>false,'error'=>'user_not_available'],404);$stmt=$pdo->prepare("SELECT * FROM (SELECT dm.*,su.display_name sender_name,su.role sender_role,su.avatar_path sender_avatar,ru.display_name recipient_name,ru.role recipient_role,ru.avatar_path recipient_avatar FROM team_direct_messages dm INNER JOIN users su ON su.id=dm.sender_user_id INNER JOIN users ru ON ru.id=dm.recipient_user_id WHERE (dm.sender_user_id=? AND dm.recipient_user_id=?) OR (dm.sender_user_id=? AND dm.recipient_user_id=?) ORDER BY dm.id DESC LIMIT 80) recent ORDER BY id ASC");$stmt->execute([$uid,$peer,$peer,$uid]);team_chat_v320_json(['ok'=>true,'user'=>team_chat_v320_user($target),'messages'=>array_map('team_chat_v320_message',$stmt->fetchAll()?:[])]);}
 if($action==='send'){if(!verify_csrf())team_chat_v320_json(['ok'=>false,'error'=>'csrf'],419);if(empty($settings['social_chat_enabled']))team_chat_v320_json(['ok'=>false,'error'=>'social_chat_disabled'],409);$peer=max(0,(int)($_POST['user_id']??0));$message=trim((string)($_POST['message']??''));if(!team_chat_v320_peer($pdo,$uid,$peer))team_chat_v320_json(['ok'=>false,'error'=>'user_not_available'],404);if($message===''||mb_strlen($message)>2000)team_chat_v320_json(['ok'=>false,'error'=>$message===''?'empty_message':'message_too_long'],422);$pdo->prepare('INSERT INTO team_direct_messages (sender_user_id,recipient_user_id,message_text,created_at) VALUES (?,?,?,NOW())')->execute([$uid,$peer,$message]);$id=(int)$pdo->lastInsertId();$stmt=$pdo->prepare("SELECT dm.*,su.display_name sender_name,su.role sender_role,su.avatar_path sender_avatar,ru.display_name recipient_name,ru.role recipient_role,ru.avatar_path recipient_avatar FROM team_direct_messages dm INNER JOIN users su ON su.id=dm.sender_user_id INNER JOIN users ru ON ru.id=dm.recipient_user_id WHERE dm.id=? LIMIT 1");$stmt->execute([$id]);team_chat_v320_json(['ok'=>true,'message'=>team_chat_v320_message($stmt->fetch()?:[])]);}
 if($action==='read'){if(!verify_csrf())team_chat_v320_json(['ok'=>false,'error'=>'csrf'],419);$peer=max(0,(int)($_POST['user_id']??0));if(!team_chat_v320_peer($pdo,$uid,$peer))team_chat_v320_json(['ok'=>false,'error'=>'user_not_available'],404);$pdo->prepare('UPDATE team_direct_messages SET read_at=COALESCE(read_at,NOW()) WHERE sender_user_id=? AND recipient_user_id=? AND read_at IS NULL')->execute([$peer,$uid]);team_chat_v320_json(['ok'=>true]);}
 team_chat_v320_json(['ok'=>false,'error'=>'unknown_action'],400);
}catch(Throwable $e){error_log('VP3 scoped Team Chat v320: '.$e->getMessage());team_chat_v320_json(['ok'=>false,'error'=>'team_chat_failed'],500);}
