<?php
declare(strict_types=1);
require dirname(__DIR__).'/includes/bootstrap.php';
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
function team_chat_v320_json(array $p,int $s=200): never{http_response_code($s);echo json_encode($p,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function team_chat_v320_avatar(string $p): string{$p=trim($p);return $p===''?'':(preg_match('#^https?://#i',$p)?$p:url($p));}
function team_chat_v320_user(array $r): array{return ['id'=>(int)$r['id'],'name'=>(string)$r['display_name'],'role'=>(string)$r['role'],'role_label'=>role_label((string)$r['role']),'avatar'=>team_chat_v320_avatar((string)($r['avatar_path']??'')),'page'=>(string)($r['page_key']??''),'context'=>(string)($r['context_label']??''),'unread'=>(int)($r['unread_count']??0),'online'=>(bool)($r['online']??false)];}
function team_chat_v320_message(array $r): array{return ['id'=>(int)$r['id'],'sender_id'=>(int)$r['sender_user_id'],'recipient_id'=>(int)$r['recipient_user_id'],'text'=>(string)$r['body'],'created_at'=>(string)$r['created_at'],'read_at'=>$r['read_at']!==null?(string)$r['read_at']:null,'sender'=>['id'=>(int)$r['sender_user_id'],'name'=>(string)($r['sender_name']??''),'role'=>(string)($r['sender_role']??''),'role_label'=>role_label((string)($r['sender_role']??'')),'avatar'=>team_chat_v320_avatar((string)($r['sender_avatar']??''))],'recipient'=>['id'=>(int)$r['recipient_user_id'],'name'=>(string)($r['recipient_name']??''),'role'=>(string)($r['recipient_role']??''),'role_label'=>role_label((string)($r['recipient_role']??'')),'avatar'=>team_chat_v320_avatar((string)($r['recipient_avatar']??''))]];}
function team_chat_v320_touch(PDO $pdo,int $uid,string $page,string $context): void{$page=substr(preg_replace('/[^a-z0-9_-]/i','',$page)?:'workspace',0,60);$context=mb_strimwidth(trim($context),0,190,'');$pdo->prepare('INSERT INTO team_user_presence (user_id,page_key,context_label,last_seen_at) VALUES (?,?,?,NOW()) ON DUPLICATE KEY UPDATE page_key=VALUES(page_key),context_label=VALUES(context_label),last_seen_at=NOW()')->execute([$uid,$page,$context]);}
function team_chat_v320_peers(PDO $pdo,int $uid): array{if(!table_exists('artist_team_members'))return [];$stmt=$pdo->prepare('SELECT member_user_id id FROM artist_team_members WHERE artist_user_id=? UNION SELECT artist_user_id id FROM artist_team_members WHERE member_user_id=? UNION SELECT a2.member_user_id id FROM artist_team_members a1 INNER JOIN artist_team_members a2 ON a2.artist_user_id=a1.artist_user_id WHERE a1.member_user_id=? AND a2.member_user_id<>?');$stmt->execute([$uid,$uid,$uid,$uid]);$out=[];foreach($stmt->fetchAll(PDO::FETCH_COLUMN)?:[] as $id){$id=(int)$id;if($id>0&&$id!==$uid)$out[$id]=true;}return array_keys($out);}
function team_chat_v320_peer(PDO $pdo,int $uid,int $peer): ?array{if($peer<1||$peer===$uid||!vp3_human_shared_workspace_v370($pdo,$uid,$peer)||empty(chat_settings_get_v237($pdo,$peer)['social_chat_enabled']))return null;$stmt=$pdo->prepare('SELECT id,display_name,role,avatar_path,is_active FROM users WHERE id=? AND is_active=1 LIMIT 1');$stmt->execute([$peer]);$row=$stmt->fetch();return $row?:null;}
function team_chat_v320_message_row(PDO $pdo,int $messageId): ?array{$stmt=$pdo->prepare("SELECT m.id,m.conversation_id,m.sender_user_id,m.body,m.created_at,c.direct_user_low_id,c.direct_user_high_id,CASE WHEN m.sender_user_id=c.direct_user_low_id THEN c.direct_user_high_id ELSE c.direct_user_low_id END recipient_user_id,su.display_name sender_name,su.role sender_role,su.avatar_path sender_avatar,ru.display_name recipient_name,ru.role recipient_role,ru.avatar_path recipient_avatar,CASE WHEN COALESCE(rr.last_read_message_id,0)>=m.id THEN rr.updated_at ELSE NULL END read_at FROM human_messages m INNER JOIN human_conversations c ON c.id=m.conversation_id AND c.conversation_type='direct' INNER JOIN users su ON su.id=m.sender_user_id INNER JOIN users ru ON ru.id=CASE WHEN m.sender_user_id=c.direct_user_low_id THEN c.direct_user_high_id ELSE c.direct_user_low_id END LEFT JOIN human_conversation_reads_v370 rr ON rr.conversation_id=c.id AND rr.user_id=ru.id WHERE m.id=? AND m.deleted_at IS NULL LIMIT 1");$stmt->execute([$messageId]);$row=$stmt->fetch();return $row?:null;}
function team_chat_v320_history_rows(PDO $pdo,int $uid,int $peer): array{$conversation=vp3_human_direct_existing_v370($pdo,$uid,$peer);if(!$conversation)return [];$stmt=$pdo->prepare("SELECT * FROM (SELECT m.id,m.conversation_id,m.sender_user_id,m.body,m.created_at,c.direct_user_low_id,c.direct_user_high_id,CASE WHEN m.sender_user_id=c.direct_user_low_id THEN c.direct_user_high_id ELSE c.direct_user_low_id END recipient_user_id,su.display_name sender_name,su.role sender_role,su.avatar_path sender_avatar,ru.display_name recipient_name,ru.role recipient_role,ru.avatar_path recipient_avatar,CASE WHEN COALESCE(rr.last_read_message_id,0)>=m.id THEN rr.updated_at ELSE NULL END read_at FROM human_messages m INNER JOIN human_conversations c ON c.id=m.conversation_id INNER JOIN users su ON su.id=m.sender_user_id INNER JOIN users ru ON ru.id=CASE WHEN m.sender_user_id=c.direct_user_low_id THEN c.direct_user_high_id ELSE c.direct_user_low_id END LEFT JOIN human_conversation_reads_v370 rr ON rr.conversation_id=c.id AND rr.user_id=ru.id WHERE m.conversation_id=? AND m.deleted_at IS NULL ORDER BY m.id DESC LIMIT 80) recent ORDER BY id ASC");$stmt->execute([(int)$conversation['id']]);return $stmt->fetchAll()?:[];}
$user=current_user();if(!$user)team_chat_v320_json(['ok'=>false,'error'=>'login_required'],401);$pdo=db();if(!$pdo)team_chat_v320_json(['ok'=>false,'error'=>'database_unavailable'],503);$uid=(int)$user['id'];try{vp3_human_messaging_v370_ensure_schema($pdo);if(!vp3_human_messaging_v370_ready($pdo))team_chat_v320_json(['ok'=>false,'error'=>'upgrade_required'],503);}catch(Throwable $e){team_chat_v320_json(['ok'=>false,'error'=>'upgrade_required'],503);}if(!table_exists('artist_team_members')||!table_exists('team_user_presence'))team_chat_v320_json(['ok'=>false,'error'=>'upgrade_required'],503);
$action=(string)($_POST['action']??$_GET['action']??'poll');$page=(string)($_POST['page']??$_GET['page']??'workspace');$context=(string)($_POST['context']??$_GET['context']??'');
try{team_chat_v320_touch($pdo,$uid,$page,$context);$settings=chat_settings_get_v237($pdo,$uid);$peers=team_chat_v320_peers($pdo,$uid);
 if($action==='poll'){$since=max(0,(int)($_GET['since']??0));$users=[];if(!empty($settings['social_chat_enabled'])&&$peers){$marks=implode(',',array_fill(0,count($peers),'?'));$stmt=$pdo->prepare("SELECT u.id,u.display_name,u.role,u.avatar_path,COALESCE(p.page_key,'') page_key,COALESCE(p.context_label,'') context_label,CASE WHEN p.last_seen_at IS NOT NULL AND p.last_seen_at>=DATE_SUB(NOW(),INTERVAL 15 SECOND) AND COALESCE(p.presence_mode,'online')='online' THEN 1 ELSE 0 END online FROM users u LEFT JOIN team_user_presence p ON p.user_id=u.id WHERE u.id IN ($marks) AND u.is_active=1 AND COALESCE(p.social_chat_enabled,1)=1 ORDER BY online DESC,u.display_name,u.id");$stmt->execute($peers);foreach($stmt->fetchAll()?:[] as $row){$conversation=vp3_human_direct_existing_v370($pdo,$uid,(int)$row['id']);$row['unread_count']=$conversation?vp3_human_unread_count_v370($pdo,(int)$conversation['id'],$uid):0;$users[]=team_chat_v320_user($row);}}
   $cur=$pdo->prepare("SELECT COALESCE(MAX(m.id),0) FROM human_messages m INNER JOIN human_conversations c ON c.id=m.conversation_id AND c.conversation_type='direct' WHERE c.direct_user_low_id=? OR c.direct_user_high_id=?");$cur->execute([$uid,$uid]);$cursor=(int)$cur->fetchColumn();if($since>$cursor)$since=$cursor;$messages=[];if($since>0&&$cursor>$since){$stmt=$pdo->prepare("SELECT m.id,m.conversation_id,m.sender_user_id,m.body,m.created_at,c.direct_user_low_id,c.direct_user_high_id,CASE WHEN m.sender_user_id=c.direct_user_low_id THEN c.direct_user_high_id ELSE c.direct_user_low_id END recipient_user_id,su.display_name sender_name,su.role sender_role,su.avatar_path sender_avatar,ru.display_name recipient_name,ru.role recipient_role,ru.avatar_path recipient_avatar,CASE WHEN COALESCE(rr.last_read_message_id,0)>=m.id THEN rr.updated_at ELSE NULL END read_at FROM human_messages m INNER JOIN human_conversations c ON c.id=m.conversation_id AND c.conversation_type='direct' INNER JOIN users su ON su.id=m.sender_user_id INNER JOIN users ru ON ru.id=CASE WHEN m.sender_user_id=c.direct_user_low_id THEN c.direct_user_high_id ELSE c.direct_user_low_id END LEFT JOIN human_conversation_reads_v370 rr ON rr.conversation_id=c.id AND rr.user_id=ru.id WHERE m.id>? AND (c.direct_user_low_id=? OR c.direct_user_high_id=?) AND m.deleted_at IS NULL ORDER BY m.id ASC LIMIT 200");$stmt->execute([$since,$uid,$uid]);foreach($stmt->fetchAll()?:[] as $row){$peer=(int)$row['sender_user_id']===$uid?(int)$row['recipient_user_id']:(int)$row['sender_user_id'];if(vp3_human_shared_workspace_v370($pdo,$uid,$peer))$messages[]=team_chat_v320_message($row);}}team_chat_v320_json(['ok'=>true,'cursor'=>$cursor,'users'=>$users,'messages'=>$messages,'settings'=>$settings,'poll_ms'=>3000]);}
 if($action==='history'){$peer=max(0,(int)($_GET['user_id']??0));$target=team_chat_v320_peer($pdo,$uid,$peer);if(!$target)team_chat_v320_json(['ok'=>false,'error'=>'user_not_available'],404);team_chat_v320_json(['ok'=>true,'user'=>team_chat_v320_user($target),'messages'=>array_map('team_chat_v320_message',team_chat_v320_history_rows($pdo,$uid,$peer))]);}
 if($action==='send'){if(!verify_csrf())team_chat_v320_json(['ok'=>false,'error'=>'csrf'],419);if(empty($settings['social_chat_enabled']))team_chat_v320_json(['ok'=>false,'error'=>'social_chat_disabled'],409);$peer=max(0,(int)($_POST['user_id']??0));$message=trim((string)($_POST['message']??''));if(!team_chat_v320_peer($pdo,$uid,$peer))team_chat_v320_json(['ok'=>false,'error'=>'user_not_available'],404);if($message===''||mb_strlen($message)>2000)team_chat_v320_json(['ok'=>false,'error'=>$message===''?'empty_message':'message_too_long'],422);$conversation=vp3_human_direct_existing_v370($pdo,$uid,$peer);if($conversation)$sent=vp3_human_send_message_v370($pdo,(int)$conversation['id'],$uid,$message);else{$started=vp3_human_start_direct_v370($pdo,$uid,$peer,$message);$sent=$started['message']??null;}if(!$sent)throw new RuntimeException('Message could not be sent.');$row=team_chat_v320_message_row($pdo,(int)$sent['id']);if(!$row)throw new RuntimeException('Message could not be loaded.');team_chat_v320_json(['ok'=>true,'message'=>team_chat_v320_message($row)]);}
 if($action==='read'){if(!verify_csrf())team_chat_v320_json(['ok'=>false,'error'=>'csrf'],419);$peer=max(0,(int)($_POST['user_id']??0));if(!team_chat_v320_peer($pdo,$uid,$peer))team_chat_v320_json(['ok'=>false,'error'=>'user_not_available'],404);$conversation=vp3_human_direct_existing_v370($pdo,$uid,$peer);if($conversation)vp3_human_mark_read_v370($pdo,(int)$conversation['id'],$uid);team_chat_v320_json(['ok'=>true]);}
 team_chat_v320_json(['ok'=>false,'error'=>'unknown_action'],400);
}catch(Throwable $e){error_log('VP3 scoped Team Chat v370: '.$e->getMessage());team_chat_v320_json(['ok'=>false,'error'=>'team_chat_failed'],500);}
